### ISSUE TITLE
File not found when filename contains spaces

### ISSUE THREAD

**Issue by shinji257** [K4YT3X/video2x#10]
When providing a filename containing spaces it throws a file not found error only showing the first word in the filename.  The filename is quoted on the commandline but doesn't seem to carry over in the script.  This is with double quotes.  Suspecting they may be getting stripped I tried with single quotes but this just results in an argument error instead.

**Comment by K4YT3X** [comment]
I saw your issue. I'm just feeling a little sick these few days.
I'll correct this as soon as I'm recovered.

**Comment by shinji257** [comment]
That's fine. Hope you feel better soon.

**Comment by K4YT3X** [comment]
@shinji257 Thanks.
I'm already working on it. It seems like that using `os.system()` to call a exe file with arguments isn't a good idea. I have the issue fixed temporarily.

I will either switch to subprocess in the future, or I might just switch over to python-ffmpeg.

I'm currently still testing the program. I'll release it ASAP.

**Comment by K4YT3X** [comment]
@shinji257 I think I already have it fixed in the previous update.
Please confirm.
