### ISSUE TITLE
ffmpeg json issues 

### ISSUE THREAD

**Issue by CardinalPanda** [k4yt3x/video2x#100]
Under 

```
"video_to_frames": {
    "-qscale:v": null,
    "-hwaccel": "auto",
    "-y": true
},
```

Setting `-qscale:v` to `2` (anything not null essentially) is an invalid input for ffmpeg.

The culprit ( I believe ) is any filter or qscale needs to go after input, where as in the current wrapper, all the settings are inserted before 

I.e

(psuedo code)

`ffmpeg.exe -qscale:v 2 -i input.mkv output.mkv`

Is invalid, but 

`ffmpeg.exe -i input.mkv  -qscale:v 2 output.mkv`

Is valid.

video2x's ffmpeg.py uses the former command. 

My temporary solution involves adding another json category (titled 'filters') that needs to go after the input, i.e

# video2x.json

```
...."ffmpeg": {
    "ffmpeg_path": "C:\\Users\\windwoz\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin",
    "video_to_frames": {
        "-ss": "00:05:01",
        "-t": "00:00:02",
        "-hwaccel": "auto",
        "-y": true
    },
    "filters": {
        "-qscale:v": "2"
    },
.....
```

# ffmpeg.py (lines 89+)

```
        execute.extend(self._read_configuration(phase='video_to_frames'))

        execute.extend([
            '-i',
            input_video
        ])

        execute.extend(self._read_configuration(phase='filters'))

        execute.extend([f'{extracted_frames}extracted_%0d.{self.image_format}'])

        self._execute(execute)
```

**Comment by CardinalPanda** [comment]
I was able to replicate this on the binaries. I'm not sure how many people this will affect though, most people are using video2x to be lossless, but I needed these commands for dandere2x to work.

**Comment by k4yt3x** [comment]
@CardinalPanda I'm looking into this right now. Should be able to get this sorted out today.

**Comment by k4yt3x** [comment]
@CardinalPanda I just pushed a new commit. Please see if it solves the issue

**Comment by CardinalPanda** [comment]
works!

**Comment by k4yt3x** [comment]
@CardinalPanda Perfect. I'm closing this issue then.
