### ISSUE TITLE
AI not maximizing GPU

### ISSUE THREAD

**Issue by ehobson** [k4yt3x/video2x#1000]
Hello,

I've noticed that video2x will not use more than 50% of my VRAM. How can I force it to maximize GPU memory allocation? This would likely also speed up processing.

**Comment by k4yt3x** [comment]
It could be bottlenecked elsewhere. You can try increasing the number of processes. Past some point it will request too much VRAM and crash. How much VRAM is used depends on the video processed. You can try it and find a optimal value. I don't think it will help too much though.
