### ISSUE TITLE
PLEASE UPDATE .EXE WITH THE NEW CODE..

### ISSUE THREAD

**Issue by Rasantis** [k4yt3x/video2x#1001]
please update the .exe file with the new code, the .exe it´s been a while that is not updated....

**Comment by Rasantis** [comment]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/13062480/video2x_error.log)

**Comment by k4yt3x** [comment]
I no longer have the original dev environment for the 4.x.x version, so I can't push more patches for the older version. I'm trying to make a new GUI for the 5.x.x version though.

Regarding your error, it looks like your GPU doesn't support Vulkan. Check GPU-Z.

> vkEnumeratePhysicalDevices failed -3
> invalid gpu device
