### ISSUE TITLE
'migrate_audio_tracks_subtitles' reuses 'frames_to_video > output_options'

### ISSUE THREAD

**Issue by Aidolii** [k4yt3x/video2x#102]
https://github.com/k4yt3x/video2x/blob/master/bin/ffmpeg.py#L155

no_audio.mp4 is already made with these output options, so specifying them a second time to create a new mp4 file will cause the video stream to be re-encoded.

**Comment by k4yt3x** [comment]
I believe that's there by mistake. See the newest commit's diff.
https://github.com/k4yt3x/video2x/commit/1280a791ecaa94c11e0b46f305d36cc30190f8b7
