### ISSUE TITLE
Upscale image in linux

### ISSUE THREAD

**Issue by gist31** [k4yt3x/video2x#1064]
Hi,
I found this project and took a look at it. Since I didn't find a .deb file, I decided to see if I needed Video2x using my Windows partition that I rarely use (I use an Ubuntu distro).
Then, since it looked like something that I would use, I decided to try to install it on linux. It was very difficult (mainly because I'm dumb, because in the end it was easy), but I managed to use it using docker.
I have an AMD gpu and every time I use the following command to upscale a video (the same command as in the wiki):

`sudo docker run -it --rm --device=/dev/dri -v $PWD:/host ghcr.io/k4yt3x/video2x:5.0.0-beta6 -i Desktop/edit.mp4 -o Desktop/edit-output.mp4 -p3 upscale -h 2160 -a waifu2x -n3`

My only problem is that when I used Video2x in Windows, I was able to also upscale images, and not only videos. Since I can't find anything in the wiki, I don't know what the command is to do so, and simply changing the input and output files doesn't work. 

Any help is appreciated,
thanks

**Comment by k4yt3x** [comment]
Sorry for the massive delay. There were too many issues and I was busy with other non-FOSS projects. Just got back to this project recently.

If you have Arch you could try the `video2x-git` package, else there's the binary release for Linux built with Debian Stable. If you're on any other distros/versions, you can either try the new container (pass `--help` for help with the new args) or compile it yourself. For compilation you could follow the instructions in the Makefile (debian target) or the workflow `.github/workflows/build.yml`. I except to add .deb releases in the future when the official release is out.

**Comment by k4yt3x** [comment]
Feel free to keep adding comments.
