### ISSUE TITLE
it was hanging at this point. after press "enter" key (after more than 2h) i continued - why?

### ISSUE THREAD

**Issue by kosuodhmwa** [k4yt3x/video2x#1067]
![image](https://github.com/k4yt3x/video2x/assets/24782840/e1485167-37f9-4f15-ad70-45b9e399b454)

**Comment by kosuodhmwa** [comment]
this is cracy, because the console wasn't seem waiting for input

**Comment by kosuodhmwa** [comment]
???

**Comment by kosuodhmwa** [comment]
yes, completed my not using anymore your product, lol

**Comment by k4yt3x** [comment]
Closed because a new version has been released. Read the homepage.
