### ISSUE TITLE
where can i get the latest build (compiled version) for windows?

### ISSUE THREAD

**Issue by kosuodhmwa** [k4yt3x/video2x#1068]
where can i get the latest build (compiled version) for windows?

**Comment by kosuodhmwa** [comment]
???

**Comment by kosuodhmwa** [comment]
yes, completed my not using anymore your product, lol

**Comment by Tsubajashi** [comment]
> 
> yes, completed my not using anymore your product, lol
> 
> 

i dont think the dev needs to explain to you basic github navigation.
go to releases. theres a compiled windows version.

**Comment by k4yt3x** [comment]
As I explained in another issue of yours, the project has been completely rewritten. All of the issues related to the older versions are closed. I can't reply to all 300 of them individually.
