### ISSUE TITLE
Don't think it's a bug, but trying to run the .exe and it just opens up and closes immediately?

### ISSUE THREAD

**Issue by rkgs** [k4yt3x/video2x#108]
## Environment Information

|Module|Version|
|-|-|
|`video2x`|2.7.1|
|`ffmpeg`|included|
|`waifu2x-caffe`|included|
|`waifu2x-converter-cpp`|included|

## Symptom

So I downloaded the full version, unzip and try to launch it like it says ("All you need to do is just to launch video2x.exe.") and I see a brief window pop up and then close. I grabbed a screenshot but it doesn't seem like much information is in that.

## Screenshots or Error Messages

![window](https://user-images.githubusercontent.com/6580931/59601804-596ece80-90c2-11e9-857c-e34e24b1c3ec.png)

**Comment by k4yt3x** [comment]
> All you need to do is just to launch video2x.exe.

This means that you do not need to have Python nor the dependencies installed, since the exe packs all of it within the executable.

You'll still have to launch it from the command line with all the arguments.

**Comment by rkgs** [comment]
Tried running the master with python after I got it reinstalled and this happens. Really weird because the video2x_setup.py finished without any issue. 

![failing](https://user-images.githubusercontent.com/6580931/59643971-1cd5be00-9128-11e9-8970-bbd25f8ea2de.png)

**Comment by k4yt3x** [comment]
that will be a duplicate problem of #106
