### ISSUE TITLE
Resume process

### ISSUE THREAD

**Issue by VanTanev** [K4YT3X/video2x#11]
Hello,

I was experimenting a bit with the program yesterday, and the core concept is neat but something that's really missing is a way to resume a video. In my testing, on a i7 5820k and 1080Ti, resolution doubling a single 22min 640x480 episode takes something close to 40 hours. 

It would definitely be useful to be able to stop the transcode and then resume later.

Any ideas about how that should be handled? I can help out with a patch.

**Comment by K4YT3X** [comment]
Oh that is indeed a **very** long time.
I'll look into adding a pause function for the program, but it would take me a while as I'm busy handling some contests right now.

Just to make sure, are you using `--gpu` or `--cudnn`?

**Comment by VanTanev** [comment]
With `--cudnn`, I am getting around `3.02s/it`, or around 28h for the episode.

With `--gpu`, it is around `4.20s/it`, or about 38 hours per episode.

**Comment by VanTanev** [comment]
![image](https://user-images.githubusercontent.com/202527/46246754-263cc000-c40b-11e8-9809-80e2f059414d.png)

Looking at this usage pattern, I suspected that we were losing a lot of time to start/stop. Indeed, when I started the same process through `waifu2x-caffee` manually (with the gui) I got just over 3 hours to convert all frames. This means that we shouldn't be executing separate commands for each image individually, but do a batch conversion.

**Comment by K4YT3X** [comment]
@VanTanev That was what I am worried about when I added the progress bar into the program.
I tried to make it look a little better and show the progress, but now it seems like it's really hurting the performance. I will restore the older version of that code, and it should work better.

I'll notify you when it's done.

**Comment by VanTanev** [comment]
Switching to `upconv_7_anime_style_art_rgb` model, I can complete the waifu2x step of full episode in 1:37h or so. Invoking `waifu2x-caffee-cui.exe` per image is definitely a HUGE waste of resources.

**Comment by VanTanev** [comment]
Since waifu2x-caffee-cui has STDOUT of one line per image, we can probably still track progress with a bit of effort I think.

**Comment by K4YT3X** [comment]
@VanTanev I'll see if I can make use of the STDOUT message.
For now, I have already restored the older code and it works like this:
![image](https://user-images.githubusercontent.com/21986859/46247247-78afb980-c3d6-11e8-95fd-8bd79be8a195.png)

**Comment by K4YT3X** [comment]
I will push the current version for you to see if it makes any difference for your videos.

**Comment by K4YT3X** [comment]
@VanTanev Also, for batch conversion, waifu2x engine only gives one "success" message for the entire conversion. Therefore I don't think I'll be able to make a progress bar without sacrificing (killing) the performance.
![image](https://user-images.githubusercontent.com/21986859/46247263-d7753300-c3d6-11e8-9261-a52664dbce31.png)

**Comment by K4YT3X** [comment]
@VanTanev I have pushed the code into the repo. Try it out!

**Comment by K4YT3X** [comment]
I forgot that this is not just about the batch conversion, but also the resuming function.
I'll reopen the issue and keep working on it.

**Comment by K4YT3X** [comment]
@VanTanev I just thought this through again. The enlarging process is taken care of by waifu2x. Therefore, I don't think there's anything that I can do unless I process each separately, which as you said, will cause the efficiency to drop drastically.

**Comment by wuast94** [comment]
I think about the performance too..my gtx 1080 chills and I can hear (yes) everything my pc do..and I hear every image is processed. And my gpu don't is used very much. 

So can we make it more "multithreaded"? Not frame by frame more like x frames at one time. Or x videos at the same time? 

Would love to say..hey..here is my folder with x video files..go for it and make magic :P

**Comment by K4YT3X** [comment]
All the enlarging are handled by the waifu2x-caffe binary. I'm not sure if we can multi-thread this thing.

**Comment by WSADKeysGaming** [comment]
https://github.com/imPRAGMA/W2XKit

PRAGMA's similar program let's you define how many threads waifu2x uses at
once.

**Comment by K4YT3X** [comment]
@WSADKeysGaming interesting. I guess we are going to have multithreading then.

**Comment by WSADKeysGaming** [comment]
Another thing I wanted to ask you about, is waifu2x doing one image at a
time and then closing? It's based off of deep learning, so I would suggest
it doing multiple images at a time before closing, it seemed to do that
faster when I did it manually, by opening up 12 programs, and then once I
had the frames extracted with virtualdub, I put about five thousand frames
in each program, and set them off overnight, and they were done. I got
entire 1080p TV show episodes converted to 4K that way.

**Comment by K4YT3X** [comment]
@WSADKeysGaming waifu2x processes multiple images before closing.
You can look at the GPU usage here https://github.com/K4YT3X/video2x/issues/11#issuecomment-425651230. Notice how the curve is shaped, it processes all the images in the sequence and then closes. It shouldn't be a concern that computing power is being wasted.

We're also doing multithreading right, so you should get an even-better performance if your hardware holds up to the challenges.

**Comment by WSADKeysGaming** [comment]
Great news! Hoping my 1080 will work it's magic then soon.

**Comment by K4YT3X** [comment]
@WSADKeysGaming I sure hope that too.
