### ISSUE TITLE
The "-qscale: v" command for JPEG quality does not work properly.

### ISSUE THREAD

**Issue by gample** [k4yt3x/video2x#110]
## Environment Information

|Module|Version|
|-|-|
|`video2x`|`2.7.1`|
|`ffmpeg`|`20190330-5282cba-win64-static`|
|`waifu2x-caffe`|`1.2.0.2`|
|`waifu2x-converter-cpp`|`5.2.4`|

## Symptom
The reason I use jpg instead of png is because I want to use jpg to maintain the yuv420 pixel format of the video file even though it is a lossy compression format, so I used "-qscale: v" command for JPEG quality but it does not work normally.

## Screenshots or Error Messages
<img width="734" alt="bug" src="https://user-images.githubusercontent.com/40362395/60021581-39946780-96cd-11e9-9dc8-2055cf987e5e.PNG">

Please paste your error message in the code block down below:
The reason is that the order of the "-qscale: v" command is incorrect.
Please check the image.

The ffmpeg settings in the json file are as follows:
  "ffmpeg": {
    "ffmpeg_path": "dependencies\\ffmpeg-latest-win64-static\\bin",
    "video_to_frames": {
        "-hwaccel": "auto",
		**"-qscale:v": 2,**
        "-y": true
    },
    "frames_to_video": {
        "input_options":{
        },
        "output_options":{
            "-vcodec": "libx265",
            "-crf": 17,
	        "-preset": "ultrafast",
            "-pix_fmt": "yuv420p"
        },
        "-y": true
    },
    "migrating_tracks": {
        "output_options":{
            "-map": "0:v:0?",
            "-map": "1?",
            "-c": "copy",
            "-map": "-1:v?",
            "-pix_fmt": "yuv420p"
        },
        "-y": true
    }
  },
  "video2x": {
    "video2x_cache_directory": "dependencies\\temp",
    "image_format": "jpg",
    "preserve_frames": false
  }
}

**Comment by k4yt3x** [comment]
It seems like you're using an outdated version. Please try 2.7.2.

**Comment by gample** [comment]
The command will not work in the latest release 2.7.1. However, it works well in 2.7.2 source code.
Thank you.

**Comment by k4yt3x** [comment]
Ok perfect.
