### ISSUE TITLE
Are there any ways to upscale videos more space efficient?

### ISSUE THREAD

**Issue by pFmuegge** [k4yt3x/video2x#1100]
Given i have a movie i want to upscale which is 480p and 2hours long (framerate is 24) the required disk space of the extracted frames is at about 200gb. Then upscaling all these images before kneading them back into a video will be another 1TB of storage space required when upscaled to 1080p. All together the exported and upscaled require about 1,2TB of storage space. And dont even think about the space required to upscale a video to 4k resolution...

Are there settings or parameters one could use already to help with this one?
Otherwise this would be a feature idea to implement in some upcoming version.

**Comment by ThrowawayLawd** [comment]
you can use lossless cut / avidemux to cut the video (losslessly) into smaller pieces
later you can join the pieces back to a full video without any issues

**Comment by pFmuegge** [comment]
> you can use lossless cut / avidemux to cut the video (losslessly) into smaller pieces later you can join the pieces back to a full video without any issues

First of all thanks for that reply @ThrowawayLawd . After that comment i dug through the net and have used "Losless Cut" for cutting into segments and "Clever FFMpeg GUI" for extracting/joining streams. They work quite well.


> @pFmuegge You can try using the 5.0.0-beta, which will pull frames from the source video with ffmpeg, upscale and append to the new video file on the fly, completely removing the need to store all intermediate frames. I upscaled a 45 minute DVD without disk IO and with ~16GB of RAM usage.

And also thank you for your reply @aa-ko . I will try the beta version next time i need to upscale something. The changelog of 5.0.0-beta does sound reeaally promising.

I think these answers wrap up this issue, so i'll be closing it.
Again thank you guys a lot.
