### ISSUE TITLE
Help with enhancing video to identify downed military plane

### ISSUE THREAD

**Issue by KeenDad** [k4yt3x/video2x#1101]
Hi, 

Looking for any direction here. I'm trying to use the Video2X program (V4.8.1) to enhance just out of focus video to be able to read an aircraft serial number from a remote submersible. I can't go into detail but the video was shot in 360P and is far enough away that the numbers just look like a line. Is there a particular driver that anyone could suggest, and or any settings? I have done the scale ratio up to 6, which definitely improved the resolution/detail, can now see gaps between numbers. But I need more detail, so thought maybe someone would know the best driver and settings possible to upscale a 360P movie. Using a reasonably decent Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz if that matters.

Any help or direction would be greatly appreciated. Thanks...KeenDad

**Comment by d0x360** [comment]
do you have topaz video ai?  can you post the video somewhere i can download it and upscale it with a couple different apps if you still need help
