### ISSUE TITLE
Bug: Interpolation arguments parsing errors

### ISSUE THREAD

**Issue by ncpa0cpl** [k4yt3x/video2x#1106]
I've run into two problems when trying to interpolate a video via the docker container on version 5.0.0-beta6

1. Incorrect algorithm validation, according to wiki there are 3 interpolation algorithms available (RIFE, CAIN and DAIN), none of which are allowed by the CLI. Here's the help message I am getting for the `interpolate` command: 
```sh
usage: video2x interpolate [--help] [-a {waifu2x,srmd,realsr,realcugan}] [-t THRESHOLD]

optional arguments:
  --help                show this help message and exit
  -a {waifu2x,srmd,realsr,realcugan}, --algorithm {waifu2x,srmd,realsr,realcugan}
                        algorithm to use for upscaling (default: rife)
  -t THRESHOLD, --threshold THRESHOLD
                        skip if the percent difference between two adjacent frames exceeds this value; set to 100 to interpolate
                        all frames (default: 10)
```
according to this message, allowed algorithms are all upscaling algorithms not interpolation algorithms. If I try to pass it a value that should be valid I get this error:
```sh
video2x interpolate: error: argument -a/--algorithm: invalid choice: 'rife' (choose from 'waifu2x', 'srmd', 'realsr', 'realcugan')
```

2. If no algorithm is provided then the above error does not occur, however another error is thrown:
```sh
10:13:59.701444 | ERROR    | 'Interpolator' object has no attribute 'process'
```
I am guessing this is related to the `-p` argument? Though curiously, this error happens regardless of if that argument is provided or not. (btw is this argument even allowed to the interpolate command? the help message doesn't list it, but the example on the wiki [here](https://github.com/k4yt3x/video2x/wiki/CLI#basic-frame-interpolation-example) does have it)

**Comment by a0n** [comment]
Seeing the same error using the docker container
