### ISSUE TITLE
Video2x needs the ability to process a list of folders with each folder in different resolutions and you should set a pause between files for your overheating GPU.

### ISSUE THREAD

**Issue by Nasdaq7** [k4yt3x/video2x#1108]
Video2x can currently only process a single folder at a specific resolution, say 1920p x 1080p, or some other ratio / resolution.

you need to be able to add to a list various folders and each folder will be processed with a different resolution, say 1600p x 900p, then 1280p x 720p, anything...

And you need to be able to specify precisely the output file name's format that will be the output of each folder....

And you can set a pause in seconds between files to avoid an overheating GPU.

**Comment by k4yt3x** [comment]
How I want to do this in the future would be to let the user set the options for each video added, or one setting for every group of videos added at the same time.

As for a timeout for the GPU to cooldown, I'll consider hooks so you can execute custom commands on certain events.

**Comment by Nasdaq7** [comment]
Hi,
What is important to add to your program is the ability to run two instances of the program at once, often you want one instance that is busy with a list and then you want to open another instance, a second instance, to quickly do an image... that would be fantastic ...!
Thank you!
Wynand Meyering.    On Thursday, 7 November 2024 at 23:55:29 SAST, K4YT3X ***@***.***> wrote:  
 
 


How I want to do this in the future would be to let the user set the options for each video added, or one setting for every group of videos added at the same time.

As for a timeout for the GPU to cooldown, I'll consider hooks so you can execute custom commands on certain events.

**Comment by k4yt3x** [comment]
> ...a second instance, to quickly do an image

That's already possible isn't it? Just pause the first instance and open another one?

**Comment by Nasdaq7** [comment]
Is there a way to resume a list from where you left off once you have stopped it?    On Sunday, 10 November 2024 at 05:16:47 SAST, K4YT3X ***@***.***> wrote:  
 
 



...a second instance, to quickly do an image


That's already possible isn't it? Just pause the first instance and open another one?

**Comment by Nasdaq7** [comment]
I may be going to make a list for you in the next few months and years for you about what I am missing,
your program is brilliant!

    On Sunday, 10 November 2024 at 05:24:44 SAST, Wynand Meyering ***@***.***> wrote:  
 
  Is there a way to resume a list from where you left off once you have stopped it?    On Sunday, 10 November 2024 at 05:16:47 SAST, K4YT3X ***@***.***> wrote:  
 
 



...a second instance, to quickly do an image


That's already possible isn't it? Just pause the first instance and open another one?

**Comment by Nasdaq7** [comment]
I've processed about 60,000 AI images...
    On Sunday, 10 November 2024 at 05:26:38 SAST, Wynand Meyering ***@***.***> wrote:  
 
  I may be going to make a list for you in the next few months and years for you about what I am missing,
your program is brilliant!

    On Sunday, 10 November 2024 at 05:24:44 SAST, Wynand Meyering ***@***.***> wrote:  
 
  Is there a way to resume a list from where you left off once you have stopped it?    On Sunday, 10 November 2024 at 05:16:47 SAST, K4YT3X ***@***.***> wrote:  
 
 



...a second instance, to quickly do an image


That's already possible isn't it? Just pause the first instance and open another one?

**Comment by k4yt3x** [comment]
> Is there a way to resume a list from where you left off once you have stopped it?

Right now, no. However, I'm going to do an overhaul of the GUI at some point like I mentioned before, and this feature is something we could consider when that happens.

Could you please fix how you're replying with email? The text looks very confusing on GitHub.

**Comment by Nasdaq7** [comment]
I thought the email communication was private! Thank you for the email communication. ;)

**Comment by k4yt3x** [comment]
After the 6.3.0 update, you can set different settings for each video. You can also add multiple videos together and apply the same settings to all of them. The file extension issue is tracked in #1264. As for GPU overheating, it doesn't quite make sense to me to add a pause between the videos as the GPU will still get however hot it gets when processing the videos. If you really want it to be cooler, tune it with MSI Afterburner or something to lower its Tjmax (whatever the NVIDIA equivalent is called) and power limits.
