### ISSUE TITLE
HELP?

### ISSUE THREAD

**Issue by Mark85Mete** [k4yt3x/video2x#111]
couldnt run it did I do sth wrong didnt know had to paste it here cause I dont know how to communicate other wise https://cdn.discordapp.com/attachments/444327782831357973/593085256018427904/122.png
```

**Comment by k4yt3x** [comment]
Please refer to the [Step-By-Step Tutorial](https://github.com/K4YT3X/video2x/wiki/Step-By-Step-Tutorial) for usages and sample commands.

**Comment by sat3ll** [comment]
You typed `-gpu` after `-m`. Notice the extra dash. It's either `gpu`, `cudnn` or `cpu`.
