### ISSUE TITLE
AMD GPU and Error

### ISSUE THREAD

**Issue by SimplyDex** [k4yt3x/video2x#114]
I am using the the RX 580 gpu so idk if it works with the cuDNN and stuff like that and I got an exception error problem as well. I don't know how to fix it, I've attached screen shots of it. 
![1](https://user-images.githubusercontent.com/25734755/60391613-4f2bd780-9aa7-11e9-8762-6c277961eadb.png)
![2](https://user-images.githubusercontent.com/25734755/60391614-505d0480-9aa7-11e9-9d84-2f923d460f5a.png)

**Comment by sat3ll** [comment]
1. your input .mkv is failing with FFmpeg. This might be a bug with FFmpeg (video2x_setup goes for the "nightly"/latest releases). To workaround this, convert your input file to another format, such as .mp4. Or manually download a "stable" ffmpeg release and extract the contents to `C:\Users\<your_user>\Appdata\Local\video2x\ffmpeg`. (You might need to enable the option to see hidden folders)
2. waifu2x_caffe is for NVIDIA. For AMD, use `waifu2x_converter_cpp` or `waifu2x_ncnn_vulkan`

**Comment by k4yt3x** [comment]
No response from issue owner.
