### ISSUE TITLE
video2x switches to internal GPU as soon as starting to upscale extracted frames

### ISSUE THREAD

**Issue by kngfbng** [k4yt3x/video2x#1140]
Trying to upscale a 720p video sample using RealSR NCNN Vulkan in the GUI.

I set GPU ID to 1 (GTX 1050 Ti) in video2x.yaml and confirmed it is set to 1 in the Driver Settings (I made sure to be in the RealSR tab). While extracting frames, CPU usage goes to almost 100% and GPU 1 hovers around 10% usage by Video Decode:
![video2x - extracting](https://github.com/user-attachments/assets/5f29bfaa-24e4-41a3-aec4-b4e7ae233845)

The moment the video2x console shows "[+] INFO: Starting to upscale extracted frames," it stops using the dedicated GPU at all and starts using 100% of the internal GPU by 3D:
![video2x - upscaling gpu1](https://github.com/user-attachments/assets/d0b3fa41-145f-48fb-8f9a-bbe7d1bf80b7)

![video2x - upscaling gpu0](https://github.com/user-attachments/assets/95a1b7ea-8315-4bf3-b0de-606156f4aff0)

I set video2x.exe, video2x_gui.exe, ffmpeg.exe and realsr-ncnn-vulkan.exe to use the dedicated GPU in both the NVIDIA Control Panel and Windows 10 Graphic Settings and tried running video2x as administrator. It never touches the dedicated GPU at all, let alone CUDA, and upscale is unsurprisingly glacially slow.

**Comment by thepaperiphone** [comment]
I haven't had a chance to try it yet, but I'm running into the same thing and found this comment, and a few other comments on other issues implying the same fix was needed:
https://github.com/K4YT3X/video2x/issues/53#issuecomment-477333206

> First install the CUDA toolkit from the nvidia website (https://developer.nvidia.com/cuda-toolkit)
and after that you still need the cuDNN library (https://developer.nvidia.com/cudnn), from which you paste the cudnn64_7.dll into the waifu2x-caffe folder that is located in AppData\Local\video2x\waifu2x-caffe
to test if it works you can start the waifu2x-caffe.exe and click "Check cuDNN" if everything is fine it will say something like cuDNN can be used
