### ISSUE TITLE
input output path type mismatch

### ISSUE THREAD

**Issue by Iliya5digital** [k4yt3x/video2x#1163]
[video2x_error.log](https://github.com/user-attachments/files/17043235/video2x_error.log)

**Comment by Iliya5digital** [comment]
why closed?

**Comment by k4yt3x** [comment]
Legacy version, duplicated issue. I'll soon release a GUI for 6.0.0 so I'll close all 4.x.x tickets. Just too many to process given I'm the only person going through all 300 issues.
