### ISSUE TITLE
Possible to add support for Android?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [k4yt3x/video2x#1170]
I'm interested in a solution for Android, to upscale images, but it seems very hard to find any solution of it.

Google offered only an example of using TensorFlowLite , but I can't find a way to create something myself, which uses a better model:

https://www.tensorflow.org/lite/examples/super_resolution/overview

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/examples/super_resolution/overview.ipynb

Is it possible to add support for this repository on Android?

**Comment by k4yt3x** [comment]
Try this:

https://play.google.com/store/apps/details?id=pro.archiemeng.waifu2x
https://github.com/ArchieMeng/ncnn-android-waifu2x-demo

Video2X, as its name suggests, is built for videos.
