### ISSUE TITLE
video2x 6.0 unable to load libavcodec.so.58 on fedora linux

### ISSUE THREAD

**Issue by BuyMyMojo** [k4yt3x/video2x#1174]
Just freshly downloaded the latest beta and tried to run it, this is the output  that I got:
```zsh
➜  video2x-linux-amd64 ./video2x 
./video2x: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
➜  video2x-linux-amd64 whereis libavcodec.so
libavcodec.so: /usr/lib64/libavcodec.so
```

I have these related packages installed:
```
ffmpeg
ffmpeg-devel
ffmpeg-free
ffmpeg-free-devel
ffmpeg-libs
```

<details>
<summary>Click to show system info (fastfetch output)</summary>

```sh
OS: Nobara Linux 40 (KDE Plasma) x86_64
Host: X570 Phantom Gaming 4
Kernel: Linux 6.11.2-202.fsync.fc40.x86_64
Uptime: 6 hours, 15 mins
Packages: 4044 (rpm), 3 (flatpak-system), 31 (flatpak-user)
Shell: zsh 5.9
Display (LC27G5xT): 2560x1440 @ 120 Hz in 32″ [External]
Display (M27U): 3840x2160 @ 160 Hz in 27″ [External] *
DE: KDE Plasma 6.1.4
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Nobara (Nobara) [Qt], Nobara [GTK2], Breeze [GTK3], Nobara [GTK4]
Icons: Papirus-Dark [Qt], Papirus-Dark [GTK3/4]
Font: Noto Sans (11pt) [Qt], Noto Sans (11pt) [GTK3/4]
Cursor: breeze (24px)
Terminal: konsole 24.8.0
CPU: AMD Ryzen 9 5900X (24) @ 4.95 GHz
GPU 1: Intel Arc A770 @ 2.40 GHz [Discrete]
GPU 2: AMD Radeon RX 7800 XT [Discrete]
Memory: 8.63 GiB / 46.95 GiB (18%)

```

</details>

<details>
<summary>Click to show fancy images (not required lol)</summary>

![video2x-termshot](https://github.com/user-attachments/assets/b59869f1-50b9-47d4-9344-0706fe1c0761)
![whereis-termshot](https://github.com/user-attachments/assets/3a42c59e-0b79-4d15-a35c-94a443659941)

</details>

**Comment by k4yt3x** [comment]
Yeah that's to be expected. It's compiled against specifically libavcodec.so.58. The version that's on your system is probably not 58. You'll need to compile it for that version.

**Comment by k4yt3x** [comment]
I made beta.2 based on ubuntu 24. Perhaps give it a try?

**Comment by k4yt3x** [comment]
> will it do this automatically during configure/make

@codecowboy CMake automatically finds the version that's available. 

> which version of libavcodec does beta2 expect and is it now merged into main?

I don't recall and honestly it doesn't matter. I'm only officially compiling for Ubuntu 22.04 and 24.04. It uses whichever version of the library that's available on those platforms. For the Arch package you compile it yourself against the library available on your system anyways.

I'm not sure what's the subject when you say "merged into main." What's merged into main?

**Comment by k4yt3x** [comment]
@codecowboy yeah the original binaries in beta.2 were built on Arch, hence this bug because the Arch version is way newer. If you have an Ubuntu you should be able to use the respective .deb just fine.

If you use any other system and encounter any issues with the build process, feel free to open another issue anytime.
