### ISSUE TITLE
video2x binary missing in docker image 6.0.0-beta.1

### ISSUE THREAD

**Issue by aureliensoria** [k4yt3x/video2x#1175]
Version: ghcr.io/k4yt3x/video2x:6.0.0-beta.1

Error when running docker command :
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/video2x": stat /usr/bin/video2x: no such file or directory: unknown.

When exploring the docker image there is indeed no video2x binary in any $PATH folder.

**Comment by axi92** [comment]
There is a video2x folder in the root dir but there are some other files

./var/lib/pacman/local/video2x-debug-r1.fa1dca8-1
./var/lib/pacman/local/video2x-debug-r1.fa1dca8-1/mtree
./var/lib/pacman/local/video2x-debug-r1.fa1dca8-1/desc
./var/lib/pacman/local/video2x-debug-r1.fa1dca8-1/files
./usr/lib/debug/usr/lib/libvideo2x.so.debug
./usr/lib/debug/usr/bin/video2x.debug
./usr/src/debug/video2x
./usr/src/debug/video2x/build
./usr/src/debug/video2x/build/realesrgan-prefix
./usr/src/debug/video2x/build/realesrgan-prefix/src
./usr/src/debug/video2x/build/realesrgan-prefix/src/realesrgan-build

Idk if the packman package was installed correctly?

**Comment by k4yt3x** [comment]
Hmmm I don't think the container was built properly. Building straigth from the Dockerfile on my machine works. I'll look into it.

**Comment by k4yt3x** [comment]
I pushed a new one. Give it a try.

**Comment by aureliensoria** [comment]
Everything seems ok now. Thank you very much !
