### ISSUE TITLE
Error: Filter type is required (libplacebo or realesrgan)

### ISSUE THREAD

**Issue by gianlucalauro** [k4yt3x/video2x#1176]
When i try to use the dockerized version, it give me this error.
I'm using Fedora Server 40, the latest docker version in a machine that has a ryzen 7 5700u (i can use only igpu)

This is the command:
`docker run -it --rm --device=/dev/dri -v $PWD:/host ghcr.io/k4yt3x/video2x:6.0.0-beta.1 -i my_input.mp4 -o output.mp4 -p3 upscale -h 1080 -a waifu2x -n3`

**Comment by aureliensoria** [comment]
The parameters required by video2x seems to have changed with version 6.0.0. The documentation is not up to date yet.

I  was able to start an upscale by providing the following parameters : 
docker run -it --rm --device=/dev/dri -v $PWD:/host ghcr.io/k4yt3x/video2x:6.0.0-beta.1 **-f realesrgan** -i my_input.mp4 -o output.mp4  **-r 4 -m realesrgan-plus-anime** 

You can have more details regarding the parameters with the following command:
`docker run -it --rm --device=/dev/dri -v $PWD:/host ghcr.io/k4yt3x/video2x:6.0.0-beta.1  --help`

**Comment by gianlucalauro** [comment]
It's working. Thank you so much!

**Comment by k4yt3x** [comment]
You can use `--help` to print the parameters for the new version:

![image](https://github.com/user-attachments/assets/825b6e8e-e5cd-499e-a544-557c5b9d0ddc)

The next version will also contain examples

![image](https://github.com/user-attachments/assets/6eb49b65-cc79-4301-8286-14d6c2064e87)

For anime, I recommend `-f realesrgan -m realesr-animevideov3 -r 4`
