### ISSUE TITLE
[V6.0.0] Hanging on 0% Progress

### ISSUE THREAD

**Issue by syntag** [k4yt3x/video2x#1182]
Hi I'm trying to upscale a video but it's been stuck on `0%` overnight for 8 hours now. It's a long video  `2 hours and 36 minutes`, so I understand it should take some time. But should it take this long with no signs of progression?

The video is a simple video with a black background with animated Halloween faces:

![image](https://github.com/user-attachments/assets/435ce496-e3ca-408f-adc2-0091c175e89f)

**Video2X screenshot**

![image](https://github.com/user-attachments/assets/6ce16b73-1c84-4af4-8584-376990f02c53)

**Comment by k4yt3x** [comment]
Interesting. It might be related to your hardware not supporting vulkan or some video codec issues. I'm adding a feature to display the console logs in the next version. After I add that you'll be able to copy the error messages.

**Comment by syntag** [comment]
> Interesting. It might be related to your hardware not supporting vulkan or some video codec issues. I'm adding a feature to display the console logs in the next version. After I add that you'll be able to copy the error messages.

Sounds great, thanks! And just for reference, here's my hardware info:
	•	Motherboard: EVGA Z170 Classified
	•	CPU: Intel i7 6700K 4.0 GHz
	•	GPU: 	EVGA GeForce RTX 3080 Ti FTW3 ULTRA
	•	RAM: 
Corsair Vengeance RGB Pro 64GB DDR4 3200
	•	PSU: Corsair HXi 1200W

I'm also using Windows 10

**Comment by k4yt3x** [comment]
Your hardware setup looks fine and it should work. I think it's with the video that you're using. I'll get the new version out soon so we can take a look at the logs. I'm guessing it's with the video's codec or something.

**Comment by k4yt3x** [comment]
@syntag Try the 6.0.0-beta.3 release. Enable the log console from Debug menu and see what it prints.

**Comment by syntag** [comment]
> @syntag Try the 6.0.0-beta.3 release. Enable the log console from Debug menu and see what it prints.

It logged this on initial start and hasn't logged anything since: 
![image](https://github.com/user-attachments/assets/da7a2e20-ff0f-4b5f-acf4-d15ab73b7c2a)

**Comment by k4yt3x** [comment]
You could use a more verbose log level like debug. That would show more details.

**Comment by k4yt3x** [comment]
I think at the root of the issue, RealESRGAN might have tossed out broken frames.

**Comment by k4yt3x** [comment]
The new version might fix you problem, which might be caused by the video not containing `nb_frames` in its metadata. I'm now reading this information using OpenCV. Please give 6.0.0-beta.4 a try. If it still doesn't work, you can reopen this issue.
