### ISSUE TITLE
win11 R7 5700G CPU core display execution program flash back 

### ISSUE THREAD

**Issue by liujing33** [k4yt3x/video2x#1190]
Uploading 20241015_212759.mp4…

![Snipaste_2024-10-15_21-30-12](https://github.com/user-attachments/assets/cd4cc9f1-19f2-4ea8-a760-cae5b20707ba)

**Comment by k4yt3x** [comment]
I don't think your video finished uploading

**Comment by k4yt3x** [comment]
You aren't providing enough information for me to understand what your problem is. Your video also didn't finish uploading. Please provide more information and reopen this issue.
