### ISSUE TITLE
[FEATURE] [v6.0.0 Beta] Add Real-CUGAN

### ISSUE THREAD

**Issue by reindex-ot** [k4yt3x/video2x#1198]
Add in the Real-CUGAN and Waifu2X filters.

**Comment by k4yt3x** [comment]
RealCUGAN is planned and will be added after RIFE. I currently don't have plans to add waifu2x unless there's very compelling proof that it offers widely needed features not provided by Anime4K, RealESRGAN, nor RealCUGAN. I'll edit the title to only include RealCUGAN for now. For waifu2x, which is a separate topic, another ticket could be created for that discussion.
