### ISSUE TITLE
[error] cannot find veruntime140_threads.dll

### ISSUE THREAD

**Issue by haohaoxiao** [k4yt3x/video2x#1200]
win11 home edition

![图片](https://github.com/user-attachments/assets/c700403a-4cd6-4644-a7b5-cc285fef132d)

**Comment by k4yt3x** [comment]
I'll consider linking this VC runtime statically or put the redistributable in the installer.

**Comment by k4yt3x** [comment]
I added a new installer that will automatically install the VC++ runtime. You can give it a try: https://github.com/k4yt3x/video2x/releases/download/6.0.0/video2x-qt6-windows-amd64-installer.exe
