### ISSUE TITLE
有教程嘛，新人看不懂

### ISSUE THREAD

**Issue by zozozo520** [k4yt3x/video2x#1203]
有教程嘛，新人看不懂

**Comment by k4yt3x** [comment]
后面我会做详细的教程和视频，其实用起来很简单，我给你个青春版教程

1. **点这个下载然后运行安装：**

https://github.com/k4yt3x/video2x/releases/download/6.0.0/video2x-qt6-windows-amd64-installer.exe

2. **把要处理的视频拖进去**

![image](https://github.com/user-attachments/assets/83e703bf-a10b-469f-93a6-904685b91b0a)

3. **设置参数**

比如我这里就是用 Anime4K（libplacebo 的一种 GLSL 着色器）的 A+A 模式，输出 3840x2160 (4K)：

![image](https://github.com/user-attachments/assets/adbfba0d-b729-4d1f-b2b9-8ba282e114cd)

想看具体说明的话鼠标移上去都有详细说明：

![image](https://github.com/user-attachments/assets/11844d24-f187-4f87-9f8e-c91130d0e06e)

5. **点击开始**

![2024-10-31_01-31](https://github.com/user-attachments/assets/0ebc1d29-f14f-4c13-ab1c-05fdbd5514af)

然后你等它完成输出的视频就会在原视频的旁边

![image](https://github.com/user-attachments/assets/34c58aee-362b-4801-921f-ce0d6ca2f37f)

**Comment by 948024326** [comment]
想问下，这个项目可以处理图片的吗？ 我尝试了一张图片报错了 @k4yt3x

**Comment by k4yt3x** [comment]
可以的，你那张图的输出尺寸太大了，你可以试试缩小点或者把编码器改成 png 试试看
