### ISSUE TITLE
Improving quality without increasing resolution

### ISSUE THREAD

**Issue by Sankyuubigan** [k4yt3x/video2x#1207]
is there a function to just improve video quality, sharpness and so on, without increasing resolution ? I don't need to increase resolution, I just need to increase quality, apparently the camera wasn't very good.

**Comment by k4yt3x** [comment]
For anime you could use Anime4K and set the output resolution the same as the input. For RealESRGAN, there's no 1x model so you'll have to do at least 2x the original resolution then downscale if you really have to.
