### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by Rovoska** [k4yt3x/video2x#1209]
Stumbled across this recently, and tried to install it only to encounter this issue

![image](https://github.com/user-attachments/assets/d3a680e9-efb5-41dc-86a8-785c90a34c0b)

![image](https://github.com/user-attachments/assets/f736ff0a-f16a-423e-8a32-1a9a0b7dab1e)

![image](https://github.com/user-attachments/assets/1f88978e-7b40-457c-a015-eafaf979421d)

Where it claims none of these can be found, and that reinstalling may fix the issue. Reinstalling hasn't changed anything though, and the portable version does the exact same thing. Using Windows 10 Pro, not the N version. Any idea on why/where I should look?

**Comment by Rovoska** [comment]
Leaving this for anyone else; for whatever reason the Media Feature Pack had gone missing, and that fixed the issue.

**Comment by k4yt3x** [comment]
I've updated the title so it's easier for other folks to search.

> ...and that reinstalling may fix the issue.

This generic error message is generated by Windows, not my application, nor do I have much control over what it says.
