### ISSUE TITLE
arch install unable to find librealesrgan-ncnn-vulkan.so

### ISSUE THREAD

**Issue by BuyMyMojo** [k4yt3x/video2x#1215]
When installing video2x-git attempting to run anything causes it to fail
```
❯ video2x --help
video2x: error while loading shared libraries: librealesrgan-ncnn-vulkan.so: cannot open shared object file: No such file or directory
```

~~This is with separately installing the `realesrgan-ncnn-vulkan` package~~

Edit: I've noticed `realesrgan-ncnn-vulkan` only provides an executable and not a .so file

**Comment by BuyMyMojo** [comment]
manually building `video2x-git` and copying it from `video2x-git/src/video2x/build/realesrgan_install/lib/` to `/usr/lib/` works just fine, I'm not versed enough in editing make files make this done automatically

**Comment by k4yt3x** [comment]
Huh maybe I broke something. Let me check.

**Comment by k4yt3x** [comment]
You are absolutely right. I broke the installation rule

**Comment by k4yt3x** [comment]
Should be fixed now. Thanks for the issue.
