### ISSUE TITLE
Python based files in bin folder for linux

### ISSUE THREAD

**Issue by Tortoise17** [k4yt3x/video2x#1219]
I am trying to install on linux based machine under python envs. I am surprised that how the instructions in the tutorials are given they are not possible/available completely. Where I can find the bin folder with python .py files for installation as shown in image?

**Comment by k4yt3x** [comment]
That document definitely needs to be updated... This program is no longer base on Python. You can install the deb file in the releases if you're using Ubuntu 24.04, or the `video2x-git` package if you're using Arch Linux. For other platforms you'll have to build it yourself.

**Comment by Tortoise17** [comment]
Unfortunately I am using CentOS and if there is easy solution for CentOS?

**Comment by k4yt3x** [comment]
Docker containers could work, although I'm not sure what's the equivalent of NVIDIA container toolkit for CentOS/RHEL. I'm also not sure about the status of NVIDIA drivers on CentOS.

**Comment by k4yt3x** [comment]
While you technically could use CentOS, I'd say Ubuntu and Arch would be much easier for this task. The container documentations are also written for Ubuntu/Debian. I just can't cover every distro out there.
