### ISSUE TITLE
Linux gui

### ISSUE THREAD

**Issue by ManuXD32** [k4yt3x/video2x#1230]
Hey, I've been trying to use the GUI on linux but it seems like it's not supported? I'm asking because I saw an issue marked as complete with this question.

Thanks!!

**Comment by k4yt3x** [comment]
I'm not sure which issue you're referring to. The new GUI technically supports Linux, but I have only pre-compiled it for Windows. Cross-platform is complex. It's just gonna be extra work to make it work on Linux.

**Comment by ManuXD32** [comment]
Oh okay, didn't know it wasn't built on the release. I'll try to compile it. Thanks!!
