### ISSUE TITLE
[Feature Request] Lossless encoding

### ISSUE THREAD

**Issue by ShortyCM** [k4yt3x/video2x#1232]
Being able to use x265 lossless encoding will likely be useful in some cases.  This may or may not work: 

https://github.com/k4yt3x/video2x/compare/master...ShortyCM:video2x:master
https://github.com/k4yt3x/video2x-qt6/compare/master...ShortyCM:video2x-qt6:master

I'd test it myself but don't currently have any dev tools installed yet after a recent Windows do-over, and not sure when I'll have time to get all that installed, too.

**Comment by k4yt3x** [comment]
I've closed the two PRs for now. I appreciate your work, though I'd like to implement something that's more versatile if anything were to be added. See my comments in the PRs for more detail.

**Comment by k4yt3x** [comment]
Implemented in https://github.com/k4yt3x/video2x/commit/3215c898700cf1aaaa59ab8455a00ca88664a897.

You can now specify any AVOptions with `--extra-encoder-option, -e`. For setting libx265 lossless to 1, do `-e x265-params=lossless=1`.

![image](https://github.com/user-attachments/assets/3a4a6b9f-d13b-44a4-89b7-aed4c963fd14)

This will be included in the next release. I'll consider when to add full support of this in the GUI.

**Comment by k4yt3x** [comment]
Another screenshot just to show the currently supported encoder options:

![image](https://github.com/user-attachments/assets/333966ec-eb2a-4c1b-b1ce-e7a394924a5a)

**Comment by k4yt3x** [comment]
I'll also leave this here. Full change for this implementation:

https://github.com/k4yt3x/video2x/compare/169509b..HEAD
