### ISSUE TITLE
Unable to Select Nvidia GPU in "GPU Selection"

### ISSUE THREAD

**Issue by ramaadhiguna** [k4yt3x/video2x#1237]
Hello, Thank you for the amazing work on Video2X. I have encountered an issue regarding GPU selection in the software.

## Issue Description
I am unable to select my Nvidia GPU (RTX 4060 8GB) under the "GPU Selection" option. The option to choose a GPU does not appear in the settings.

## System Information
Laptop Model: Lenovo LOQ 15IRH8
Processor: Intel Core i7-13620H
Memory: 32 GB RAM
GPU: Nvidia RTX 4060 (8 GB VRAM)
Operating System: Windows 11 Home 23H2
Video2X Version: QT6 6.1.1 ([Using installer provided from video2x github page](https://github.com/k4yt3x/video2x/releases/download/6.1.1/video2x-qt6-windows-amd64-installer.exe))
Nvidia Driver Version: 566.14
CUDA Toolkit Version: 12.6 Update 3

## Steps to Reproduce
- Launch Video2X.
- Navigate to the GPU Selection menu.
- Observe that there is no option to select my Nvidia GPU.

## Expected Behavior
I expected to see an option to select my Nvidia GPU (RTX 4060) under "GPU Selection."

## Actual Behavior
The "GPU Selection" menu does not show an option to select the Nvidia GPU, leaving me unable to utilize its processing capabilities for upscaling.

## Screenshot
![image](https://github.com/user-attachments/assets/1c2c7f65-e4d3-4ef2-bbe2-b2c7972d46e2)

**Comment by ramaadhiguna** [comment]
Resolved, I re-installed the Video2x and the Nvidia option finally there. Perhaps it was caused that I installed the Cuda after I installed Video2x. Clossing this issues

**Comment by k4yt3x** [comment]
Oh nice, I was just pulling my hair out thinking what it could have been 😂

**Comment by k4yt3x** [comment]
Video2X just calls the Vulkan functions. If v2x doesn't see the GPU it's because the Vulkan loader doesn't see it.
