### ISSUE TITLE
[Bug] MSVCP140.dll silent crash

### ISSUE THREAD

**Issue by BoringName15** [k4yt3x/video2x#1240]
I've already solved this issue by updating microsoft C++ redistributables but I think how the error was handled is a problem and worth letting you know.

Video2x would immediately close on my second machine with no errors even with logging enabled. Using the command line was the same. It would just close immediately with no errors listed.

I had to check windows event viewer to see details of the crash and that it was caused by an exception from MSVCP140.dll

The system was on version 14.28, once I updated the redistributables, the new version of 14.42 worked successfully.

If it's possible maybe set a minimum runtime version required and prompt the user to update if the system is below this version.

Also, you probably already know but some of the command line documentation on the wiki page is out of date. Specifically related to ffmpeg extra encoder options.

edit: just to clarify it would crash when I clicked start.

**Comment by BoringName15** [comment]
Keep in mind some people don't use the installer. I just extracted the zipped version to a folder and ran it from there.

**Comment by BoringName15** [comment]
It did run in the case I reported, it didn't crash until I clicked "Start" so I'd assume in theory you could do a check when Start is clicked and abort the process if the version is too old to avoid the crash then notify the user to update the runtime libraries.

**Comment by k4yt3x** [comment]
Added a check in the new version to prompt the user if the VC runtime version is below 14.42.
