### ISSUE TITLE
Google Colab "--input" error

### ISSUE THREAD

**Issue by pin6pts** [k4yt3x/video2x#1249]
Went through all the steps using Google Colab but I get an odd error at step 3 "video2x [critical] "Error parsing options: option '--input' cannot be specified more than once".

From what I see in the code "--input" isn't being duplicated. Anyone else have this error or know what to do.

Trying to use filter: realesrgan, model: realesrgan-plus. Everything else was left as default. My file is an .mp4 saved under My Drive of Google Drive.

**Comment by k4yt3x** [comment]
I just made some changes to the notebook. Can you try again?

**Comment by k4yt3x** [comment]
I'm closing this issue for now. Feel free to add more comments or reopen if the issue persists.

**Comment by pin6pts** [comment]
Sorry, I’ve been really busy. I’ll try again this evening. On Dec 9, 2024, at 2:12 PM, K4YT3X ***@***.***> wrote:﻿
I'm closing this issue for now. Feel free to add more comments or reopen if the issue persists.

**Comment by k4yt3x** [comment]
Oh that interesting. Perhaps there's rotation information that got lost. If you can open a new issue and give me a sample video I can fix it.
