### ISSUE TITLE
reduce cpu and diskio for updating upscaling progress

### ISSUE THREAD

**Issue by nihui** [k4yt3x/video2x#125]
video2x always scan the entire folder to count images per second.
It is quite slow for folders with lots of images, and consumes cpu resource and diskio.

In fact, the waifu2x driver knows the progress, and is able to report the info via printing to stderr or writing to a pipe/file, so that video2x can load the progress immediately. No need to scan filesystem over and over.

```
total_frames_upscaled = len([f for f in os.listdir(self.upscaled_frames) if f[-4:] == f'.{self.image_format}'])
```

**Comment by k4yt3x** [comment]
> In fact, the waifu2x driver knows the progress, and is able to report the info via printing to stderr or writing to a pipe/file, so that video2x can load the progress immediately.

Would love to know how that can be achieved.
I understand scanning the directory isn't an elegant solution.

**Comment by k4yt3x** [comment]
To this date, there are no means of knowing waifu2x or any driver's internal processing progress.
I'll close this issue since I don't think it's possible to implement at this point.
You're welcome to reopen or post updates.
