### ISSUE TITLE
'Fail to load translation for locale' in 6.0.0-6.1.1

### ISSUE THREAD

**Issue by GRFTSOL** [k4yt3x/video2x#1250]
OS: Windows 10
Locale: zh_CN
Default language is English, when change language to any other language, error pops up
![图片](https://github.com/user-attachments/assets/63936a12-c682-4994-bce4-d421572547c3)

**Comment by k4yt3x** [comment]
Can you check if the translation files exist? They should be alongside the exe like this:

![image](https://github.com/user-attachments/assets/238ee6f1-d055-4f99-a9dc-b11a354fc6c9)

**Comment by GRFTSOL** [comment]
> Can you check if the translation files exist? They should be alongside the exe like this:
> 
> ![image](https://private-user-images.githubusercontent.com/21986859/393505169-238ee6f1-d055-4f99-a9dc-b11a354fc6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzA1OTIsIm5iZiI6MTczMzU3MDI5MiwicGF0aCI6Ii8yMTk4Njg1OS8zOTM1MDUxNjktMjM4ZWU2ZjEtZDA1NS00Zjk5LWE5ZGMtYjExYTM1NGZjNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMjZmNGM2OTA2YjdjZGY4NWYyY2EyOGVlYjMzNTExZmMwOWQ1MmExNjE2YjQzNmUzNGVhMjkxM2ZhZTYyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1IHQbr08eaAZPH0NRHXNZpCU-qNT0Ca0b0PrFLTLiJI)

![图片](https://github.com/user-attachments/assets/dd863cd2-50e7-478b-9d47-8ee05276aa69)
Yes, the translation file is along side of the exe.

**Comment by GRFTSOL** [comment]
> Can you check if the translation files exist? They should be alongside the exe like this:
> 
> ![image](https://private-user-images.githubusercontent.com/21986859/393505169-238ee6f1-d055-4f99-a9dc-b11a354fc6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzEyMTIsIm5iZiI6MTczMzU3MDkxMiwicGF0aCI6Ii8yMTk4Njg1OS8zOTM1MDUxNjktMjM4ZWU2ZjEtZDA1NS00Zjk5LWE5ZGMtYjExYTM1NGZjNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NWZkMjlhZTQ4ZTkxNWRlMDhiYzkxMWM2ZTZiY2VlNDVkNTA0MGM0ZjRkNTA0NWZiZGEzZDVhYThjNWRlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VYlaygErDX_R_k9WclcJfdzcOh7DTlcpFU0vwh_aOsA)

It seems to be an issue caused by folder/file's ownership, I changed the ownership of whole folder to let my account have permission to `read and execute`, the error disappears, and translation also can be applied. 
So I assume it may not be a problem of video2x, close this issue for now.
