### ISSUE TITLE
Cache folder

### ISSUE THREAD

**Issue by farouk-bi** [k4yt3x/video2x#1251]
I couldn't find the cache folder like the older versions of the app so I can check the extracted images

**Comment by k4yt3x** [comment]
6.0.0 does not extract the frames anymore. The old <4.0.0 versions do that and it's very inefficient and often takes up hundreds of gigabytes of disk storage. It now a pipeline/frame-serving architecture so no intermediate data is written to disks anymore. You can read more here:

https://docs.video2x.org/developing/architecture.html

If you need to test the output, you can abort it after it processes the video for like 5% or something and the output video will be incomplete but playable. You can test the output this way.
