### ISSUE TITLE
[Feature Request] Notify Users About Available Updates with Option to Update Directly

### ISSUE THREAD

**Issue by 123-soleil** [k4yt3x/video2x#1258]
Hi,

I would like to suggest a feature to enhance the user experience:

Notification of Updates:

When a new version of the application is available, notify the user with a clear message (e.g., a popup, banner, or system notification).
Include basic information about the update, such as the version number and a short description of the changes or improvements.
Option to Update:

Allow the user to initiate the update process directly from the notification.
If possible, provide options to defer the update (e.g., "Remind me later") or view more details before proceeding.
This feature would make it easier for users to stay up-to-date and benefit from the latest improvements without manually checking for updates.

Thank you for considering this request!

Best regards

**Comment by k4yt3x** [comment]
Agreed. This is already planned for the next version actually.

**Comment by 123-soleil** [comment]
Wonderful!

if it possible, this feature could also be used to download non-default RIFE versions for those who need them

**Comment by k4yt3x** [comment]
There:

![image](https://github.com/user-attachments/assets/eb24c971-d942-4e65-818f-e47420881872)

RIFE is more complex to implement. Honestly I don't think the older models are worth trying either. I'll leave it for later.
