### ISSUE TITLE
[Feature Request] Combine Upscaling and Interpolation in a Single Pass

### ISSUE THREAD

**Issue by 123-soleil** [k4yt3x/video2x#1259]
Hi,

I would like to suggest a feature to improve the efficiency of the application:

Single-Pass Upscaling and Interpolation:

Instead of requiring separate steps for upscaling and interpolation, it would be great if both processes could be performed in a single pass.
This would save processing time and reduce the complexity for users who often use these two features together.
Use Case:

This feature would be especially helpful for workflows involving video or image enhancement, where combining these steps can significantly improve efficiency and user experience.
If this is technically feasible, it could be a valuable addition to the tool.

Thank you for considering this request!

Best regards

**Comment by k4yt3x** [comment]
It's not a bad idea, but it will make the software too complicated. Maybe I'll reconsider this at some point later, but right now the priority is to improve user guidance and performance optimizations. This will be a topic for much later when the higher priority tasks are completed. I appreciate the advice though.
