### ISSUE TITLE
Use non internal gpu

### ISSUE THREAD

**Issue by CodeDashie** [k4yt3x/video2x#126]
Video2X version 2.8.1

https://i.imgur.com/vGZaDjP.jpg
https://i.imgur.com/kRQ656u.jpg

How to use my non internal gpu (NVIDIA GeForce GTX 1050)? Using a laptop. Awesome program btw. Thanks.

**Comment by k4yt3x** [comment]
You can change the GPU id used by waifu2x.

![2019-07-20_18-12-54](https://user-images.githubusercontent.com/21986859/61584687-a91a3d00-ab3b-11e9-885b-a0d2ebc4a5de.png)
