### ISSUE TITLE
can this project process the image?

### ISSUE THREAD

**Issue by 948024326** [k4yt3x/video2x#1265]
i test the mp4 format file , it works well
but the image format get wrong,Does this project support image format processing？
![image](https://github.com/user-attachments/assets/e8d62f82-5819-4332-b7b2-bcc46dabfa4a)

Thanks @k4yt3x

**Comment by k4yt3x** [comment]
Yeah it can process images. Your output image dimensions is just way too large for the encoder. Try lowering it.

**Comment by 948024326** [comment]
> Yeah it can process images. Your output image dimensions is just way too large for the encoder. Try lowering it.

我现在处理了一张普通的图片，显示是成功
![Uploading image.png…]()

**Comment by 948024326** [comment]
> Yeah it can process images. Your output image dimensions is just way too large for the encoder. Try lowering it.

我现在处理了一张图片，显示是成功了，但是打不开？
![image](https://github.com/user-attachments/assets/dfdd2180-929b-4e1d-ae91-83c30d8ec44d)
![image](https://github.com/user-attachments/assets/15a23c18-7e9d-4235-a0ed-b548c38a2771)

**Comment by 948024326** [comment]
这是日志
![image](https://github.com/user-attachments/assets/a6548807-f05e-4c73-805b-161199725bca)

**Comment by 948024326** [comment]
please help?

**Comment by k4yt3x** [comment]
Try setting the codec to png and the suffix to .png

**Comment by k4yt3x** [comment]
Also take a look at https://github.com/k4yt3x/video2x/issues/1204

**Comment by k4yt3x** [comment]
Closed as it's a question.
