### ISSUE TITLE
ERROR: An exception has occurred

### ISSUE THREAD

**Issue by thepinkbanana** [k4yt3x/video2x#127]
Hi, this is my second attempt using this tool. I got the same error about can't open extracted frame.
I installed the tool with video2x_setup.py. The only difference I added between each attempt is I updated my NVIDIA driver to latest version before running the 2nd attempt.
I do notice however I keep running out of space of my C: drive (running the C: drive with 128 GB SSD and I'm using a whole full featured movie to test this since I don't have anything else).

[Here's a Pastebin of the log](https://pastebin.com/acYgU6bm)

Update before posting: I downloaded a 5 second 480p clip to remake to 1080p and it is working beautifully. So if I need to guess, the first two attempt failed because I am indeed running out of space.
If this isn't the issue, it would be nice to be able to change where the temp folder is, regardless :P
Thanks, and any help is appreciated!

**Comment by k4yt3x** [comment]
```
[image2 @ 0000024a61f37ec0] Could not open file : C:\Users\Z2RAYN~1\AppData\Local\Temp\video2x\tmp8vvp5lwu\extracted_15952.png
av_interleaved_write_frame(): I/O error
```

Are you sure you have enough disk space?

**Comment by thepinkbanana** [comment]
Yeah, that's exactly I was worrying about. I don't unfortunately for a whole movie, running C: with 128 GB SSD and I only have like 45 GB free.
Is it possible to change where the temp folder video2x would use? I do have much more space on D: partition with hard drive.

**Comment by thepinkbanana** [comment]
Never mind, figured it out.
On line 300-301 of video2x.py I can change it to specific path.
`if not video2x_cache_directory:`
`video2x_cache_directory = "D:\\New Folder"`

Thanks anyway for the help!

**Comment by k4yt3x** [comment]
@thepinkbanana This is what  you actually need in `video2x.json` configuration file.
![2019-07-24_22-48-58](https://user-images.githubusercontent.com/21986859/61842183-cd04b800-ae86-11e9-8f1c-9a98c074848f.png)

**Comment by thepinkbanana** [comment]
Well.... I never said I'm not an idiot, I didn't check the json file :P
Thanks, will do it and fix it properly.
