### ISSUE TITLE
Additional ubuntu dependency

### ISSUE THREAD

**Issue by jason-kane** [k4yt3x/video2x#1273]
ubuntu (at least 24.04) will need:

sudo apt install libboost-program-options1.83.0

**Comment by k4yt3x** [comment]
It's already specified in the deb

**Comment by jason-kane** [comment]
That is weird, it installed for me but complained about the missing .so
when I tried to run it; I did install it from “dpkg -i” I guess it could be
that.

Thanks for the project, it’s really helpful!

**Comment by k4yt3x** [comment]
dpkg doesn't install the dependencies. You'll need to do `sudo apt-get install ./video2x-linux-ubuntu2404-amd64.deb`. This way APT will install all the dependencies. It's in the docs: https://docs.video2x.org/installing/linux.html#ubuntu
