### ISSUE TITLE
[video2x-qt6] packaging on Arch

### ISSUE THREAD

**Issue by Misaka13514** [k4yt3x/video2x#1274]
Package version:
```
video2x-git 6.3.1.r12.g2cfdb69-1
video2x-qt6-git 6.3.1.r8.gcb7492c-1
```

- [x] Translation files should be [installed](https://github.com/k4yt3x/video2x-qt6/blob/cb7492ced62a632ec3072a571a7b4d8d14486cd8/CMakeLists.txt#L186) and [loaded](https://github.com/k4yt3x/video2x-qt6/blob/cb7492ced62a632ec3072a571a7b4d8d14486cd8/src/mainwindow.cpp#L480)
- [ ] [Freedesktop icon](https://github.com/k4yt3x/video2x-qt6/blob/cb7492ced62a632ec3072a571a7b4d8d14486cd8/resources/video2x-qt6.desktop#L6) is not shown on GNOME, is this just me or fix needed?
- [x] `clang` should be added to `makedepends`

**Comment by k4yt3x** [comment]
Yeah you're right, the translation files should be installed. I'll need to check how and where they should be installed.

**Comment by k4yt3x** [comment]
I *think* I fixed it in this commit: https://github.com/k4yt3x/video2x-qt6/commit/d3655971a11849124e9aea8bb126d812f78f4564. I'll do some more tests.

**Comment by Misaka13514** [comment]
I have confirmed `changeLanguage` working on `6.3.1.r9.gd365597-1`, thank you!

**Comment by k4yt3x** [comment]
clang added to makedepends.

**Comment by k4yt3x** [comment]
As for the last issue with the icon, I checked and it seems to be compliant with XDG standards:

```
./
└── video2x-qt6/
    └── usr/
        ├── bin/
        │   └── video2x-qt6*
        └── share/
            ├── applications/
            │   └── video2x-qt6.desktop
            ├── icons/
            │   └── hicolor/
            │       └── 1024x1024/
            │           └── apps/
            │               └── video2x.png
            └── licenses/
                └── video2x-qt6/
                    └── LICENSE
```

I'm not sure what else is needed for it to display correctly. I'm using i3 with rofi right now and I can't see icons.

**Comment by Misaka13514** [comment]
Maybe try adding more resolutions or try using absolute path to the icon

**Comment by k4yt3x** [comment]
The standard 1024x1024 resolution should work, and I don't think absolute path in the desktop file is standard practice. The main issue here is that I can't confirm the change works. rofi doesn't display icons. I'll need a VM or someone else to confirm it.

**Comment by Misaka13514** [comment]
I can test it for you, just send me the PKGBUILD :)

**Comment by Misaka13514** [comment]
![Screenshot From 2024-12-28 20-20-24](https://github.com/user-attachments/assets/77afa750-c449-4da5-8a32-d59a2076b0e8)

The icon is not showed on KDE either according to my test in a VM

**Comment by k4yt3x** [comment]
Can you please try the newest `video2x-qt6-git`? I've updated more icon resolutions and it seems to work.

**Comment by Misaka13514** [comment]
It works, thank you!
