### ISSUE TITLE
Bug: Chinese characters loaded in Japanese

### ISSUE THREAD

**Issue by reindex-ot** [k4yt3x/video2x#1276]
Chinese characters are loaded in Japanese.
https://heistak.github.io/your-code-displays-japanese-wrong/

**Comment by k4yt3x** [comment]
I had to update four translations, and three of them I don't speak at all, so I ChatGPT'd most of it. If there are character issues, it's most likely GPT that made the mistake.

**Comment by k4yt3x** [comment]
Fixed in https://github.com/k4yt3x/video2x-qt6/commit/9893ac1be611ba2abfb4e588266e2bfcc1783ad4
