### ISSUE TITLE
Full Video Not fully processing

### ISSUE THREAD

**Issue by ghyujkilop** [k4yt3x/video2x#1277]
For some reason it speeds up the whole thing when using ESRGAN 
https://www.mediafire.com/file/4emcpx806l7xn0e/extra01.wmv/file
https://www.mediafire.com/file/480bk5rtet05gtk/extra04.wmv/file
https://www.mediafire.com/file/evjrxpokobc8ge8/extra06.wmv/file

Any ideas? These are just some of the files this happens with. Other files can process normally.

I use Both Anime Presets, and standard other settings.

**Comment by k4yt3x** [comment]
I'll give it a try

**Comment by k4yt3x** [comment]
This is some rare video format. FYI, if you first convert it into MP4, it processes fine.

```bash
ffmpeg -i extra01.asx extra01.mp4
video2x -i data/extra01.mp4 -o data/output.mkv -e crf=20 -e preset=slow -p realesrgan -s 4 --realesrgan-model realesrgan-plus
```

**Comment by k4yt3x** [comment]
thub.com/user-attachments/assets/a4487ef5-47e0-4892-8500-1d408853b709

**Comment by ghyujkilop** [comment]
Anyway to have this set in the GUI?

**Comment by k4yt3x** [comment]
Not yet. I'll look into why it calculated the parameters incorrectly.

**Comment by ghyujkilop** [comment]
Yeah, there's other videos from the same have, that are like way old, and grainy as anything. What's a good setting to keep the grain in? The upscaling seems to move faces and things around like someone mixing a pancake with a spoon.

Thank you.

**Comment by k4yt3x** [comment]
So I've debugged the program to see why it's playing so fast. The weird thing is that the encoder context always has the right time base:

![image](https://github.com/user-attachments/assets/c06c5606-e5f7-4b2d-9760-901a92f59bd0)

... but somehow in the final video it's completely off. I don't quite understand why it's happening yet.

![image](https://github.com/user-attachments/assets/ec13d278-98ac-42c1-b925-4f3c691ca06f)

This value seems to be handled correctly in my program. Maybe it's some special behavior of the encoder.

**Comment by k4yt3x** [comment]
> What's a good setting to keep the grain in?

If you're using RealCUGAN, you can tune the noise settings. Make it lower to preserve more texture/grain. Other models are not tunable.

On the encoder's side, you can set the tune of the encoder like `tune = grain` for H.264 ([ref](https://trac.ffmpeg.org/wiki/Encode/H.264#Tune)).

**Comment by k4yt3x** [comment]
So I did some tests and checked the math again, the original frame rate calculates to ~90FPS. It's either an upstream bug or a broken file.

![image](https://github.com/user-attachments/assets/024e83f7-8289-4556-b2ce-dec17e142cb2)

**Comment by k4yt3x** [comment]
I think what might have happened here is that your video is using a timestamp that doesn't match the declared frame rate. You can convert it and manually set the framerate:

```bash
ffmpeg -i extra01.wmv -r 1 extra01.mp4
```

The `-r 1` here means 1 FPS. This will "fix" the file and allow it to be processed correctly.

**Comment by ghyujkilop** [comment]
Is there not a way using the back end to be able to identify what sort of file has been inputted? (When using the GUI I mean)

And also regarding the GUI, where might I find the grain setting? And how would the adjustment with that work?

Thank you for digging into this.

**Comment by k4yt3x** [comment]
The program has no issue identifying "what sort of file has been inputted." The issue is that your file:

- contains incorrect metadata (i.e., a broken file); and
- it is FFmpeg's C library that's having trouble working with it, not Video2X.

As for gain settings, you can add a custom option like this to set tune to grain for H.264:

![image](https://github.com/user-attachments/assets/a5d43472-c6c2-44bc-9127-aaf59b95d85d)
