### ISSUE TITLE
Upload new release version

### ISSUE THREAD

**Issue by NNowakowski** [k4yt3x/video2x#131]
Is it possible for you to upload a new release version.
The last release is v2.7.1 while the project is already on v2.9.0
I'd like to try out the vulkan driver which isn't supported in v2.7.1 yet but would rather not go through all the hassle to install everything myself.

**Comment by k4yt3x** [comment]
Sure. Will work on it.

**Comment by k4yt3x** [comment]
2.9.0 release published.
