### ISSUE TITLE
Image is "in use by another process"

### ISSUE THREAD

**Issue by HunterAP23** [k4yt3x/video2x#133]
## Environment Information

|commit e12db41213a87f5dce072373023b393f23b2bcb5|
|`Video2X`||

## Symptom

Sometimes while running a job, I run into a what seems to be a threading issue where a process is trying to access an image that is in use by another process.
These can occur both when taking the extracted frames and feeding into the waifu2x programs, or when takign the upscaled images and giving them to ffmpeg to put it back together into a video. The error message I have included below with a screenshot refers to the latter situation.

The exact command I'm running is fro ma batch script that loops over all video files in a directory, and it looks like the following:

```
for %%a in (*.avi) do (
	python D:\Downloads\CompTools\Media\video2x\bin\video2x.py -i "%%a" -o "%%~na_VULKAN_CUDNN.mp4" -m cudnn -d waifu2x_ncnn_vulkan -r 2 -b
)
```
You can substitute the `-m cudnn` with `-m gpu`, and `-d waifu2x_ncnn_vulkan` with the other possible choices for waifu2x, but the error still occurs.

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/14364070/62682173-7c628400-b989-11e9-922a-28f5e1cd67fd.png)

Please paste your error message in the code block down below:

```
Upscaling Progress: 100%|#########################################################9| 1438/1439 [05:28<00:00,  4.36it/s]2019-08-08 03:03:39.891448 [+] INFO: [upscaler] Thread 0 exiting
2019-08-08 03:03:39.894448 [+] INFO: Killing upscaled image cleaner

[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "D:\Downloads\CompTools\Media\video2x\bin\video2x.py", line 379, in <module>
    upscaler.run()
  File "D:\Downloads\CompTools\Media\video2x\bin\upscaler.py", line 351, in run
    fm.convert_video(framerate, f'{self.scale_width}x{self.scale_height}', self.upscaled_frames)
  File "D:\Downloads\CompTools\Media\video2x\bin\ffmpeg.py", line 164, in convert_video
    (upscaled_frames / frame_name).rename(upscaled_frames / regex.sub('.png', str(frame_name)))
  File "c:\python37\lib\pathlib.py", line 1319, in rename
    self._accessor.rename(self, target)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Downloads\\CompTools\\Media\\video2x\\cache\\tmpw20rrxou\\extracted_1158.png.png' -> 'D:\\Downloads\\CompTools\\Media\\video2x\\cache\\tmpw20rrxou\\extracted_1158.png'
Press any key to continue . . .
```

My suggestion for fixes:
1. Add a delay between the different tasks so the next task does not throw this exception when the previous task is still seemingly using the images.
2. Add exception handling to retry the job if this issue throws an exception.

**Comment by HunterAP23** [comment]
I believe I fixed it by changing some stuff in line 210 of upscaler.py:

```py
for image in frames:
    # move image
    while True:
        try:
            image.rename(thread_pool[0][0] / image.name)
        except Exception as e:
            print("Caught Image-Rename Exception on image " + str(image.name) +", continuing normally.")
            continue
        else:
            break
        # rotate list
         thread_pool = thread_pool[-1:] + thread_pool[:-1]
```

**Comment by HunterAP23** [comment]
Came across another instance of the same issue and applied a similar change on line 163 in ffmpeg.py:

```py
for frame_name in upscaled_frames.iterdir():
    try:
        (upscaled_frames / frame_name).rename(upscaled_frames / regex.sub('.png', str(frame_name)))
    except Exception as e:
        print("Caught Image-Rename Exception on image " + str(frame_name) +", continuing normally.")
        continue
    else:
        break
```

**Comment by k4yt3x** [comment]
I'll take a look into the error.
You can upscale an entire folder of videos. Just do `-i [folder]` instead of using a for loop.

**Comment by k4yt3x** [comment]
I never seemed to be able to reproduce this error.
I'll close it for now since it has been inactive, but if you are still able to reproduce this error, feel free to keep posting in this thread or reopen this issue.
