### ISSUE TITLE
hwaccel doesn't work due to position in the command line

### ISSUE THREAD

**Issue by ImportTaste** [k4yt3x/video2x#134]
You can't use -hwaccel at the end of an ffmpeg command, it has to be before the input. AFAIK -y can be used anywhere though, so:

This line
https://github.com/k4yt3x/video2x/blob/e12db41213a87f5dce072373023b393f23b2bcb5/bin/ffmpeg.py#L133

Should be moved up before https://github.com/k4yt3x/video2x/blob/e12db41213a87f5dce072373023b393f23b2bcb5/bin/ffmpeg.py#L122-L125

**Comment by k4yt3x** [comment]
Acknowledged. Will fix.

**Comment by justinian-balaskas** [comment]
OMFG I couldn't figure this out for the life of me

**Comment by k4yt3x** [comment]
![2019-08-11_23-56-01](https://user-images.githubusercontent.com/21986859/62845117-26f1e400-bcb5-11e9-8d9d-c186ff55521c.png)

I think that's fixed.
