### ISSUE TITLE
output_depth in converted images does not change from default of 8

### ISSUE THREAD

**Issue by sjscotti** [k4yt3x/video2x#135]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.9.0|
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

I set the `output_depth` value in the json file to 16, but the images saved in temp folder appear to be 8 bit per channel (i.e., they show up as bit depth of 32 in windows file explorer list.)  I am using png for the image format.
 
## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
Currently, v2x automatically detects appropriate image color depth from video codec.
Do you want to be able to overwrite the settings? I don't think making the color depth higher than input file codec will do you any good though.

![2019-08-12_0-03-17](https://user-images.githubusercontent.com/21986859/62845266-260d8200-bcb6-11e9-90bc-693ccaaba21c.png)

**Comment by sjscotti** [comment]
Hi
Thanks for the speedy response!  In my case, my input video was yuv420p which the figure above says has 12 bits per color channel (if I am interpreting what "bits_per_pixel" means correctly).  In the step of executing waifu2x from within video2x, the outputs from waifu2x are png files having 8 bits per color channel by default.  Setting the `output_depth` to 16 should have switched the png files that video2x produces from the waifu2x step to 16 bits per color channel, but they stayed the default value of 8.  I have tested the standalone waifu2x program on using the `-d `(`-output_depth`) flag and it correctly switches the png files it produces to 16 bits per color channel.  So I am assuming that there is a disconnect in how the  `output_depth`  parameter is passed to waifu2x.  That being said, the 16 bit per color channel files created are almost 6 times larger than the comparable 8 bit per color channel files, so having enough storage space for a concern.

**Comment by k4yt3x** [comment]
Just to let you know, is issue is acknowledged and investigation is in progress. However, due to the exam week schedule, it will take extra time to have this figured out.

**Comment by k4yt3x** [comment]
I believe this issue has been addressed.
You can now choose output pixel format for the extraction step.

![image](https://user-images.githubusercontent.com/21986859/82712484-94389980-9c77-11ea-9bc3-941e18f50904.png)
