### ISSUE TITLE
video2x stuck after upscaling all images

### ISSUE THREAD

**Issue by Senjar** [k4yt3x/video2x#136]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.9.0|
|`FFmpeg`|4.1.3|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

Using Cuda with nvidia GPU

## Symptom

video2x is stuck at [+] INFO: Killing upscaled image cleaner

waifu2x-caffe is not running. I checked.
I have about 200Gb of upscaled images (+200Gb of extracted). if I close the terminal I'm pretty sure it will delete them all.
(I had changed the location of the cache in the json to my 2nd HDD before running video2x)

Is there a way to continue with a new instance without extracting and upscaling for 2 days again?

## Screenshots or Error Messages

![powershell_2019-08-15_01-05-01](https://user-images.githubusercontent.com/11983420/63059749-ebdff280-bef8-11e9-9a2f-83e4e7ac85f3.png)

**Comment by k4yt3x** [comment]
I'm not sure why that's happening -- this is the first instance reporting this issue.

I have looked into the code that's responsible for that portion, and I'm still not quite sure why the process was stuck in a loop. I'll continue investigating and make sure this bug is resolved.

Unfortunately, Video2X currently doesn't have the ability to continue its work from extracted frames. **However**, it's totally possible. **However again**, it will take me probably quite some time to write this feature, since it's exam week right now. If you want a number, at least 4 days.

**Comment by Senjar** [comment]
I have now backed up all the upscaled images so it's fine. Take your time. Thanks

**Comment by k4yt3x** [comment]
@Senjar sorry for all this waiting. A lot of things happened this past month.

Could you please verify that the problem still exists in 2.10.X?
I looked over the code, and I didn't find why it could be failing.

**Comment by Senjar** [comment]
I'll try it again in a few days and get back

**Comment by k4yt3x** [comment]
Sure, thanks.

**Comment by OldClassicGamer** [comment]
> @Senjar sorry for all this waiting. A lot of things happened this past month.
> 
> Could you please verify that the problem still exists in 2.10.X?
> I looked over the code, and I didn't find why it could be failing.

When I try to go on this link: https://github.com/k4yt3x/video2x/releases

It is written that latest one is 2.9.0. I do not have option to download 2.10.X and btw I have exactly same problem with 2.9.0 like Senjar.

**Comment by k4yt3x** [comment]
@OldClassicGamer The releases page contain Windows executable releases (EXE files), however, they are usually not up-to-date.

To obtain the newest version, use the Python version by cloning or downloading the zip file of the repository directly, and launch with a Python interpreter.

**Comment by OldClassicGamer** [comment]
> @OldClassicGamer The releases page contain Windows executable releases (EXE files), however, they are usually not up-to-date.
> 
> To obtain the newest version, use the Python version by cloning or downloading the zip file of the repository directly, and launch with a Python interpreter.

Sadly I don't know how to deal without GUI so I guess I will wait for future update of 2.10.X GUI

**Comment by ItsSK** [comment]
I also just got the error message while reading this page... unlucky me.

![image](https://user-images.githubusercontent.com/15605513/64755295-83783700-d4df-11e9-9989-d3153af47a85.png)

**Comment by k4yt3x** [comment]
@ItsSK you just ran out of memory, see the 4th line.

**Comment by ItsSK** [comment]
Ran out of memory in GPU or system memory? because both were low. (below 50%)

**Comment by k4yt3x** [comment]
> 
> 
> Ran out of memory in GPU or system memory? because both were low. (below 50%)

GPU (CUDA) memory.

**Comment by ItsSK** [comment]
> > Ran out of memory in GPU or system memory? because both were low. (below 50%)
> 
> GPU (CUDA) memory.

I restarted the process with 1 thread. But that "_out of _memory_" error happened before running for 5 hours. so then was it running somewhere else, or still in GPU memory? or why didn't the program crash when it ran out of memory?

**Comment by Senjar** [comment]
Seems to be fixed or at least I can't reproduce it in 2.10.0
You can close this issue.

**Comment by k4yt3x** [comment]
Ok, sounds good.

**Comment by Palaparazula** [comment]
Please help me, i can't use this app. When the Upscaling finish, nothing happens. No notification or nothing. The last thing i see at the bottom is " Start assembling video=Folder location " and that's it. It dont says finish for long long time. What should i do?
