### ISSUE TITLE
How to use Anime4k

### ISSUE THREAD

**Issue by Suleman-Elahi** [k4yt3x/video2x#138]
![image](https://user-images.githubusercontent.com/24384996/63206674-ac6efd00-c0d6-11e9-8955-510213a7255e.png)

How to use Anime4k for the enlarging process. There is no option for that on the GUI.
ps im a beginner in python

**Comment by Suleman-Elahi** [comment]
It also stuck every time no matter the method I choose.
![image](https://user-images.githubusercontent.com/24384996/63206948-e4c50a00-c0db-11e9-9358-f0857f67e53f.png)

**Comment by k4yt3x** [comment]
The Anime4K feature has just been added, and is not in any stable releases yet.
If you would like to try it out, please run the source code directly.

**Comment by Suleman-Elahi** [comment]
And what about `Subprocess.CalledProcessError` ?I am getting it with every method and every driver.

**Comment by k4yt3x** [comment]
> And what about `Subprocess.CalledProcessError` ?I am getting it with every method and every driver.

Read the error message. Your CUDA driver needs to be updated.
