### ISSUE TITLE
Unable to download Anime4k with video2x_setup.py

### ISSUE THREAD

**Issue by samuelboland** [k4yt3x/video2x#139]
## Environment Information

|Module|Version|
|-|-|
|`Video2X` |2.10.0|
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

SHA = 2b63b5f0a62f65d78229aa6347a7a59bdfc9927c
## Symptom

Cannot download Anime4k with video2x_setup.py. 

## Screenshots or Error Messages

```
Installing Anime4K
Traceback (most recent call last):
  File "video2x_setup.py", line 329, in <module>
    setup.run()
  File "video2x_setup.py", line 91, in run
    self._install_anime4k()
  File "video2x_setup.py", line 215, in _install_anime4k
    with zipfile.ZipFile(anime4k_zip) as zipf:
UnboundLocalError: local variable 'anime4k_zip' referenced before assignment
An error has occurred
Video2X Automatic Setup has failed
```

## Discussion

According to https://api.github.com/repos/bloc97/Anime4K/releases: 
```
The Java pre-compiled binaries are removed due to cross-platform incompatibility issues. Please build the project yourself using maven.
```

**Comment by samuelboland** [comment]
I was able to download the rest by modifying video2x_setup.py and putting the "with" portion in the "if" block starting on line 210. I suppose I could have just removed that entire section too.

**Comment by k4yt3x** [comment]
If you only want to download a specific driver, then you can use `-d [driver name]`.
I have applied a temporary fix for Anime4K's download link. It's now redirected to my cached zip file of Anime4K release zip.

I'll figure out how to keep that zip file updated later, but that should solve the problem for now.
Thanks for reporting the bug.

**Comment by samuelboland** [comment]
Neat, thanks for that, I did want to try out Anime4k. 

Thanks for making this! Have a good one.

**Comment by seyedaed** [comment]
I know this closed but you can fix the issue by editing the video2x_stup.py file and changing the filename in the for loop search on line 217

from:
r"waifu2x-DeadSix27-win64_v[0-9]*\.zip", a["browser_download_url"]

to:
 r"waifu2x-converter-cpp-win64_v[0-9]*\.zip", a["browser_download_url"]

As the filename  changed.  glhf
