### ISSUE TITLE
Anime4k directory problem video2x_setup.py

### ISSUE THREAD

**Issue by raijin90** [k4yt3x/video2x#141]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
Traceback (most recent call last):
  File "video2x.py", line 331, in <module>
    raise FileNotFoundError(waifu2x_settings['anime4k_path'])
```

I successfully run the Anime4k by bringing out the Anime4k.jar inside another anime4k folder

Before:
![git2](https://user-images.githubusercontent.com/45709556/63648671-b099bb00-c765-11e9-8966-4aa7cdf467c6.PNG)
After:
![git](https://user-images.githubusercontent.com/45709556/63648395-cad19a00-c761-11e9-8da0-508e736c9ef1.PNG)

**Comment by Smarthard** [comment]
Check paths of Anime4K in `video2x\bin\video2x.json`, because default value is "anime4k_path": "C:\\Users\\**K4YT3X**\\AppData\\Local\\video2x\\anime4k\\Anime4K.jar", change **K4YT3X** to your username (**MAN**, I suppose)

**Comment by raijin90** [comment]
I already can run the program by bringing out Anime4k.jar that is inside another anime4k file

**Comment by k4yt3x** [comment]
Problem should be resolved now.
