### ISSUE TITLE
[Feature request] VLC addon

### ISSUE THREAD

**Issue by Ghost---Shadow** [k4yt3x/video2x#142]
## Description

Addon for VLC media player which upscales the video on the fly. (Or maybe buffers a bit, thats ok too, I will wait)

## Sources

https://addons.videolan.org/

**Comment by k4yt3x** [comment]
A video that's a few minutes long might take up to hours to upscale.
There's no way to make waifu2x real time.

**Comment by Ghost---Shadow** [comment]
:(
