### ISSUE TITLE
Unable to process a folder

### ISSUE THREAD

**Issue by verbiate** [k4yt3x/video2x#143]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.9.0|
|`FFmpeg`|N-94405-g43891ea8ab|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Following [a tip I saw you'd posted](https://github.com/k4yt3x/video2x/issues/133#issuecomment-519653997) in response to another bug, I tried upscaling a folder of videos. However, ffmpeg throws an exception saying "FFmpeg cannot edit existing files in-place", as it seems to be trying to overwrite the input file instead of sending it to the specified output folder.

"Output {C:\path_goes_here} same as Input #1 - exiting"

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
Did you make input folder and output folder the same folder?

**Comment by k4yt3x** [comment]
Check out the newest commit. It should have fixed the problem.

**Comment by verbiate** [comment]
Awesome! Will try tonight 👍

**Comment by verbiate** [comment]
Works like a charm. Thanks!

**Comment by k4yt3x** [comment]
Nice to hear that.
