### ISSUE TITLE
ZeroDivisionError in 2.10.0

### ISSUE THREAD

**Issue by verbiate** [k4yt3x/video2x#145]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.10.0|
|`FFmpeg`|N-94405-g43891ea8ab|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Getting a "ZeroDivisionError" in version 2.10.0

Interestingly, the line before says it's calling \bin\ffprobe.exe, but I'm running the Python scripts directly and that executable isn't located in \bin

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 431, in <module>
    upscaler.run()
  File "E:\upscale\video2x-2.10.0\bin\upscaler.py", line 334, in run
    framerate = float(Fraction(video_info['streams'][video_stream_index]['avg_frame_rate']))
  File "C:\Program Files\Python37\lib\fractions.py", line 178, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)
```

**Comment by k4yt3x** [comment]
Theoretically, there's supposed to be a "avg_frame_rate" key in the ffprobe output like such:

![2019-09-03_10-20-24](https://user-images.githubusercontent.com/21986859/64181463-02bd9900-ce56-11e9-9bc5-bc89528769cf.png)

I'm not quite sure why the value of that key in your case evaluates to x/0.
Here's the command if you want to try it yourself to get an output.

```shell
ffprobe.exe -v quiet -print_format json -show_format -show_streams -i video.mp4
```

**Comment by verbiate** [comment]
Here's my output. It seems the video is providing a valid frame rate, but that `r_frame_rate` and `avg_frame_rate` both return "0/0"

`{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "600601/36000000",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 640,
            "height": 360,
            "coded_width": 640,
            "coded_height": 368,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 30,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "18000000/600601",
            "time_base": "1/90000",
            "start_pts": 2070,
            "start_time": "0.023000",
            "duration_ts": 600601,
            "duration": "6.673344",
            "bit_rate": "357353",
            "bits_per_raw_sample": "8",
            "nb_frames": "200",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2017-09-17T08:36:56.000000Z",
                "language": "eng",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/44100",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 295936,
            "duration": "6.710567",
            "bit_rate": "66386",
            "max_bit_rate": "66386",
            "nb_frames": "289",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2017-09-17T08:36:56.000000Z",
                "language": "eng",
                "handler_name": "SoundHandler"
            }
        }
    ],
    "format": {
        "filename": "video.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "6.711000",
        "size": "362142",
        "bit_rate": "431699",
        "probe_score": 100,
        "tags": {
            "major_brand": "qt  ",
            "minor_version": "512",
            "compatible_brands": "qt  ",
            "creation_time": "2017-09-17T08:36:56.000000Z",
            "encoder": "Lavf57.56.100"
        }
    }
}`

**Comment by k4yt3x** [comment]
Is it possible for me to have the input file so I can try to fix the problem?

**Comment by verbiate** [comment]
Actually, I've discovered that the cache drive was nearly completely full, so I'm going to retest to verify that this bug isn't somehow a strange manifestation of that issue. Will keep you posted.

**Comment by k4yt3x** [comment]
@verbiate Have you got any progress?

**Comment by k4yt3x** [comment]
Issue timed out: author not responding.
Versions have since iterated many times as well.
