### ISSUE TITLE
Update Wiki instruction with anime4k support?

### ISSUE THREAD

**Issue by fintogive** [k4yt3x/video2x#146]
Just wondering if the wiki can be updated for how to use the anime4k driver with video2x?  Thanks!

**Comment by k4yt3x** [comment]
Sure. I'll update the drivers section shortly.

**Comment by fintogive** [comment]
Thank you very much!

    On Monday, September 16, 2019, 2:16:33 PM PDT, K4YT3X <notifications@github.com> wrote:  
 
 
Sure. I'll update the drivers section shortly.

**Comment by k4yt3x** [comment]
I was just reading Anime4K's documentation, and there doesn't seem to be an official guide on how to build Anime4K.

They've also removed the JAR builds, so I only have the old JAR file at the moment.

I'll have to figure out how to build Anime4K then I guess.

**Comment by fintogive** [comment]
Alright well take your time.  thank you

    On Monday, September 16, 2019, 2:30:08 PM PDT, K4YT3X <notifications@github.com> wrote:  
 
 
I was just reading Anime4K's documentation, and there doesn't seem to be an official guide on how to build Anime4K.

They've also removed the JAR builds, so I only have the old JAR file at the moment.

I'll have to figure out how to build Anime4K then I guess.

**Comment by Smarthard** [comment]
>here doesn't seem to be an official guide on how to build Anime4K.

You'll need: JDK 12 and Maven
1) Clone Anime4K and open it's folder in cmd.
2) `mvn install`
3) `mvn package`

Packaged JAR should be in `target/` directory

**Comment by k4yt3x** [comment]
Anime4K (Java) will be deprecated soon in favor of Anime4KCPP.
