### ISSUE TITLE
video2x_setup Exits Without Finishing Setup

### ISSUE THREAD

**Issue by deton24** [k4yt3x/video2x#148]
|`Video2X`|| 2.9

I downloaded lite version, and tried to run setup, but it only downloads ffmpeg, then exits, and when I run setup again, it does exactly the same, and so on.

Looks like downloaded file in temp is created, but deleted on setup exit.

Tried to extract ffmpeg after manual download everywhere or copy zip, but setup still does the same and doesn't proceed to next components.

I will use full version instead.

**Comment by k4yt3x** [comment]
1. How did you run the setup script? with what arguments?
  - Do you have a screenshot?
1. Does v2x actually run when you try to upscale something with it?

Also, the downloaded files will be extracted to `%LOCALAPPDATA%\video2x`, and the compressed files will be deleted.

**Comment by deton24** [comment]
There was no waifu folder, so nothing could be processed.
ffmpeg was downloading as the first
I only runned exe via LMB without arguments.

CMD shown:

Video2X Setup Script
Version: 1.4.0

Script is packaged as exe, skipping pip module download

Installing FFMPEG
Downloading:
https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip
Total size: 71640539
Chunk size: 4096
Saving to: C:\Users\XXX\AppData\Local\Temp\ffmpeg-latest-win64-static.zip
  0%|3                                                                   |
335872/71640539 [00:03<09:59, 118938.01it/s]

niedz., 22 wrz 2019 o 21:16 K4YT3X <notifications@github.com> napisał(a):

**Comment by k4yt3x** [comment]
Theoretically if you run the script without any arguments, it will download and setup all drivers.
The section of output you have provided doesn't provide enough debugging information. Could you please show more of the output?

**Comment by deton24** [comment]
That's all what CMD shows before it disappear on 100% download of ffmpeg.

Maybe I will try to run it via console instead of opening exe, to see
whether it shows anything more on exit. If it simply won't run in separate
window.

pon., 23 wrz 2019, 08:34 użytkownik K4YT3X <notifications@github.com>
napisał:

**Comment by min050820** [comment]
I got (probably) same error, saying `video2x.json` was not found.

Maybe you need to pack `video2x.json` along with the setup file. It took me a while to realize that `video2x.json` is in source code directory.

Just in case you want log:
```
Generating Video2X configuration file
Traceback (most recent call last):
  File "video2x_setup.py", line 336, in <module>
  File "video2x_setup.py", line 103, in run
  File "video2x_setup.py", line 231, in _generate_config
FileNotFoundError: [Errno 2] No such file or directory: 'video2x.json'
```

**Comment by min050820** [comment]
@deton24 Please try putting [video2x.json](https://github.com/k4yt3x/video2x/blob/master/bin/video2x.json) in the same folder with `video2x_setup.exe`. It _probably_ will fix the error.

**Comment by k4yt3x** [comment]
It's already in there.

**Comment by Veshurik** [comment]
No, it doesn't help. I have that problem too, during waifu2x-caffe installing through setup.exe the command line is closed, and in AppLocal folder there is only "ffmpeg" folder. I don't know what happens...

**Comment by deton24** [comment]
Has anyone got that lite version working at all?
Of course with e.g. waifu copyed.
Looks like extracting of this downloaded ffmpeg is broken.

**Comment by k4yt3x** [comment]
I'll switch back to Windows tonight to see what's wrong with the setup script since so many people are having problem with it.

**Comment by k4yt3x** [comment]
Try the following:

1. Open cmd.exe with Administrator privilege.
1. Navigated to the directory where video2x_setup.exe and video2x.json are stored.
1. Run `video2x_setup.exe`

If the steps above works, you should see the script finishing successfully. I would also know what's wrong if the above steps work. If the script still doesn't run successfully, at least now you'll have error messages on your screen which you can send over.

**Comment by deton24** [comment]
It downloads all components correctly now.

Don't know whether it was because of priviliges or runnning via CMD.

Thanks

czw., 14 lis 2019 o 23:22 K4YT3X <notifications@github.com> napisał(a):

**Comment by k4yt3x** [comment]
@deton24 ok then, there are a few things I want to change right now to address this issue:

1. V2X setup reads JSON file in its current directory, not the console's current directory.
1. V2X setup pauses and show execution summaries before exiting.
1. Print error message to request for Admin privilege on PermissionError.

**Comment by k4yt3x** [comment]
Can someone please try this build?

[video2x_setup.zip](https://github.com/k4yt3x/video2x/files/3850104/video2x_setup.zip)
SHA224 Checksum: b806142a1b4022beef3407ba2007a2ce5f58c44898af4754208a2f51

**Comment by Veshurik** [comment]
Well, waifu2xcaffe.zip extracting freezing on 4%... 
![Скриншот 15-11-2019 135155](https://user-images.githubusercontent.com/26744056/68938388-55e58d80-07af-11ea-8c7b-78f04e3ab2bf.jpg)

And then...
![Скриншот 15-11-2019 135622](https://user-images.githubusercontent.com/26744056/68938630-cf7d7b80-07af-11ea-949e-52e507c511a0.jpg)
![Скриншот 15-11-2019 135638](https://user-images.githubusercontent.com/26744056/68938632-cf7d7b80-07af-11ea-9c94-cb5c8beda6da.jpg)

**Comment by deton24** [comment]
Mark by the mouse all the text and press ctrl+c and paste here.
These cyrylic texts are system specific, and can be translated by copy
pasting elsewhere.

Not being a dev though, I'd suggest you use VPN, or make sure your Internet
connection is stable if really connection was broken. Didn't have that
issue.

pt., 15 lis 2019, 10:57 użytkownik Veshurik <notifications@github.com>
napisał:

**Comment by Veshurik** [comment]
Thanks, not all installed, but there's new problem... 0% upscaling, and that's all...
![Скриншот 17-11-2019 182513](https://user-images.githubusercontent.com/26744056/69011013-defaf100-0976-11ea-9a5d-db2e53d23db1.jpg)
![Скриншот 17-11-2019 182519](https://user-images.githubusercontent.com/26744056/69011014-defaf100-0976-11ea-91e4-5efc6b7e9ffc.jpg)

**Comment by deton24** [comment]
Try to use the last Lite version and choose Anime4K. Sometimes it may work,
and even better than Waifu.

niedz., 17 lis 2019 o 18:14 Veshurik <notifications@github.com> napisał(a):

**Comment by Veshurik** [comment]
Now FileNotFoundError... what the file, I don't understand...
![image](https://user-images.githubusercontent.com/26744056/69045065-27fa8600-0a07-11ea-9e61-9f043075de88.png)

**Comment by deton24** [comment]
Now it's Java dependency since you use Anime4K.
It's already in issues section.
Look there to see the fix.

pon., 18 lis 2019, 11:27 użytkownik Veshurik <notifications@github.com>
napisał:

**Comment by k4yt3x** [comment]
The topic of this issue has already been addressed in the new source code, and will soon be in a new release.
