### ISSUE TITLE
Where is the Anime4K option in the gui?

### ISSUE THREAD

**Issue by danielkp1234** [k4yt3x/video2x#150]
I can't find the Anime4K driver in  the GUI

**Comment by danielkp1234** [comment]
Also it would be nice if it saved the tmp exported frames and all that into a folder on an external drive since i have almost no space left on my c drive but i have over 1tb on my external drive

**Comment by gregoryw3** [comment]
I agree, however, I don't believe this is a bug. As far as I can tell, you'll need to compile video2x yourself and/or compile the Anime4k .jar file yourself as well and set up the video2x.json file.

**Comment by Dev-krauser** [comment]
For change exported frames folder go to video2x.json and at the buttom you need change "video2x_cache_directory":

Exemple : "video2x_cache_directory": "D:\\video2x",

**Comment by MatteCrystal** [comment]
version 2.10.0 added support for anime4k but the releases page only goes up to version 2.9.0

**Comment by k4yt3x** [comment]
See the new release.
