### ISSUE TITLE
Video2X 2.10.0 release - Anime 4k Bug

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#152]
## Environment Information
windows 10 pro

## Symptom

When using Anime4k as a driver program gets stuck on up scaling process. No gpu or cpu use regardless of which method is chosen. CPU, GPU, and CUDNN all don't work. I've also tried 1 to 3 threads of each option. Scale was 2, image format png, and perserved frames 1 for each test. 

waifu2x-caffe seems to work as expected.

Also the default output file generated uses \ not / (see image) manually changing this to / didn't seem to fix anything.

##Steps taken before testing
unzip video2x-2.10.0-win32-light

run video2x_setup.exe

run video2x_gui.exe (initiate testing)

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/32424764/65824837-e6363600-e234-11e9-81da-2fe4b8cf5602.png)

![image](https://user-images.githubusercontent.com/32424764/65824991-00711380-e237-11e9-8ec4-dd97577e9d8f.png)

## My video2x.json file

```json
{
  "waifu2x_caffe": {
    "waifu2x_caffe_path": "C:\\Users\\MatteCrystal\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe",
    "input_extention_list": null,
    "output_extention": null,
    "mode": "noise_scale",
    "scale_ratio": null,
    "scale_width": null,
    "scale_height": null,
    "noise_level": 3,
    "process": "gpu",
    "crop_size": 128,
    "output_quality": -1,
    "output_depth": 8,
    "batch_size": 1,
    "gpu": 0,
    "tta": 0,
    "input_path": null,
    "output_path": null,
    "model_dir": null,
    "crop_w": null,
    "crop_h": null
  },
  "waifu2x_converter": {
    "waifu2x_converter_path": "C:\\Users\\MatteCrystal\\AppData\\Local\\video2x\\waifu2x-converter-cpp",
    "output-format": null,
    "png-compression": null,
    "image-quality": null,
    "block-size": null,
    "disable-gpu": null,
    "force-OpenCL": null,
    "processor": null,
    "jobs": null,
    "model-dir": null,
    "scale-ratio": null,
    "noise-level": 3,
    "mode": "noise-scale",
    "silent": true,
    "output": null,
    "input": null
  },
  "waifu2x_ncnn_vulkan": {
    "waifu2x_ncnn_vulkan_path": "C:\\Users\\MatteCrystal\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe",
    "v": null,
    "i": null,
    "o": null,
    "n": 2,
    "s": 2,
    "t": 400,
    "m": "models-cunet",
    "g": 0,
    "j": "1:2:2"
  },
  "anime4k": {
    "anime4k_path": "C:\\Users\\MatteCrystal\\AppData\\Local\\video2x\\anime4k\\Anime4K.jar",
    "java_path": "C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe"
  },
  "ffmpeg": {
    "ffmpeg_path": "C:\\Users\\MatteCrystal\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin",
    "video_to_frames": {
      "output_options": {
        "-qscale:v": null,
        "-pix_fmt": "rgba64be"
      },
      "-hwaccel": "auto",
      "-y": true
    },
    "frames_to_video": {
      "input_options": {
        "-qscale:v": null,
        "-qscale:a": null,
        "-f": "image2"
      },
      "output_options": {
        "-vcodec": "libx264",
        "-crf": 17,
        "-b:v": null,
        "-pix_fmt": null
      },
      "-hwaccel": "auto",
      "-y": true
    },
    "migrating_tracks": {
      "output_options": {
        "-map": [
          "0:v:0?",
          "1?",
          "-1:v?"
        ],
        "-c": "copy",
        "-pix_fmt": null
      },
      "-hwaccel": "auto",
      "-y": true
    }
  },
  "video2x": {
    "video2x_cache_directory": null,
    "image_format": "png",
    "preserve_frames": false
  }
}
```

**Comment by k4yt3x** [comment]
Did you have Java installed?

**Comment by MatteCrystal** [comment]
Yes, but perhaps you could provide insight on if I have things set up correctly since I believe I have a few versions due to java development, and the paths and whatnot confuse me. 

My Java control panel says I have Version 9.

![image](https://user-images.githubusercontent.com/32424764/65838548-b6853d80-e2c9-11e9-9997-f7e04b8f113b.png)

However these following are also installed when I look at windows add or remove program section.

![image](https://user-images.githubusercontent.com/32424764/65838563-d9afed00-e2c9-11e9-8f16-33634844dfea.png)

Under User variables I have JAVA_HOME listed as

![image](https://user-images.githubusercontent.com/32424764/65838589-3e6b4780-e2ca-11e9-9275-00904fa9795c.png)

And My path variable under user variables is the following -- Java at the bottom.

![image](https://user-images.githubusercontent.com/32424764/65838624-9e61ee00-e2ca-11e9-95c4-e42b3b47f46c.png)

And finally the path under System variables has the following

![image](https://user-images.githubusercontent.com/32424764/65838647-d832f480-e2ca-11e9-8463-f9b2f2c74819.png)

While writing this I can looked at the Anime4k GitHub page itself and see it says it needs Java jdk12 i'm suspecting that's the issue and will try that next. If I do install jdk12 will I have to also enter it into the path? if so should it be the user or system variables path or both? 

Also, since the java instructions are only available on the anime4k github page I would recommend mentioning those prerequisites and or linking to the prerequisites for anime4k as well as for the other drivers.  I know it took awhile for me to figure out how to use CUDNN and I gave up on waiffu2x NCNN vulkan as it seemed impossible to get working, plus it's not immediately obvious what the differences and advantages are to each option even when looking at their github pages. like will waiffu2x NCNN vulkan provide any real benefit to me on a nvidia card? And how would that compare to CUDNN? A section explaining the pros and cons of each driver and method would be greatly helpful.

-sorry for the slightly off topic ramble at the end

**Comment by MatteCrystal** [comment]
Installing JDK 12 fixed the issue, I would recommend mentioning it somewhere as a prerequisite for anime4k.

**Comment by k4yt3x** [comment]
I am currently writing the wiki page for a4k. I have already put in the info about JDK in there.
