### ISSUE TITLE
Video2X GUI release 1.1.1 output file adds second .mp4 to name

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#153]
## Environment Information

OS: Windows 10
Video2X release: 2.10.0
Video2X GUI: 1.1.1

## Symptom

The default generated output path which should take the form **"videoname_output.mp4"** is instead generating **"videoname.mp4_output.mp4"**

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/32424764/65840537-07079580-e2e0-11e9-984d-4bf29e06bbe2.png)

**Comment by k4yt3x** [comment]
I don't see why it will be useful to make the code more complex to detect and delete the original suffix. You can change the output name if you don't like it.

**Comment by MatteCrystal** [comment]
I disagree, auto generating the output filename is a nice quality of life feature but, it the generated name something nobody would ever want to use then whats the point. 

Ultimately it's up to you and I realize in the grand scheme of things it doesn't truly impact the core of the program but it's definitely not a worthless cause either. If you ever get some spare time it's just another thing to look at and make better, even if it's the low priority.

**Comment by k4yt3x** [comment]
I still don't think it's necessary, but I'll do it since you have very clear arguments and points.

**Comment by k4yt3x** [comment]
This issue has been addressed in Video2X GUI version 1.1.2 (https://github.com/k4yt3x/video2x/commit/dce778b3bfe03a5b1f92ced32f1806b3513f73fd).
