### ISSUE TITLE
Can't get to run the program

### ISSUE THREAD

**Issue by HokutoShinken** [k4yt3x/video2x#155]
I downloaded the last full package of video2x, and all seemed to be ready to run, but as i started video2x.exe, a black window pops out for a second showing an error message and closing right after. 

The error says: You must specify input video file/directory path.

I expected to specify such path in the inteface (as it seems to be looking at the screenshots posted in the main page). I took a look to the Step by Step guide, but it only shows how to proceed using commands. It still works that way, regardless you're using full or light package? Is it necessary to install python anyway?  

Sorry, i'm a bit lost n__n' 
![Sin título](https://user-images.githubusercontent.com/30272756/66275246-f7132700-e886-11e9-8ad8-ba23c6e6800f.png)

**Comment by k4yt3x** [comment]
`video2x.exe` is meant to be ran from the command line.
If you want a GUI, use `video2x_gui.exe`.

**Comment by HokutoShinken** [comment]
Damn, i'm so dumb. n__n'

okay, i have it working now. Thank you for your work and patience

**Comment by k4yt3x** [comment]
No problem. You're welcome.
