### ISSUE TITLE
SyntaxError: invalid syntax during setup (Kubuntu 19.04)

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [k4yt3x/video2x#157]
## Environment Information

|Module|Version| 
|-|-|
|`Video2X`|2.10.0| 
|`FFmpeg`|4.1.3-0ubuntu1|  
|`waifu2x-caffe`|n/a| 
|`waifu2x-converter-cpp`|n/a|
|`waifu2x-ncnn-vulkan`|n/a|

## Symptom
When running `video2x.setup.py`, I get the following:
```marshmellosucks@marshmellosucks-mainrig:~/Downloads/video2x/bin$ python video2x_setup.py
  File "video2x_setup.py", line 119
    print(f'Deleting directory: {file}')
                                      ^
SyntaxError: invalid syntax
```
I have no knowledge with Python, so I can't fix the issue. Using Python 3.7.3.

**Comment by MarshmelloSUCKS** [comment]
Just throwing something in: the reason I don't have waifu2x is because I plan on using Anime4K

**Comment by k4yt3x** [comment]
That line is using f-string, which requires python >= 3.6.

Also note that the current version of video2x does NOT have full official Linux support yet. However, it can work in theory if you configure everything correctly.

**Comment by k4yt3x** [comment]
If you're attempting to run video2x 2.10.0 on Linux, don't use the setup script. That's only configured for Windows at the moment.

**Comment by MarshmelloSUCKS** [comment]
Sorry for sounding like a dumbass, but how exactly would I use it under Linux? Ubuntu, to be exact.

**Comment by k4yt3x** [comment]
@MarshmelloSUCKS It's a completely fine question.

Here's a tutorial by a contributor that can make v2x work on Ubuntu. However, it's more like a workaround. You'll have to modify and play with it quite a bit. Expect official convenient support in the future though.
https://github.com/k4yt3x/video2x/issues/74#issuecomment-526899181

**Comment by ddouglas87** [comment]
@MarshmelloSUCKS To add to k4yt3x there is a temporary version of video2x that works on Linux found here: https://github.com/k4yt3x/video2x/tree/2.11.0

To get video2x working using waifu2x-ncnn-vulkan (the fastest waifu2x driver) you'll want to have cuda installed (try: `apt-get install nvidia-cuda-toolkit` or see the #74 comment for more info installing cuda).  Then you'll want to copy paste this:

```
sudo apt-get install -y software-properties-common &&
sudo add-apt-repository -y ppa:graphics-drivers/ppa &&
sudo apt-get install -y nvidia-driver-435
```
To install up-to-date nvidia video drivers.  Then to grab the video2x branch that works with linux:
```
sudo apt-get install git-core python3-pip python3-setuptools python3-wheel python3-psutil ffmpeg
cd ~ &&
git clone --progress --branch=2.11.0 https://github.com/k4yt3x/video2x.git &&
pip3 install -r video2x/bin/requirements.txt
```
Then to install waifu2x-ncnn-vulkan:
```
sudo apt-get install git-core build-essential cmake libvulkan-dev glslang-tools libprotobuf-dev protobuf-compiler &&
git clone --progress https://github.com/Tencent/ncnn.git &&
cd ncnn &&
mkdir -p build &&
cd build &&
cmake -DCMAKE_INSTALL_PREFIX=/usr -DNCNN_VULKAN=ON .. &&
sudo make -j$(nproc) install &&
rm -rf ../../ncnn &&
cd ~ &&
git clone --progress https://github.com/nihui/waifu2x-ncnn-vulkan.git &&
cd waifu2x-ncnn-vulkan &&
mkdir -p build &&
cd build &&
cmake ../src &&
make -j$(nproc) &&
cd .. &&
mkdir waifu2x-ncnn-vulkan &&
mv models/models-cunet waifu2x-ncnn-vulkan/ &&
mv build/waifu2x-ncnn-vulkan waifu2x-ncnn-vulkan/ &&
mv waifu2x-ncnn-vulkan ~/video2x/ &&
rm -rf ../waifu2x-ncnn-vulkan
```

This will leave you with a video2x folder in your home folder.  In `~/video2x` there is `video2x.py` which can be ran by typing `cd ~/video2x/` && `python3 video2x.py --help`

eg: `python3 video2x.py -b -d waifu2x_ncnn_vulkan -r 2 -i 'input_file.mp4' -o 'outfile.mkv'`

**Comment by MarshmelloSUCKS** [comment]
Would I have to do the whole Nvidia Cuda stuff if I use an AMD GPU?

**Comment by ddouglas87** [comment]
Oh!  I don't have an AMD gpu so this is untested on my end, but waifu2x-ncnn-vulkan should be possible using an AMD gpu.  Just install the proper up-to-date amd driver instead of the nvidia one and follow the rest of the steps.  (The guide has been updated to help clarify this.)

**Comment by MarshmelloSUCKS** [comment]
I installed it successfully while skipping the CUDA stuff. It worked... until I tried to open Firefox. My PC crashed.

**Comment by ddouglas87** [comment]
None of this messes with Firefox.  It could be bad video drivers, but I'm only guessing.  I hope you figure it out.

**Comment by MarshmelloSUCKS** [comment]
It might just be my PC crashing due to running out of memory or something else

**Comment by k4yt3x** [comment]
Version 3.0.0 has rolled out and has better Linux support. You can try setting that version of v2x up. It should give you a better experience.

Should you have any questions, don't hesitate to reopen or open a new issue.
