### ISSUE TITLE
setup failed

### ISSUE THREAD

**Issue by zhangboyang** [k4yt3x/video2x#160]
## Environment Information

Nothing installed.

## Symptom

I downloaded `video2x-2.10.0-win32-light.zip` and unzipped it to `C:\`, then I ran "video2x_setup.exe" to setup dependencies. However, it exited without creating "video2x.json". Thus, the program is simply unuseable.

## Screenshots or Error Messages

The last lines of output of "video2x_setup.exe" is attached.
![output](https://user-images.githubusercontent.com/7912829/68388582-f8908180-019b-11ea-8dbd-48a968db23ac.png)

```
```

**Comment by zhangboyang** [comment]
I looked into `video2x_setup.py`, it seems there should be a `video2x.json` template packaged into release package.

**Comment by k4yt3x** [comment]
You are right, there should be a JSON file there. I just haven't got time to do that yet, I'm just buried in dues after dues right now. I'll do it later today.
