### ISSUE TITLE
Description mistake - 2.10.0 lite also contains Anime4K

### ISSUE THREAD

**Issue by deton24** [k4yt3x/video2x#162]
Looks like description has one mistake.
Lite version has Anime4K listed in the program's GUI, not full version only.

Furthermore, currently there is no full version of 2.10.0 on releases page, so where Anime4K was introduced.

**Comment by k4yt3x** [comment]
Oh yeah I just forgot to add A4k to the lite version's description. I'll add it in 3.0.0 release.
