### ISSUE TITLE
Anime4K Java dependency - couldn't find specified file

### ISSUE THREAD

**Issue by deton24** [k4yt3x/video2x#163]
During attempt of conversion, it gave me error that it couldn't find specified file.

Few lines above was this non-existing location:
2019-11-15 01:01:56.402029 [+] INFO: Executing: ['C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe'

I downloaded Java SE (which includes JDK)
https://www.oracle.com/technetwork/java/javase/downloads/index.html

I had to manually make a copy of current 13.xx folder, and rename it to 12.0.2 (C:\Program Files\Java\jdk-12.0.2) and conversion started to work.

It shouldn't be like that.

**Comment by k4yt3x** [comment]
You're right. It shouldn't be like that.
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html
