### ISSUE TITLE
CUDA not working? 

### ISSUE THREAD

**Issue by Alphaheat** [k4yt3x/video2x#165]
## Environment Information

OS: Windows 10 
Video2X Version: 2.10.0 

## Symptom
I want to upscale using CUDA but it seems like my CPU is doing all the work according to task manager. I am running Video2X using the GUI and have the method selected as GPU. 

Both of my GPU's are at 0% in task manager.

**Comment by k4yt3x** [comment]
https://github.com/k4yt3x/video2x/wiki/Q&A#no-gpu-usage

**Comment by Alphaheat** [comment]
> https://github.com/k4yt3x/video2x/wiki/Q&A#no-gpu-usage

Thanks, I'm currently not at the up-scaling process yet. It's still creating frames from the video so does CUDA only work during the up-scaling step?

**Comment by k4yt3x** [comment]
> Thanks, I'm currently not at the up-scaling process yet. It's still creating frames from the video so does CUDA only work during the up-scaling step?

Correct. FFmpeg is executed with `-hwaccel auto`, but it doesn't seem to like to use GPU. The upscaling portion on the other hand, always follows the arguments you give v2x.

**Comment by Alphaheat** [comment]
> > Thanks, I'm currently not at the up-scaling process yet. It's still creating frames from the video so does CUDA only work during the up-scaling step?
> 
> Correct. FFmpeg is executed with `-hwaccel auto`, but it doesn't seem to like to use GPU. The upscaling portion on the other hand, always follows the arguments you give v2x.

Ah I see, thank you so much for the answer! 

I also have another quick question. I understand that the frames we pull from the video are stored in a folder in the Local/Temp directory. I also read that that folder in particular gets deleted whenever the upscaling process fails or crashes. Is this true? 

Is it also possible for me to make a copy of that folder and in the event that the folder does get deleted, I could simply replace it and upscale it again through Video2X GUI essentially skipping the process of creating the frames?

**Comment by k4yt3x** [comment]
Currently, v2x will just create a new directory for a new upscaling instance -- it won't matter if you have some already-upscaled frames. I have always been wanting to make what you've described come to life, but for now I have very little time for open source dev.

It is though, possible, to preserve the frames if you still want them for some reason. Just set the `preserve_frames` key to `true` in `video2x.json`.

![image](https://user-images.githubusercontent.com/21986859/68922710-5ad91b80-0774-11ea-9c8d-39455488cd30.png)
