### ISSUE TITLE
Temp clean on exit

### ISSUE THREAD

**Issue by deton24** [k4yt3x/video2x#166]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|| 2.10
|`OS: W10`||

It seems like all temp processed images are not being cleaned after exit.
And for sure when the conversion process is interrupt by closing CMD or in case of error.

If it's impossible to implement on exit, I'd suggest doing it on next program launch.
It can be gigabytes of data.

**Comment by k4yt3x** [comment]
I will write a better try-except clause to address this issue. This will be in the 3.0.0 release.

**Comment by k4yt3x** [comment]
This turned out to be quite a problem.
I'm fixing it right now.

**Comment by k4yt3x** [comment]
This should now be fixed in https://github.com/k4yt3x/video2x/commit/332055a4e50e3ef0077b89f88ce77c5c21e91d65
