### ISSUE TITLE
Anime4k stop re-creating the kernel for every picture

### ISSUE THREAD

**Issue by Dalayeth** [k4yt3x/video2x#169]
Hidden in Anime4k's "documentation", if it can be called that, there is a footnote to developers to change the code in Main.java so as not to re-create the kernel every time you process a picture. 

> Note to developers: For faster batch processing please look at Main.java and modify the code so that the Kernel is not re-created for each picture. (Kernel reuse will accelerate processing greatly.)

This can be found here [https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md](url). With a small change to the Main.java file to accept an array of images instead of a single image and thereby not recalling and re-creating the kernel each time you could see a massive speedup. Anime4k was never meant to be used for one image at a time the JAVA program just makes it seem that way. Thought that this might be helpful.

**Comment by k4yt3x** [comment]
I might try this if I find time for it. Though for now, it looks like time is not on my side.

**Comment by Veshurik** [comment]
Link doesn't work. 
To be honest, I don't understand what to do :(

**Comment by k4yt3x** [comment]
@Veshurik 
> Link doesn't work.
> To be honest, I don't understand what to do :(

He's saying that I can modify the source code of A4k to achieve better upscaling efficiency.
The link is [this](https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md), and it points to A4k's docs for Java.
If you're not a developer, then there's nothing you should worry about here.

**Comment by k4yt3x** [comment]
Honestly, I don't think this should be a video2x issue.

As much as rewriting a4k will help video2x, it shouldn't be v2x project's duty to rewrite/modify a4k source code. This project focuses on automation, where this issue's direction is not included.

Although I will be closing this issue for now, I will keep an eye out for better a4k implementations. In fact, I might be writing a python implementation in the future if I have time.
