### ISSUE TITLE
Output file missing but it says upscaling completed successfully

### ISSUE THREAD

**Issue by Reflex-x** [k4yt3x/video2x#177]
I'm new to this website so forgive me if i make any mistakes.

I updated the Python and ran the video2x_gui.exe as Admin too, but there is no output file too be seen , i tried multiple times , it ways the same thing , upscaling complete, but no output file.

![Annotation 2019-12-07 152007](https://user-images.githubusercontent.com/58624130/70372507-fe49c600-1905-11ea-969b-67f899beeca2.png)

**Comment by k4yt3x** [comment]
What does the console output look like?

**Comment by Reflex-x** [comment]
THe console text diappears almost instantly leaving a blank cmd window open without any text. i might record it and then screenshot it later, hold on.

**Comment by k4yt3x** [comment]
Any followups?

**Comment by asaucedev** [comment]
Unsure if this is the same cause as Reflex-x's experience, but I had the same situation develop on me here. The source video has two subtitle tracks and two audio tracks @ 29.97 fps mkv. I had another unrelated ffmpeg task in the background (using a different ffmpeg executable etc) I assume it's from not running Video2x as admin, will experiment.
![oof](https://user-images.githubusercontent.com/15789447/75082982-ebde3200-54db-11ea-803c-498d85c47ca7.PNG)
