### ISSUE TITLE
issues with frame to image on Anime4k

### ISSUE THREAD

**Issue by CaptainTuckerRvB** [k4yt3x/video2x#179]
I'm using the exe version on my pc and when I try to convert with Anime4K, progress gets to 80% and the error appear. Instead, i used the waifu2x-converter-cpp. The frame to image worked but now the same error appears. I linked the full copy from the second go: https://paste2.org/a7WXM7mA

**Comment by k4yt3x** [comment]
I don't see any errors at the end of the output.
Do you have anything else related to the issue? or is that all you've got?

**Comment by CaptainTuckerRvB** [comment]
sorry the character limit only allowed a certain amount of characters. i'll include a txt file if tyhe issue comes up again later

**Comment by CaptainTuckerRvB** [comment]
[hs_err_pid19048.log](https://github.com/k4yt3x/video2x/files/3987195/hs_err_pid19048.log)
[hs_err_pid17896.log](https://github.com/k4yt3x/video2x/files/3987197/hs_err_pid17896.log)
[hs_err_pid16520.log](https://github.com/k4yt3x/video2x/files/3987198/hs_err_pid16520.log)

**Comment by k4yt3x** [comment]
I'm not a Java expert, and as far as I can tell, A4K operations crashed outside of JVM in native code sections. I can only guess that this is a memory management issue e.g. ran out of RAM, etc.

Try reducing the number of threads and see if the error goes away will be my suggestion for now.

**Comment by CaptainTuckerRvB** [comment]
Hi Back again. It has the same error on 1 thread only. Is my rig not powerful enough for this program?

Operating System
	Windows 10 Home 64-bit
CPU
	AMD FX-8350	29 °C
	Vishera 32nm Technology
RAM
	32.0GB Dual-Channel DDR3 @ 803MHz (11-11-11-28)
Motherboard
	Gigabyte Technology Co. Ltd. 970A-UD3 (CPU 1)	35 °C
Graphics
	DELL E2316H (1920x1080@60Hz)
	2048MB ATI AMD Radeon R7 200 Series (XFX Pine Group)	41 °C
Storage
	232GB Crucial CT250BX100SSD1 (SATA (SSD))	31 °C
	931GB Seagate ST1000DM003-1ER162 (SATA )	27 °C
	931GB Seagate ST1000DM003-1CH162 (SATA )	29 °C
Optical Drives
	ATAPI DVD A DH20A6S
Audio
	AMD High Definition Audio Device

**Comment by k4yt3x** [comment]
Your spec shouldn't be the problem. Something else is hindering a4k's normal functionality.
