### ISSUE TITLE
Can you add full package of video2x 2.10.0/3.0.0?

### ISSUE THREAD

**Issue by Hlwan03** [k4yt3x/video2x#184]
The `light` package with Anime4K did not work for me. After the setup, the program told I lacks some file to start. Other variants of Waifu2x works normally but is very slow for video conversion.

**Comment by k4yt3x** [comment]
I think what you need is JRE12
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html

**Comment by k4yt3x** [comment]
If I were to make a new release, it's going to be fore 3.0.0.

**Comment by k4yt3x** [comment]
Just uploaded a new release.
