### ISSUE TITLE
Can't open video2x

### ISSUE THREAD

**Issue by xXHenlolXx** [k4yt3x/video2x#185]
Hey, I am new here and just started to use your program. I followed the guide, and I am able to use the program using console (by downloading your repository). But I can't open the one on the releases page, doesn't matter if it is the light or full version. Also, the driver I really wanted to use is anime4k, but it keeps giving me an error. 
PS: Already tried to close everything in the background and reinstalling everything running python video2x_setup.py. The weird thing is that my sisters's pc opens the program just fine, she has an i3-8100, while I have a Ryzen 3700x
![Captura de Tela (48)](https://user-images.githubusercontent.com/27168630/71849517-ffab1180-30b0-11ea-9c8b-29035bf23abd.png)

**Comment by k4yt3x** [comment]
For A4K you'll need JRE 12 which is mentioned in a4k's instructions.
I really should add that into v2x's instructions.
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html
