### ISSUE TITLE
No tutorial or direction for linux port, even though it apparently exists.

### ISSUE THREAD

**Issue by databoose** [k4yt3x/video2x#186]
## Description

In the changelog it is stated that there is a linux port..... However that is absolutely nowhere to be found, not on the wiki, and nowhere on the github page, what gives? 

Also, i know telegram would be more of an appropriate place for this, but i don't have a carrier number as i don't need one and honestly cannot be bothered to bug someone else to use their carrier number simply to sign up for a chatting service that i will never use other than for asking a single question ( and **cough** discordisbetterinjustabouteveryway **cough**)

## Sources

Paste links to descriptions of related documentations, websites and etc. here.

There are none for linux that's the issue.

**Comment by k4yt3x** [comment]
There are some documentations on how to get things to work under some issues.
I have talked to some of the authors of those documentations and they have agreed to edit the wiki page.
I just didn't keep pushing that forward.
I'll open up the wiki page editing permission so they can do it.

**Comment by k4yt3x** [comment]
Btw posting questions in the Telegram is just one way to ask questions. If you would like to get answers quicker + $(other_instant_messaging_benefits), then you can come to the Telegram group.

With that said, it is completely fine and normal to post questions/issues/comments/suggestions/etc. here.

**Comment by Doomsdayrs** [comment]
``There are some documentations on how to get things to work under some issues.`` Sauce?

**Comment by k4yt3x** [comment]
@Doomsdayrs This for example: https://github.com/k4yt3x/video2x/issues/74#issuecomment-526899181
