### ISSUE TITLE
GUI版本能否添加降噪程度的设置

### ISSUE THREAD

**Issue by BanYiMeng** [k4yt3x/video2x#187]
现在版本降噪程度,有时候过高了
CLI似乎也没有找到调整降噪程度的选项

**Comment by k4yt3x** [comment]
降噪的调整目前需要直接在配置文件里调整，因为每个驱动降噪的命令行选项都不一样，所以当初设计的时候没有把它直接放进 v2x 的选项里。
以后可以考虑一下直接加进去，可能方便点。

**Comment by k4yt3x** [comment]
最新的 GUI 已经加进去了
