### ISSUE TITLE
Hey, is there a way to continute a process if it was stopped?

### ISSUE THREAD

**Issue by ThoradTM** [k4yt3x/video2x#191]
## Description

I ended up having an issue where the process stopped midway while it was up scaling the images. I would like to continue it instead of restarting it, mainly because I don't want to write 600+ GB to a drive again, especially considering that it was dropped on accident once, if I don't have to. Is there any way to do that?

From my understanding it should be as simple as letting the program know "Hey, here is a list of images. Finish up scaling all of them, then batch them into a video file." Am I oversimplifying it? Thanks!
## Sources

Paste links to descriptions of related documentations, websites and etc. here.

**Comment by k4yt3x** [comment]
Unfortunately Video2X doesn't support automatically resuming from a point of failure at this point.

> From my understanding it should be as simple as letting the program know "Hey, here is a list of images. Finish up scaling all of them, then batch them into a video file."

Your understanding is correct, but to program that and write it out in Python, it will require more than just having the idea. I have yet have time to actually implement this.

**Comment by ThoradTM** [comment]
Ok thats fine. I'll likely leave the files there for the time being then until a later date. Thank you!
