### ISSUE TITLE
I am not able to install the new version

### ISSUE THREAD

**Issue by Pk555555** [k4yt3x/video2x#192]
First I'm sorry for the English, I would like you to update the tutorial

**Comment by k4yt3x** [comment]
I need more details on this.

- What do you mean you failed to install the new version? Which version exactly?
- Which tutorial do you need me to update?
- What do you need me to update in the tutorial?

**Comment by Pk555555** [comment]
version 3.0.0
the tutorial step by step
how to install and how to use
Ps. this tutrorial is kind of confusing

**Comment by k4yt3x** [comment]
Ok I see. Yeah that tutorial is for an older version.
I'll review it and update it when I get time.

**Comment by Pk555555** [comment]
Thank you

**Comment by Pk555555** [comment]
I don't want to rush you but do you have a schedule to update the tutorial?

**Comment by k4yt3x** [comment]
As a student I'm already struggling to handle my course load.
I'm not sure when I'll be able to get time to update this.

**Comment by Pk555555** [comment]
I understand I am also a student thank you for responding.

**Comment by k4yt3x** [comment]
I finally have time. I'll update the tutorials.
