### ISSUE TITLE
程序似乎无法识别我卸载配置文件里的Anime4k地址

### ISSUE THREAD

**Issue by xiaowang2017** [k4yt3x/video2x#195]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|3.0.0|
|`FFmpeg`|4.1|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||
The system is centos7
## Symptom
当我试图运行时显示找不到Anime4K.jar。我已经下载好了JRE12
It seems that the program can't find where is Anime4K.jar
I have already installed JRE12
这是我配置文件中关于anime4k相关的字段
This my profile about anime4k
"anime4k": {
    "anime4k_path": "/home/anime4k/Anime4K.jar",
    "java_path": "/usr/java/jdk-12.0.2/bin/java"
  },
## Screenshots or Error Messages

[!] ERROR: Specified driver executable directory doesn't exist
[!] ERROR: Please check the configuration file settings
Traceback (most recent call last):
  File "video2x.py", line 316, in <module>
    raise FileNotFoundError(driver_settings['path'])
FileNotFoundError: C:\Users\K4YT3X\AppData\Local\video2x\anime4k\Anime4K.jar

**Comment by k4yt3x** [comment]
这个 `anime4k_path` 键不对，改成 `path`
我去看看源码是不是写错了

---

The `anime4k_key` is deprecated in favor of `path`
I'll go check if it's wrong in the source code

**Comment by k4yt3x** [comment]
源码里的是对的，这个 clone 可能太老了

---

The source code on master contains the correct key.
It's probably just that the clone is too old.
