### ISSUE TITLE
在运行一段时间后会自动崩溃

### ISSUE THREAD

**Issue by xiaowang2017** [k4yt3x/video2x#196]
## Environment Information

|Module|Version|
|`System`|Centos7|
|`Video2X`|3.0.0|
|`FFmpeg`|4.1|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom
我持续运行十分钟左右就会崩溃
The program will crash in 10 min when I run it
## Screenshots or Error Messages
video:6191858kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 398, in <module>
    upscaler.run()
  File "/home/video2x/src/upscaler.py", line 314, in run
    fm.extract_frames(self.input_video, self.extracted_frames)
  File "/home/video2x/src/ffmpeg.py", line 134, in extract_frames
    self._execute(execute)
  File "/home/video2x/src/ffmpeg.py", line 287, in _execute
    return subprocess.run(execute, check=True).returncode
  File "/usr/local/bin/python3/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/ffmpeg/bin/ffmpeg', '-hwaccel', 'auto', '-y', '-i', '/home/video2x/src/sample_input.rmvb', '-pix_fmt', 'rgba64be', '/tmp/video2x/tmpu65qkxip/extracted_%0d.png']' returned non-zero exit status 1.

**Comment by xiaowang2017** [comment]
另外建议给软件添加一个批量处理整个文件夹里的视频的功能

**Comment by k4yt3x** [comment]
错误日志不够完整

--- 

Incomplete error logs

**Comment by k4yt3x** [comment]
> 另外建议给软件添加一个批量处理整个文件夹里的视频的功能

已经有了，`-i` 指向目录就行了

**Comment by xiaowang2017** [comment]
上面的问题解决了，是因为我剩余空间过小的缘故，但是我用一个三十秒的视频片段测试的时候首先弹出我缺少OpenCL 环境但是没有影响处理，但是最后好像在合成文件时出现了问题。
![14BCD994-45CA-4D20-952D-B791079864B0](https://user-images.githubusercontent.com/42296908/73900846-f4275200-48cb-11ea-9932-37ddfae6e6b2.jpeg)
![FF782412-3CC3-43A5-8CE1-EA95E44A70C0](https://user-images.githubusercontent.com/42296908/73900854-f8536f80-48cb-11ea-8f07-bb6c4f456753.jpeg)
![B577C5A0-E463-4449-B208-ED26EFF166F3](https://user-images.githubusercontent.com/42296908/73900858-f9849c80-48cb-11ea-99d5-9de7b0bce6dc.jpeg)

**Comment by k4yt3x** [comment]
I don't think your FFmpeg is compile with libx264 support. Try a different version or a different machine.

**Comment by xiaowang2017** [comment]
问题确实解决了，编译安装的FFMpeg确实不会自带libx264，感谢
