### ISSUE TITLE
"OpenCL execution seems to have failed" error with Anime4K

### ISSUE THREAD

**Issue by junglized** [k4yt3x/video2x#197]
Hello,

First of all thank you for keeping such a great project alive!

Unfortunaltely I encoutered and error. I tried to upscale the sample video you provide in this repository with Amine4K set as upscaling algorithm, but this what I got with every upscaled image:

![error_1](https://user-images.githubusercontent.com/26525585/74101514-86c92a80-4b32-11ea-8304-9a581e0f44e4.jpg)

I checked Anime4K and JRE12 path in .json file and they seem to be correct. Is it the application or is it me doing something wrong?

**Comment by k4yt3x** [comment]
I would say try the Python source code directly and see if the problem still exists in the newest 3.0.0 code.

**Comment by junglized** [comment]
"try the Python source code directly" - I'm not sure I understand. Do you mean to use command console instead of GUI?

**Comment by k4yt3x** [comment]
I mean cloning the repo directly and running it with the Python interpreter.

**Comment by k4yt3x** [comment]
I'm actually having the same problem on my new workstation setup.
Investigating.

**Comment by junglized** [comment]
> I mean cloning the repo directly and running it with the Python interpreter.

I won't be too much of help here unfortunately. My knowledge of Python = 0. Sorry... :(

> I'm actually having the same problem on my new workstation setup.
> Investigating.

Ah, I see the right person with right amount of skills is already at it :)

**Comment by k4yt3x** [comment]
Actually, I haven't had much luck with this yet.
Any help will be appreciated.

**Comment by Gong-Mi** [comment]
Python operation registry


pulls  JDK_address

**Comment by Gong-Mi** [comment]
Python3.8
import winreg
###注册表路径自己定
JDK_Edition=12
time=0
JDK_registry_address=f"SOFTWARE\\JavaSoft\\JDK\\{JDK_Edition}\\MSI"

while time<20:
    try:
        key= winreg.OpenKeyEx(winreg.HKEY_LOCAL_MACHINE, JDK_registry_address)
    except FileNotFoundError:
        # 不存在  继续循环
        time =time+1
        JDK_Edition=JDK_Edition+1
        JDK_registry_address =f"SOFTWARE\\JavaSoft\\JDK\\{JDK_Edition}\\MSI"
        print("超过设本  提示安装jdk")
    else:
        # 存在 就跳出  data[0]为输出软件地址
        data = winreg.QueryValueEx(key, "INSTALLDIR") 
        break
else:
    # 超过设定版本  提示安装jdk
   key= winreg.OpenKeyEx(winreg.HKEY_LOCAL_MACHINE, JDK_registry_address)

print(data[0])

**Comment by k4yt3x** [comment]
Question is related to Anime4K.
Anime4K support has been deprecated and replaced with Anime4KCPP.
