### ISSUE TITLE
JSON object must be str, not bytes

### ISSUE THREAD

**Issue by Mirrorman95** [K4YT3X/video2x#2]
I get this error when I try to run the latest version of video2x:
JSON object must be str, not bytes
I was able to fix it by changing video2x.py line 98 to the following:
return json.loads(json_str.decode('utf-8'))

I also had to perform the following package install commands to get this new version of video2x to run:
pip install tqdm
pip install avalon_framework
pip install colorama

That's not an issue in and of itself, but if the readme doesn't already advise the user to install those packages beforehand, it should be changed to do so.

**Comment by K4YT3X** [comment]
Thanks a lot for the suggestions. I will change line 98 after I verify the issue. I will also add a requirements.txt and add dependency installation instructions.

**Comment by K4YT3X** [comment]
I have already resolved the decode error and added a requirements.txt.
I will update the usages soon.
Thank you for the feedbacks.
