### ISSUE TITLE
add Config file

### ISSUE THREAD

**Issue by wuast94** [K4YT3X/video2x#20]
I think a Config file would be nice for the path of ffmpeg and waifu2x (and any other ?). When updating for now i must go into the main file and edit it

**Comment by K4YT3X** [comment]
I was actually thinking about the same thing. A JSON file will be a nice-to-have. I'll work on it.

**Comment by K4YT3X** [comment]
Config file should already be usable in 2.1.2. I've also included a config file generator. See if that makes it easier for you.
