### ISSUE TITLE
可以加入对英特尔核芯显卡的支持吗？

### ISSUE THREAD

**Issue by MZW-BG** [k4yt3x/video2x#202]
我同学表示在一台使用核显的电脑上用不了，看了一下readme好像是需要A/N卡？
要是能加入对I卡的支持就真的是太美妙了（高中生表示在学校里只能用班里的渣机乱搞搞）
还是说本来就支持只是他的电脑不行？
（话说这个项目原来是国人开发的吗）

**Comment by k4yt3x** [comment]
显卡的支持是 waifu2x 实现控制的，并不是这个自动化软件所管理的范畴。

比如，`waifu2x-caffe` 是基于 CUDA 和 CUDNN 开发的，所以能够支持 CPU, GPU (CUDA) 和 CUDNN 三种模式，而  `waifu2x-converter-cpp` 是基于 OpenCV 和 CUDA 开发的，所以可以支持所有支持 CUDA 和 OpenCV 的平台。综上所述，可以试试看 `wafiu2x-converter-cpp` 和  `waifu2x-ncnn-vulkan` 能不能指定 Intel 核显。直接调用 `waifu2x-converter-cpp` 的命令行可以打印所有可用的设备和设备 ID，然后在 YAML 文件里设置 GPU ID。

但是问题是，Intel 核显的计算力完全无法比拟 AMD 和 Nvidia 高端显卡，所以效果可能并不会有多好，这么做我个人并不认为有多大意义，不过试试看 `Anime4K` 这种靠 CPU 的算法倒是可以。

> （话说这个项目原来是国人开发的吗）

是

**Comment by k4yt3x** [comment]
还有就是，即使某些驱动不能用显卡，用 CPU 还是可以的

**Comment by nihui** [comment]
https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility
windows 上 intel 6代及以上可以升级显卡驱动用 vulkan

https://downloadcenter.intel.com/product/80939/Graphics-Drivers
