### ISSUE TITLE
which means "preserve frames"?

### ISSUE THREAD

**Issue by kppomzh** [k4yt3x/video2x#205]
What is the use of this option?

**Comment by k4yt3x** [comment]
The simplified process of upscaling:

1. Dissect video into frames
1. Upscale frames
1. Put frames back into a video

`preserve_frames` prevents the extracted original frames and upscaled frames from being deleted if it's set to `True`. Otherwise, v2x will delete these cache files.

**Comment by kppomzh** [comment]
thanks!
