### ISSUE TITLE
questions with using video2x

### ISSUE THREAD

**Issue by chocolatecake2020** [k4yt3x/video2x#206]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||

## Symptom

I downloaded  **video2x-3.0.0-win32-full.zip** latest version from this
https://github.com/k4yt3x/video2x/releases

Video2x Caffe seems to work great. But I don't how to use scale ratio.

Anything above scale ratio 2 seems to be not working.

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/61452736/75234536-1bec4480-57fe-11ea-8078-327ad8aa0be2.png)

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
Please take a screenshot of the console's output.
That's where the useful info is.

**Comment by k4yt3x** [comment]
I saw the question has already been answered in the discussion group.
You're out of VRAM.
