### ISSUE TITLE
'--process' parameter option ignored when specified from .yaml

### ISSUE THREAD

**Issue by enekthedog** [k4yt3x/video2x#207]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|video2x-3.0.0-win32-light|
|`FFmpeg`|20200225-36451f9-win64-static|
|`waifu2x-caffe`|version: 1.2.0.2|

## Symptom

Changes to the 'process' parameter in the .yaml don't seem to be passed on to waifu2x-caffe-cui when video2x is ran from the command prompt on Windows. I don't know if this is intended considering some other waifu2x-caffe settings (noise_level, gpu, crop_size, batch_size) seem to be passed on from the .yaml fine if changed to non-default values (unless overwritten at the command prompt when starting video2x). I inserted a '--preset' parameter for ffmpeg using the .yaml and that's pushing through fine so seeing the 'process' parameter basically ignored by waifu2x-caffe seemed odd considering the established behavior with other stuff. Unless the only intended way to change this is by using -m <cpu|gpu|cudnn> at the command prompt when initializing video2x and never through the .yaml? Doing it at the command is fine and works but I'm just wondering why this parameter specifically doesnt seem to pass through, any clarification would be appreciated.

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/54195989/75410811-b2923180-58e2-11ea-8c7a-011dbe8096b2.png)

![Untitled2](https://user-images.githubusercontent.com/54195989/75415425-32bf9380-58f1-11ea-9219-813f54396e98.png)

**Comment by k4yt3x** [comment]
Please use `-m` command line argument. This will overwrite the configuration file option.
