### ISSUE TITLE
报错求解

### ISSUE THREAD

**Issue by Z-fly** [k4yt3x/video2x#209]
## Environment Information

video2x-3.0.0-win32-full

## Symptom

video2x -i 1.mp4 -o 2.mp4 -m cudnn --width=1920 --height=1080

## Screenshots or Error Messages
![image](https://user-images.githubusercontent.com/10470892/75967232-7d9b6580-5f06-11ea-9983-0a1c2aefe557.png)

![image](https://user-images.githubusercontent.com/10470892/75967040-2bf2db00-5f06-11ea-84ca-8110f52c307d.png)

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/75968253-0961c180-5f08-11ea-97da-a9d14883e361.png)

**Comment by k4yt3x** [comment]
Waifu2x-Caffe is saying that it can't open the model file, I'm not quite sure why it's throwing that error.
Do you have cuDNN installed?

**Comment by Z-fly** [comment]
视频文件：https://c-t.work/s/7ea1486a3f3a4e
电脑配置：![image](https://user-images.githubusercontent.com/10470892/76042594-2e017c00-5f90-11ea-9fb7-7c8dab4a6cd0.png)
![image](https://user-images.githubusercontent.com/10470892/76042613-3a85d480-5f90-11ea-8774-16efc6571157.png)

**Comment by k4yt3x** [comment]
You're specifying the mode to be cuDNN. Do you have cuDNN 10 installed?

**Comment by Z-fly** [comment]
@k4yt3x 
![image](https://user-images.githubusercontent.com/10470892/76042918-019a2f80-5f91-11ea-8e77-265249f45ae6.png)

**Comment by k4yt3x** [comment]
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

**Comment by k4yt3x** [comment]
Try using `gpu` instead of `cudnn`. I don't think you understand what it is.

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/76043791-87b77580-5f93-11ea-8b5e-7cc51e7fe627.png)

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/76044159-7458da00-5f94-11ea-9089-3d7584844c80.png)

**Comment by k4yt3x** [comment]
You ran out of VRAM. Try waifu2x-converter-cpp or a better GPU.
