### ISSUE TITLE
Add a Cancel Button to the GUI.

### ISSUE THREAD

**Issue by ZeroCool940711** [k4yt3x/video2x#210]
Would be nice to have a Cancel button on the GUI to cancel the current job and merge whatever Video2x has done so far into a video, sometimes the video you are processing is too long and after some work has been done you might want to see what the result is so far, this could be used as a preview to know what the final result would looks like also would be nice to have cancel button to safely cancel the current job and see the result instead of having to kill the process or close the whole program.

**Comment by k4yt3x** [comment]
This function has just been implemented in the latest version 3.0.0.
It will take a bit of time for this feature to be available for the GUI.

**Comment by k4yt3x** [comment]
Done! now you have it!
