### ISSUE TITLE
remove_upscaled_frames

### ISSUE THREAD

**Issue by 28598519a** [k4yt3x/video2x#211]
Since path.iterdir() return absolute path
but input_directory != output_directory
so the if file_path.is_file() and file in output_frames: will never True

This is code fixed
```
    def remove_upscaled_frames(self):
        output_frames = [f.name for f in self.output_directory.iterdir() if f.is_file()]
        for thread_id in range(self.threads):
            dir_path = self.input_directory / str(thread_id)
            for file in dir_path.iterdir():
                if file.is_file() and file.name in output_frames:
                    file.unlink()
                    output_frames.remove(file.name)
```

**Comment by 28598519a** [comment]
By the way, when I run video2x on Linux ? type(config['video2x']['video2x_cache_directory']) is <class 'pathlib.PosixPath'>
if isinstance(config['video2x']['video2x_cache_directory'], str) will be False

I use this instead
`if config['video2x']['video2x_cache_directory'] is None`

**Comment by k4yt3x** [comment]
Thanks for this issue. I saw your PR #214 as well.
I'll run through the code again and do some tests.
If everything checks out to be okay, I'll merge your PR.

**Comment by k4yt3x** [comment]
Thanks for the fix. I've already merged your PR.
