### ISSUE TITLE
Upscaler ran into an error: return non-zero exit status 3228369022

### ISSUE THREAD

**Issue by rombat** [k4yt3x/video2x#213]
## Environment Information

Video2x 3.0.0 full on Windows 7

## Symptom
video is splitted into pictures, but video2x crashes just after that (see screenshots)

## Screenshots or Error Messages
[Settings](https://www.dropbox.com/s/bub7058o4gy2msn/v2x_settings.PNG?dl=0)
[Error (GUI)](https://www.dropbox.com/s/bt99s70mgawta4h/v2x_error_box.PNG?dl=0)
[Error (cmd)](https://www.dropbox.com/s/bb471fleap6fhwv/v2x_error_cmd.PNG?dl=0)

```
```

**Comment by 28598519a** [comment]
what's your cuda and cudnn version?

**Comment by rombat** [comment]
Sorry about that, I just forgot to put cudnn dll into waifu2x-caffe directory...
It's working just fine, I'll close the issue
