### ISSUE TITLE
在运行时报错，不知道怎么回事

### ISSUE THREAD

**Issue by xiaowang2017** [k4yt3x/video2x#215]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|Newest|
|`FFmpeg`|4.1|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

合成视频时突然报错

## Screenshots or Error Messages

![QQ图片20200320213703](https://user-images.githubusercontent.com/42296908/77168686-2e9f2400-6af3-11ea-893e-4d621b6745ac.png)

```
```

**Comment by 28598519a** [comment]
你可以考慮先把 anime4k.py 的 107行註解掉
 因為shlex.join 依賴python 3.8

**Comment by xiaowang2017** [comment]
好的，另外还有个问题，批量处理视频的时候能否设置处理完一个视频以后就立即清空缓存，再去处理下一个视频，我的渲染服务器扛不住这么多缓存，一处理第二个文件就崩溃

**Comment by xiaowang2017** [comment]
另外，我在渲染过程中遇到了提示opencl错误，但是似乎对渲染没有影响
![QQ图片20200320213703](https://user-images.githubusercontent.com/42296908/77218870-f509ff80-6b6a-11ea-8d0e-8b7c87eddb6e.png)

**Comment by 28598519a** [comment]
#197

**Comment by 28598519a** [comment]
#197

**Comment by xiaowang2017** [comment]
> 
> 看起來是有的，所以不確定你在問什麼 [video2x.py#L425](https://github.com/k4yt3x/video2x/blob/master/src/video2x.py#L425)
> 
> #197

我就是很担心为什么它会不断报错，我跟https://github.com/k4yt3x/video2x/issues/197的报错信息还不一样

**Comment by k4yt3x** [comment]
> 
> 
> > 好的，另外还有个问题，批量处理视频的时候能否设置处理完一个视频以后就立即清空缓存，再去处理下一个视频，我的渲染服务器扛不住这么多缓存，一处理第二个文件就崩溃
> 
> 看起來是有的，所以不確定你在問什麼 [video2x.py#L425](https://github.com/k4yt3x/video2x/blob/master/src/video2x.py#L425)
> 
> #197

可能是因为 #211 ？

**Comment by xiaowang2017** [comment]
> > > 好的，另外还有个问题，批量处理视频的时候能否设置处理完一个视频以后就立即清空缓存，再去处理下一个视频，我的渲染服务器扛不住这么多缓存，一处理第二个文件就崩溃
> > 
> > 
> > 看起來是有的，所以不確定你在問什麼 [video2x.py#L425](https://github.com/k4yt3x/video2x/blob/master/src/video2x.py#L425)
> > #197
> 
> 可能是因为 #211 ？

不知道，不过我对比了一下处理前和处理后的画面，确实变清晰了，看来它不影响什么
