### ISSUE TITLE
converting webm is invalid

### ISSUE THREAD

**Issue by conghuahuadan** [k4yt3x/video2x#216]
full package, using the video2x_gui, driver is waifu2x caffe, converting webm is invalid

**Comment by k4yt3x** [comment]
Need more details on this error.

**Comment by conghuahuadan** [comment]
![Snipaste_2020-03-21_08-35-53](https://user-images.githubusercontent.com/20864280/77215493-52905300-6b4f-11ea-90f8-ecab120b8aa4.png)
![Snipaste_2020-03-21_08-37-44](https://user-images.githubusercontent.com/20864280/77215494-545a1680-6b4f-11ea-89e8-2536c6ca8040.png)
![Snipaste_2020-03-21_08-38-12](https://user-images.githubusercontent.com/20864280/77215495-5623da00-6b4f-11ea-88e7-a7f36bf339cf.png)

**Comment by 28598519a** [comment]
Your input is webm, and what you want to output is mp4.
But webm's sound format is opus, which cannot be combined with mp4.
You can convert webm to mp4 and then use video2x or output webm and then convert to mp4.
