### ISSUE TITLE
Request support for EDVR (MMSR)

### ISSUE THREAD

**Issue by xpirad** [k4yt3x/video2x#217]
Hello, can you please help implement EDVR in video2x?
It can be found here: https://github.com/xinntao/EDVR

It seems that EDVR is the "Winning Solution in NTIRE19 Challenges on Video Restoration and Enhancement", so uh, it's like , state-of-the-art?

It would be great if it's supported in video2x.

Anyways, thanks for making this amazing tool!

**Comment by k4yt3x** [comment]
Thanks, this sounds interesting. I'll probably work on this once I finish support for SRMD if I have time.

**Comment by xpirad** [comment]
That would be great! Thank you!

**Comment by k4yt3x** [comment]
I guess I'll do MMSR since they've merged EDVR into MMSR.

**Comment by ABDOELSHEMY** [comment]
It will be a dream come true, we strongly appreciate it, thank you

**Comment by k4yt3x** [comment]
It's not clear to me how to use MMSR to, say, upscale a frame or a video.
Does anyone know anything about that?

**Comment by ABDOELSHEMY** [comment]
@k4yt3x 
Unfortunately no, I have tried before and failed, it seems a little complicated to get it run

**Comment by k4yt3x** [comment]
They seem to have crammed everything in the repo without providing a usable interface?

**Comment by ABDOELSHEMY** [comment]
Correct, and so I can't understand it till now

**Comment by xpirad** [comment]
Will this help?
https://github.com/xinntao/EDVR/wiki/Testing-and-Training

**Comment by k4yt3x** [comment]
@xpirad that's training and testing the model, not actually how to run the software I believe.

**Comment by skerit** [comment]
@k4yt3x Isn't "testing" their way of saying "running"? Most super-resolution repositories I've used always refer to actually upscaling the images as "testing".

**Comment by skerit** [comment]
@k4yt3x @xpirad 
They renamed their collection, calling it "BasicSR" now: https://github.com/xinntao/BasicSR
Seems like there is some more information, but I'm not sure how useful it'll be since I believe there's only a model based on animals right now?
