### ISSUE TITLE
ERROR: An exception has occurred

### ISSUE THREAD

**Issue by PhiMphi** [k4yt3x/video2x#218]
![eror](https://user-images.githubusercontent.com/62534767/77286517-ff143580-6d05-11ea-96d7-ae41e6ebbd0d.png)
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```I have ERROR: An exception has occurred
What should i do?
It was working well at first but then it's turn out like this.
```

**Comment by k4yt3x** [comment]
Ah, the latest version of Video2X on master branch requries Python >= 3.8.x.
You can upgrade to Python 3.8, or comment line on 107 in file anime4k.py
