### ISSUE TITLE
How can i queue up several files?

### ISSUE THREAD

**Issue by Darnasion** [k4yt3x/video2x#219]
Hello,

i am fairly new to this. Is it possible to queue up more t han one file to be upscaled? And how do i do this? I guess via command line?

**Comment by k4yt3x** [comment]
This is currently only available through command line, since you can only choose a file in the GUI right now. Simply point the input to a folder, and v2x will upscale all files in that folder.

**Comment by k4yt3x** [comment]
FYI the ability to do so in GUI is already requested in #178

**Comment by Darnasion** [comment]
Thank you.
Got it to work with the command line.
