### ISSUE TITLE
Add GPU Acceleration for FFMPEG

### ISSUE THREAD

**Issue by wuast94** [K4YT3X/video2x#22]
When i use --gpu all threads are starting but using Cpu

**Comment by K4YT3X** [comment]
Video2x passes that argument through to waifu2x-caffe. Do you have proper CUDA drivers installed?

**Comment by wuast94** [comment]
All nvidea drivers are installed. Are cuda drivers seperatly ? I thibk i testes with waifu direct with cuda without problems. But i test this to be sure

**Comment by K4YT3X** [comment]
Nvidia drivers should be sufficient. Note that during the beginning of the process, CPU and RAM will be peaking before you see the GPU doing anything.

**Comment by wuast94** [comment]
But cpu just for ffmpeg ? Or am i wrong ?

**Comment by K4YT3X** [comment]
I took a look at the documentations and my code.

1. FFMPEG in my code indeed uses only CPU.
1. FFMPEG supports GPU acceleration.

I think it's time to add it.

**Comment by K4YT3X** [comment]
I think hardware acceleration for ffmpeg is working right now.
Hardware acceleration will be enabled by if `--gpu` or `--cudnn` is given.
