### ISSUE TITLE
Could find no file with path ...  and index in the range 0-4

### ISSUE THREAD

**Issue by sooxt98** [k4yt3x/video2x#221]
![image](https://user-images.githubusercontent.com/13378059/78473511-c3508580-7773-11ea-9561-408c4968a1c1.png)

**Comment by k4yt3x** [comment]
Look at the progress bar at the top. Upscaling didn't complete.
Something's wrong with the waifu2x binary. Try a different upscaling method and see if it works.

**Comment by sooxt98** [comment]
@k4yt3x do you mean try using different driver? If yes, my laptop only support this method

**Comment by k4yt3x** [comment]
That's what I mean. waifu2x-vulkan-ncnn should work on your machine as well.
