### ISSUE TITLE
source avi audio codec pcm_s16le

### ISSUE THREAD

**Issue by TReisser** [k4yt3x/video2x#224]
hi video2x team,
sorry i have a little Problem with my source and changing the configfile to handle it. 
Error from ffmpeg: 
error is: `Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container.`
i tried to set to acodec to aac but i can't get it working. my change in video2x.json
```
"output_options": {
    "-vcodec": "libx264",
    "-acodec": "aac",
    "-crf": 17,
    "-b:v": null,
    "-pix_fmt": null
},
```
Thanks for your help in advance and best regards,
Thomas

**Comment by k4yt3x** [comment]
I have a few questions:

- What version of v2x are you using? The latest version of v2x comes with YAML file as the config file by default.
- What does the FFmpeg command look like in the console?
- Try `-c:a aac`?

**Comment by TReisser** [comment]
it's the latest Version from git. 3.1.0 I tried also to change in the yaml config file.
[CompleteConsoleOutput.txt](https://github.com/k4yt3x/video2x/files/4468709/CompleteConsoleOutput.txt)
[video2x.yaml.txt](https://github.com/k4yt3x/video2x/files/4468716/video2x.yaml.txt)

**Comment by k4yt3x** [comment]
I see what's going wrong.

First, here's the order each section in FFmpeg will be used. This is sorted in order of execution in the original file, but when the setup script reads/writes to the file, the order changes.
![image](https://user-images.githubusercontent.com/21986859/79110682-7ddf1a00-7d6a-11ea-8d82-ab1238156feb.png)

What you should change is what's in `migrating_tracks`, when audio and subtitle tracks are moved from the original video. The codec here is set to `copy`.
![image](https://user-images.githubusercontent.com/21986859/79110756-a23af680-7d6a-11ea-9f2c-7933494918a8.png)

Take the `-c copy` apart into vcodec and acodec. Then set acodec to aac and it should do.
![image](https://user-images.githubusercontent.com/21986859/79110860-df06ed80-7d6a-11ea-95d6-78d73e2e9f22.png)

**Comment by TReisser** [comment]
great that worked!
i'd tried with 
-c:a aac
-c:v copy
before i asked you, that didn't worked.
thanks for your Help.

**Comment by k4yt3x** [comment]
no problem
