### ISSUE TITLE
Leaving width or height empty in GUI causes unclear error

### ISSUE THREAD

**Issue by metanomial** [k4yt3x/video2x#225]
If the `height` and `width` inputs are left blank on start, the following error is logged:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 535, in get
_tkinter.TclError: expected integer but got ""
```
This cropped up when the GUI informed me that the selected driver only allowed a scale ratio and I deleted the dimensions. The process failed to start. It took me a moment to work out what had caused the error.

**Comment by k4yt3x** [comment]
Leave it as 0?

**Comment by k4yt3x** [comment]
GUI redesigned.
