### ISSUE TITLE
Not able to install modules because of a "BadZipFile" error?

### ISSUE THREAD

**Issue by Itsyaboiidon** [k4yt3x/video2x#228]
Hi, I'm not entirely well versed on what's going on when installing the modules needed. 

I tried a couple times with an old and a new version of video2x, I followed the Step by Step tutorial but got stuck when installing the dependencies when executing "python video2x_setup.py" in cmd.

It seemed to complain about a zipfile.py (its name?) with the comment "file is not a zipfile".

In the end I tried using your latest light build that automatically setup dependencies but I had the same issue here aswell. Might be a very minor thing but I'm not a computer whiz so I have a hard time seeing what's the issue. 

Here's the screenshot: https://imgur.com/WcdRsLX

Thanks again

**Comment by k4yt3x** [comment]
Oh I see what's going on.
I just relocated the file server and I forgot that ZIP file is on there.

**Comment by k4yt3x** [comment]
I just pushed a patch. The issue should be fixed in https://github.com/k4yt3x/video2x/commit/47f94dfd6c485da4805c157a6f0c676bfe102d66.
Please try again.
