### ISSUE TITLE
希望可以添加切黑边和反交错的功能

### ISSUE THREAD

**Issue by Fiend1019** [k4yt3x/video2x#229]
DVD视频好多都有这些问题，所以后期十分希望可以添加切黑边和反交错的功能

**Comment by k4yt3x** [comment]
这种东西感觉 Premiere Pro 之类的做会比较方便吧
不过如果 FFmpeg 可以比较方便实现的话可以考虑一下

**Comment by Fiend1019** [comment]
> 这种东西感觉 Premiere Pro 之类的做会比较方便吧
> 不过如果 FFmpeg 可以比较方便实现的话可以考虑一下

十分感谢菊苣回复， FFmpeg可以实现，不过对于你来说方便不方便实现这我就不了解了。不过还是期待中ing

**Comment by k4yt3x** [comment]
请问您是否知道有什么相关的文档吗？我正在调查这个怎么做
还有如果有视频可以给做一下样本的话就更好了

**Comment by k4yt3x** [comment]
## 切黑边 (Crop/Cropdetect)

切黑边看起来比较容易实现，FFmpeg 做一个简单的 filter 就行了。

https://superuser.com/questions/810471/remove-mp4-video-top-and-bottom-black-bars-using-ffmpeg/810524

## 反交错（Deinterlacing）

反交错的实现看起来更复杂一些，首先如果是 Telecine 处理的视频需要 IVTC，而 true interlaced video 才会需要去用反交错滤镜。滤镜中最高质量的看起来是 [QTGMC](http://avisynth.nl/index.php/QTGMC)。

http://avisynth.nl/index.php/QTGMC

**Comment by Fiend1019** [comment]
很抱歉现在才回复，你回复的时候我这都凌晨三点了。有时差的感觉。。
首先黑边应该是很好解决的
交错是DVD视频的通病，尤其是运动场景多的。日本动漫一般都是“5烂2”。具体可以看看
https://zhuanlan.zhihu.com/p/33326278
文章末尾的参考资料也可以看看

这些问题一般出现在直接从DVD原盘提取的视频中，没有经过压制的。这里我传了一份remux的视频
是有上下左右黑边和交错的。文件里还有从缓存文件夹里复制的10帧图片，可以看看。
https://mega.nz/folder/cgtFyIZA#5jdcCcIYny_F9LkSCCI16Q

希望对你有帮助，我也是个小白。。。
ps: 这个视频放大完后能否发一份我瞅瞅效果

**Comment by k4yt3x** [comment]
> https://zhuanlan.zhihu.com/p/33326278

这篇文章我查资料的时候也看到了，挺有帮助的

**Comment by k4yt3x** [comment]
我们在 v2x 的群里讨论了很久要不要在 v2x 里加入 deinterlacing, IVTC, frame interpolation 等功能，大致结论如下：

- 项目的开发者都时间有限（大部分代码是我写的，我又是个学生），如果要加入这些功能，将会需要花很多时间更改现在代码的结构。如果要实现这些功能，最好的办法是让这个项目变得模块化，这样势必会彻底更改目前的结构，增添很多代码。这个过程会消耗很多时间，也会给后续的维护增添很多工作。目前大多数开发者，包括我和其他贡献者都没有时间精力来处理。
- 如果不重构项目让项目模块化，功能将以硬编码而不是插件的形式实现，这样前期工作量会小一些，但是项目结构会变得非常僵硬且难管理。
- 对于切黑边、反交错、补帧等功能，已经有其他的框架项目（avisynth, hybrid, etc.）可以完成，并且 avisynth 这个框架还有 FFmpeg 所没有的 QTGMC、FineDehalo 这样的插件。
- 增添这些功能对视频的处理流程也会产生影响，例如去交错必须在放大之前进行。如果不将项目模块化，更改流程也是件棘手的事。
- 切黑边、反交错、补帧等功能并不是 v2x 的设计初衷，v2x 使使用 waifu2x 放大视频成为可能，但是以上的这些功能并不是，也不应该是 v2x 的工作。

综上所述，我并不认为 v2x 会加入对这些功能的支持，至少在可以预见的短期内不会，因为这些功能并不是 v2x 所该负责的，而且已经有现成的，更好的选择。

不过用其它工具反交错切黑边应该也并不会很难，用 FFmpeg 的 cropdetect 切黑边，再用 bwdif 算法反交错，应该也是两条命令就能解决的事情。在命令行里处理不会很复杂，而把这两条命令编进 v2x 里将会很难。

虽然我也很想让 v2x 成为一个全能的工具，不过现在好像看来这么做的意义并不大，而消耗却非常巨大。希望您能够理解。

**Comment by k4yt3x** [comment]
虽说目前大概不会将这些功能加入 v2x，不过我还是可以看看您提供的视频
并且我在考虑的一个可能性是将这些功能的 FFmpeg 命令做成脚本放进一个 script 文件夹
这样也算是个折衷选择

**Comment by Fiend1019** [comment]
可以理解，还是十分感谢您的答复！
起初是想到放大是一帧一帧的放大，这些交错的帧可能会造成一些影响。再来视频压制虽然可以实现反交错，但是会造成画质损失。
不过具体有没有影响我这也不知道，我这软件打开一直报错。还在找问题解决中。。。貌似和图片那两个缓存文件夹有关。放大时找的是哪个空的文件夹，一直提示找不到文件。

**Comment by k4yt3x** [comment]
如果解决不了的话可以把日志（整个输出）复制粘贴上来我看看是什么问题
截图也行

**Comment by Fiend1019** [comment]
![QQ图片20200425094719](https://user-images.githubusercontent.com/64277417/80268524-4feac580-86da-11ea-96d9-94ff3414d0d5.png)
顺着路径找了下，文件夹为空，倒是另一个文件夹里面有文件

**Comment by k4yt3x** [comment]
是不是跟路径中文名有关

**Comment by Fiend1019** [comment]
![QQ图片20200425105704](https://user-images.githubusercontent.com/64277417/80269581-985ab100-86e3-11ea-9871-e545ef33152c.png)
![QQ图片20200425105612](https://user-images.githubusercontent.com/64277417/80269582-9a247480-86e3-11ea-8e12-db478d4ad440.png)
![QQ图片20200425105520](https://user-images.githubusercontent.com/64277417/80269583-9abd0b00-86e3-11ea-8292-5bff6bc07e40.png)
试了，没用。。。

**Comment by k4yt3x** [comment]
我试着跑了一下，MKV 文件音频有问题，但是视频我先放出来
http://akas.io/t12

**Comment by k4yt3x** [comment]
@Fiend1019 这个找不到文件大概是没装 JDK12
