### ISSUE TITLE
Upscaler ran into an error

### ISSUE THREAD

**Issue by CheaterHu** [k4yt3x/video2x#230]
我就是直接调整一个MP4的文件，结果最后的时候弹出这个错误。

![image](https://user-images.githubusercontent.com/12546922/80314273-1b365580-8823-11ea-8999-2410c38249f6.png)

还有救吗？不知道怎么办，另外.webm的格式也是不行的。

**Comment by k4yt3x** [comment]
这个错误并不能看出来到底什么出了问题
看下命令行输出了什么

**Comment by CheaterHu** [comment]
嗯，我以为这个弹窗是你们自己输出的错误。。看了下日志，好像是jdk版本低了，需要多少版本的啊？另外有支持Mac的打算吗？

**Comment by CheaterHu** [comment]
> 这个错误并不能看出来到底什么出了问题
> 看下命令行输出了什么


嗯，我以为这个弹窗是你们自己输出的错误。。看了下日志，好像是jdk版本低了，需要多少版本的啊？另外有支持Mac的打算吗？

**Comment by k4yt3x** [comment]
V2X 使用的 Anime4K.jar 必须要 JDK 12，然后作者也没有更新 JAR 文件甚至还把 release 删了
他最后发布的一个版本就只能用 JDK 12 跑所以没什么办法
下载的话去下面这个官网链接，需要注册个 Oracle 账号
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html

对 Mac 的支持还要看各种 waifu2x driver，比如如果想要在 Mac 上跑 waifu2x-caffe，那就必须先在 Mac 上编译安装 Nvidia CUDA/cuDNN 和 waifu2x-caffe。如果这两者能装上去，v2x 是 python 所以是跨平台的，改一下配置文件就能用。

**Comment by CheaterHu** [comment]
> V2X 使用的 Anime4K.jar 必须要 JDK 12，然后作者也没有更新 JAR 文件甚至还把 release 删了
> 他最后发布的一个版本就只能用 JDK 12 跑所以没什么办法
> 下载的话去下面这个官网链接，需要注册个 Oracle 账号
> https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html
> 
> 对 Mac 的支持还要看各种 waifu2x driver，比如如果想要在 Mac 上跑 waifu2x-caffe，那就必须先在 Mac 上编译安装 Nvidia CUDA/cuDNN 和 waifu2x-caffe。如果这两者能装上去，v2x 是 python 所以是跨平台的，改一下配置文件就能用。

英伟达官方CUDA/cuDNN 没得mac平台支持吗？那要是不是英伟达显卡的mac是不是就根本没得希望了

**Comment by k4yt3x** [comment]
Nvidia 官方有 macOS 的 CUDA 驱动的，但是编译 waifu2x 还是个问题

**Comment by CheaterHu** [comment]
> Nvidia 官方有 macOS 的 CUDA 驱动的，但是编译 waifu2x 还是个问题

另外为什么我转化十来秒的视频会占用10多个G的内存，最终还因为内存不够而失败，是vide2x.yaml文件没配置对吗？我用下载的full版本使用的默认配置

**Comment by k4yt3x** [comment]
内存？还是存储空间？

**Comment by CheaterHu** [comment]
> 内存？还是存储空间？

磁盘，我觉得是配置问题，full的默认配置可以用吗？感觉配置太高了，太占用磁盘空间了，十几秒的视频能占用几十个g

**Comment by k4yt3x** [comment]
因为这个程序的本意就是增强画质，所以所有设置都默认调的是最高上限
在配置里可以调拆出来帧的格式，默认是 rgba64be，可以调成 rgb24 之类的试试看，应该会小一些
`video2x.yaml` 配置文件里的下图位置就是

![image](https://user-images.githubusercontent.com/21986859/80526636-93fff380-8982-11ea-8360-3a89441c4aea.png)

**Comment by ImportTaste** [comment]
```
[+] INFO: Framerate: 20.0
[+] INFO: Starting to upscale extracted images
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 418, in <module>
    upscaler.run()
  File "D:\video2x\upscaler.py", line 356, in run
    self._upscale_frames()
  File "D:\video2x\upscaler.py", line 220, in _upscale_frames
    self.image_format))
  File "D:\video2x\waifu2x_caffe.py", line 85, in upscale
    Avalon.debug_info(f'[upscaler] Subprocess {os.getpid()} executing: {shlex.join(execute)}')
AttributeError: module 'shlex' has no attribute 'join'
Cleaning up cache directory: C:\Users\ImportTaste\AppData\Local\Temp\video2x\tmpus6hl4oy
Cleaning up cache directory: C:\Users\ImportTaste\AppData\Local\Temp\video2x\tmpczpidgm8
Cleaning up cache directory: C:\Users\ImportTaste\AppData\Local\Temp\video2x
Press any key to continue . . .
```

**Comment by ImportTaste** [comment]
https://docs.python.org/3/library/shlex.html

![image](https://user-images.githubusercontent.com/53661808/80649543-ddf6e100-8a37-11ea-9624-b70e8740a812.png)

Python 3.8 is still incompatible with some of the things I use, so this is probably the problem.

**Comment by k4yt3x** [comment]
Question is related to Anime4K.
Anime4K support has been deprecated and replaced with Anime4KCPP.
