### ISSUE TITLE
Retention of extracted images

### ISSUE THREAD

**Issue by githupper** [k4yt3x/video2x#232]
## Description
Stop V2X from deleting extracted images automatically

Briefly describe the feature you want to be added into `video2x`.
V2X currently deletes extracted images automatically when application hits an error or issue during upscaling process. In my example, I wrongly set it to 4x scaling when using Waifu2x Vulkan NCNN as I was not aware it doesn't support above 2x scaling. This forces me to re-extract the same images again.

Extracted images can also be useful when user wants to do a comparison between different configurations (RGB24 vs RGB64BE for example), speed/quality comparison between different drivers/methods etc

Suggestion: a GUI option to disallow/allow deletion of extracted images or an option within yaml file.

**Comment by k4yt3x** [comment]
This feature is already supported. Change `preserve_frames` to `true` in the config file.
