### ISSUE TITLE
Gray out certain options in Video2x GUI when option is illegal

### ISSUE THREAD

**Issue by githupper** [k4yt3x/video2x#234]
## Description
To support graying out of unsupported options

Briefly describe the feature you want to be added into `video2x`.

Video2x 1.1.3 currently allows setting of Scale Ratio of above 2 when used with Waifu2x NCNN Vulkan which currently supports 2x only.  Hence after it extracts the images, it throws an invalid scale argument and stop all process and delete all extracted images

This could have been prevented by disallowing Scale Ratio of more than 2 for Waifu2x NCNN Vulkan. The error should return an error much like "Selected drive "Waifu2x NCNN Vulkan" accepts only scaling ratio when I try to define the width and height manually.

Thanks

**Comment by k4yt3x** [comment]
Implemented.
