### ISSUE TITLE
waifu2x-ncnn-vulkan System Crash on Conversion Step

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#235]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|3.0.0 full|
|`FFmpeg`|whats included in 3.0.0 full release| 
|`waifu2x-caffe`|whats included in 3.0.0 full release| 
|`waifu2x-converter-cpp`|whats included in 3.0.0 full release| 
|`waifu2x-ncnn-vulkan`|whats included in 3.0.0 full release| 

## Symptom

When using Driver Waifu2x NCNN Vulkan, scale 2, image format PNG, Threads 1, Method tried both GPU and CDUNN  

So when doing longer videos my entire computer seems to die on the last step (conversion) after the gpu intensive upscaling . The upscaling seems to finish and the cpu intensive conversion portion which I assume is simply re merging the upscaled  images fails. On all my tests it seems to get roughly 2000 frames into this process before suddenly making my entire computer die. 

What I mean by this is the computer is still on but all the monitors lose signal and hard reboot is necessary. I'm guessing this is gpu related but it's strange because it happens during the second cpu intensive portion. Also since the last step is relatively quick 5 -10 mins usually I figured maybe it's just that the gpu died and wont display to the monitors but the program is still working in the background. So I waited 15 - 20 mins to ensure if it was still working in the background than that would be enough time to finish the video. But on reboot it seems the video was not created. 

It's worth mentioning that my testing using the same settings on a 2 second video works without issue. The issue only occurs with longer videos. I've had it happen on 3 different videos around 3, 4, and 5 mins respectively. 

My drivers are fully up to date. I'm using a gtx 1070, windows 10.

**Comment by MatteCrystal** [comment]
I have tested doing the long videos using the waifu2x-caffe driver and got the same issue. I then switched to the old version of video2x-2.9.0-win32-full that I used in the past for a long 20min video. I used  waifu2x-caffe driver with GPU and had the same crash.

I haven't changed any hardware on my pc it seems it may have to do with the newest drivers not working properly, or some other hardware or software issue i'm having.

**Comment by dgcampea** [comment]
This sounds like your RAM or HDD might be failing.

**Comment by renafsouza** [comment]
I'm having the same issue. I've tried on linux with the docker container, tried on windows, tried with different disks. Nothing seems to help. It crashes after processing 3 to 5 frames, the system just reboots.

**Comment by k4yt3x** [comment]
@renafsouza Unless you're still using version 3.0.0, this is the wrong place to comment. Every major revision has a completely rewritten code base, so it is more likely it's a completely different issue. Open a new issue for it.
