### ISSUE TITLE
User change cache location

### ISSUE THREAD

**Issue by AlexFlait** [k4yt3x/video2x#236]
## Description

Hello! I don't have a lot of memory on system disk, because it's too small and I want to work with the program. Can you add option to give user ability to change cache folder location? I can cut the video on 2-5 seconds pieces to use less space, but it's look like I'm ill, when I working with 20+ mins videos :(

**Comment by k4yt3x** [comment]
You can modify the `video2x_cache_directory` key in the configuration file to change the cache location.

![image](https://user-images.githubusercontent.com/21986859/80874951-29b0c100-8caa-11ea-9ac2-918004696058.png)
