### ISSUE TITLE
除了Anime4k，其余全部报错

### ISSUE THREAD

**Issue by Fiend1019** [k4yt3x/video2x#237]
安装JDK后，anime4k可以跑了，但是其余的还是报错，如图所示。

![QQ图片20200505001334](https://user-images.githubusercontent.com/64277417/81083286-f4fd6d80-8f26-11ea-927a-f37849f120ef.png)

**Comment by k4yt3x** [comment]
waifu2x-caffe 的话，有 Nvidia GPU 和 CUDA 驱动吗？

**Comment by Fiend1019** [comment]
有的，CUDNN也安装了


![QQ图片20200506114038](https://user-images.githubusercontent.com/64277417/81136560-82c07380-8f8e-11ea-89f5-aab3c359a31d.png)

**Comment by k4yt3x** [comment]
这是 CUDA compiling tool，只要装普通的 Nvidia 显卡驱动就有 CUDA 了。
Waifu2x Caffe 只是说出错了，也没有打印什么有用的信息，一般来说这种情况是驱动没装好。

**Comment by Fiend1019** [comment]
果然是驱动的问题。真是太感谢了！问题已经解决了，很抱歉打扰你这么次。

**Comment by k4yt3x** [comment]
没事没事，开发者兼客服 2333
是我的职责
