### ISSUE TITLE
Cache folder not created again after processing a video

### ISSUE THREAD

**Issue by ZeroCool940711** [k4yt3x/video2x#238]
## Symptom
When you finish processing a video, if you start processing another video it will 100% of the time fail as video2x GUI does not create the cache folder, it will then fail because it won't be able to find the cache folder to place the video frames.

**Comment by k4yt3x** [comment]
Thanks will investigate

**Comment by ZeroCool940711** [comment]
Also, if you set the cache folder to something different from the default location sometimes it goes back to the default location after processing a video, what I mean is it deletes the new cache folder on the new location and falls back to the default location, could be that somewhere on the code the first time it checks for the new location but then later checks for the old/default location to see if there is the cache folder, in either case it still doesn't create the cache folder anywhere. BTW, im on Windows 10 and im using the Full package of the 4.0.0 release.

**Comment by k4yt3x** [comment]
Issue addressed on master branch.
