### ISSUE TITLE
Some problems of Anime4KCPP Driver

### ISSUE THREAD

**Issue by TianZerL** [k4yt3x/video2x#239]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|`4.0.0 Beta1`|
|`Anime4KCPP`|`1.6.0`|

## Symptom

If GPU Mode is enabled, it will get an error of `Read kernel error`

## Reason
If enabled the GPU Mode, Anime4KCPP will try to read the kernel file `Anime4KCPPKernel.cl` in the current working directory, which is `./Anime4KCPPKernel.cl`, this is for the convenience of debugging.  
I will integrate the kernel file to the cpp source at the proper moment, but now you may need to copy this file to the current  working directory of V2X.  

BTW, `--preProcessing` and `--postProcessing` has been replaced by  `--preprocessing` and `--postprocessing` in the newest release of Anime4KCPP

**Comment by k4yt3x** [comment]
Thanks I'll never be able to figure that out myself.
I'll do an `os.chdir` for the moment to mitigate this issue for now.

**Comment by ZeroCool940711** [comment]
I was going to make an issue for this as I also noticed that error on the Anime4KCPP driver, good to see it was already reported :)

**Comment by k4yt3x** [comment]
This issue has been fixed on master.
