### ISSUE TITLE
Some quality-of-life improvements (command line arguments and core processing tweaks)

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#24]
So been playing around with this script a bit more. I have an old show of about ~90 episodes I'd like to start processing with this. Some things that immediately came to mind that could probably be improved upon:

1) Currently the 'demux' and 'remux' stages assume a single AAC audio track and fail if there's any other formats used and miss secondary audio tracks. Being able to dynamically work with what is in the source file would be nice, including multiple audio tracks as well as subtitle tracks. Maybe just automatically say all tracks after the video track just copy them 1:1 to the output video. Don't even need to re-encode here since that can be done after the fact pretty easily.

2) There are a LOT of command line arguments being given to ffmpeg along the way as well as even waifu2x-caffe which are currently hardcoded and could be more suitable having some of them as either command line options or in the config file. Prime example is the h264 encoding stage and being able to fine tune the encoding settings. Even a one off case I'm running into is cropping black borders off at the frame extraction stage that otherwise get blown up needlessly otherwise in the end.

3) Maybe choose to have options to redirect the frames and upscale folders to a different location.

I may play around with these on my own but can't guarantee anything or even a timeframe. Not a developer by any means (unless you count some crusty php knowledge from 10+ years ago that barely counts as novice level. lol) but have been meaning to pick up python at some point so may give me something to toy around with.

**Comment by K4YT3X** [comment]
@cr08 I'll have to thank you before I get to what you've just said. I love getting useful and well structured suggestions like yours from the community.

And to answer each of your points:

1. Yes, I agree that video2x isn't handling streams very well. I'll have to read deeper into how video/audio streams work before I can enhance the experience properly.

1. You can already add FFMPEG arguments manually in `video2x.json` in a few updates ago, but I still want to give the user more control over what's being passed to FFMPEG. You can also define the encoding by just changing the suffix of the output video I believe. As for extra arguments for `waifu2x-caffe`, I'll make it happen.

1. That's a good idea, I'll add a cache folder setting in the config file (`video2x.json`).

**Comment by cr08** [comment]
I think I've figured out the stream bit after toying around with ffmpeg and finding some obscure superuser.com posts. This is essentially what I have come up with:

`ffmpeg -i ORIG_VIDEO.mkv -i upscaled\no_audio.mp4 -map 1:v:0 -map 0 -c copy -map -0:v FINAL_MUX.mkv`

This is assuming the original video is still intact during this process which it should be. We are initially pulling in both the original with all streams as well as the newly upscaled video only stream. **-map 1 :v :0** says we want to start right off the top with the newly upscaled video stream from the second input file to take precedence as stream 0 in the final mux. **-map 0** has us taking every stream, video, audio, subtitles, and otherwise, from the original video and **-c copy** obviously has us copying it all over without any re-encoding. **-map -0:v** (see the extra hyphen at -0, which eluded me for some time as an option) says any video streams in the original video we will ignore and will not make it into the final mux.

As for the ffmpeg arguments bit, I am aware of that. However in its current state it applies to all stages that use ffmpeg equally which may not be desired. ie: The scenario I made above about needing to crop the source video before exporting frames. That crop filter will not apply well on the h264 encode after everything is upscaled for example. I will admit, however, that it may be a limited use case.

Additionally certain options in ffmpeg are sensitive to what order the arguments are in which makes it even more of a pain. Honestly I'm not even sure at this point how to accomplish that in the cleanest way possible.

**Comment by K4YT3X** [comment]
@cr08 Thanks for the explaination for the map option.

The most ideal way for this project to be written will be to use the python-ffmpeg library instead of the ffmpeg binary. I still really want to look into the library.

The only way I can add customization into every ffmpeg command is to create a separate entry for every ffmpeg command executed, which will be quite some work, and deosn't seem very elegant.

I'm pretty busy recerntly with my school work, I'll take a look at how to improve this script once I'm done with this intense period of time.
