### ISSUE TITLE
Accelerated video

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#240]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|Video2X 4.0.0 Beta1|

## Symptom

Video2x processed to the end without error but when i play the video, the sound is good but the images are accelerated, around x4 and the last 3/4 time is just the last image with the sound.

## Screenshots or Error Messages

![Setings](https://user-images.githubusercontent.com/65050591/81465439-817b8a80-91ca-11ea-872c-1af1159cad39.png)

Should i try with the newest version?

**Comment by k4yt3x** [comment]
I don't think the newer version will fix this problem.
I think it's the best if I can have the source file so I can debug the program and see what went wrong.
I'll need to see FFprobe's output.

**Comment by Faniia** [comment]
I tried with the original video and un cut, the 2 ones bugged. Where can i upload the video to provide it to you?

**Comment by k4yt3x** [comment]
You can use [Firefox Send](https://send.firefox.com/) if it's under 1 GB.
I'll find another way if it's too large for Firefox Send.

**Comment by Faniia** [comment]
I send the cut video, as i said the original video bugged too.
https://send.firefox.com/download/1caeb9d9e8ee85bf/#25x3Cctv68-GQf-6FmKTVw

**Comment by k4yt3x** [comment]
Alright thanks. I'll investigate.

**Comment by k4yt3x** [comment]
Ok I was able to reproduce what you described.
For some reason FFmpeg reads an average frame rate of about 120 FPS.
I'm looking into how to fix this. I'll probably have to sleep and look more into it tomorrow.

![image](https://user-images.githubusercontent.com/21986859/81468690-9d822a80-91d0-11ea-83a6-9e2cb913e71a.png)

**Comment by k4yt3x** [comment]
It appears maybe I should be using `r_frame_rate` instead of `avg_frame_rate`.
I'll make some changes and test and it should be fixed in the next release.
If you're in a hurry, I can get you an internal alpha build.

https://video.stackexchange.com/questions/20789/ffmpeg-default-output-frame-rate

**Comment by k4yt3x** [comment]
This issue should be addressed in master branch commit: https://github.com/k4yt3x/video2x/commit/bcb54b6d2cef71d01191196b31d5c22c00e09e74

Here's a temporary alpha build that should address your problem
https://send.firefox.com/download/b7f711cdaed6e04a/#AuYnROMXAiZGwzN_uQI89g

**Comment by Faniia** [comment]
Thanks for your quick reaction, i'm going to test it.

**Comment by Faniia** [comment]
Thanks it perfectly worked!

**Comment by k4yt3x** [comment]
Glad to hear that.
