### ISSUE TITLE
Is there a way to pass -threads # to the ffmpeg portion of the process?

### ISSUE THREAD

**Issue by andyhines** [k4yt3x/video2x#241]
## Description

For thermal reasons and to have it operate in the background more easily, it would be nice to be able to restrict the number of threads ffmpeg uses while disassembling/reassembling the video files. Is this already an option? I may be able to re-compile ffmpeg or the project to do it manually but a setting would be nice. Thank you for your work!

**Comment by k4yt3x** [comment]
Video2X provides a highly customizable interface for FFmpeg. To add `-thread 1` to all FFmpeg commands for example, you can add an item to these places in the config file.

![image](https://user-images.githubusercontent.com/21986859/81483550-938f1480-922e-11ea-957b-9fc1bc373ba0.png)

You can add it like this

![image](https://user-images.githubusercontent.com/21986859/81483597-dd77fa80-922e-11ea-8da3-17b6dfaca6ae.png)

This new line will add these args to the FFmpeg command.

![image](https://user-images.githubusercontent.com/21986859/81483617-12844d00-922f-11ea-842a-e35d16c02132.png)

**Comment by andyhines** [comment]
![threads_1](https://user-images.githubusercontent.com/7064299/81484155-89125200-9211-11ea-8230-34d28e68776e.PNG)
 Thank you for the help, I had tried setting the -threads in the .yaml in those locations as you've shown, and I tried '- threads' and '-thread' as well but  for some reason even with '-threads': 1 (or another value, like 6) set, I am seeing full use of 8cores/16 threads during the initial ffmpeg rip. I can set core affinity and that restricts the load, though it unfortunately needs to be set every time. Is the -threads 1 setting restricting ffmpeg to one thread for you? If so the issue may simply be something else on my end. Thank you for your time!

**Comment by k4yt3x** [comment]
Ok I see what's wrong. It shouldn't be appended as an input option, but an output option.

Move that line from the end into the output_options section, and it should be fine.

![image](https://user-images.githubusercontent.com/21986859/81485438-8ed15d00-923c-11ea-9e67-aacf733e1f6a.png)

![image](https://user-images.githubusercontent.com/21986859/81485437-84af5e80-923c-11ea-9629-30a833cd6cb9.png)

**Comment by andyhines** [comment]
That does it! Brilliant! I suppose I should have tried moving it around to different locations, thank you. Now it's running quickly but nice and cool and controlled!

**Comment by k4yt3x** [comment]
Video2X's FFmpeg parser is quite powerful and flexible, but it's a bit hard to learn, and I haven't wrote much documentations for it. It will be then, my job, for now, to tell you how to make it work.

Expect more documentations around it and GUI support in the future though.
