### ISSUE TITLE
Failedupscaling

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#242]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||

## Symptom

Failed upsclaing.

## Screenshots or Error Messages

I tried to used video2x on my laptop and itdoesn't work on it.
First message error didn't block the software but tesecond did.
![Bug0_video2x](https://user-images.githubusercontent.com/65050591/81484645-774ba180-9247-11ea-92c0-377a6898d446.png)
![Bug_video2x](https://user-images.githubusercontent.com/65050591/81484646-7dda1900-9247-11ea-82ce-b2ad0354fe2b.png)

**Comment by k4yt3x** [comment]
You're using waifu2x-caffe with GPU mode, which requires Nvidia GPU and CUDA driver.
Do you have those installed?

**Comment by k4yt3x** [comment]
The first error message just says the codec your video is in cannot be accelerated by hardware. You can ignore it for now.

**Comment by Faniia** [comment]
There is a NVIDIA GeForce GT 540M. Maybe i don't have CUDA driver installed, i'm checking it.

**Comment by Faniia** [comment]
Ok, i think it's just that my GPU is dead.
Well, on my main pc, i feel the upscaling low, it does around 1 fps. Is it normal or can i improve it?
Thank you in advance.

**Comment by k4yt3x** [comment]
It's supposed to be around that speed.
If you want it to be faster, using waifu2x-caffe with cuDNN is an option, but cuDNN's installation process is a bit complicated.

**Comment by Faniia** [comment]
Could you make a tutoriel? I'm sorry for asking if it already exist.

**Comment by k4yt3x** [comment]
You can follow the official guide here: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-windows
To download, you'll also have to create an account and join the developer program.

As for how much the improvement will be, check waifu2x-caffe's official test results: https://github.com/lltcggie/waifu2x-caffe#cudnn%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
I know, it's in Japanese. Just use Google translate if you need to.

**Comment by k4yt3x** [comment]
When you're done installing cuDNN, you can use waifu2x-caffe's built-in check cuDNN function to check if you've installed it correctly.
