### ISSUE TITLE
Decoding stalls with low CPU usage and 100% HDD active time

### ISSUE THREAD

**Issue by STribbey125** [k4yt3x/video2x#244]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.0.0 beta3|
|`FFmpeg`|Included with full package|
|`waifu2x-caffe`|Included with full package|
|`waifu2x-converter-cpp`|Included with full package|
|`waifu2x-ncnn-vulkan`|Included with full package|

## Symptom

Decoding step stalls around the 7 minute mark, with 100% HDD active time, low write speed, 1% CPU usage. 

Non-default driver settings (waifu2x-caffe):
Process: cudnn
Processes: 3

I successfully completed a 2x upscale on a 720x480 video, and encountered this issue by attempting to 2x upscale the resulting output. I was successful the first time with placing the temp folder on my SSD, but had to switch to my 2TB HDD due to my SSD being too small for the next upscale.
Upon opening resource manager, the HDD usage all comes from the remaining active frame writes.
Is there anything more I can consider other than hardware failure? I've ran chkdsk with no drive errors found.

**Comment by STribbey125** [comment]
I made a slight improvement by setting Processes to 1, but now the CPU stays mostly idle or <25% and spikes up to full load intermittently and briefly. Hard drive condition remains the same, and write speed is of course terrible.

**Comment by k4yt3x** [comment]
Why did you close the issue? I haven't got to it yet.
If you're using waifu2x, you don't necessarily need to use multi-processing. Leaving it at 1 thread should consume most of your GPU's computing power.
You're talking about CPU usage, but what about your GPU usage?

**Comment by STribbey125** [comment]
I got around the problem by just leaving Processes at 1, but perhaps I shouldn't have closed the issue yet. Sorry about that.
Should I expect to see GPU usage when it's pulling frames from the video? This problem was during that step, and I had no GPU usage. I do see GPU usage once I get to the upscaling step.

**Comment by k4yt3x** [comment]
Oh ok if it's during the FFmpeg, step, then what happened should be what's supposed to happen. Considering frame extraction creates a large amount of small files on your disk, it will be a lot of random reads and writes on your disk, which HDD is known to be bad at.

**Comment by STribbey125** [comment]
Ah gotcha. Thanks for the quick help.
