### ISSUE TITLE
CUDNN_STATUS_SUCCESS (1 vs. 0) CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#246]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Failing upscaling, i think the problem is the cache folder.

## Screenshots or Error Messages

![Cache_folder](https://user-images.githubusercontent.com/65050591/81606201-eb668080-93d2-11ea-85e6-14fbf2765133.png)

**Comment by k4yt3x** [comment]
From what I see in the error message, something's wrong with your GPU driver.

**Comment by Faniia** [comment]
Hum ok, i made un update of my drivers, video2x worked before i made it.
I installed GeForce Game Ready Driver, version 445.87.
Do you have to make an update of your software or i have to change my drivers?

**Comment by k4yt3x** [comment]
Try rebooting first, it might be a temporary issue.

**Comment by Faniia** [comment]
I tried again after rebooting, but i still have an error upcaling.
![Error](https://user-images.githubusercontent.com/65050591/81624147-c0d9ef00-93f5-11ea-979f-ebdfe75100a5.png)

**Comment by Faniia** [comment]
I tried to reinstal, reboot and made multiple tests with differents versions of video2x but it can't upscale.
I don't know if the issue comes from the installation of my drivers or my attempt to install CUDA.

**Comment by k4yt3x** [comment]
You don't seem to be using cuDNN, but it seems like it's warning you about something related to a cuDNN failure. If it still doesn't work for you, maybe try another driver.

**Comment by Faniia** [comment]
i tried it with 3 differents Drivers for my configuration (GTX1600), recommanded/Dertified versions but it does not work.
I don't know what to do, i think i made something wrong following with guide https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-windows

Is it possible it cause the issue?

**Comment by Faniia** [comment]
God damn, i finally found what was the problem.
It effectively was an issue when i tried to follow the guide.
I followed this:

4.1.2. Installing The CUDA Toolkit For Windows

Refer to the following instructions for installing CUDA on Windows, including the CUDA driver and toolkit: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html


But it made me download a version that does not work with Video2x.
In the CUDA directory path C:\Program Files\NVIDIA GPU Computing Toolkit\
i deleted the CUDA folder and replace it by an other that i downloaded here: https://developer.nvidia.com/cudnn

**Comment by k4yt3x** [comment]
Oh you're supposed to install CUDA kit then paste the content of the cuDNN download in to the CUDA folder. It's your installation's problem then.

**Comment by Faniia** [comment]
Yes it was my fault.
Well, thanks a lot for your assistance, i can use waifu2x-ncnn-vulkan now.

**Comment by Faniia** [comment]
Hello,

I am sorry but i don’t get a good video with waifu2x-ncnn-vulkan.
Could you try to use it with my 20s video test to say me if it’s me or a bug ?
https://send.firefox.com/download/24db862855aaecd1/#-7KBl1L_l5btyVtsY98pKg

I really would like to use waifu2x-ncnn-vulkan because i made tests and i saw that it takes half the time and i have many videos to upgrade.

Fania,

**Comment by k4yt3x** [comment]
Ok I'll take a look

**Comment by k4yt3x** [comment]
I've also noticed python-magic to have this bug.

![image](https://user-images.githubusercontent.com/21986859/81890504-a6d71280-9595-11ea-94e0-b626e1552f18.png)

**Comment by k4yt3x** [comment]
Looks fine at my end.
https://send.firefox.com/download/2e6d208b7ffdcde8/#NZ8IQ6OT7gzwhGtmOBjWJg

**Comment by Faniia** [comment]
Thank for the answer,

I’ll send you what i get when i do it. https://send.firefox.com/download/d3c0b72d12fe23e2/#zprUYzTzhNzxPFwnTyh_zw

I join you some error frame that i saw when i upscaled the full video (only 9 for 44000 frames)

If you say that the issue should be my configuration, i won’t make you waste more time and i will apologize for that.

Just an other question, you said that there is an option to check if the waifu2x-ncnn-vulkan is usable but i did not find the button you screened. Where is this option ?

Fania,

De : K4YT3X
Envoyé le :jeudi 14 mai 2020 05:57
À : k4yt3x/video2x
Cc : Faniia; State change
Objet :Re: [k4yt3x/video2x] CUDNN_STATUS_SUCCESS (1 vs. 0)CUDNN_STATUS_NOT_INITIALIZED (#246)

Looks fine at my end.
https://send.firefox.com/download/2e6d208b7ffdcde8/#NZ8IQ6OT7gzwhGtmOBjWJg

**Comment by k4yt3x** [comment]
I think there's something wrong with waifu2c-ncnn-vulkan itself or something wrong with your configuration. Do a simple test and upscale a single image to see if that fails.

> Just an other question, you said that there is an option to check if the waifu2x-ncnn-vulkan is usable but i did not find the button you screened. Where is this option ?

The option I talked about was for waifu2x-caffe, not ncnn-vulkan.
