### ISSUE TITLE
KeyError: 'path' in _upscale_frames

### ISSUE THREAD

**Issue by STribbey125** [k4yt3x/video2x#247]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.0.0 beta4|
|`FFmpeg`|Included with full version|
|`waifu2x-caffe`|Included with full version|
|`waifu2x-converter-cpp`|Included with full version|
|`waifu2x-ncnn-vulkan`|Included with full version|

## Symptom

Fails at the beginning of upscale

## Screenshots or Error Messages

![cl](https://user-images.githubusercontent.com/16655817/81631865-e3104480-93d6-11ea-8e6f-72696e699d9a.PNG)
![gui_1](https://user-images.githubusercontent.com/16655817/81631873-e4da0800-93d6-11ea-9f85-f235e80b2c8d.PNG)
![gui_2](https://user-images.githubusercontent.com/16655817/81631878-e73c6200-93d6-11ea-9381-bfd3a28f98a9.PNG)

**Comment by k4yt3x** [comment]
I've noticed this issue and have already fixed it on master branch.

**Comment by STribbey125** [comment]
Excellent, thank you!
