### ISSUE TITLE
Does video2x double the framerate?

### ISSUE THREAD

**Issue by andyhines** [k4yt3x/video2x#248]
![fps_doubled](https://user-images.githubusercontent.com/7064299/81699697-b0e1ff80-9435-11ea-86e6-084fa0727905.PNG)

## Environment Information

I used two seperate systems to test waifu2x-caffe and anime4kcpp and both produced output video files that seem to have double the frame rate of the input .avi. Is this intended? I was thinking this could possibly be due to some sort of de-interlacing or something similar but I am uncertain and haven't been able to find any indication of an fps setting in the ffmpeg config section. Looking through the wiki I saw example screenshots of 23.9fps input resulting in 23.9fps output (so not doubling it), so it may be specific to the input file selected. I didn't notice at first until I went to run anime4kcpp on files i had processed with waifu2x-caffe and noticed that they had twice the number of frames. Possibly as a result, I haven't been able to get anime4k to successfully run on an waifu2x-caffe processed videoyet. I left it running for 8 hours, and it did not seem to be making any progress. I am trying to use a 1.5 scaling factor in anime4k, instead of a 2x, so perhaps that is somehow incompatible.

Thank you for your help, and this really cool software!

**Comment by k4yt3x** [comment]
Do you have a sample of this file that I can take a look at?

**Comment by andyhines** [comment]
Sure, I can provide that. Would you like the input source video, the output from waifu2x or the output of anime4kcpp, or all three? Also, would you like the files attached here or sent via google drive or similar?

**Comment by k4yt3x** [comment]
I'll just need the input video.
See if the video is small enough to fit into [Firefox Send](https://send.firefox.com)

**Comment by andyhines** [comment]
[Here's the link!](https://send.firefox.com/download/7bd262bce19aae34/#9IbxQomKe24qNDO74tYILA)

Thank you for taking a look.

**Comment by k4yt3x** [comment]
From the debugging info I'm getting, everything looks fine.

![image](https://user-images.githubusercontent.com/21986859/81758252-bd576e00-94b0-11ea-9090-00d1036f1f25.png)

![image](https://user-images.githubusercontent.com/21986859/81758274-c8120300-94b0-11ea-87ae-f501990ba866.png)

**Comment by k4yt3x** [comment]
Which version of build are you using?

**Comment by andyhines** [comment]
I had run these with the 4.0.0 beta 3, I meant to recheck with beta 4 but I think i ran into an issue with it, I will have to re-run them with beta 4. I scrolled up in the logs (running a few files) and I can see where the audio is being re-merged that it lists 
![high_fr](https://user-images.githubusercontent.com/7064299/81759224-1e237e00-9492-11ea-9090-ff94d4e7dc32.png) tbn and tcb matching that framerate but I do not know what these values mean. Oddly it does also list the fps correctly there, but when I check the codec information in vlc or properties -> details in windows, it lists the 47.95 value. Odd. Perhaps it's something flawed int he way the metadata is stored, not "real" fps. Or possibly an issue with the way windows/vlc are pulling that information.

I will run files with 4.0.0 beta4 and check for this same issue. Thank you for your help!

**Comment by k4yt3x** [comment]
Your FPS looks fine. Is your output video faster than the original?

![image](https://user-images.githubusercontent.com/21986859/81759504-72d7f080-94b4-11ea-8d6e-3540c0319c94.png)

**Comment by k4yt3x** [comment]
also your `tbr` looks fine

**Comment by andyhines** [comment]
No it does not appear faster (or slower) that the original, which is part of my confusion. At the end of the day I'm totally fine with it just being an oddity but not real/not causing trouble. I just wanted to make sure there wasn't a setting I had missed that was interpolating extra frames or doubling them up or something odd. Thank you for looking into it!

**Comment by k4yt3x** [comment]
If from metadata and from appearance it looks fine on both aspects, then it should be fine.
I suspect this to be a Windows display issue really.
You can see what FFprobe says for the output video.

**Comment by k4yt3x** [comment]
If you don't know how to FFprobe a video, I just pushed a new commit with a new feature.
You can download the latest nightly build, which will have a "Tools" tab. Go in there and drag the video into the text box. It will show the FFprobe info for the video.

**Comment by andyhines** [comment]
oh, that's fantastic! Thank you, I will check that out!

**Comment by mirh** [comment]
Maybe the original video was interlaced?
640x480 at 23.976 sounds like how I'd encode stuff from NTSC.
