### ISSUE TITLE
[WinError 17] The system cannot move the file to a different disk drive: 'D:'' -> 'X:'

### ISSUE THREAD

**Issue by GitGerby** [k4yt3x/video2x#249]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`| 4.0 |
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Can't have final destination on a different drive than the cache

## Screenshots or Error Messages
![image](https://user-images.githubusercontent.com/36684477/81751153-d9d9b300-947c-11ea-9a46-e59680e4c100.png)

Please paste screenshots 
or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
Traceback (most recent call last):
  File "video2x_gui.py", line 95, in run
  File "upscaler.py", line 549, in run
  File "upscaler.py", line 540, in run
  File "pathlib.py", line 1353, in rename
OSError: [WinError 17] The system cannot move the file to a different disk drive:
```

**Comment by GitGerby** [comment]
root cause appears to be on line 604 of upscaler.py `rename(output_video_path)` is an atomic rename but only functions where the intermediate file and final destination are on the same filesystem; replacing this with a copy and then letting the cleanup script handle removal of the intermediate would remove that limitation.

**Comment by GitGerby** [comment]
https://docs.python.org/3/library/shutil.html#shutil.move should take care of this

**Comment by k4yt3x** [comment]
Oh nice catch. I've just pushed a fix for it.
You should be able to find and test the newest version in the nightly builds.

**Comment by GitGerby** [comment]
Thanks!

**Comment by k4yt3x** [comment]
Ah actually move will be nicer than copy.
I'll change that as well.

**Comment by k4yt3x** [comment]
Just wait for the CD to finish building the last nightly and you can try the new one out.

**Comment by k4yt3x** [comment]
https://github.com/k4yt3x/video2x/actions/runs/103020415

**Comment by GitGerby** [comment]
that's awesome thanks for the quick turnaround!

**Comment by GitGerby** [comment]
Tested the nightly and it works perfectly, thanks again!
