### ISSUE TITLE
KeyError: 'ffmpeg_hwaccel'

### ISSUE THREAD

**Issue by Azeemotron** [K4YT3X/video2x#25]
I'm in understanding that i've installed all Prerequisites. I've checked that they are correctly installed by typing 'ffmpeg' or 'python' in cmd. 

I've also defined in the Config generator the location of the installed prerequisties, although I didn't know what to write for arguments passed ffmpeg or something along those lines. 

When i try to use the program and type in what is required, I am met with the follow.

===================================================================
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.1.5

Traceback (most recent call last):
  File "video2x.py", line 300, in <module>
    ffmpeg_hwaccel = config['ffmpeg_hwaccel']
KeyError: 'ffmpeg_hwaccel'

===================================================================
I did 'ffmpeg -hwaccel_device 1' in cmd thinking it would do something but it didn't fix this. Truth be told I only half know what I'm doing, but I somehow got this far. 

I've probably done something wrong, any help would be much appeciated. 

Many Thanks

**Comment by K4YT3X** [comment]
I think there might be an error in the JSON file, which is an error on my part. I'll take a look as soon as I'm home.

**Comment by K4YT3X** [comment]
@Azeemotron can you please check that you're on the latest version of video2x? Just do a git pull to make sure that you have the latest version of the configuration file.

**Comment by K4YT3X** [comment]
@Azeemotron Yes it would be. I just checked the config generator and what you did indeed caused a problem. I will mark this as a bug, fix it and push an update.

**Comment by K4YT3X** [comment]
@Azeemotron I've just pushed a fix for this bug. Try it out.
