### ISSUE TITLE
Add include audio setting and choose video codec

### ISSUE THREAD

**Issue by luca2125** [k4yt3x/video2x#250]
## Description

Hi,

I ask to add a option to include audio in the output file and choose the output video codec "h.264, h.265' etc...

Actually save always in h.264 and don't include audio.

## Sources

Paste links to descriptions of related documentations, websites and etc. here.

**Comment by GitGerby** [comment]
[mkvtoolnix](https://mkvtoolnix.download) may be a better solution for selecting streams and multiplexing audio / video / attachments?

**Comment by luca2125** [comment]
in my experience for mkv file yes.

Generally I use ffmpeg for audio, but for operation in mkv file I use mkvmerge / mkvextract 

https://mkvtoolnix.download/doc/mkvextract.html

**Comment by k4yt3x** [comment]
Currently, you can change the output codec in the config file.
I'm programming that part into the GUI right now.

![image](https://user-images.githubusercontent.com/21986859/81983704-53aba100-9623-11ea-9311-7e64bbf91e57.png)

**Comment by k4yt3x** [comment]
Mapping control has been added into GUI, along with output codec.

**Comment by luca2125** [comment]
thank you !
