### ISSUE TITLE
MKV File not recognized

### ISSUE THREAD

**Issue by GitGerby** [k4yt3x/video2x#251]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|Nightly 2020.05.12|
|`FFmpeg`|ffmpeg-20200504-5767a2e-win64-static|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`|bundled with 4.0 release|

## Symptom
Briefly describe what's going on.
.mkv container with mpeg2 DVD stream not recognized as a valid input
Contents of mkv:
![image](https://user-images.githubusercontent.com/36684477/81953301-83cc5300-95d5-11ea-9a7f-92e57cda3ef9.png)

File does play in vlc and other players; not sure what's going on here; I was able to export a PNG frame using AVID and upscale that without issue.

## Screenshots or Error Messages
```
[+] INFO: Upscaling single file: U:\title_t00.mkv
[!] ERROR: File U:\title_t00.mkv (inode/blockdevice) neither an image of a video
[!] WARNING: Skipping this file
```

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
The python-magic package is responsible for detecting file types.
Could you please send me a sample of the file so I can take a look?
I suspect it to be a python-magic bug.

**Comment by GitGerby** [comment]
working on slicing this up in a way that can reproduce the issue so you can get a sample; in the meantime it does appear this works with the 4.0 beta4 release but not the nightly with the cache fix

**Comment by k4yt3x** [comment]
4.0 beta4, or as what it's called now the 4.0 stable, has various bug fixes and enhancements as compared to the previous release. I believe that's the time when python-magic was introduced to v2x.

**Comment by GitGerby** [comment]
yeah it's weird, I expect the nightly you made for the cache being on a different drive was newer and would have rolled up those fixes so I'm not sure what's going on.

**Comment by k4yt3x** [comment]
Can I have the file sample then to test against python-magic?

**Comment by k4yt3x** [comment]
This problem should be fixed in the newest commit.
