### ISSUE TITLE
'path'

### ISSUE THREAD

**Issue by Bur0ri** [k4yt3x/video2x#253]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Happens everytime I try processing multiple files
## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```[+] INFO: Framerate: 30.0
[+] INFO: Starting to upscale extracted images
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x\tmptm9uus8p
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x\tmp4hk3s2dk
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 95, in run
  File "upscaler.py", line 549, in run
  File "upscaler.py", line 503, in run
  File "upscaler.py", line 290, in _upscale_frames
  File "C:\Users\W\AppData\Local\Temp\_MEI159322\wrappers\waifu2x_caffe.py", line 82, in upscale
    execute = [self.driver_settings.pop('path')]
KeyError: 'path'
```

**Comment by k4yt3x** [comment]
Should be fixed in the newest version.
Try nightly.

**Comment by Bur0ri** [comment]
> Should be fixed in the newest version.
> Try nightly.

How do you respond so fast?

**Comment by k4yt3x** [comment]
I'm working on some new code right now.
My GitHub page is just always open.

**Comment by Bur0ri** [comment]
> I'm working on some new code right now.
> My GitHub page is just always open.

Also, I recently discovered your program and it does wonders

**Comment by k4yt3x** [comment]
Thanks, welcome to the repo then I guess?
