### ISSUE TITLE
waifu2x-ncnn-vulkan yellow upscale images GTX 1060/1070 GPU

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#254]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Video2x use waifu2x-ncnn-vulkan newest version, it runs but the images upscaled are pixelated and yellow.

## Screenshots or Error Messages

No message error.
The problem comes from waifu2x-ncnn-vulkan, not video2x. I tried to use it on GTX 1060 and 1070 GPU and it was the same result.
To resolve the issue, you need to copy this version: https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20200223 in the folder video2x-4.0.0_beta4-win32-full\dependencies.

**Comment by k4yt3x** [comment]
What do you mean? The latest version won't work?

**Comment by k4yt3x** [comment]
Also can I have a sample of the said output?

**Comment by Faniia** [comment]
Last version of waifu2x-ncnn-vulkan does not work with thoose GPU.
You need to use 20200223 version of waifu2x-ncnn-vulkan (the link) to temporary solve the issue.
It's a waifu2x-ncnn-vulkan bug, not video2x.

**Comment by k4yt3x** [comment]
I see. You can fix that temporarily by downloading w2x manually and replace the folder in dependencies. I'll change the file in the release as well. Thanks for letting me know.

**Comment by k4yt3x** [comment]
I have a GTX 1060 6G, and the latest release seems fine with me.
Could you confirm that the bug still exists with Video2X 4.1.0 release?

**Comment by Faniia** [comment]
Sorry about the answer delay.
I tried just now and the bug does not exist anymore on Video2X 4.2.0 release.
I experienced an other bug. Some videos i try to upscale are read with 120 fps. I think it's a video2x bug but i am not sure. Could you take a look?
https://send.firefox.com/download/a62af64f35cc337b/#LJiK2Lg4QqxV5hP2eSAi3g

**Comment by nihui** [comment]
@Faniia  Hi Faniia

For the yellow upscaled images, I cannot reproduce this issue on my box.
Please try this new build, though I am not sure if it solves the problem :|
Thanks

https://github.com/nihui/waifu2x-ncnn-vulkan/suites/712261121/artifacts/6959415

**Comment by Faniia** [comment]
@nihui Hi
It is ok, k4yt3x changed something in Video2x that corrected the bug.

**Comment by k4yt3x** [comment]
@Faniia He's the author of waifu2x-ncnn-vulkan. Could you please try that on your machine since non of us can reproduce the bug?

**Comment by Faniia** [comment]
Hello,
You didn't make the update on the last patch 4.1.
I used it and got yellow result.
I'm using old version waiting for patch.

**Comment by k4yt3x** [comment]
@Faniia wait the new release still didn't address this issue?

**Comment by Faniia** [comment]
you corrected the issue just after i posted the report bug (with patch 4.2) but i downloaded 4.4.1 patch and this one have the same bug. So i think you didn't made the changes you did for 4.2 patch.

**Comment by k4yt3x** [comment]
I meant if @nihui has fixed the bug in the newest upstream release

**Comment by Faniia** [comment]
Well, it seems he did not if you took his last release.
I can make tests if you want.

**Comment by k4yt3x** [comment]
I think he's still unable to reproduce that missing channel bug.
Maybe you should contact him on Telegram and help him fixing that?
I'll revert the versions back in the next release.

**Comment by Xyz00777** [comment]
the problem is the windows display language. i have 2 systems with these problems in german. changed them language to englisch nad now its working without problems

**Comment by Faniia** [comment]
I have french windows display language.
So the issue does not come from GPU?

**Comment by k4yt3x** [comment]
> I have french windows display language.
> 
> So the issue does not come from GPU?

I think it is the problem. You don’t have English, and you’re experiencing problems.

**Comment by Xyz00777** [comment]
can you try change your display language to english? and try it again? i think it will work than.

**Comment by Faniia** [comment]
nihui fixed the bug.
https://github.com/nihui/waifu2x-ncnn-vulkan/releases

**Comment by k4yt3x** [comment]
Got it, will update it in the next release.
