### ISSUE TITLE
Videos can't be played using the Movies and TV app

### ISSUE THREAD

**Issue by Bur0ri** [k4yt3x/video2x#255]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

With every video I upscaled, none of them could be played using the stock Windows player without reconverting

**Comment by k4yt3x** [comment]
What's your command/config

**Comment by Bur0ri** [comment]
I tried with Waifu2x Caffe and Waifu 2x Converter CPP
Also, NCNN Vulkan gives the same result but gives a green tint

**Comment by k4yt3x** [comment]
What I mean is your FFmpeg output codec, the default should be libx264, which should create H.264 MP4 files.

Check the metadata of your output video and see what it says.

W2X NCNN Vulkan has a bug right now: https://github.com/nihui/waifu2x-ncnn-vulkan/issues/59
I'll revert the version in the release later.

**Comment by k4yt3x** [comment]
Also, which release of Video2X are you using?

**Comment by Bur0ri** [comment]
The metadata doesn't show up in the file properties and I am using the 4.1.0 version

**Comment by k4yt3x** [comment]
It's not in properties. You can view it in VLC but that might be annoying.
I've added a little tool in 4.1.0, go to Tools tab and drag the video into FFprobe window.
Paste the output or screenshot here.

**Comment by Bur0ri** [comment]
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High 4:4:4 Predictive",
      "codec_type": "video",
      "codec_time_base": "8523/512000",
      "codec_tag_string": "avc1",
      "codec_tag": "0x31637661",
      "width": 1600,
      "height": 1200,
      "coded_width": 1600,
      "coded_height": 1200,
      "closed_captions": 0,
      "has_b_frames": 2,
      "pix_fmt": "yuv444p10le",
      "level": 40,
      "chroma_location": "left",
      "refs": 1,
      "is_avc": "true",
      "nal_length_size": "4",
      "r_frame_rate": "30/1",
      "avg_frame_rate": "256000/8523",
      "time_base": "1/16000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 8523,
      "duration": "0.532687",
      "bit_rate": "7164485",
      "bits_per_raw_sample": "10",
      "nb_frames": "16",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "VideoHandler"
      }
    }
  ],
  "format": {
    "filename": "G:\\Sabri\\Backup Samsung\\hntgame\\iyaanimation\\Install\\a\\a_ev27cd_output.mp4",
    "nb_streams": 1,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.000000",
    "duration": "0.533000",
    "size": "478256",
    "bit_rate": "7178326",
    "probe_score": 100,
    "tags": {
      "major_brand": "isom",
      "minor_version": "512",
      "compatible_brands": "isomiso2avc1mp41",
      "comment": "Upscaled by Video2X",
      "encoder": "Lavf58.43.100"
    }
  }
}

**Comment by Bur0ri** [comment]
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High 4:4:4 Predictive",
      "codec_type": "video",
      "codec_time_base": "8523/512000",
      "codec_tag_string": "avc1",
      "codec_tag": "0x31637661",
      "width": 1600,
      "height": 1200,
      "coded_width": 1600,
      "coded_height": 1200,
      "closed_captions": 0,
      "has_b_frames": 2,
      "pix_fmt": "yuv444p10le",
      "level": 40,
      "chroma_location": "left",
      "refs": 1,
      "is_avc": "true",
      "nal_length_size": "4",
      "r_frame_rate": "30/1",
      "avg_frame_rate": "256000/8523",
      "time_base": "1/16000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 8523,
      "duration": "0.532687",
      "bit_rate": "7164485",
      "bits_per_raw_sample": "10",
      "nb_frames": "16",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "VideoHandler"
      }
    }
  ],
  "format": {
    "filename": "uhh, there is no path, take off your clothes",
    "nb_streams": 1,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.000000",
    "duration": "0.533000",
    "size": "478256",
    "bit_rate": "7178326",
    "probe_score": 100,
    "tags": {
      "major_brand": "isom",
      "minor_version": "512",
      "compatible_brands": "isomiso2avc1mp41",
      "comment": "Upscaled by Video2X",
      "encoder": "Lavf58.43.100"
    }
  }
}

**Comment by k4yt3x** [comment]
Looks completely fine

**Comment by Bur0ri** [comment]
I can still convert it using Premiere Pro but that takes too much time

**Comment by k4yt3x** [comment]
Ok I have a guess here. Try changing the pixel format from `yuv444p10le` to `yuv420p`

![image](https://user-images.githubusercontent.com/21986859/82154687-06b40e80-985f-11ea-81a7-b142f1d9fb59.png)

**Comment by Bur0ri** [comment]
That worked, thanks! Is there a way to safe the settings though? I can't find a save button anywhere

**Comment by k4yt3x** [comment]
GUI loads settings from the YAML file.
You can edit the default settings in the configuration files.
![image](https://user-images.githubusercontent.com/21986859/82155306-8643dc80-9863-11ea-9e71-ceeac4e1cb5c.png)

**Comment by k4yt3x** [comment]
Maybe I'll consider shipping `yuv420p` as the default pixel format for better compatibility?

**Comment by Bur0ri** [comment]
Now I experience a bug where bulk upscaling gives me an error at 99% of the first file, upscaling them one-by-one doesn't give any error though

**Comment by k4yt3x** [comment]
Could you please show me what error it is?

**Comment by Bur0ri** [comment]
![image](https://user-images.githubusercontent.com/50540735/82155693-193a4200-9877-11ea-83a3-b7f65727d4cd.png)

**Comment by k4yt3x** [comment]
"When reporting an error, please include console output."

**Comment by k4yt3x** [comment]
Please take a screenshot of the console output

**Comment by Bur0ri** [comment]
Sorry, my bad

**Comment by Bur0ri** [comment]
[!] ERROR: Subprocess 22332 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
2020-05-17 19:42:02.803137 [+] INFO: Killing progress monitor
Upscaling Progress:  36%|#####################8                                      | 151/414 [07:25<12:55,  2.95s/it]
2020-05-17 19:42:02.819324 [+] INFO: Killing upscaled image cleaner
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x\tmpyig_1qvs
Unable to delete: C:\Users\W\AppData\Local\Temp\video2x\tmpyig_1qvs
Traceback (most recent call last):
  File "upscaler.py", line 525, in run
  File "upscaler.py", line 317, in _upscale_frames
  File "upscaler.py", line 309, in _upscale_frames
  File "upscaler.py", line 379, in _wait
  File "upscaler.py", line 363, in _wait
subprocess.CalledProcessError: Command '['E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpyig_1qvs\\0', '--output_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpawrosw3h']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upscaler.py", line 136, in cleanup_temp_directories
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 596, in _rmtree_unsafe
  File "shutil.py", line 593, in _rmtree_unsafe
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpyig_1qvs'
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x\tmpawrosw3h
Unable to delete: C:\Users\W\AppData\Local\Temp\video2x\tmpawrosw3h
Traceback (most recent call last):
  File "upscaler.py", line 525, in run
  File "upscaler.py", line 317, in _upscale_frames
  File "upscaler.py", line 309, in _upscale_frames
  File "upscaler.py", line 379, in _wait
  File "upscaler.py", line 363, in _wait
subprocess.CalledProcessError: Command '['E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpyig_1qvs\\0', '--output_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpawrosw3h']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upscaler.py", line 136, in cleanup_temp_directories
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 596, in _rmtree_unsafe
  File "shutil.py", line 593, in _rmtree_unsafe
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpawrosw3h'
Cleaning up cache directory: C:\Users\W\AppData\Local\Temp\video2x
Unable to delete: C:\Users\W\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "upscaler.py", line 525, in run
  File "upscaler.py", line 317, in _upscale_frames
  File "upscaler.py", line 309, in _upscale_frames
  File "upscaler.py", line 379, in _wait
  File "upscaler.py", line 363, in _wait
subprocess.CalledProcessError: Command '['E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpyig_1qvs\\0', '--output_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpawrosw3h']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upscaler.py", line 136, in cleanup_temp_directories
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 596, in _rmtree_unsafe
  File "shutil.py", line 593, in _rmtree_unsafe
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x'
Traceback (most recent call last):
  File "video2x_gui.py", line 100, in run
  File "upscaler.py", line 605, in run
  File "upscaler.py", line 525, in run
  File "upscaler.py", line 317, in _upscale_frames
  File "upscaler.py", line 309, in _upscale_frames
  File "upscaler.py", line 379, in _wait
  File "upscaler.py", line 363, in _wait
subprocess.CalledProcessError: Command '['E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\Telechargement Chrome\\video2x-4.1.0-win32-full\\video2x-4.1.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpyig_1qvs\\0', '--output_path', 'C:\\Users\\W\\AppData\\Local\\Temp\\video2x\\tmpawrosw3h']' returned non-zero exit status 1.

**Comment by k4yt3x** [comment]
The output is incomplete, but it appears you're using multiple instances of waifu2x-caffe?
The upscale seems to be running and died half way, which may be caused by one of the threads terminated due to the lack of available VRAM.
If you're using waifu2x, don't use multiple processes.

**Comment by Bur0ri** [comment]
I only had one instance of Waifu2x open and one tab of Chrome open

**Comment by k4yt3x** [comment]
All that I can see from the error message is that waifu2x ran into an error half-way and died.
What setup do you have, specifically, what GPU are you using?

**Comment by Bur0ri** [comment]
A GeForce 1050ti

**Comment by k4yt3x** [comment]
You might have ran out of VRAM.
Try waifu2x-converter-cpp, it should consume less VRAM and still give you similar results with its cunet model.

**Comment by Bur0ri** [comment]
I'm trying to guess why it can convert files one-by-one just fine but can't do the same thing when importing a folder

**Comment by Bur0ri** [comment]
I think I found the issue, there were two files that were 80 - 100mb big, that might have been the issue so I removed them and so far it's not giving any errors

**Comment by k4yt3x** [comment]
do you mean an image file that's 80-100MB in size?

**Comment by Bur0ri** [comment]
No, a video

**Comment by k4yt3x** [comment]
Thinking about it it doesn't quite make sense.
I'll do some more experiments with it.

**Comment by k4yt3x** [comment]
Also, please create a new issue since this issue is a completely new problem.

**Comment by nihui** [comment]
> 
> 
> I tried with Waifu2x Caffe and Waifu 2x Converter CPP
> Also, NCNN Vulkan gives the same result but gives a green tint

Hello
For the green tint result, I cannot reproduce this issue on my box.
Please try this new build, though I am not sure if it solves the problem :|
Thanks

https://github.com/nihui/waifu2x-ncnn-vulkan/suites/712261121/artifacts/6959415
