### ISSUE TITLE
Video output image quality decreasing

### ISSUE THREAD

**Issue by thmPedro** [k4yt3x/video2x#256]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

> **Settings that I played with**
> Driver: Waifu2x Converter CPP
> Processes: 1 to 3
> FFmpeg pixel format: yuv420p
> Preserve Frames

I'm trying to upscale a small video with 14 seconds, and this is what've I done:
1. I ran the GUI version with all values default but got an error, then I tried it in the CLI version without success either. Ended up learning here that I was out of memory, and then changed to waifu2x converter cpp and it worked.
2. The upscale succeeded, but the output had no image, only sound. Then I found a suggestion in another report and changed the FFmpeg's `pixel format` to ` yuv420p`, which fixed the problem.
3. But now although the output has initially the aimed quality, it rapidly reduces, and every 122th frame has an even lower quality, which visibly flashes the video.

I tried messing with the values of `processes` and `preserve frames`, with no effect, and my poor knowledge didn't give me confidence to explore other settings.

Using GTX 750 and i5-3330 (it's weak, I know.....)

## Screenshots or Error Messages

Screenshots:
[imgur.com/a/jBNIH9O](https://imgur.com/a/jBNIH9O)

Samples:
[imgur.com/a/iE2QLio](https://imgur.com/a/iE2QLio)

No error messages.

**Comment by k4yt3x** [comment]
could you please send me the input file? I'll take a look at what's going on

**Comment by thmPedro** [comment]
[Here's the output and input files](https://imgur.com/a/iE2QLio), it's downloadable on the arrow on the upper-right corner of the videos

**Comment by k4yt3x** [comment]
I see the download button at the lower right but ok I'll take a look.

**Comment by k4yt3x** [comment]
I can confirm the flash. Not sure exactly why this is happening though.
Might have something to do with framerate.

**Comment by thmPedro** [comment]
I did it with [another file](https://imgur.com/a/suwNVlu), and it went nice. I compared both input file's metadata but I'm not competent to diagnose anything.
Might be helpful though.


(I just realized I can upload files here, but mp4 is not supported :v)

**Comment by DavidAustine** [comment]
Anytime i try upscaling either a video or photo i get 'returned non-zero exit status 259
![Screenshot (24)](https://github.com/k4yt3x/video2x/assets/162473458/6492c5a4-a1e3-4399-8aed-3d88c1570453)
