### ISSUE TITLE
"(inode/blockdevice) neither an image or a video"

### ISSUE THREAD

**Issue by xXHenlolXx** [k4yt3x/video2x#258]
I am using Video2X 4.2.0 and tried to upscale a video with waifu2x-caffe, and other drivers. But I keep getting this error: 
"[+] INFO: Upscaling single file: C:\Users\henri\Videos\Garden.mp4
[!] ERROR: File C:\Users\henri\Videos\Garden.mp4 (inode/blockdevice) neither an image of a video
[!] WARNING: Skipping this file"

I already tried to rename the video, move it to a different folder and convert it to mkv.

The video is The Garden of Sinners 1, that I downloaded from Crunchyroll using SVPtube (based on youtube-dl). The program is working normally with other videos. Thanks in advance.
[Garden.mp4.MediaInfo.txt](https://github.com/k4yt3x/video2x/files/4645601/Garden.mp4.MediaInfo.txt)

**Comment by k4yt3x** [comment]
First of all that's a typo you found, it should be "or a video".
Can I have the file? I would like to run it through python-magic manually and see what happens.

**Comment by xXHenlolXx** [comment]
Here is it: https://drive.google.com/file/d/1ce0GqN7IasBXffMHc-5P6a1i9Cedh9sw/view?usp=sharing

**Comment by Felixkruemel** [comment]
I've got exactly the same issue.
I've tried Version 4.0.0 and there my file works so it has to be a bug in version 4.2.0.

**Comment by k4yt3x** [comment]
If it turns out to be a bug, it will be python-magic library's issue.

**Comment by k4yt3x** [comment]
You named it a MP4 but it's encapsulated in Quicktime MOV format

![image](https://user-images.githubusercontent.com/21986859/82705577-651a2c00-9c67-11ea-997f-4a3ae7409c43.png)

**Comment by k4yt3x** [comment]
python-magic thinks it's an `inode/blockdevice` file for some reason.

![image](https://user-images.githubusercontent.com/21986859/82705711-b1656c00-9c67-11ea-9415-8d303c8653b7.png)

**Comment by k4yt3x** [comment]
Maybe it makes sense to fall back to mimetypes?

![image](https://user-images.githubusercontent.com/21986859/82706241-baa30880-9c68-11ea-90e4-ead8804a2625.png)

**Comment by k4yt3x** [comment]
Now video2x will try guessing the type with `mimetypes` if `python-magic` thinks this is neither a video nor an image.
Honestly python-magic's problem, but this should mitigate the problems.

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/82706820-38b3df00-9c6a-11ea-9e21-2a99a5504ada.png)

**Comment by k4yt3x** [comment]
btw I ran your video straight through FFmpeg

![image](https://user-images.githubusercontent.com/21986859/82706877-6436c980-9c6a-11ea-8d23-4cc89f69acc8.png)

Then python-magic is able to recognize it.

![image](https://user-images.githubusercontent.com/21986859/82706865-5c772500-9c6a-11ea-9bfc-c6ab95023878.png)

**Comment by xXHenlolXx** [comment]
Thanks!

**Comment by obeesechurger** [comment]
I've got the same problem, solved it by converting the mp4 with vlc to H.264 + MP3 (MP4)
