### ISSUE TITLE
Command '['C:\\Users\\vichox\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'C:\\Users\\vichox\\AppData\\Local\\video2x\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\vichox\\AppData\\Local\\Temp\\video2x\\tmpouzz46uu\\0', '--output_path', 'C:\\Users\\vichox\\AppData\\Local\\Temp\\video2x\\tmpn6tqpeq9']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by vichoxthepanda** [k4yt3x/video2x#259]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
You didn't fill any of the information in.
Either fill them in or open a different issue.
