### ISSUE TITLE
Can't figure out what features are available...

### ISSUE THREAD

**Issue by sok0** [K4YT3X/video2x#26]
1. always throws and error that there is no factor specified, even when using height and width, even when a factor is specified

2. gpu always throws an error 
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 357, in <module>
    video2x()
  File "video2x.py", line 207, in video2x
    ffmpeg_arguments.append('-hwaccel {}'.format(ffmpeg_hwaccel))
AttributeError: 'str' object has no attribute 'append'

3. since only CPU works and I have to modify video2x.py to remove the check for the factor parameter in order to proceed, output still fails:
[image2 @ 000001b40701b2c0] Could find no file with path 'c:\Documents\Downloads\video2x-master\upscaled\extracted_%d.png' and index in the range 0-4
c:\Documents\Downloads\video2x-master\upscaled\extracted_%d.png: No such file or directory
c:\Documents\Downloads\video2x-master\upscaled\no_audio.mp4: No such file or directory

It is possible to provide an example of a situation when the script works?

**Comment by sok0** [comment]
this is what happens when attempting to use height and width

c:\Documents\Downloads\video2x-master>python video2x.py -v testvid.mp4 -o testvid2.mp4 --width 1000 --height 1000 --gpu
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.1.6

Traceback (most recent call last):
  File "video2x.py", line 291, in <module>
    elif (not args.width or not args.height) or not args.upscale_factor:
AttributeError: 'Namespace' object has no attribute 'upscale_factor'

c:\Documents\Downloads\video2x-master>

**Comment by sok0** [comment]
when attempting to use factor:

c:\Documents\Downloads\video2x-master>python video2x.py -v testvid.mp4 -o testvid2.mp4 --f 2 --gpu
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.1.6

[!] ERROR: You must specify output video width and height or upscale factor

c:\Documents\Downloads\video2x-master>

**Comment by K4YT3X** [comment]
@sok0 I will look into it immediately. Give me a second.

**Comment by K4YT3X** [comment]
[Commit #71](https://github.com/K4YT3X/video2x/commit/d6f1bae2e6f07bfe226379f07c229a3570de3dc5) has been released to fix this problem. The patch should fix this problem.

Sorry about this bug. I have recently virtualized my workstation, so I was unable to do a test run before releasing the current version. I was able to debug just now it in a VM.
