### ISSUE TITLE
Frame upscaling fails due to "The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by HunterAP23** [k4yt3x/video2x#260]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.2.0 Win32|
|`FFmpeg`|git-2020-05-15-b18fd2b|
|`waifu2x-caffe`|1.0.0|
|`waifu2x-converter-cpp`|v5.3.3 (master-b45498b)|

## Symptom

Attempting to upscale a video using different models for some testing. After decoding the frames and saving them as PNG's inside my cache folder, the upscaling portion fails due to one of the frames being "in use by another process". Curious part is that I'm only running this with a single process thread, so not sure what is holding that file.

I did have this exact same issue before when I used v2.10, and I ended up fixing it by changing line 289 in upscaler.py:
```py
for image in frames:
    # move image
    try:
            image.rename(process_directories[0] / image.name)
    except FileExistsError as fee:
        continue
    except PermissionError as pe:
        pass
    # rotate list
    process_directories = process_directories[-1:] + process_directories[:-1]
```

This will skip the file if it somehow already exists (meaning another thread is handling the renaming process) or if the file is currently in use (since renaming it will throw a permission error).

## Screenshots or Error Messages

Settings I use when this error occurs:
![video2x_gui_2020-05-19_22-32-03](https://user-images.githubusercontent.com/14364070/82398324-9fde5300-9a20-11ea-96c4-4729dc68f196.png)
![video2x_gui_2020-05-19_22-32-14](https://user-images.githubusercontent.com/14364070/82398332-a40a7080-9a20-11ea-8165-f4f4a02084c0.png)

This is the actual error message I am met with:
![video2x_gui_2020-05-19_22-24-01](https://user-images.githubusercontent.com/14364070/82398344-ac62ab80-9a20-11ea-9dec-8a3fc5a316f3.png)

Screenshot of the console output when this error occurs:
![video2x_gui_2020-05-19_22-24-24](https://user-images.githubusercontent.com/14364070/82398369-b7b5d700-9a20-11ea-8dd2-30192912da50.png)

```
Cleaning up cache directory: D:\Downloads\CompTools\Media\video2x-4.2.0-win32-full\cache\tmpsl2y_xj1
Cleaning up cache directory: D:\Downloads\CompTools\Media\video2x-4.2.0-win32-full\cache\tmpwwb9l7ug
Cleaning up cache directory: D:\Downloads\CompTools\Media\video2x-4.2.0-win32-full\cache
Traceback (most recent call last):
  File "video2x_gui.py", line 99, in run
  File "upscaler.py", line 607, in run
  File "upscaler.py", line 527, in run
  File "upscaler.py", line 291, in _upscale_frames
  File "pathlib.py", line 1353, in rename
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Downloads\\CompTools\\Media\\video2x-4.2.0-win32-full\\cache\\tmpsl2y_xj1\\extracted_135.png' -> 'D:\\Downloads\\CompTools\\Media\\video2x-4.2.0-win32-full\\cache\\tmpsl2y_xj1\\0\\extracted_135.png'
```

**Comment by k4yt3x** [comment]
Hmm that doesn't make sense.
Video2X will wait for the extraction phase to finish before moving on, so FFmpeg shouldn't be what's holding the file handle open.
Do you have some kind of antimalware software constantly scanning for new files?
