### ISSUE TITLE
Add expected upscaling Performance in the Wiki

### ISSUE THREAD

**Issue by Felixkruemel** [k4yt3x/video2x#262]
It would be nice to get a little List of GPUs (or CPUs) with the expected frames per second performance while upscaling pre-defined video clips so that a user knows what performance he has to expect.

I was shocked to only get around 2.5fps with my RTX 2060Super until I read how ressource heavy upscaling really is.

I could deliver necessary data for a 2060Super in combination with a Ryzen 7 3700X.

**Comment by k4yt3x** [comment]
2.5 is quite high really, I'm only getting 0.8 with my GTX 1060 6G.

The things is, upscaling performance is relative to the original and target image size. It also depends on GPU, CPU and storage media.
Of couse we can have a page that lists the performance of some systems as a reference.
In which case, the Wiki is open to edits. Anyone can add stuff into it.

**Comment by Felixkruemel** [comment]
On the Wiki page I don't see an "Edit" Button like on my local projects. I don't use the Wiki portion of GitHub that often, so maybe that's a thing which I just don't know how to use it.

I could clone the wiki and maybe commit it again (?) but that shouldn't be the way to go I would say.

**Comment by k4yt3x** [comment]
Actually my bad. I've restricted edit access to collaborators.
I've just opened the access to everyone. You can try again.

**Comment by andyhines** [comment]
Not certain if this is the place for it but I can contribute another data point: I get around 4.1 (ish) fps upscaling 480p->720p on a 2080 ti (FE), and 9900k using an 970 evo nvme drive for the temp directory. If I play a game or something I've been really impressed how smoothly the software drops to the background and just processes at 1-1.5fps and doesn't seem to harm game fps (though I haven't really watched too closely)

**Comment by andyhines** [comment]
Sorry to be more specific, I am upscaling 640x480 -> 960x720, 1.5x

**Comment by Felixkruemel** [comment]
Ok, nice. 

To be fair upscaling performance varies a lot based on the video and input resolution.
I've made a wiki page for it, but need more data:
https://github.com/k4yt3x/video2x/wiki/Performance-Benchmarks

Please also provide a second test-video which can utilize another driver. I will test it then.
@andyhines

**Comment by k4yt3x** [comment]
> Please also provide a second test-video which can utilize another driver and scaling settings. I will test it then.

Simply upscale the upscaled video then?

**Comment by k4yt3x** [comment]
Also thanks for providing the results. I'll expand on that later when my new hardware arrives.

**Comment by k4yt3x** [comment]
I've just added your page to ToC

**Comment by Felixkruemel** [comment]
> 
> Simply upscale the upscaled video then?

I don't know wether it would make sense to upscale a realistic video with e.g. waifu2x-converter-cpp as it isn't meant for something like that.

**Comment by k4yt3x** [comment]
Just for benchmarking

**Comment by andyhines** [comment]
Ok, to further assess upscaling performance in a somewhat standardized way, I am using v4.3 and testing with the umbrella girl sample clip k4yt3x has on the readme page.
For reference these tests use an i9 9900k cpu and 2080ti gpu.
Here are my results:

Original clip size: 426x240 pixels, 19.019 seconds long (456 frames)

Upscaling with Waifu2X Caffe, scale ratio 2.0: 9.3-9.5 it/s reported in the log window, ~8 fps in the gui. 59.12s total time (852x480 output)
Upscaling with Waifu2X Caffe, scale ratio 4.0: 2.16-2.3 it/s reported in the log window, ~2.1 fps in the gui. 213.63s total time (1704x960 output)
Upscaling with Waifu2X Caffe, scale ratio 9.0: ~5.8 s/it reported in log window, ~.15 fps in the gui. Estimated 43m34s to complete, will update.

**Comment by Felixkruemel** [comment]
@andyhines 

You can add your results in the Wiki. I will post mine tomorrow if I find time to test them.

**Comment by k4yt3x** [comment]
This should be closed since the section has already been added.
