### ISSUE TITLE
Different time remaining guesses and frames per second in GUI and CLI

### ISSUE THREAD

**Issue by Felixkruemel** [k4yt3x/video2x#263]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.0.0|
|`FFmpeg`|git-2020-05-15-b18fd2b|

## Symptom

The remaining time calculation of the GUI and CLI is different by a huge margin. 

## Screenshots 

![grafik](https://user-images.githubusercontent.com/12109804/82673981-ef03ce00-9c42-11ea-94d1-a078e3aba5eb.png)

**Comment by k4yt3x** [comment]
Time remaining in CLI is calculated by tqdm, where the time remaining in GUI is calculated by the math implemented in GUI.
This is completely normal.
