### ISSUE TITLE
ffmpeg: Use NVENC instead of libx264 if supported

### ISSUE THREAD

**Issue by Felixkruemel** [k4yt3x/video2x#267]
After the upscale finished the video will be transcoded through ffmpeg with the libx264 Codec purely on CPU encoding. That's pretty slow, especially on high-resolution media.

It would be better to use the Video Engine of an Nvidia GPU (if the system has one) through the codec h264_nvenc or hevc_nvenc to gain way better speed results. 

I know there's a setting in the GUI for that, but I would prefer it to be a standard setting. Although you would need to detect wether the system has a NV GPU or not (which may be tricky - Idk)

**Comment by k4yt3x** [comment]
NVENC could yield significantly lower quality at the same bitrate though. General problem with hardware encoding codecs.

**Comment by Felixkruemel** [comment]
@k4yt3x 
Since the RTX series the Hardware encoder is really really good, in some cases better than x264. 
The old GTX series have a non-usable encoder though if you want high quality.
Look here for a good comparison: https://www.youtube.com/watch?v=ccoOGfX9qxg

**Comment by k4yt3x** [comment]
I went through the video, for future references, below is a conclusion.

> Turing HVENC and some other new-generation HVENC h264 encoding yields better Netflix/vmaf scoring than x264 encoding on medium profile, while being hardware-accelerated so potentially much faster.

There are a few problems with making this the default option in Video2X:

1. Video2X is an upscaling software, and it cares the most about quality, not speed.
1. Upscaling takes way longer than encoding, sometimes tens of hours to finish. Encoding might only take 10 minutes, which is nothing when compared to the amount of time needed for upscaling.
1. Video2X will very likely switch to the `slow` or `veryslow` profile in the future to guarantee maximum quality. libx264 with these profiles might yield better quality than Turing HVENC.
1. x264 encoding is widely adopted, so it won't be facing any compatibility issues.
1. x264 videos require a lower bitrate to achieve the same level of quality than that of a HVENC video. This means x264 videos will be smaller. In my tests, half the size of a HVENC (h264) video.
1. Detection algorithms add another layer of unnecessary complexity to Video2X.
1. For normal users, it's better for the default option to be the most compatible with decent quality. For experts, switching to NVENC is always an option through GUI or the config file. You may always change the default encoder in the config file and make, say, `h264_hvenc` the default.

![image](https://user-images.githubusercontent.com/21986859/82729620-840cd280-9ce8-11ea-983c-0ecaede74f90.png)
