### ISSUE TITLE
'NoneType' object has no attribute 'is_file'

### ISSUE THREAD

**Issue by methenewb** [k4yt3x/video2x#268]
## Symptom

I downloaded video2x-4.2.0-win32-full.zip, but video2x.exe just close right after that error.

## Screenshots or Error Messages
![error](https://user-images.githubusercontent.com/65810655/82728612-65c8c600-9d2c-11ea-8020-abcfafecada4.png)

**Comment by dgcampea** [comment]
Did you extract the archive first and then run the application?

**Comment by k4yt3x** [comment]
`video2x.exe` is a console application. For GUI you'll need `video2x_gui.exe`

**Comment by k4yt3x** [comment]
Also this error message shouldn't appear. It has been fixed in the newest commit.
