### ISSUE TITLE
Chose output format

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#269]
## Description

I would like to choose the format output file. I use mkv files and i have to make the change.
Not really boring but it's a simple enhancement.

**Comment by Felixkruemel** [comment]
@Faniia 
You can already change the output codec to e.g. libx265. In any workflow there shouldn't be a difference between the .mkv and .mp4 container, except supported codecs. For what reason do you need the .mkv instead if the .mp4 container?

**Comment by k4yt3x** [comment]
If you just want to change the output container, just change the output file name.

**Comment by Faniia** [comment]
ok my bad, sorry

**Comment by kelvinnkat** [comment]
MP4 output is a lossy compression format, while MKV is not, or at least doesn't need to be. There is a difference.

**Comment by k4yt3x** [comment]
@kelvinnkat Both MP4 and MKV are container formats. The underlying codec is what matters (e.g., h.264, h.265, nvenc, etc.). H.264 with CRF of 17-18 can be considered visually lossless according to [FFmpeg's documentation](https://trac.ffmpeg.org/wiki/Encode/H.264). You can set H.264 in MP4 to have a CRF of 0, which will make it lossless H.264. The codec matters, not the container format, at least in this case.
