### ISSUE TITLE
Frame extraction error

### ISSUE THREAD

**Issue by laqyx** [k4yt3x/video2x#271]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

tried to upscale Kaiji, this is what I get

![grafik](https://user-images.githubusercontent.com/32618189/82833778-5cbc2e00-9ebf-11ea-86f7-e38b91d6d6f7.png)

**Comment by k4yt3x** [comment]
> When reporting an error, please include console output.

**Comment by k4yt3x** [comment]
Ok I'm closing this for now until the creator replies.
