### ISSUE TITLE
Cache Directory not cleared after operation conclusion

### ISSUE THREAD

**Issue by sparkpedia** [k4yt3x/video2x#272]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.4.0|

## Symptom

After completing an upscale operation the cache directory is not cleared of temporary files leading to the disk it is stored on getting filled up. I have queued files in the GUI by selecting them manually and then output to a folder. I have a separate SSD that stores my cache directory as I do not want to wear out my boot drive if I am running batch operations. I have done some testing with running as admin and waiting for the entire batch to finish but the cache files are never removed.

## Screenshots 

![image](https://user-images.githubusercontent.com/31021545/82859586-28f3ff00-9ee5-11ea-9d2e-2d0c0b9e814e.png)
Looks Normal in the GUI

![image](https://user-images.githubusercontent.com/31021545/82859748-8ee08680-9ee5-11ea-976a-e1d5dd69ed29.png)
Temp files from previously completed episodes still in cache folder.

To my knowledge there is no console output for trying to remove files but I could have missed it if it is right before the upscaling starts.

**Comment by k4yt3x** [comment]
I don't seem to be able to reproduce this.
What version of the release are you using?

**Comment by Felixkruemel** [comment]
@sparkpedia @k4yt3x 
He selected "Preserve Frames" in the GUI which as a result doesn't clear the cache folder. 
Doesn't seem like a bug for me.

**Comment by sparkpedia** [comment]
> @sparkpedia @k4yt3x
> He selected "Preserve Frames" in the GUI which as a result doesn't clear the cache folder.
> Doesn't seem like a bug for me.

Sorry to waste your time with that, I feel so dumb for that one. Keep up the amazing work! It is greatly appreciated!

**Comment by k4yt3x** [comment]
@Felixkruemel lol ok I didn't see that at all.
