### ISSUE TITLE
Upscaling regular video on Linux?

### ISSUE THREAD

**Issue by skerit** [k4yt3x/video2x#273]
I've seen some comments about how to install the waifu drivers on Linux, but what about SRMD? Or even RealSR? The github repository it links to is seemingly only for Windows. So can video2x only be used for Anime videos on Linux?

**Comment by skerit** [comment]
My bad, the READMEs seemed very windows-centric, but compiling them with cmake on linux just works. (At least, realsr compiled just fine)

I did notice it was looking for the models directories in the same place as where it's built, so I had to move those around a bit.

**Comment by skerit** [comment]
My bad, the READMEs seemed very windows-centric, but compiling them with cmake on linux just works. (At least, realsr compiled just fine)

I did notice it was looking for the models directories in the same place as where it's built, so I had to move those around a bit.

**Comment by k4yt3x** [comment]
Yeah the drivers have to be installed manually on Linux, using whichever method that's the most convenient for you.
Me and @lhanjian have also been working on a docker image. It's still in the early stages but that image has some pre-compiled waifu2x implementations. More will be added in the future.

**Comment by skerit** [comment]
Great! Also, don't know if an issue needs to be made for this here but: the default pixel format (rgba64be, I think?) produces empty, transparent PNG outputs when using RealSR. Changing the pix_fmt to `rgb8` seems to do the trick.

**Comment by k4yt3x** [comment]
`rgba64be` seems works fine on my end, I can't seem to reproduce this problem.

**Comment by skerit** [comment]
@k4yt3x Yes, they fixed it in the RealSR repository yesterday :)
