### ISSUE TITLE
ERROR: No matching distribution found for python-magic-bin 

### ISSUE THREAD

**Issue by idanka** [k4yt3x/video2x#276]
## Environment Information
Run From Source Code
Ubuntu 20.04/Fedora 32

Fedora 32
pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement python-magic-bin (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for python-magic-bin (from -r requirements.txt (line 7))

Ubuntu 20.04
pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement python-magic-bin (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for python-magic-bin (from -r requirements.txt (line 7))

**Comment by idanka** [comment]
https://pypi.org/project/python-magic-bin/#files
Linux missing python-magic-bin
only:
- win_amd64.whl 
- win32.whl  
- macosx_10_6_intel.whl

**Comment by k4yt3x** [comment]
I actually realized that when I was trying to run it on Linux myself yesterday.
That package is actually not required on Linux, so I'm creating a separate requirements.txt for Linux.
For now, you can just delete that line.
