### ISSUE TITLE
Exits unexpectedly (no error codes)

### ISSUE THREAD

**Issue by shplack** [k4yt3x/video2x#277]
## Environment Information

|Module|Version|
|GUI|3.0.0 and up|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||

## Symptom

Starting batch upscaling results in the program exiting unexpectedly after frame extraction.

## Screenshots or Error Messages

No error codes whatsoever, only that it exits unexpectedly. The program cleans the temp folder as per usual. The output shows several question marks in boxes under upscaling status. Reverting to version 2.9.0 fixes this

**Comment by k4yt3x** [comment]
Are you sure you're talking about version 3.0.0? that's kind of ancient.
Please confirm that the issue still exists in 4.x.x.

**Comment by shplack** [comment]
Yes, I'm sure of it. Tested on 3.0.0, 4.2.0, 4.3.0, 4.4.0

**Comment by k4yt3x** [comment]
Okay then. Need more info on the error, either screenshots or logs.

**Comment by shplack** [comment]
There was literally no errors on the console, I can screenshot it for you
tmw. As for logs, where would I find those?

**Comment by k4yt3x** [comment]
Just copy&paste console output will be fine.

**Comment by shplack** [comment]
Alright, I'll get back to you tmw

**Comment by shplack** [comment]
Don't know what happened, can't reproduce the error. It seems like a restart might have fixed it

**Comment by k4yt3x** [comment]
O well, reopen if you get it again.
