### ISSUE TITLE
Non zero exit status(edit: looks like I'm getting the cudaSuccess 2 vs 0 for even 1 thread)

### ISSUE THREAD

**Issue by AdityaSoni25** [k4yt3x/video2x#279]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.5.0|
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/50522232/83390637-d7310480-a40f-11ea-841d-a3d6ebc3bac8.png)

Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by AdityaSoni25** [comment]
Command '['C:\\Users\\Aditya\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'cudnn', '--model_dir', 'C:\\Users\\Aditya\\AppData\\Local\\video2x\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\Aditya\\AppData\\Local\\Temp\\video2x\\tmprxjwz_0d\\0', '--output_path', 'C:\\Users\\Aditya\\AppData\\Local\\Temp\\video2x\\tmpep2zavww']' returned non-zero exit status 3221226505.

I was using cudnn as the process type.

**Comment by AdityaSoni25** [comment]
I got the error again at the end of the process, the process did iterate over the 30k frames of the episode. I got the cudaSuccess error mentioned in the Q and A but I was using only 1 thread.
GPU: GTX 1650

**Comment by k4yt3x** [comment]
Looks like you have only 4G of VRAM. waifu2x-caffe uses a lot of VRAM. Try waifu2x-ncnn-vulkan, which also has cunet model, but it uses less VRAM.

**Comment by AdityaSoni25** [comment]
Yeah, I've got only 4GB of RAM, will try using Vulcan.
