### ISSUE TITLE
Empty mp4 file created after successful upscaling through Anime4kcpp

### ISSUE THREAD

**Issue by Dasyud** [k4yt3x/video2x#280]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Took me 4 hours to upscale a 480p 30 min episode by a factor of 2 using anime4kcpp. It was successful in the end, unlike my previous failures with waifu2x. The temp images that were being created were correctly upscaled, but the final mp4 was empty for some reason.
I cloned the repository yesterday, GUI version is 2.5.0

Edit: I noticed that an mkv file was created too, slipped my eye. However, there isn't any audio in this file and it is occupying 720MB, 8 times bigger than the original 90 MB.

Edit 2: It's missing the subtitles too.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```

**Comment by k4yt3x** [comment]
The MKV file will be created only if the audio/subtite/etc migration has failed.
Do you have any logs or screenshots?

**Comment by AdityaSoni25** [comment]
This is the only screenshot that I have, it's most probably useless though without the console output.
![image](https://user-images.githubusercontent.com/50522232/83481356-2aac5c80-a4bb-11ea-8419-c7795d79bc29.png)

Could there be a problem on my end? I got the same error after upscaling a 20 min episode through dandere2x. The mp4 in the output folder is empty in dandere's case and there is a mkv without sound and subtitles in dandere's workspace folder. This is after using the dandere 1.8 beta though.

I know that I shouldn't expect you to know about dandere, but just giving you all the info I have.

**Comment by k4yt3x** [comment]
Well dandere2x's using some of older versions of v2x's code, so technically I wrote some of it?
Besides, both of them are based on the same concept.
The MKV file will be produced only if audio and other stream failed to get migrated, so I'm suspecting an incompatible audio codec or something of that sort.

If you disable stream copying or use mkv as output format it should be fine.
![image](https://user-images.githubusercontent.com/21986859/83482016-c4a9e000-a48e-11ea-864f-ada025a64674.png)

**Comment by AdityaSoni25** [comment]
What exactly changes when I disable stream copying?
I ran out of disk space while converting the upscaled photos to a video, had 200gb free space. It was a 24 min episode, 720p to 1440p. I used Anime4kcpp for the process.

**Comment by k4yt3x** [comment]
If "Copy streams" is checked, all streams except for the first video stream (which has been upscaled) will be copied directly from the original video to the upscaled video without re-encoding. At times the codec used in the original video might not be compatible with the new container format (e.g. FLAC from MKV into MP4). Unchecking this will instruct FFmpeg to re-encode all streams copied automatically with a codec that the output container supports.

**Comment by AdityaSoni25** [comment]
Isn't there an option to keep the new container format as mkv by default as most anime files are mkv? Will copying streams save space on my laptop? I didn't face this storage problem when I had 110GB free last time, but I freed up another 80GB this time and for some reason ran into the issue.

**Comment by k4yt3x** [comment]
1. The output format will be MP4 by default.
1. The output format for each file will follow input container format if multiple output files are specified.
1. Copying streams will not save any space, but save processing time as no re-encoding is required. Also, it will preserve the original quality of the stream (e.g., audio stream).
1. This issue should not be related to your storage, but your input file container format, streams codecs, etc.

**Comment by AdityaSoni25** [comment]
Yeah, even I thought the same, don't know why the storage problem popped up
though. I'll try upscaling an episode again tonight.

**Comment by k4yt3x** [comment]
Leave another message if you're still experiencing issues

**Comment by Dasyud** [comment]
I apologize for not following up, didn't get an opportunity to try it again.  I'll open a separate issue if I experience the storage space problem again.
