### ISSUE TITLE
close/crash while add video

### ISSUE THREAD

**Issue by Xyz00777** [k4yt3x/video2x#282]
aktuall version of the application in the full version 4.4.1
|`waifu2x-ncnn-vulkan`||

wanted too add a video and while the adding progress the application crash with no other output. simply closed itself.

**Comment by k4yt3x** [comment]
I think I might know what happened.
Python magic is acting up again.

**Comment by k4yt3x** [comment]
This issue should be solved, try the newest nightly build.
