### ISSUE TITLE
waifu2x-caffe 无法放大图片

### ISSUE THREAD

**Issue by BaiYiJue** [k4yt3x/video2x#285]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```
![图片](https://user-images.githubusercontent.com/66427329/83768730-bb4c8d80-a6b1-11ea-8cb8-8854941bf919.png)

**Comment by k4yt3x** [comment]
waifu2x-caffe 需要 Nvidia GPU 及其驱动
请问有正确安装吗？

**Comment by BaiYiJue** [comment]
> 
> 
> waifu2x-caffe需要Nvidia GPU和驱动
> 请问有正确安装吗？

没得 是AMD

**Comment by k4yt3x** [comment]
waifu2x-caffe 是只能使用 Nvidia GPU 和 CUDA，如果是 AMD 的话用 waifu2x-ncnn-vulkan 试试看
