### ISSUE TITLE
Crash in GUI when deleting items after a long upscale

### ISSUE THREAD

**Issue by HarryFreeMyLand** [k4yt3x/video2x#287]
## Environment Information
Tested version 4.3.0 Full - CUDnn installed

Cache Drive is J:\ on my system however I've seen this crash on the default cache path too.

## Symptom

when up-scaling a long batch of videos and it finishes. deleting out the que in the GUI to add new items can sometimes result in a crash.

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/47612589/83836475-8cd6ae80-a6c1-11ea-9707-fa3d1429435d.png)

Please paste your error message in the code block down below:

```
Traceback (most recent call last):
  File "video2x_gui.py", line 810, in input_table_delete_selected
ValueError: list.remove(x): x not in list

```

**Comment by k4yt3x** [comment]
Try the new nightly.
I've pushed https://github.com/k4yt3x/video2x/commit/5f2ad35d41c3b662c9f9920ee0c9e249ffe7b65b to try addressing this issue. I've changed the way how items are deleted from the list.

**Comment by HarryFreeMyLand** [comment]
Wow that was fast lol, I logged off for the day at that point.
I will set up the nightly with a batch of videos and see when I get home from work today.
