### ISSUE TITLE
"Time Elapsed" counter continues running after program crashes

### ISSUE THREAD

**Issue by Xyz00777** [k4yt3x/video2x#288]
when a upscale crash then the time elapsed timer continues and when you start a other job in the same window than it will overlap the old time and the new time in change

**Comment by Xyz00777** [comment]
and when i want to close the GUI after crash it quests me if i want to cancel the upscale... but its already canceled(crashed)

**Comment by k4yt3x** [comment]
- [x] The first question, is simple, reset the dashboard first or display the error message first.
- [ ] Warning after crash should be investigated

**Comment by k4yt3x** [comment]
Fixed.
