### ISSUE TITLE
Extracting frames stopping

### ISSUE THREAD

**Issue by WSADKeysGaming** [K4YT3X/video2x#29]
Ffmpeg stops extracting frames after a certain period of time, around 25 seconds. I know it is time based, because it was a different amount of frames before it stopped on my ssd vs my hdd with the same video. No cpu or disk usage, complete halt. All i have done is cloned the git and used the setup.py.

Edit: this only happens when you lose focus of the cmd window. Whoops.

**Comment by K4YT3X** [comment]
That's a strange issue..
FFMPEG binaries will eventually be replaced by python-ffmpeg, so issues like this should be reduced by then.

**Comment by WSADKeysGaming** [comment]
Yeah, but there's nothing to fix, it was user error

**Comment by WSADKeysGaming** [comment]
Interestingly enough, I had the same problem today, but I had to press the
spacebar for upscaler to start after ffmpeg finished extraction

**Comment by K4YT3X** [comment]
Are you using the windows built in come?

**Comment by WSADKeysGaming** [comment]
*"* windows built in come"

*come* again?
