### ISSUE TITLE
Customizable output file extensions during batch processing

### ISSUE THREAD

**Issue by Xyz00777** [k4yt3x/video2x#290]
At the moment when you use a folder (with pictures) as input then v2x is setting the output suffix = input suffix, that won't work with ncnn vulkan and realsr. It would be awesome when we get a config in the config file where is per default png aas suffix and you can change it to the suffix you want, when it not supported (like jpg) than its should be by default png
[video2x_2020-06-06_23-43-05.log](https://github.com/k4yt3x/video2x/files/4741022/video2x_2020-06-06_23-43-05.log)

**Comment by k4yt3x** [comment]
Added.
