### ISSUE TITLE
Can't use waifu2x-ncnn-vulkan 

### ISSUE THREAD

**Issue by xXHenlolXx** [k4yt3x/video2x#291]
Hello, I am having some problems with Video2X 4.5.0. I am trying to upscale a video using waifu2x-ncnn-vulkan, but I keeping getting this error:
[video2x_2020-06-07_19-00-37.log](https://github.com/k4yt3x/video2x/files/4743174/video2x_2020-06-07_19-00-37.log)

I tried to update waifu2x-ncnn-vulkan and change file directory, but nothing worked. Standard waifu2x and anime4k are working - but anime4k had a lot of artifacts.

Also, I wanted to reported that I was also having an error while using temp as cache folder (while extracting frames), but I didn't saved the log or took a screenshot, as it was easily solved.

My system:
CPU: Ryzen 7 3700x
GPU: GTX 1060 6GB
Ram: 16GB

Thanks in advance

**Comment by k4yt3x** [comment]
On my phone right now. Will take a look later.

**Comment by k4yt3x** [comment]
> video2x_2020-06-07_19-00-37.log

Looks like `waifu2x-ncnn-vulkan` just didn't launch properly. Usually this kind of situations are caused by missing drivers. However, w2x-ncnn-vulkan doesn't really require any drivers, so I'm not sure exactly what went wrong.

> Also, I wanted to reported that I was also having an error while using temp as cache folder (while extracting frames), but I didn't saved the log or took a screenshot, as it was easily solved.

What error did you have exactly?

**Comment by xXHenlolXx** [comment]
Waifu2x-ncnn-vulkan is still not working for me on 4.6.0. 

[video2x_2020-06-08_13-03-14.log](https://github.com/k4yt3x/video2x/files/4748555/video2x_2020-06-08_13-03-14.log)

> What error did you have exactly?

I tried to use temp again, to see the error: 

[video2x_2020-06-08_14-23-27.log](https://github.com/k4yt3x/video2x/files/4748517/video2x_2020-06-08_14-23-27.log)
[video2x_2020-06-08_11-28-42.log](https://github.com/k4yt3x/video2x/files/4748556/video2x_2020-06-08_11-28-42.log)

But I think it may be because of the disk space. I have 52 GB free on my ssd, while the video is 1920x1080 24fps 7:30.

**Comment by k4yt3x** [comment]
> Invalid GPU device
You can try listing available devices and select manually.

![image](https://user-images.githubusercontent.com/21986859/84147751-74fa8400-aa4d-11ea-8267-e338b4e957f5.png)

**Comment by HyperTesto** [comment]
Got the same error inside docker but i can list the devices correctly using w2x-converter-cpp:
```
./waifu2x-converter-cpp -l
   0: GeForce RTX 2060 SUPER                         (CUDA      ): num_core=34
   1: AMD Ryzen 9 3900X 12-Core Processor            (FMA       ): num_core=24
```

**Comment by xXHenlolXx** [comment]
Unfortanely it didn't work. 
![image](https://user-images.githubusercontent.com/27168630/84189055-fe6c7f00-aa6a-11ea-8fce-243a3a9455a6.png)


It should be 0, right?
![image](https://user-images.githubusercontent.com/27168630/84188850-a0d83280-aa6a-11ea-99b9-dfbbc883d567.png)

**Comment by k4yt3x** [comment]
> It should be 0, right?
> ![image](https://user-images.githubusercontent.com/27168630/84188850-a0d83280-aa6a-11ea-99b9-dfbbc883d567.png)

Yeah looks about right. If it doesn't work, try 1.

**Comment by xXHenlolXx** [comment]
I tried 0, 1 and 2, as you can see in the first screenshot, but it's always the same error. Redownloading it to test if it was corrupted also didn't help.

**Comment by xXHenlolXx** [comment]
So I fixed it. All I needed to do was reinstall my video driver. Strangely, only the vulkan API programs were affected, as Doom Eternal was also not opening on my pc, but DirectX games were normal. Sorry for the trouble and thanks for your help.

**Comment by k4yt3x** [comment]
Was it just the version of your driver?

**Comment by xXHenlolXx** [comment]
No, I just opened GeForce Experience and reinstalled the same driver

**Comment by k4yt3x** [comment]
Huh interesting... well then congrats

**Comment by xXHenlolXx** [comment]
So, as it is working now, I have a question. Why waifu2x_ncnn_vulkan's tile-size need to be at least 32? Since version 20200530, I think that it uses "0" as default and automatically defines it based on the gpu. Even if I try to set "0" in video2x.yam, and then make it read-only, video2x will set the tile-size to 32. So what is the better tile-size for my 1060 6GB? Since I'm not sure how exactly it correlates with vram and I want it to use everything it can to go as fast as possible

Also, I have 2 suggestions:
I think it would be nice if video2x could show a preview of the upscale, using a frame from the video. Therefore, it would be possible to see the difference in quality and time between drivers and automatically test the ideal noise, model, filter, etc. 

If the "preserve frames" feature could be used to upscale the same video more times, without having to extract everything again.

**Comment by k4yt3x** [comment]
> I think it would be nice if video2x could show a preview of the upscale, using a frame from the video. Therefore, it would be possible to see the difference in quality and time between drivers and automatically test the ideal noise, model, filter, etc.

I can consider that. Open an issue for people to discuss about it.

> If the "preserve frames" feature could be used to upscale the same video more times, without having to extract everything again.

Already on agenda. Mentioned in other issues.
