### ISSUE TITLE
Additional FFmpeg options?

### ISSUE THREAD

**Issue by mason1171** [k4yt3x/video2x#292]
## Description
If possible, could more ffmpeg options be added to the program please?; namely the "ultra-fast to placebo" speed presets, as well as the "-rc vbr_hq" and "-maxrate:” flags

## Sources

> https://trac.ffmpeg.org/wiki/Encode/H.264

> http://ntown.at/knowledgebase/cuda-gpu-accelerated-h264-h265-hevc-video-encoding-with-ffmpeg/

**Comment by k4yt3x** [comment]
I considered that before, but options are passed to the FFmpeg wrapper as a `dict`, not a list, so it's a bit hard to implement elegantly.

If you want that added, you can always add additional FFmepg options in the config file.

**Comment by mason1171** [comment]
You are an extremely active dev. By "config", are you talking the yaml file?

**Comment by k4yt3x** [comment]
Yes I am. If you want to apply what you just said on the last step, then do this.

**Comment by k4yt3x** [comment]
Basically key:value

**Comment by mason1171** [comment]
Thanks so much. I appreciate the very fast help

**Comment by k4yt3x** [comment]
Hmmmm... I'm hesitating whether to add this feature into the GUI, but as I said, it's kinda hard to implement, while being a nice-to-have.

You can leave it open. I'll see if I can do something about it.

**Comment by k4yt3x** [comment]
I don't think I'll be adding this now. It's hard to mash this into the current settings structure.
