### ISSUE TITLE
Settings not clear

### ISSUE THREAD

**Issue by Auno94** [k4yt3x/video2x#293]
Hi,

while i managed to upscale some Videos already with Caffe I don't understand some of the Settings. For Example the GPU no is by default  0. Does that mean it doesn't use the GPU or is just GPU 0 my GPU (RTX 2080) if I Don't have another. Also with Output Quality -1

**Comment by k4yt3x** [comment]
Hey sorry I didn't see this message somehow until just now.
GPU=0 means v2x will be using the GPU with ID=0, yet which GPU will have ID=0 is up to the specific application.
Generally speaking, if you have a discrete graphics card like rts 2080, it will be 0.
Output quality=-1 just means as high as possible.
