### ISSUE TITLE
Unknown FFmpeg errror

### ISSUE THREAD

**Issue by Auno94** [k4yt3x/video2x#294]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
subprocess.CalledProcessError: Command '['C:\\Users\\nphil\\Desktop\\video2x-4.6.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'Y:\\Renderer\\Ausgabe\\Dance In The Vampire Bund - S01e01.mkv', '-pix_fmt', 'rgba64be', 'C:\\Users\\nphil\\AppData\\Local\\Temp\\video2x\\tmpqg55vylz\\extracted_%0d.png']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
This log doesn't mean anything.
Please include your error log.

**Comment by Auno94** [comment]
[video2x_2020-06-10_08-17-33.log](https://github.com/k4yt3x/video2x/files/4769055/video2x_2020-06-10_08-17-33.log)

**Comment by k4yt3x** [comment]
hmmmm not sure what went wrong here. FFmpeg didn't give any output.
What happens if you disable hardware acceleration?

**Comment by Auno94** [comment]
Without it it works. 

Will try to use a different Quadro driver.

**Comment by k4yt3x** [comment]
Hmmmm that's FFmpeg's issue then.
You can find `-hwaccel`s in the config and set them to `false` if you want to set this to be off by default.

**Comment by Auno94** [comment]
Found the issue. 
The Quadro Driver was not working as intended. After fixing the issue. FFmpeg works as intended

**Comment by k4yt3x** [comment]
Glad to hear you fixed it
