### ISSUE TITLE
Output video larger than original

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#298]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.6.0-win32-full|
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Video2x goes to the end but the output video is larger than the original.
I have this issue with some videos that have the same format.
I don't understand where could be the problem because i did not have this issue this the test i did with a cut video (re-encoded).

## Screenshots or Error Messages
![Screen_original](https://user-images.githubusercontent.com/65050591/84324473-061a4980-ab79-11ea-86e9-5931d2bd9d55.png)
![Screen_upscale](https://user-images.githubusercontent.com/65050591/84324676-57c2d400-ab79-11ea-9a5b-2061dcf06b32.png)

Please paste your error message in the code block down below:
https://send.firefox.com/download/da3ca24dab49dea7/#rKoxHH5IqhG8yVIXXmMmAA
This is the original video.

**Comment by Faniia** [comment]
![extracted_12585](https://user-images.githubusercontent.com/65050591/84349789-5cf34380-abb8-11ea-8f07-2a5191882822.png)
I reproduced the bug with this image, it would be faster to investigate.

**Comment by Faniia** [comment]
I tried on an other video2x release.
It failed upscaling this the message error:
Incompatible pixel format 'rgba64be' for codec 'libx264', auto-selecting format 'yuv444p10le'

**Comment by k4yt3x** [comment]
4.0.0 is way too old and contains way too many issues.
Also, this is not an error, but a warning/notification. It has corrected itself.

**Comment by Faniia** [comment]
I corrected the bug using ffmpeg.
ffmpeg -i in.mkv -c copy -aspect 4:3 output.mkv

**Comment by Faniia** [comment]
After, searching for the cause of the problem, i think it is the same one that https://github.com/k4yt3x/video2x/issues/161
