### ISSUE TITLE
Run From Source / Ubuntu 20.04

### ISSUE THREAD

**Issue by idanka** [k4yt3x/video2x#299]
Hi!
sudo  ./video2x_setup_ubuntu.sh
...

Collecting tqdm
  Using cached tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied, skipping upgrade: PyQt5-sip<13,>=12.8 in /usr/local/lib/python3.8/dist-packages (from pyqt5->-r /root/.local/share/video2x/src/requirements.txt (line 4)) (12.8.0)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->-r /root/.local/share/video2x/src/requirements.txt (line 8)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r /root/.local/share/video2x/src/requirements.txt (line 8)) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r /root/.local/share/video2x/src/requirements.txt (line 8)) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r /root/.local/share/video2x/src/requirements.txt (line 8)) (1.25.8)
Installing collected packages: pyqt5, python-magic, requests, tqdm
  Attempting uninstall: pyqt5
    Found existing installation: PyQt5 5.14.1
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] Nincs ilyen fájl vagy könyvtár: '/usr/lib/python3/dist-packages/PyQt5-5.14.1.dist-info/RECORD'

How to fix the error?

**ERROR: Could not install packages due to an EnvironmentError: [Errno 2] missing file or folder: '/usr/lib/python3/dist-packages/PyQt5-5.14.1.dist-info/RECORD'**

**Comment by k4yt3x** [comment]
I think you have a broken installation of PyQt5. Try removing it and reinstalling.

```bash
pip remove pyqt5
```

**Comment by idanka** [comment]
# pip3 uninstall pyqt5
Found existing installation: PyQt5 5.14.1
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/uninstall.py", line 85, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_install.py", line 675, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_uninstall.py", line 535, in from_dist
    for path in uninstallation_paths(dist):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_uninstall.py", line 67, in unique
    for item in fn(*args, **kw):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_uninstall.py", line 85, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] Nincs ilyen fájl vagy könyvtár: '/usr/lib/python3/dist-packages/PyQt5-5.14.1.dist-info/RECORD'

**Comment by k4yt3x** [comment]
Yeah you have a broken package. You might have to go in that directory and remove it manually.
I remember encountering a similar issue a while back.

**Comment by idanka** [comment]
ok, but next problem

mkdir: '/tmp/video2x/waifu2x-caffe-ubuntu/build' könyvtár létrejött
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at caffe/cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  caffe/CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.46") found components: system thread filesystem 
-- Found Threads: TRUE  
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.4") found components: HL 
-- Found LMDB: /usr/include  
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 10.1
-- Added CUDA NVCC flags for: sm_75
-- OpenCV found (/usr/lib/x86_64-linux-gnu/cmake/opencv4)
-- Found Atlas: /usr/include/x86_64-linux-gnu  
-- Found Atlas (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libatlas.so)
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7") 
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2.7")
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.16.5", minimum required is "1.7.1") 
-- NumPy ver. 1.16.5 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.46") found components: python 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   de4a5dc
--   System            :   Linux
--   C++ compiler      :   /usr/bin/g++-8
--   Release CXX flags :   -O3 -DNDEBUG -std=c++11 -fpermissive -Wunused-variable  -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -std=c++11 -fpermissive -Wunused-variable  -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.71)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.6.1)
--   lmdb              :   Yes (ver. 0.9.24)
--   LevelDB           :   Yes (ver. 1.22)
--   Snappy            :   Yes (ver. 1.1.8)
--   OpenCV            :   Yes (ver. 4.2.0)
--   CUDA              :   Yes (ver. 10.1)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_75
--   cuDNN             :   Not found
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /usr
-- 
-- Found cuDNN (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found cuDNN (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found OpenCV: /usr (found version "4.2.0") found components: core imgproc highgui 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: filesystem system iostreams 
-- Found GLOG: /usr/include  
-- Found CUDA: /usr (found version "10.1") 
-- Configuring done
CMake Error at caffe/CMakeLists.txt:108 (add_dependencies):
  The dependency target "pycaffe" of target "pytest" does not exist.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by idanka** [comment]
Open Gui/ Binary path Ubuntu 20.04:)
python3 video2x_gui.py

- /home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\waifu2x-caffe\waifu2x-caffe-cui
- /home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\waifu2x-converter-cpp\waifu2x-converter-cpp
- /home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan
- /home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\srmd-ncnn-vulkan\srmd-ncnn-vulkan
- /home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\realsr-ncnn-vulkan\realsr-ncnn-vulkan
-/home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI
-/home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\ffmpeg-latest-win64-static\bin
-/home/dankahazi/Colorize/video2x/src/%LOCALAPPDATA%\video2x\gifski\win\gifski

**Comment by k4yt3x** [comment]
> The dependency target "pycaffe" of target "pytest" does not exist.

Looks like you're missing pycaffe?
Keep in mind that the installation script is tested only on Ubuntu 19.10. To get it to work on other systems, you might need some tweaking.

**Comment by idanka** [comment]
Thx, help!
But howto install pycaffe?
Pls:)

**Comment by k4yt3x** [comment]
I'm not quite sure, you might be able to get it from APT or pip. Otherwise, you might have to build it manually.
