### ISSUE TITLE
Several dependencies missing

### ISSUE THREAD

**Issue by BeholdenCypress** [K4YT3X/video2x#3]
It says that I need to download both TQDM and Avalon Framework because they are showing up as modules that are missing

I downloaded TQDM from GitHub and that worked, however, I was then met with an error saying that there was no module called Avalon. I downloaded your Avalon package from GitHub but that did not work. 

I ended up having to remove every instance of Avalon from the video2x.py in order for it to run
properly.

![image](https://user-images.githubusercontent.com/23390938/41494002-597aee3e-70c2-11e8-8a3b-283201fb3f1c.png)

That is the one for TQDM, but it said the same for Avalon once I got TQDM sorted.

**Comment by Mirrorman95** [comment]
It worked for me after I did the following package install commands:
pip install tqdm
pip install avalon_framework
pip install colorama

**Comment by K4YT3X** [comment]
@Mirrorman95 You're right. I should add a requirements.txt into the repository.
