### ISSUE TITLE
AMD / OpenCV support?

### ISSUE THREAD

**Issue by SnaxxNZ** [K4YT3X/video2x#30]
Is there any chance this can be updated to include support for AMD cards?

ffmpeg supports AMD/VCE and there is a version of Waifu2x that supports AMD (and intel) here - https://github.com/DeadSix27/waifu2x-converter-cpp

**Comment by K4YT3X** [comment]
Since you asked, I don't see why we don't.

Version 2.2.0 is still being tested. AMD support will be scheduled for the next version.

**Comment by SnaxxNZ** [comment]
Oh that's awesome.

Thanks heaps.

**Comment by K4YT3X** [comment]
I've already started working on this one. I'm now stuck on the question of how to decompress the binary file of waifu2x-converter-cpp since it's archived with 7z. Not sure how to do that elegantly yet with python.

**Comment by K4YT3X** [comment]
I have released update 2.4.0 which added support for waifu2x_converter_cpp. If you encounter any issues, please open new issues for the specific problem.
