### ISSUE TITLE
arbitrary upscaling ratio on video with any driver of fixed upscaling ratio

### ISSUE THREAD

**Issue by nihui** [k4yt3x/video2x#300]
waifu2x-ncnn-vulkan 只支持 2x 放大

如果需要 3x 放大，有三种实现方法

1. 类似于 caffe / converter-cpp，做两遍 waifu2x，得到 4x 图，然后 bicubic 缩小到 3x
2. 先 bicubic 放大到 1.5x，做一遍 waifu2x，得到 3x
3. 先做一遍 waifu2x，得到 2x 图，然后 bicubic 放大到 3x

方法1做了两遍 waifu2x，速度会明显更慢
方法2和3速度较快，并且可以在video2x pipeline中直接实现，并且方法3比方法2更快些，但可能画质更差些

2= 在解码视频时，直接存出 1.5x 放大的图
3= 在编码视频时，直接编码 3x 放大的视频

----------------

Waifu2x-ncnn-vulkan only supports 2x zoom

If 3x scaling is required, there are three kinds of implementation

1. Similar to caffe / converter-cpp, do waifu2x twice, get 4x image, and then the bicubic to 3x
2. First bicubic zooms to 1.5x, does waifu2x again, gets 3x
3. Do the waifu2x first, get the 2x image, and then scale to 3x

Method 1 has been done twice waifu2x, the speed will be significantly slower
Methods 2 and 3 are faster and can be implemented directly in video2x pipeline, and method 3 is faster than method 2, but the quality may be worse

2= Save 1.5x zoomed picture directly when decoding video
3= Code 3x zoomed video directly when encoding video

**Comment by k4yt3x** [comment]
Much appreciated for the suggestion. Will put it into agenda.
I think it's most likely for me to implement the second method.

**Comment by k4yt3x** [comment]
Actually I'll do method one.

**Comment by nihui** [comment]
why method one ?

**Comment by k4yt3x** [comment]
Despite being significantly slower, method one should deliver better quality in theory right?

**Comment by k4yt3x** [comment]
This has already been implemented in https://github.com/k4yt3x/video2x/commit/7059852586b4db497155588f968cf2cb1f40b1be.
More optimizations might be desirable in the future, but they will be tracked separately if needed.

**Comment by mirh** [comment]
I agree with the adopted solution, and it may even get better with #478
But maybe fixed scaling ratios should be mentioned somewhere (a tooltip, or maybe some extra line on the command line).

I get that people somehow may just wish a *lower* output resolution for whatever reason, but it was only today that I realized 2x RealSR was a "lie" performance-expectations-wise.

**Comment by k4yt3x** [comment]
@mirh I totally agree with you. The UI will be remastered in version 5.0.0. I'll make sure to have that in there along with driver differences explanations and more.
