### ISSUE TITLE
waifu2x-caffe return with error

### ISSUE THREAD

**Issue by itsSony** [k4yt3x/video2x#305]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
[video2x_2020-06-18_20-22-13.log](https://github.com/k4yt3x/video2x/files/4802348/video2x_2020-06-18_20-22-13.log)

**It is highly recommended to include your error log.**
[](url)

**Comment by k4yt3x** [comment]
Looks like a driver issue.
You're using waifu2x-caffe. Do you have Nvidia GPU and drivers installed?

**Comment by itsSony** [comment]
I have installed video2x by following steps from
https://github.com/k4yt3x/video2x/wiki/Step-By-Step-Tutorial 

Is there a way I can check to see the drivers installed? 

Thanks
-SG

**Comment by k4yt3x** [comment]
That tutorial is really old. It's for Video2X 2.x.x, and we're already on 4.6.0.
Let's start simple, do you have an NVIDIA GPU?
