### ISSUE TITLE
returned non-zero exit status 3221225785.

### ISSUE THREAD

**Issue by hytebackup** [k4yt3x/video2x#308]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.
I wanted to upscale the image via Anime4k, but these errors come out, I do it on a remote server from Microsoft azure, I don’t have a GPU
## Error Log or Screenshots
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-06-24 08:42:09.937850 [+] INFO: Input path(s): C:\Users\DrePC\Desktop\video2x-4.6.0-win32-full\324_GMxjubvg5Pk.jpg[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-06-24 08:42:09.955596 [+] INFO: Input file: C:\Users\DrePC\Desktop\video2x-4.6.0-win32-full\324_GMxjubvg5Pk.jpg[0m
[32m[+] INFO: Starting to upscale image[0m
[90m2020-06-24 08:42:09.957584 [+] INFO: [upscaler] Subprocess 9720 executing: 'C:\Users\DrePC\Desktop\video2x-4.6.0-win32-full\dependencies\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI' --passes 2 --pushColorCount 2 --strengthColor 0.3 --strengthGradient 1.0 --zoomFactor 2.0 --threads 16 --preFilters 4 --postFilters 40 --platformID 0 --deviceID 0 --codec mp4v --input 'C:\Users\DrePC\Desktop\video2x-4.6.0-win32-full\324_GMxjubvg5Pk.jpg' --output 'C:\Users\DrePC\Desktop\video2x-4.6.0-win32-full\324_GMxjubvg5Pk_output.png'[0m
[90m2020-06-24 08:42:09.961625 [+] INFO: Main process waiting for subprocesses to exit[0m
[31m[1m[!] ERROR: Subprocess 5108 exited with code 3221225785[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 667, in run
  File "upscaler.py", line 534, in run
  File "upscaler.py", line 401, in _wait
  File "upscaler.py", line 385, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\DrePC\\Desktop\\video2x-4.6.0-win32-full\\dependencies\\anime4kcpp\\CLI\\Anime4KCPP_CLI\\Anime4KCPP_CLI', '--passes', '2', '--pushColorCount', '2', '--strengthColor', '0.3', '--strengthGradient', '1.0', '--zoomFactor', '2.0', '--threads', '16', '--preFilters', '4', '--postFilters', '40', '--platformID', '0', '--deviceID', '0', '--codec', 'mp4v', '--input', 'C:\\Users\\DrePC\\Desktop\\video2x-4.6.0-win32-full\\324_GMxjubvg5Pk.jpg', '--output', 'C:\\Users\\DrePC\\Desktop\\video2x-4.6.0-win32-full\\324_GMxjubvg5Pk_output.png']' returned non-zero exit status 3221225785.

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
![image](https://user-images.githubusercontent.com/47600499/85523552-a733e600-b5f6-11ea-8c2f-ed707c5c4b85.png)
![image](https://user-images.githubusercontent.com/47600499/85523669-cfbbe000-b5f6-11ea-985c-dc545abf3c02.png)

**Comment by TianZerL** [comment]
You need a opencl runtime even there is no GPU in the server, try to install an Intel CPU OpenCL runtime.

**Comment by hytebackup** [comment]
> You need an opencl runtime even there is no GPU in the server, try to install an Intel CPU OpenCL runtime.

Thanks, it works now
