### ISSUE TITLE
Waifu2X Caffe returned with an error

### ISSUE THREAD

**Issue by leodomi** [k4yt3x/video2x#309]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

Video2X 4.6.0 full version

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
[video2x_2020-06-25_22-56-47.log](https://github.com/k4yt3x/video2x/files/4833791/video2x_2020-06-25_22-56-47.log)

![image](https://user-images.githubusercontent.com/33042520/85795078-f6356480-b737-11ea-8297-89bb8c1f9b9b.png)

**Comment by mason1171** [comment]
Check this out: https://github.com/k4yt3x/video2x/issues/213
You likely need to put the cudnn.dll file in your waifu2x directory 
https://developer.nvidia.com/rdp/cudnn-download

**Comment by k4yt3x** [comment]
1. Do you have an Nvidia GPU?
1. Do you have Nvidia drivers installed?

**Comment by leodomi** [comment]
Hi, yes I have a GTX 1070. I installed CUDA then copied the cudnn dlls in the CUDA directories as requested in the guide.

However, I downloaded the full package of video2x, extracted it then run the GUI without copy anything in the folder "dépendances"

**Comment by k4yt3x** [comment]
You shouldn't need to move anything over.
I'm suspecting that your cuDNN isn't installed properly.
If you go open dependencies/waifu2x-caffe/waifu2x-caffe.exe, you should see this window with this button.

![image](https://user-images.githubusercontent.com/21986859/85839325-51904280-b78a-11ea-8b84-dfa974b0c89e.png)

Go ahead and click it. It will tell you if cuDNN is installed correctly.
Also, don't worry if it's not. It's a bit annoying to configure for the first time.

**Comment by leodomi** [comment]
Ok I think I found something interresting : 

![image](https://user-images.githubusercontent.com/33042520/85881061-53372600-b7dd-11ea-8828-9a78f2591e4c.png)
(roughly translate in "impossible to find cudnn64_7.dll")

In "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin" I have "cudnn64_8.dll" and not "cudnn64_7.dll"

**Comment by leodomi** [comment]
Is there a way to use cudnn64_8.dll or should I uninstall CUDA 11 to install the 10.2 version, that is required to use the cudnn7 version ?

**Comment by k4yt3x** [comment]
Ok then, I’m closing this issue if it’s solved.
