### ISSUE TITLE
Always give an error when zooming in

### ISSUE THREAD

**Issue by keyutao9** [K4YT3X/video2x#31]
Trailing options were found on the commandline.
G:\video2x-master\video2x-master\upscaled\no_audio.mp4: No such file or directory
[+] INFO: Program completed, taking 19.93307 seconds

**Comment by K4YT3X** [comment]
It seems like that the upscale has failed. Could you please provide the full log or a screenshot?

**Comment by keyutao9** [comment]
Chóngxīn ānzhuāng zhīhòu wèntí jiějuéle, qǐngwèn zuòzhě lèisì de chāo fēnbiàn lǜ ruǎnjiàn hái yǒu ma?Waifu2X màosì zhǐ néng fàngdà mànhuà, fàngdà pǔtōng shìpín gǎnjué méiyǒu xiàoguǒ
57/5000
After the reinstallation, the problem is solved. Does the author have similar super resolution software? waifu2X seems to only enlarge the comics, zooming in the ordinary video feels no effect

**Comment by keyutao9** [comment]
After the reinstallation, the problem is solved. Does the author have similar super resolution software? waifu2X seems to only enlarge the comics, zooming in the ordinary video feels no effect

**Comment by K4YT3X** [comment]
@keyutao9 you can set the upscale model. The default is anime, and you can set it to photo, which suits regular videos better.
