### ISSUE TITLE
Output Filename Formatting

### ISSUE THREAD

**Issue by mason1171** [k4yt3x/video2x#310]
## Description

Can there be a output filename formatting feature added? The feature would be handy for bulk processing and reduce the need for post process renaming.  If this can be done independently by editing the yaml, can you please show me how?
- Ex) xxxxx[Upscaled].mkv

**Comment by k4yt3x** [comment]
This isn't a feature yet, I'm thinking how I should do this properly.

**Comment by mason1171** [comment]
Thanks

**Comment by k4yt3x** [comment]
I'm thinking about adding a editable format string in the config file so you can edit the format string to alter how the output file names should look like.

```python
output = "{original_filename}_output{extension}".format(input, extension)
```

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/86069793-74607680-ba6a-11ea-8502-0834818800db.png)

Here's a concept work. I don't quite like the design though. Needs some tweaking.

**Comment by mason1171** [comment]
It works for me. The label could just be shortened

**Comment by k4yt3x** [comment]
It has the same name as the key in the config file. It's easier to correspond the two settings this way.
Do you have any ideas how it can be shortened?

**Comment by mason1171** [comment]
“Output Name Format”
Can that work?

**Comment by k4yt3x** [comment]
but it is technically a format string

**Comment by mason1171** [comment]
Then why not “Output Format String”?

**Comment by k4yt3x** [comment]
Output (what) format string
Not precise enough

**Comment by mason1171** [comment]
“Output Name Pattern”

**Comment by k4yt3x** [comment]
Still not precise

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/86138546-25ecbf80-bade-11ea-883e-a28ee96ee4c0.png)

**Comment by k4yt3x** [comment]
This has been added in the latest commits.
