### ISSUE TITLE
Qt5Core.dll crashes during long video upscales

### ISSUE THREAD

**Issue by HarryFreeMyLand** [k4yt3x/video2x#311]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**: Caffe Latest
- **GUI version**: 2.7.1
- **CLI version**: NA

## Symptom

When up-scaling a long video the main python process exits with no error, with no obvious trigger.
It's also notable that longer videos seem to make it more likely to exit like this.
the driver (Caffe in this case) will continue to run. where ffmpeg can be run manually.

## Error Log or Screenshots

There isn't really a specific error in regular use, it just... exits abruptly, without any exception or error.
![image](https://user-images.githubusercontent.com/47612589/86065598-ff774780-ba3d-11ea-9b65-bdde37d11ba5.png)

**It is highly recommended to include your error log.**
The logs don't show anything more than the last message in the console.

**Comment by 78Alpha** [comment]
This also occurs when multiple videos are queued up. The process will actually start to get slower and slower until the application quits. Degraded from 6 fps to 3 to .0.3 then shutdown.

2 GPUs were set to run, the 2060 exited out before the 1650, both stopping at episode 4 of their respective queues.

**Comment by k4yt3x** [comment]
From our investigations in the discussion group, it seems like it's Qt5Core.dll that's crashing.
Theoretically it shouldn't degrade waifu2x/other drivers' performance.

**Comment by k4yt3x** [comment]
For documentation purposes, here are some screenshots
![image](https://user-images.githubusercontent.com/21986859/87463784-87924b00-c601-11ea-970d-1c33ef3ba39c.png)

**Comment by 78Alpha** [comment]
Since it's QT5 I assume it only affects the GUI version?

**Comment by k4yt3x** [comment]
Yes, that's what's been observed so far, only the GUI version should be affected.
