### ISSUE TITLE
UI is too big and dissapears when trying to scale it.

### ISSUE THREAD

**Issue by ObscenityIB** [k4yt3x/video2x#312]
## Component Versions

- **GUI version**: 2.7.1

## Symptom

UI is vertically too long, and its impossible to press the start button, since everything below the "Current Video Processing Progress" text is off the end of the screen.

Also wondering why the most important button is the very last thing on the UI.

## Error Log or Screenshots

My screen
![image](https://user-images.githubusercontent.com/6983255/86250619-27101080-bbf4-11ea-8f63-108014e6827e.png)

The missing part I found on google images:
![image](https://user-images.githubusercontent.com/6983255/86250720-49099300-bbf4-11ea-9729-43c96f0467c6.png)

**Comment by k4yt3x** [comment]
How's your screen less than 900px though?

**Comment by ObscenityIB** [comment]
It is the regular standard laptop screen size. 1366x768.

**Comment by k4yt3x** [comment]
None of my laptops are below 1080, so this didn't come across my minding when designing the interface.
What would you suggest to make this work though? Make it scrollable?

**Comment by k4yt3x** [comment]
It's actually easier than I thought. What do you think about this?

![image](https://user-images.githubusercontent.com/21986859/86287966-b14a7b80-bbd8-11ea-91d9-026a3f8f5729.png)

**Comment by ObscenityIB** [comment]
Ah yes, that's nice, my other idea was to try horizontal scaling, but that just stretched the buttons, I was hoping it would create a blank space for the buttons to snap to, but it's not responsive like that.

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/86304617-f1245980-bbfe-11ea-8de1-dc3dfd09ec23.png)

Honestly horizontal scaling might be harder. This is probably a bit more elegant as both the vertical size and the horizontal size can be flexible. I'm happy with it, should you think it's fine I'll push the new commits up.

**Comment by k4yt3x** [comment]
Alright I pushed a new commit, you can try it in the newest nightly build when it finishes.

**Comment by ObscenityIB** [comment]
Nice, ill let you know.

**Comment by ObscenityIB** [comment]
oof, that took forever, but damn that difference, ill trade 30+ hours for a minute of clean video anytime.

thanks for the UI fix, works great.

**Comment by k4yt3x** [comment]
Glad to hear that!
