### ISSUE TITLE
Jobs setting has no effect

### ISSUE THREAD

**Issue by GitGerby** [k4yt3x/video2x#313]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0 RELEASE 
- **Upscaler version**: 
- **GUI version**: 2.7.1
- **CLI version**:

## Symptom

Jobs seem to be hardcoded to 1:1:1 on the Vulkan NCNN driver setting; tried setting anything else and the log window always shows the param passed to the scaler as 1:1:1.

Issue appears to be on line 61 of waifu2x_ncnn_vulkan.py; Working on understanding how this variable is populated.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

![image](https://user-images.githubusercontent.com/36684477/87214437-865bd800-c2fa-11ea-8d89-31408fda5881.png)

**Comment by GitGerby** [comment]
looks like processes is set globally whereas this should be populated from the jobs field in the GUI or yaml; I'm not sure where those settings are ingested.

**Comment by GitGerby** [comment]
Looking at the yaml there's this line 
```
j: "1:2:2" # thread count for load/proc/save (default=1:2:2)
```
which specifies a string, I _think_ this means that line 61 of the wrapper isn't actually needed?

**Comment by k4yt3x** [comment]
Yeah this setting is overwritten by the global processes option.

**Comment by GitGerby** [comment]
Is this working as intended then? Should documentation or the GUI be updated to remove the field? I suspect I can squeeze a bit more performance out of this card based on the usage pattern if I could spawn a second inferencing thread in ncnn.

**Comment by k4yt3x** [comment]
Basically what's happening right now is the global processes will be applied to *-ncnn-vulkan as the following:
if p = 2
j will be overwritten to 2:2:2

**Comment by GitGerby** [comment]
Ahh ok, so it won't actually fork two processes but it will thread the job
2:2:2.  I'll give that a shot, thank you!

**Comment by GitGerby** [comment]
not ignoring this; but waiting for a heatwave to pass in this area so I can test

**Comment by k4yt3x** [comment]
Feel free to keep posting if you're still having problems.

**Comment by GitGerby** [comment]
I'll do more investigation later, unfortunately 30+ degrees c outside and
working from home my rig pumps out too much heat to work on upscaling
personal projects right now.
