### ISSUE TITLE
Conversion fails if the filename has Russian charachters

### ISSUE THREAD

**Issue by ApoorvRChincholkar** [k4yt3x/video2x#315]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **GUI version**: 2.7.1

## Symptom

Error message is received whenever filename has Russian characters in it.
NOTE: This issue may present for other languages too. 

## Error Log or Screenshots
Error Log: 
```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
Redirecting console logs to C:\Users\Apoorv\Downloads\video2x-4.6.0-win32-full\video2x_2020-07-17_12-01-33.log
[+] INFO: Loading files into processing queue
2020-07-17 12:02:24.643480 [+] INFO: Input path(s): C:\Users\Apoorv\Desktop\русский.jpgTraceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 430, in run
  File "site-packages\avalon_framework\__init__.py", line 197, in debug_info
  File "site-packages\avalon_framework\__init__.py", line 152, in _print
  File "bilogger.py", line 40, in write
  File "c:\users\k4yt3x\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 81-87: character maps to <undefined>
```

![image](https://user-images.githubusercontent.com/27355235/87755999-bab52400-c825-11ea-829c-610c602fed12.png)

**Comment by k4yt3x** [comment]
Opening the log file with UTF-8 encoding might solve it. I'll push an update.

![image](https://user-images.githubusercontent.com/21986859/87820664-fd92ee00-c85d-11ea-9101-ff16d35d9255.png)

**Comment by k4yt3x** [comment]
Please fetch the artifacts produced by this workflow after it finishes building and see if it solves the problem.
https://github.com/k4yt3x/video2x/actions/runs/173052683

**Comment by ApoorvRChincholkar** [comment]
> Please fetch the artifacts produced by this workflow after it finishes building and see if it solves the problem.
> https://github.com/k4yt3x/video2x/actions/runs/173052683

Yes, with this build it did solve the problem.

**Comment by k4yt3x** [comment]
Great. The patch will be added in the next release.
