### ISSUE TITLE
input output path type mismatch

### ISSUE THREAD

**Issue by troy125478** [k4yt3x/video2x#317]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.6.0
- **Upscaler version**: Waifu2x Caffe (Latest)
- **GUI version**: 2.7.1
- **CLI version**: 4.1.1

## Symptom

I used one of the builds you sent ApoorvRChincholkar's issue. Because I had the same issue just different positions. But anyway this was the error.
[video2x_2020-07-19_10-14-13.log](https://github.com/k4yt3x/video2x/files/4944157/video2x_2020-07-19_10-14-13.log)

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
`Input is single file but output is directory`

**Comment by troy125478** [comment]
I am very stupid. Thank you.
