### ISSUE TITLE
Video2x folder is gone after first run

### ISSUE THREAD

**Issue by Imsokray** [k4yt3x/video2x#318]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.2.0
- **Upscaler version**:
- **GUI version**:
- **CLI version**: Sorry, couldn't screenshot my CLI version. There is nothing to show.

## Symptom
After running the Video2x for the first time, I left the machine on and left, but the next morning, there is not output and the video2x folder in my C:// is empty. I was able to find the model folders (anime4kccp  etc.) in the Local folder. C:\Users\Media\AppData\Local\video2x. But the video2x.py is gone.

## Error Log or Screenshots
 
![Annotation 2020-07-21 102604](https://user-images.githubusercontent.com/13956798/88005776-ae3e0d80-cb3c-11ea-850f-88f1e19a81b4.png)

**Comment by TianZerL** [comment]
How clould this possible？Did the V2X be deleted 
mistakenly by any anti-virus software？

**Comment by k4yt3x** [comment]
The program contains no such self-destruction logic. Also, I don't think 4.2.0 is the release version. If you're running directly from source code, then there's no release version.
I would suggest the same as @TianZerL did. Please check your AV logs and see if it was deleted mistakenly.

**Comment by Imsokray** [comment]
As far as I'm aware there is only a "High CPU Usage by: ffmpeg.exe" notice. I installed again and ran again for a 5 min video, and it failed at ~99% with this error:

[!] ERROR: Subprocess 3780 exited with code 1

I'm not sure what I'm doing wrong. Should I start a new issue for this?

**Comment by k4yt3x** [comment]
That doesn't look like a 99% to me, more like 0%.
You're using waifu2x-caffe in GPU mode. Do you have NVIDIA GPU and its drivers installed?

**Comment by Imsokray** [comment]
Oh, I see. I actually have AMD. Does waifu2x-caffe run for AMD? Thanks.

**Comment by k4yt3x** [comment]
waifu2x-caffe uses CUDA and cuDNN which are NVIDIA-only. For AMD I recommend you to try waifu2x-ncnn-vulkan.

**Comment by Imsokray** [comment]
Sorry for a dense question, but how do I disable the other drivers and only run waifu2x-ncnn-vulkan? Thanks.
