### ISSUE TITLE
waifu2x-caffe error

### ISSUE THREAD

**Issue by vrinlive** [k4yt3x/video2x#319]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots
![image](https://user-images.githubusercontent.com/24270971/88449632-f03bbc00-ce7a-11ea-8a5b-9cb5cc27ddcd.png)

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Do you have an NVIDIA GPU and its drivers installed?

**Comment by k4yt3x** [comment]
This thread has been idle for too long.
