### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by archienz** [K4YT3X/video2x#32]
please delete this, i suspect it has something to do with incomparable versions of windows 10, i had errors with pip/python earlier only just managed to get it working with this, it seems nvidia drivers don't like working for this version of windows (cuda, cudnn) BUILD (17134) got 32gb of ram, ryzen 1800x +1050ti it won't actually let me use it for some reason :(

**Comment by K4YT3X** [comment]
@archienz Feel free to reopen this at any time.

Maybe I should raise an exception in the future if the upscale was unsuccessful.
