### ISSUE TITLE
OpenCV Error code 3221226505

### ISSUE THREAD

**Issue by leodomi** [k4yt3x/video2x#320]
I'm using Video2X 4.6.0 full version with the GUI.

I was using Waifu2X Caffe with cudnn process, with a GTX1070 and 32gb of RAM, and I've used this config before without problems

I was upscaling a video but after 6h I got an OpenCV Error :

![image](https://user-images.githubusercontent.com/33042520/88477872-e5992980-cf43-11ea-8bf1-941c55edff78.png)

For some reason I can't find the log file sorry, I have 2 logs but not from this crash.

I was wondering if it was possible to resume an upscale that crashed or if it was necessary to start all over again from the beginning, even if I saved the temp folders ?

**Comment by k4yt3x** [comment]
The key here seems to be OpenCV loadsave assertion failure.
At the moment there's no resuming feature, so you'll have to start from the beginning.
I'd say try waifu2x-ncnn-vulkan which might give you a bit more stability.
