### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: 'G:\\Temp\\video2x' 

### ISSUE THREAD

**Issue by jekabsmilbrets** [k4yt3x/video2x#321]
## Component Versions

- **video2x-4.6.0-win32-full**: GUI version

## Symptom

I have been trying to convert folder of videos using anime4k driver(video2x, temp folders and video materials are on the same external hdd with exFat format but 9/10 times I right and 99% stage of video converting i get error that access denied to temp folders -> PermissionError: [WinError 5] Access is denied: 'G:\\Temp\\video2x'

Same thing happens if I only try to convert one file.

## Error Log or Screenshots
[video2x_2020-07-27_19-25-31.log](https://github.com/k4yt3x/video2x/files/4986728/video2x_2020-07-27_19-25-31.log)

**Comment by k4yt3x** [comment]
Despite the error, the one file should be upscaled successfully right?

**Comment by jekabsmilbrets** [comment]
In both ways (select file or select folder) it did not finish upscaling and no output video file was not created.

**Comment by jekabsmilbrets** [comment]
I have tried multiple external drives and all of them were exFat formatted

**Comment by VigilantBag** [comment]
Have you checked the permissions of the folder?
[https://answers.microsoft.com/en-us/windows/forum/windows_7-security/error-5-access-denied-setup-unable-to-create-the/e9e9ad9b-9a81-4a99-962e-3e5f0708a855]

**Comment by jekabsmilbrets** [comment]
> Have you checked the permissions of the folder?
> https://answers.microsoft.com/en-us/windows/forum/windows_7-security/error-5-access-denied-setup-unable-to-create-the/e9e9ad9b-9a81-4a99-962e-3e5f0708a855

I'll try today, but as  I know and as google says exfat formatted drives does not have permissions ->

"exFAT, as an extension of FAT, is not capable of storing discretionary access control metadata. This is why all the files on an exFAT volume appear to be 777 permissions. It's basically saying "this volume is wide-open because we can't not make it wide-open due to the file system format"."

**Comment by zxsean** [comment]
Hi all.I think this bug because the select file's permission is readonly.V2x try to remove the folder but the file is readonly.

**Comment by k4yt3x** [comment]
This still needs to be verified by @jekabsmilbrets. Since Video2X (at least its Python code) never set permissions, the program should respect the user's permissions unless one of Video2X's components is proven to set the permissions by mistake.

**Comment by jekabsmilbrets** [comment]
I'll verify this by the end of this week.

**Comment by jekabsmilbrets** [comment]
Looks that it works now as intended;
