### ISSUE TITLE
Error while upscaling using waifu2x caffe

### ISSUE THREAD

**Issue by SimplyDex** [k4yt3x/video2x#323]
## Component Versions

- **Video2X release version**: 4.6.0
- **GUI version**: 2.7.1

## Symptom

First time using this so I don't really know what's wrong, but an error popped up while I was upscaling a vid. Anyway to fix this?

## Error Log or Screenshots

[video2x_2020-08-02_16-26-18.log](https://github.com/k4yt3x/video2x/files/5013963/video2x_2020-08-02_16-26-18.log)

**Comment by k4yt3x** [comment]
Looks like an NVIDIA driver issue.

- Make sure you have NVIDIA GPU and drivers, or
- Try waifu2x-ncnn-vulkan.

**Comment by SimplyDex** [comment]
I'm using a 2070 super with the latest driver atm. I will try the waifu2x-ncnn-vulkan later on.

**Comment by SimplyDex** [comment]
I tried waifu2x-ncnn-vulkan and it worked, but I forgot how to change the resolution. How do you pick which resolution you want?

**Comment by k4yt3x** [comment]
waifu2x-ncnn-vulkan doesn't support output resolution, only scaling ratio.

![image](https://user-images.githubusercontent.com/21986859/89317173-8be3de00-d66c-11ea-8824-49572d527d96.png)

**Comment by SimplyDex** [comment]
Anyway to get waifu2x to work than? I want to upscale out at an output resolution.

**Comment by k4yt3x** [comment]
Your error looks like a driver issue. Try verifying that your GPU driver is the latest.

**Comment by SimplyDex** [comment]
I use Geforce experience to update my driver and it says I have the latest already.

**Comment by SimplyDex** [comment]
I use Geforce experience to update my driver and it says I have the latest already.

**Comment by k4yt3x** [comment]
Why did you close the issue? Did you manage to solve it?

**Comment by SimplyDex** [comment]
No, I closed it on accident. I did not solve it yet. I reinstalled my driver today and will check later if I still get the problem.

**Comment by SimplyDex** [comment]
yea, after reinstalling my gpu driver, waifu2x caffe works correctly now.

**Comment by SimplyDex** [comment]
rip nvm, I got the error again, I forgot ot change the heigh and width last time. Maybe it's something to do with that or me changing the output to .mkv.
[video2x_2020-08-09_23-26-18.log](https://github.com/k4yt3x/video2x/files/5052462/video2x_2020-08-09_23-26-18.log)

**Comment by k4yt3x** [comment]
Changing the output to MKV shouldn't break it. Does it start upscaling correctly if you specify only the scaling ratio?

**Comment by SimplyDex** [comment]
Yea, I did that the first time and it worked. Second time, I realized that I forgot to change it and tried it than the error popped up.

**Comment by k4yt3x** [comment]
Doesn't make sense, that simple difference shouldn't be causing any problems.
How many processes are you using?

**Comment by SimplyDex** [comment]
Sorry new to this, what do you mean by processes? I only have 1 GPU and 1 CPU and only run the video2x gui with no other programs up

**Comment by k4yt3x** [comment]
Oh I just mean if you've changed this value at all.
![image](https://user-images.githubusercontent.com/21986859/89950806-ddb2d800-dc19-11ea-8210-cd4e5e19eedf.png)

**Comment by SimplyDex** [comment]
Nope, left that on by default. Oh, it might be the scale ratio. I put it at 3.0 and changed the Waifu2x resolution setting to 1920x1080. I'll test it out later.

**Comment by SimplyDex** [comment]
Yea, I tried again and still got an error. Guess I can't use Waifu2x than. :l Maybe its my Waifu2x settings? Is there anything wrong with it? [https://i.gyazo.com/d8f41065e1b1f9e092aa53d47e12d3ce.png](url)
[video2x_2020-08-15_22-36-14.log](https://github.com/k4yt3x/video2x/files/5081114/video2x_2020-08-15_22-36-14.log)

**Comment by k4yt3x** [comment]
You've set it to cuDNN mode. Do you have cuDNN installed properly?

**Comment by SimplyDex** [comment]
Oh, maybe that's the issue. I thought I already have cuDNN when I updated my driver, is cuDNN a good option or should I use the other ones? I can install it if cuDNN make's it look better.

**Comment by k4yt3x** [comment]
cuDNN doesn't help with quality, only speed. Actually thinking about it I don't remember exactly how much speed improvement you'd be looking at, but I do remember it's pretty significant.

On a side note here, waifu2x-ncnn-vulkan is way faster, while delivering comparable quality. If you're okay with manually adjusting the resolution after upscaling, it would be a better choice.

**Comment by SimplyDex** [comment]
Hm, how do I manual adjust the resolution after upscaling?

**Comment by k4yt3x** [comment]
You'll ether have to use FFmpeg directly or use some editing software like Premiere Pro.

**Comment by SimplyDex** [comment]
Do you know any guides to do it on ffmpeg?

**Comment by k4yt3x** [comment]
> Do you know any guides to do it on ffmpeg?

This?
https://trac.ffmpeg.org/wiki/Scaling
