### ISSUE TITLE
[Feature Request] Demo Output Option that returns 5-10 random slides from a video upscaled using different settings

### ISSUE THREAD

**Issue by anonymousUsers1** [k4yt3x/video2x#324]
## Description

An option that when selected chooses a selection of random slides from a given video and tries up-scaling these using several different  options. These could be user defined or preset defaults. This can act as a demo of what we might expect from different modes, scale ratios, noise levels, etc... 

This could be useful as sometimes it's difficult to tell how a video might fare under different conditions and would prevent wasting time upscaling a video with settings that result in a terrible output. Currently this can be done manually but involves a lot of frequent user input.

**Comment by k4yt3x** [comment]
That sounds like a neat feature to have actually.
