### ISSUE TITLE
Anime4kCPP unavailable in Docker container

### ISSUE THREAD

**Issue by zerotohero** [k4yt3x/video2x#325]
I'm not sure if this is an oversight or not. While the other drivers are included in /video2x/src/dependencies, there is no folder for anime4kcpp in the docker image. I appreciate how easy it is to get the other drivers running under Docker though!

**Comment by k4yt3x** [comment]
Anime4KCPP hasn't been added to the Docker image yet, merely because I haven't been able to compile it successfully on Ubuntu.
I'll try to add it in the next release of the Docker image.
