### ISSUE TITLE
No Progress in Gui and Non-Zero Exit 

### ISSUE THREAD

**Issue by pale2hall** [k4yt3x/video2x#327]
## Component Versions

4.6.0-win32-full

- **Video2X release version**: 
- **Upscaler version**:
- **GUI version**: 2.7.1
- **CLI version**:  4.6.0

## Symptom

When running Video2X I don't see progress in the GUI, but I do see progress in the CLI read-out.  At the end it failed with a non-zero exit status.

## Error Log or Screenshots

[video2x_2020-08-08_12-58-45.log](https://github.com/k4yt3x/video2x/files/5045847/video2x_2020-08-08_12-58-45.log)

I'm eager to help diagnose, but this is my first time trying the software and I'm honestly not very familiar with it.

**Comment by k4yt3x** [comment]
The log is pretty chaotic, but I do see a waifu2x-caffe error. Are you using an NVIDIA GPU?

**Comment by pale2hall** [comment]
Yes, I have a 2080 Super installed.  I am not sure if it was being used.

**Comment by k4yt3x** [comment]
How many processes are you using? I'm trying to figure out why is the log so chaotic.

**Comment by k4yt3x** [comment]
I think this is no longer relevant for the newer versions.
