### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by nekokasumikancolle** [k4yt3x/video2x#330]
![image](https://user-images.githubusercontent.com/52006801/90258215-688e0f80-de72-11ea-9517-33c7f1a143c1.png)
i cant do this because of? i upload 12 video in it.

**Comment by k4yt3x** [comment]
Please attach the log file.

**Comment by nekokasumikancolle** [comment]
> Please attach the log file.

![image](https://user-images.githubusercontent.com/52006801/90468685-3ebe3c80-e141-11ea-9f4d-8fffba773d5e.png)

**Comment by nekokasumikancolle** [comment]
> Please attach the log file.
![image](https://user-images.githubusercontent.com/52006801/90468793-7200cb80-e141-11ea-8a8e-009c65ab899e.png)

@k4yt3x

**Comment by k4yt3x** [comment]
Looks like a driver issue. waifu2x-caffe is NVIDIA exclusive. Do you have an NVIDIA GPU with its drivers installed?

**Comment by nekokasumikancolle** [comment]
i guess i have tho

**Comment by k4yt3x** [comment]
Make sure of it, then try updating your driver.
