### ISSUE TITLE
[Errno 13] Permission denied: 'C:\\Users\\Michael\\Documents\\Code\\video2x-4.6.0-win32-full\\input\\chsichanaeonflux_output.mkv'

### ISSUE THREAD

**Issue by mhan4** [k4yt3x/video2x#331]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**: what is that
- **GUI version**: 2.7.1
- **CLI version**: what is that

## Symptom

Trying to convert a simple .mp4 file

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by SgtBlade** [comment]
I'm not the dev of this program but this probably isn't an issue with the program but with your file permissions. Here are some things you can try.


Make sure the file has it's permission correctly configured. (right click file -> properties -> Security) It should have read permission on all users listed (I always give full control) I have 3 users listed; SYSTEM, Administrators & my personal account/user.

You could also try running the GUI as administrator, that usually helps with these kind of issues

**Comment by k4yt3x** [comment]
You're did not provide sufficient information for me to be able to diagnose the problem.
Please attach the log file or past the logs.
