### ISSUE TITLE
Trouble with upscale using Cudnn - Error Code 3228369022

### ISSUE THREAD

**Issue by greyskull256** [k4yt3x/video2x#332]
Running Windows 10, 64-bit
Nvidia GTX 970
Installed cuda_11.0.3_451.82_win10
Installed cudnn-11.0-windows-x64-v8.0.2.39

Using CPU appears to work however can take over 3 days for some files.

When attempting to use Cudnn once it starts upscale processes they fail with error code 3228369022
-------------------------------------------------------------

[90m2020-08-15 13:08:05.722115 [+] INFO: [upscaler] Subprocess 7264 executing: 'C:\Users\USERNAME\Downloads\video2x-4.6.0-win32-full\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process cudnn --model_dir 'C:\Users\USERNAME\Downloads\video2x-4.6.0-win32-full\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --scale_height 1080 --scale_width 1920 --noise_level 3 --mode noise_scale --output_extention png --input_path 'C:\Users\USERNAME\AppData\Local\Temp\video2x\tmppmiismau\0' --output_path 'C:\Users\USERNAME\AppData\Local\Temp\video2x\tmpi4li2823'[0m
[90m2020-08-15 13:08:05.747760 [+] INFO: Starting progress monitor[0m
[90m2020-08-15 13:08:05.750275 [+] INFO: Starting upscaled image cleaner[0m
[90m2020-08-15 13:08:05.752790 [+] INFO: Main process waiting for subprocesses to exit[0m

Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:00<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:01<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:02<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:03<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:04<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:05<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:06<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:07<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:08<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:09<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:10<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:11<?, ?it/s]
Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:12<?, ?it/s][31m[1m[!] ERROR: Subprocess 10740 exited with code 3228369022[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2020-08-15 13:08:18.985715 [+] INFO: Killing progress monitor[0m

Upscaling Progress:   0%|                                                                                                                                                    | 0/57067 [00:13<?, ?it/s]
[90m2020-08-15 13:08:19.476364 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: C:\Users\USERNAME\AppData\Local\Temp\video2x\tmppmiismau
Cleaning up cache directory: C:\Users\USERNAME\AppData\Local\Temp\video2x\tmpi4li2823
Cleaning up cache directory: C:\Users\USERNAME\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 667, in run
  File "upscaler.py", line 596, in run
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 331, in _upscale_frames
  File "upscaler.py", line 401, in _wait
  File "upscaler.py", line 385, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\USERNAME\\Downloads\\video2x-4.6.0-win32-full\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'cudnn', '--model_dir', 'C:\\Users\\USERNAME\\Downloads\\video2x-4.6.0-win32-full\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--scale_height', '1080', '--scale_width', '1920', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--input_path', 'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\video2x\\tmppmiismau\\0', '--output_path', 'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\video2x\\tmpi4li2823']' returned non-zero exit status 3228369022.

**Comment by k4yt3x** [comment]
1. Enter directory via Explorer: `C:\Users\USERNAME\Downloads\video2x-4.6.0-win32-full\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\`.
1. Double click on `waifu2x-caffe.exe`. This will launch waifu2x-caffe's GUI.
1. Click on the `Check cuDNN` button on the right and waifu2x-caffe will check if cuDNN is installed correctly (I'm not on Windows right now so I'm not 100% sure about the name, but it should be something alike).
1. Refer to the output message of the self-test.

**Comment by greyskull256** [comment]
Thanks for the tip on where to test cuDNN. Looks like i'm missing cudnn64_7.dll
Cudnn v8.0.2.39 for Cuda 11.0 came with cudnn64_8.dll

![image](https://user-images.githubusercontent.com/26423421/90327645-a3637680-df4a-11ea-97b4-be4ef822a997.png)

Looks like i need files from Cudnn v7 and to install Cuda 10 instead?

**Comment by greyskull256** [comment]
downloaded Cudnn v7 for Cuda 10 then threw that one missing dll into my nvidia directory and it seems to have made waifu2x-caffe.exe happy with my cuDNN setup. Will test an upscale now.

**Comment by greyskull256** [comment]
No luck with the upscale using cuDNN during the test, however, I am failing on a different error code now:

[00:26<?, ?it/s][31m[1m[!] ERROR: Subprocess 2336 exited with code 3221226505[0m

**Comment by k4yt3x** [comment]
That error code doesn't mean much. If you've installed cuDNN correctly it should work.
Paste the log or a screenshot so I can take a better look at the error message.

**Comment by greyskull256** [comment]
So what ended up working for me was not using the Driver settings for --scale_height 1080 --scale_width 1920 and instead using the Scale Ratio only from the main screen. For some reason it would fail every time when using manual scale height and width settings on the driver.

**Comment by greyskull256** [comment]
[video2x_2020-08-15_23-26-46.log](https://github.com/k4yt3x/video2x/files/5100409/video2x_2020-08-15_23-26-46.log)
Here's the log of the failed attempt using manual scale height and width if it helps. Using Scale Ratio instead appears to consistently succeed in upscale processes.

**Comment by k4yt3x** [comment]
> [video2x_2020-08-15_23-26-46.log](https://github.com/k4yt3x/video2x/files/5100409/video2x_2020-08-15_23-26-46.log)
> Here's the log of the failed attempt using manual scale height and width if it helps. Using Scale Ratio instead appears to consistently succeed in upscale processes.

I actually can't see why it failed.
