### ISSUE TITLE
rgb24 vs rgba64be

### ISSUE THREAD

**Issue by Inrixia** [k4yt3x/video2x#333]
## Description
Currently ffmpeg is set to extract frames using the rgba64be pixel format, this is very slow and CPU intensive. I have found that rbg24 is significantly faster (for frame extraction) 8x in some cases while giving a result that is identical to using rgba64be. 

Is there a reason that rgba64be is used over rgb24? 
If not then I would like to suggest making rgb24 the default.

**Comment by k4yt3x** [comment]
`rgba64be` is there just to ensure absolutely every bit of color depth is preserved.
Current default settings are tuned towards perfect output instead of optimized for efficiency.
This change may or may not be necessary, I don't have an answer yet at this point.
I'd like to see more discussions around this for a decision to be made.

**Comment by Inrixia** [comment]
I totally agree, if there is a tangible reason to use it I would take the better quality over processing time. Though so far every test I have done when comparing the output frames has been identical.

Maybe someone can think of some format of content to show a difference. Either way its possible to set it manually so no big deal.

**Comment by k4yt3x** [comment]
There will be a difference only if the input file has a pixel color depth greater than 64 bits.

**Comment by k4yt3x** [comment]
I do have a better argument though for the switch. The default output pixel format is now yuv420p for compatibility reasons. This format only preserves 12 bits of color info. Even if all 64 bits of info are preserved during extraction, it will be capped by the final export.
In this way I DO find this switch reasonable.

**Comment by Inrixia** [comment]
Right, but realistically your never going too encounter content higher than 10 or 12 bits right? Prettymuch all SDR content is 8bit Even then most 10/12bit content is already 4k. Unless we aren't talking about colour depth.

So if that's the case technically rgb24 is still overkill?

**Comment by Inrixia** [comment]
@k4yt3x I originally tried yuv420p but that pixel format is not supported by PNG so its gonna default to rgb24 regardless lol
![image](https://user-images.githubusercontent.com/6373693/90499225-65aa5c00-e19d-11ea-9367-5b0aa7077f3c.png)

**Comment by k4yt3x** [comment]
"Sufficient"-wise rgb444le could be enough for most cases, but first I want to make sure the machine learning engine is getting enough color info to make a good output, second I don't know rgb444 well enough to switch to it.

**Comment by k4yt3x** [comment]
I think I can justify the change from rgba64be to rgb24. I'll do that now.

**Comment by k4yt3x** [comment]
Changes have been made in commit https://github.com/k4yt3x/video2x/commit/5621eb306afebbcec40b3abe2b7f6db1f9be04a8

**Comment by k4yt3x** [comment]
Thanks for the suggestion. If you find anything that supports another change to something like rgb444le, please feel free to keep posting in this thread.
