### ISSUE TITLE
ffmpeg deinterlacing support

### ISSUE THREAD

**Issue by Inrixia** [k4yt3x/video2x#334]
## Description
Currently if you want to upscale a interlaced file the ffmpeg settings have to be manually specified, along with output framerate if using yadif=1. Would be nice to have these as options in the interface instead of having to go into the config.

Here is an example of the ffmpeg config I'm using for yadif=1 deinterlacing with the framerate set manually to double the source (50fps)
![image](https://user-images.githubusercontent.com/6373693/90498292-37784c80-e19c-11ea-9194-413249d344b5.png)

**Comment by k4yt3x** [comment]
There has been discussions going on around the topics of deinterlacing and IVTC support in the Telegram group. The thing is, FFmpeg supports a lot of features. We can keep adding features into Video2X to make it "nicer", but at the same time it will mean a lot of extra work on features outside of Video2X's original scope.

However, it will still be nice for users to be able to customize the FFmpeg options. Therefore, the configuration file gives you that liberty.

**Comment by Inrixia** [comment]
Perhaps just having the option to specify additional arguments or modify the commands for each step with your own in the gui would be nice. But I do agree trying to add full fat interface integration with ffmpeg is a bit much

**Comment by k4yt3x** [comment]
About that, here's why additional arguments can't be specified in the GUI: https://github.com/k4yt3x/video2x/issues/292#issuecomment-640418612

**Comment by mirh** [comment]
Deinterlacing is a really big can of worms, and between QTGMC and IVTC it's really better off left to some dedicated tool. 
And I feel like there should be some sort of autodetection that warns the clueless users to avoid running upscaling on such videos.

**Comment by Inrixia** [comment]
Yep, Im using GTGMC with Staxrip now which is significantly better than yadif as a pre processing step. Having a warning about interlaced content is a good idea

**Comment by ghost** [comment]
The deinterlacing issue is what brought me here. I see why it's not done automagically, but seriously, please detect it. The resultant video is far worse than the original when watching it. Video2x produces worse output than the original if the original has not been deinterlaced. Fortunately I aborted after 20 mins into the 4 hour run to see how it was going. Just a few seconds into the output video I could see that it was awful.
