### ISSUE TITLE
Allow exporting just the muxed frames

### ISSUE THREAD

**Issue by Inrixia** [k4yt3x/video2x#336]
## Description
When up-scaling I usually get video2x to just output the muxed frames into a video container to encode using a separate process than the ffmpeg pipeline built into video2x. However there is no option as far as I can tell to stop video2x from attempting to encode and do stream merging, I have just been setting ffmpeg to mux instead of encode but its still a lot of unnecessary IO and I get constant errors with the stream merging stages resulting in the inability to batch process things.

Is there a way or could you make it possible to only output the "intermediate.mkv" file to the output directory and stop there?

**Comment by k4yt3x** [comment]
You could change the stream merging options and choose what to copy:
![image](https://user-images.githubusercontent.com/21986859/90835362-eef79500-e33b-11ea-97a5-de2cdf1d4aca.png)

**Comment by Inrixia** [comment]
That still doesn't let you disable it completely however. I've unchecked every box there and it still attempts to do it. Plus the previous ffmpeg "encoding step" will also run regardless of settings.

What I'm talking about is an option to only output the intermediate.mkv file and not do the encoding and stream merging steps at all

**Comment by k4yt3x** [comment]
The final "stream migration" **should** run regardless of your mapping settings.
The intermediate video that contains only the frames muxed into a video is in a fixed video and container format (libx264 in MKV). The final step is required to convert that into whatever you specify it to output (libx265, MP4, etc.).

**Comment by Inrixia** [comment]
Yea if you actually want all the encoding and muxing to be done by ffmpeg which I don't. I want to be able to take the muxed images in a mkv container and encode it into a format using a process seperate from video2x/ffmpeg, the muxing etc required to create a full video with all audio/subs streams would ofc be manual. But with the current setup to do this you basically have to set ffmpeg to just copy the streams 3 times which when one 20min episode is around 100GB takes forever and is completely pointless.

Ideally just some sort of config option where you can have the upscaling process rename/move the intermediate.mkv file (which just contains the muxed pngs) to the output would be great. That way I can encode using a much better process than what ffmpeg can do, without having to wait hours for 100GB to copy over and over
