### ISSUE TITLE
Command '['C:\\Users\\Administrator\\Desktop\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '12', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'C:\\Users\\Administrator\\Desktop\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\Administrator\\Desktop\\images\\13 (1).jpg', '--output_path', 'C:\\Users\\Administrator\\Desktop\\images\\13 (1)_output.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by sunuping** [k4yt3x/video2x#339]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
![image](https://user-images.githubusercontent.com/36906597/91247998-32ac2d80-e786-11ea-8e0a-459fdf20da47.png)

**Comment by k4yt3x** [comment]
https://github.com/k4yt3x/video2x/wiki/Q&A#waifu2x-caffe-cuiexe-returned-non-zero-exit-status-1
