### ISSUE TITLE
video2x_gui.py requires Python3.8, unnecessarily.

### ISSUE THREAD

**Issue by 13steinj** [k4yt3x/video2x#341]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**: Don't know, not relevant
- **GUI version**: Don't know, not relevant
- **CLI version**: Don't know, not relevant

## Symptom

I'm using the raw Python modules-- nothing in the readme indicates Python 3.8 as a requirement. The only thing that requires 3.8 support is the actual use of the walrus operator a few times in video2x_gui.py. While I'm all for syntactic sugar, I don't think this should be an artificial hard requirement while Python 3.8 is still so relatively new, and isn't the default python3 installation on many linux / mac machines.

Edit: There's also a minimal use of shlex_join in the wrapper submodule, however that can be fixed with the following simple lambda: `shlex_join = lambda split_command: ' '.join(shlex.quote(arg) for arg in split_command)`

Edit: at a very minimum make this known somewhere in the readme.

## Error Log or Screenshots

![image](https://user-images.githubusercontent.com/10525230/91490219-17bde400-e880-11ea-8c52-4b99fbb46186.png)

**Comment by k4yt3x** [comment]
You're right that it doesn't have to be written with Python 3.8, but it also doesn't have to be written with Python 3.7 or 3.6.
My philosophy in using 3.8 is that if the language has a newer version that provides more features, why not using it?

As for compatibility issues, it can be addressed easily by running the released PE files. The source code is intended for development and advanced users only. i.e., if you're running from source, I'll assume that you're willing to deal with the trouble that comes with it.

You are right about the part that I should include the version information somewhere in the README. I'll do it now.

**Comment by k4yt3x** [comment]
Actually I just checked it. The version number is already mentioned in this file: https://github.com/K4YT3X/video2x/wiki/Run-From-Source-Code

**Comment by 13steinj** [comment]
@k4yt3x that wiki page is a bit of an unnecessary hunt to find the prerequisite whereas the readme only mentions Python3. It's as simple as changing "3" to "3.8+" on this line.

> Video2X is a video/GIF/image upscaling software based on Waifu2X, Anime4K, SRMD and RealSR written in Python 3.

Further, I accept your philosophy, though I and many others would heavily disagree with it.

> My philosophy in using 3.8 is that if the language has a newer version that provides more features, why not using it?

Because when the new features aren't necessary, you open people up to a forced upgrade if they want to use your software, whereas traditionally software stays the same version for months if not years. The features added in the new version that you *use* are so minuscule that you can fix them with two `sed` commands, It's a different story if say, you were using some fancy high-precision statistics / random method added in the math standard library.

It's a strangely unnecessary hardship. Or at least, have some form of version check in-code at startup / download time when you don't specify the version in clean, right in front of the eyes documentation) to go through a program and find out after you start running it that you have to change it and restart to get it to work.

**Comment by k4yt3x** [comment]
You do have some good points there, but is it really worth it to sacrifice benefits of the newer versions for backwards compatibility? Most users are expected to run the executable file from the release, and Linux/macOS users are expected to run the Docker container. Running from source, from what I see, is only for developers and advanced users who are willing to fiddle with things such as the Python versions.

**Comment by 13steinj** [comment]
> You do have some good points there, but is it really worth it to sacrifice benefits of the newer versions for backwards compatibility?

I mean, it depends on what those benefits are. I could understand if there was a significantly large feature added that the author / maintainers decide to use, however, at the time of making the issue (and now assuming you didn't add any more 3.8 features), the only 3.8 features you used were assignment expressions, which were syntactic sugar, 

The general rule is to support the versions of the language that are still supported, assuming not large feature of the most recent version is necessary. For example, Python 3.4 is EOL, so I'm not gonna fault anyone for using a Python 3.5 feature.

However, Python 3.6[.5] isn't expected to be EOL until after the first few months of 2022, according to the PEP, and making the small modifications I mentioned would allow Python 3.6 support.

> Running from source, from what I see, is only for developers and advanced users who are willing to fiddle with things such as the Python versions.

Not really, plenty of people run from source all the time, mostly because of security paranoia (ability to audit the code that's running, there's no guarantee that your release does what it says it does). Further, there are plenty of users that wouldn't call themselves developers or even advanced users, but still run from source in order to make incredibly minor changes-- for example, the way that "ffmpeg" is looked for on windows assumes that the only thing starting with "ffmpeg" in that directory is "ffmpeg.exe", however, the standard [@m-ab-s/media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite) also builds a "ffmpeg" link meant only to be used internally by the build process (as well as later on, if you wanted to use ffmpeg from within mingw).

But most of all, some people just don't want bloat on their systems. In using the binary, there is an extra download of *at least* Python (in fact, I believe the 32 bit version at that), and maybe even an extra download of the necessary libraries (I'm unfamiliar of the build options you have at your disposal / which you use). If the standard user used programs like this, their hard drive would be filling up with embedded versions of Python every time, whereas instead they could simply install Python, then download the master branch and run the main file.

In fact this is to some extent, the entire point of the fact that in Python you can make packages that install scripts. Then you release your package, and people can just do a `pip install`, some even get a graphical user interface. Then your binary release, if you choose to do so, for those other users, uses the pip package.

**Comment by k4yt3x** [comment]
I think you have a fair point. I have therefore removed all invocations of the walrus operator and `shlex.join` in the program.

- https://github.com/k4yt3x/video2x/commit/107d31e5dcb8afa6389e8743993617cc8d37cd64
- https://github.com/k4yt3x/video2x/commit/227cf54a478d1099f79386df774824ec39e15191

Thank you for caring about this project and your persistence.
