### ISSUE TITLE
Command '['C:\\Users\\019-3094786\\Desktop\\video2x-4.6.0-win32-full\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'C:\\Users\\019-3094786\\Desktop\\video2x-4.6.0-win32-full\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\019-3094786\\AppData\\Local\\Temp\\tmpj2h8hs4e\\0', '--output_path', 'C:\\Users\\019-3094786\\AppData\\Local\\Temp\\tmppuj72vcg']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by y0gur7** [k4yt3x/video2x#342]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:2.7.1
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
You've provided no logs and no detailed descriptions of the issue.
