### ISSUE TITLE
Error: Gifski Option formatting

### ISSUE THREAD

**Issue by RomanKode** [k4yt3x/video2x#343]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: Latest git
- **Upscaler version**:4.2.2
- **GUI version**:2.7.1
- **CLI version**:4.2.0

## Symptom

The python program seems to be formatting gifski commands and options with quotes in them. and that does not allow wildcards to be read.

## Error Log or Screenshots

```
[+] INFO: Converting extracted frames into GIF image
2020-08-29 00:01:17.225997 [+] INFO: Executing: ['/usr/bin/gifski', '-o', '/home/uramn/Pictures/openwallpaper/fadcb24075acb650de29f258af69d830_output.gif', '--fps', '17', '--fast', '--quality', '100', '/home/uramn/.local/share/video2x/tmp/video2x/tmp8koheu_n/extracted_*.png']
2020-08-29 00:01:17.229988 [+] INFO: Main process waiting for subprocesses to exit
error: Unable to find the input file: "/home/uramn/.local/share/video2x/tmp/video2x/tmp8koheu_n/extracted_*.png"
The path contains a literal "*" character. If you want to select multiple files, don't put the special wildcard characters in quotes.
[!] ERROR: Subprocess 95498 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Cleaning up cache directory: /home/uramn/.local/share/video2x/tmp/video2x/tmpcobegxbz
Cleaning up cache directory: /home/uramn/.local/share/video2x/tmp/video2x/tmp8koheu_n
Cleaning up cache directory: /home/uramn/.local/share/video2x/tmp/video2x
Traceback (most recent call last):
  File "./video2x_gui.py", line 104, in run
    self.fn(*self.args, **self.kwargs)
  File "/home/uramn/.local/share/video2x/src/upscaler.py", line 669, in run
    raise e
  File "/home/uramn/.local/share/video2x/src/upscaler.py", line 609, in run
    self._wait()
  File "/home/uramn/.local/share/video2x/src/upscaler.py", line 403, in _wait
    raise e
  File "/home/uramn/.local/share/video2x/src/upscaler.py", line 387, in _wait
    raise subprocess.CalledProcessError(process_status, process.args)
subprocess.CalledProcessError: Command '['/usr/bin/gifski', '-o', '/home/uramn/Pictures/openwallpaper/fadcb24075acb650de29f258af69d830_output.gif', '--fps', '17', '--fast', '--quality', '100', '/home/uramn/.local/share/video2x/tmp/video2x/tmp8koheu_n/extracted_*.png']' returned non-zero exit status 1.
QPixmap::scaled: Pixmap is a null pixmap
```

![Screenshot_20200829_004742](https://user-images.githubusercontent.com/70252656/91628794-68713200-e991-11ea-9e62-dc16496a3a4d.png)
Kubuntu 20.04.1

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
> error: Unable to find the input file: "/home/uramn/.local/share/video2x/tmp/video2x/tmp8koheu_n/extracted_*.png"
> The path contains a literal "*" character. If you want to select multiple files, don't put the special wildcard characters in quotes.

This seems to be the problem. Gifski works great in Windows. I wonder if path name expansion works differently in Linux.

**Comment by k4yt3x** [comment]
I did not explicitly put the path in quotes. Rather, I fed the list directly into subprocess, and it did whatever it did to make this issue occur.
I'll check on this later when I return to Linux to see how I can fix this thing.

**Comment by 1349422030** [comment]
I using windows and powershell to pass through the params, and i meets this problem.

when i change the variable to "Simple String txt", it works, but do not works with variable,.

this makes big trouble for script writing.
