### ISSUE TITLE
Incorrect output_quality parameter used with waifu2x-caffe (JPG mode)

### ISSUE THREAD

**Issue by STribbey125** [k4yt3x/video2x#348]
## Component Versions

- **Video2X release version**: 4.6.0
- **GUI version**: 2.7.1

## Symptom

Specifically when starting from the GUI, waifu2x-caffe-cui seems to always be passed the value 8 for output_quality regardless of the respective GUI setting.

This issue does not occur with the CLI.

## Error Log or Screenshots

![cli](https://user-images.githubusercontent.com/16655817/92163484-c7a3cc00-ee01-11ea-8425-616d08a79bd0.png)
![gui](https://user-images.githubusercontent.com/16655817/92163489-c96d8f80-ee01-11ea-96ee-ec3ca1c4c9ea.png)
[YAML settings](https://github.com/k4yt3x/video2x/files/5170986/settings.txt)

**Comment by k4yt3x** [comment]
Will investigate

**Comment by k4yt3x** [comment]
Yeah you are right. There's a typo here. I'll fix in a later release.
\If you want this patched right now, check out this nighly build: https://github.com/k4yt3x/video2x/actions/runs/238956805

![image](https://user-images.githubusercontent.com/21986859/92205074-71bc3c00-ee74-11ea-857f-1a05eaaef7b1.png)
