### ISSUE TITLE
can't run video2x

### ISSUE THREAD

**Issue by unmellow** [k4yt3x/video2x#349]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.6.1
- **Upscaler version**:waifu2x-ncnn-vulkan:20200606-1
- **GUI version**: 4.6.1?
- **CLI version**: 4.6.1?

## Symptom
I'm on Manjaro 
when i run video2x.py
I get this error

## Error Log or Screenshots

```
~/video2x-4.6.1/src via 🐍 v3.8.5
❯ sudo python3.8 video2x.py
Traceback (most recent call last):
  File "video2x.py", line 53, in <module>
    from upscaler import AVAILABLE_DRIVERS
  File "/home/meltonmb/video2x-4.6.1/src/upscaler.py", line 48, in <module>
    language = gettext.translation(DOMAIN, LOCALE_DIRECTORY, [default_locale], fallback=True)
  File "/usr/lib/python3.8/gettext.py", line 583, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.8/gettext.py", line 554, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.8/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.8/locale.py", line 401, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
⏎
```

**Comment by k4yt3x** [comment]
Before I get into the error, why are you using sudo?

**Comment by k4yt3x** [comment]
Ok thanks for checking. Let's take a look at the error now then.

It looks like something went wrong when the script tries to get translation for your locale.
Theoretically this line should fallback into English if your locale is not supported. Something, however, went wrong internally inside of the gettext module which is not a part of Video2X.

```python
language = gettext.translation(DOMAIN, LOCALE_DIRECTORY, [default_locale], fallback=True)
```

What locale are you using?
You can get the exact answer by executing the following commands in a Python interactive terminal.

```python
import locale
locale.getdefaultlocale()
```

![image](https://user-images.githubusercontent.com/21986859/92255263-95f23a00-eec1-11ea-88e3-2f12cc69e5c9.png)

**Comment by unmellow** [comment]
So I didn't have a locale at all
I set one and now it works 
thanks 
IDK how I forgot to set a locale

**Comment by k4yt3x** [comment]
Oh ok glad it works.
