### ISSUE TITLE
ffmpeg file not found

### ISSUE THREAD

**Issue by unmellow** [k4yt3x/video2x#350]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.2.0
- **Upscaler version**:idk
- **GUI version**:idk
- **CLI version**:idk

## Symptom
I put the path to ffmpeg in the config
as `/usr/bin/ffmpeg`
which I know is the correct path to ffmpeg
but it's saying it can't find the file
so how do I format the path and can you put an example in the 
[run from source guide?](https://github.com/k4yt3x/video2x/wiki/Run-From-Source-Code)
Or do I have an incompatible ffmpeg version?

## Error Log or Screenshots
`❯ python3.8 video2x.py -d waifu2x_ncnn_vulkan -i ~/dwhelper/2ce1d4cff2442e96b97793b72cda5179c39e5c18.mp4.mp4 -o ~/Videos/output.mp4

    __      __  _       _                  ___   __   __
    \ \    / / (_)     | |                |__ \  \ \ / /
     \ \  / /   _    __| |   ___    ___      ) |  \ V /
      \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
       \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
        \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

                  Video2X Video Enlarger

                       Version 4.2.0

2020-09-04 18:20:01.660569 [+] INFO: Redirecting console logs to /home/meltonmb/video2x/src/video2x_2020-09-04_18-20-01.log
[+] INFO: Loading files into processing queue
2020-09-04 18:20:01.695353 [+] INFO: Input path(s): /home/meltonmb/dwhelper/2ce1d4cff2442e96b97793b72cda5179c39e5c18.mp4.mp4
[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path
[!] ERROR: Please check the configuration file settings
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 261, in <module>
    upscaler.run()
  File "/home/meltonmb/video2x/src/upscaler.py", line 515, in run
    self._check_arguments()
  File "/home/meltonmb/video2x/src/upscaler.py", line 215, in _check_arguments
    raise FileNotFoundError(self.ffmpeg_settings['ffmpeg_path'])
FileNotFoundError: /usr/bin/ffmpeg
⏎
video2x/src on  master [!] via 🐍 v3.8.5
❯ /usr/bin/ffmpeg
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'`

**Comment by k4yt3x** [comment]
You'll have to change FFmpeg's path in the config file.

**Comment by unmellow** [comment]
i did it says file not found and the path to my ffmpeg our did i put it in incorrectly?

**Comment by unmellow** [comment]
so the issue was me putting the path to the ffmpeg executible in video2x.yaml 
and not the path to the folder that contained ffmpeg 
thanks idk why i didn't understand the error message

**Comment by k4yt3x** [comment]
Yeah maybe I should change the way that config works and just separate FFmpeg path and FFprobe path into two key/value pairs. This is a bit confusing, but it's like so because it's easier for Windows releases when this software wasn't Linux-compatible.

**Comment by unmellow** [comment]
that or just add an error message along the lines of
"FFmpeg not found make sure you put the path to the folder that contains ffmpeg in the config"
but in more elegant terms
