### ISSUE TITLE
"out of memory"

### ISSUE THREAD

**Issue by arkomega** [k4yt3x/video2x#351]
## Component Versions

- **Video2X release version**: 4.6.1-win32-full
- **Upscaler version**: I don't know xd
- **GUI version**: 2.7.2
- **CLI version**: 4.2.0

## Symptom

Uh i tried to upscale a 720p video to 4K and i get errors and i don't know how to fix it
**I have a lot of disk space avaible, and i have 6gb of ram avaible when i tried**
Also, i updated all of my drivers, my nvidia driver is working perfectly.

## Error Log or Screenshots

![git](https://user-images.githubusercontent.com/67123792/92307805-3a937b00-ef99-11ea-9476-0d7fd60b11f3.png)

**Comment by arkomega** [comment]
Ok i fixed it i just changed the number of threads

**Comment by arkomega** [comment]
Fixed.

**Comment by k4yt3x** [comment]
I suggest using only one process for machine-learning based drivers.
