### ISSUE TITLE
cuDNN fails with waifu2x-caffe

### ISSUE THREAD

**Issue by Ersikan** [k4yt3x/video2x#353]
## Component Versions

- **Video2X release version**: 2.7.2
- **Upscaler version**: 4.2.2
- **GUI version**: 2.7.2

## Symptom

waifu2x-caffe driver fails with this message:

```
F0910 14:02:00.431798  3976 cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
```

This happens in `cudnn` **AND** `gpu` mode.

waifu2x-caffe gui says that cuDNN is ready to be used when checking installation.

## Error Logs

waifu2x-caffe log:

```
Log file created at: 2020/09/10 14:02:00
Running on machine: XXXX
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0910 14:02:00.431798  3976 cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
```

[video2x log](https://pastebin.com/w6D10eYQ)

**Comment by k4yt3x** [comment]
Looks like a driver issue. Try updating your GPU driver.
