### ISSUE TITLE
[+] INFO: Killing progress monitor and Time Travel

### ISSUE THREAD

**Issue by EstebanZapataME** [k4yt3x/video2x#354]
## Component Versions

- **Video2X release version**: 4.6.1
- **Upscaler version**: 4.2.2
- **GUI version**: 2.7.2

## Symptom

I just downloaded the Program from Github.

After starting with a short video using the "Waifu2X NCNN Vulkan" Driver with the GUI, and default settings (besides the Driver choice) I saw that the "Time Elapsed" and "Time Remaining" values were off, since they marked that the process had been started almost a full day ago (23:59:40ish) and the "Rate (FPS)" value was going into the negatives, maxing out at -13 when the job finished.

When all jobs finished, it displayed a Finished time of -17.97829 seconds.

Output video works fine and looks as expected.

## Error(?) Log

[video2x_2020-09-12_18-23-30.log](https://github.com/k4yt3x/video2x/files/5213111/video2x_2020-09-12_18-23-30.log)

The log file is presented as is, no modifications made to it.

**Comment by k4yt3x** [comment]
That's interesting, I've never seen something like that before.
I'm actually not quite sure what's causing the problem.
Only the GUI is exhibiting this behavior right?

**Comment by k4yt3x** [comment]
This issue is a bit dated. I still can't seem to reproduce this error, nor have I seen any other reports like this one.
Could you please confirm that this issue still exists in the newest version?
I'll reopen this issue if it's still a problem,
