### ISSUE TITLE
Command '['D:\\video2x-4.6.1-win32-full\\dependencies\\anime4kcpp\\CLI\\Anime4KCPP_CLI\\Anime4KCPP_CLI', '--passes', '2', '--pushColorCount', '2', '--strengthColor', '0.3', '--strengthGradient', '1.0', '--zoomFactor', '2.0', '--threads', '16', '--preFilters', '4', '--postFilters', '40', '--HDNLevel', '1', '--platformID', '0', '--deviceID', '0', '--codec', 'mp4v', '--forceFps', '0.0', '--input', 'C:\\Users\\dEN5\\AppData\\Local\\Temp\\video2x\\tmp5o1k661a', '--output', 'C:\\Users\\dEN5\\AppData\\Local\\Temp\\video2x\\tmp24utjo72']' returned non-zero exit status 3221225785.

### ISSUE THREAD

**Issue by dEN5-tech** [k4yt3x/video2x#355]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
There isn't enough information in this message.
Please attach your error log.
