### ISSUE TITLE
Add support for butterflow

### ISSUE THREAD

**Issue by k4yt3x** [k4yt3x/video2x#359]

**Comment by Tsubajashi** [comment]
Any Updates on it? just want to make sure, im currently figuring out how your software works when it comes to code so i can help improving it by a bit.
my skills are my no means great, but i hope i can help good.

**Comment by k4yt3x** [comment]
Support for Butterflow is quite easy to add. I'm waiting on an official dain-ncnn-vulkan release to get started on the upscaler redesign. Since v2x only had upscaling in mind, it will require a major redesign of the framework, which is time-consuming.
I'll probably have time to work on that around Christmas since I'm really busy with school right now.
