### ISSUE TITLE
Add support to copy over multiple audio streams and subtitles

### ISSUE THREAD

**Issue by AusNaminator** [K4YT3X/video2x#36]
Is it possible to add the ability to copy over multiple audio streams (for dvd rips with commentary tracks etc), subtitles and chapter markers over to the upscaled video file?

**Comment by K4YT3X** [comment]
Yes it is **possible**, but it will require a lot of work and debugging.
If someone can help me out and submit some pull requests, it will make it more feasible in terms of time.

**Comment by cr08** [comment]
With the current ffmpeg implementation, the info I've posted over in #24 towards the bottom should suffice. I want to get my own private fork set up first for some of my own custom modifications but once I do I'll try and test that addition and file a PR.

**Comment by K4YT3X** [comment]
The newest version now supports copying over audio streams and subtitles.
