### ISSUE TITLE
Redesign upscaler, GUI and CLI for frame interpolation features

### ISSUE THREAD

**Issue by k4yt3x** [k4yt3x/video2x#360]

**Comment by kelvinnkat** [comment]
Is there much going on in regards to the projects for version 5.0.0?

**Comment by k4yt3x** [comment]
@kelvinnkat there are some components that still are being finalized. Once those are done, 5.0.0 should be ready to be released. I am not sure about the exact dates, but I'm hoping to get enough time to work on it around Xmas.
