### ISSUE TITLE
waifu2x-caffe error

### ISSUE THREAD

**Issue by SCHOOLAAD** [k4yt3x/video2x#361]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**: Waifu2X Caffe? is this what you mean
- **GUI version**: 2.8.0
- **CLI version**: what?

## Symptom

I don't know it's not working? that's all I know

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5249655/video2x_error.log)

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
https://github.com/k4yt3x/video2x/wiki/Q&A#waifu2x-caffe-cuiexe-returned-non-zero-exit-status-1

**Comment by SCHOOLAAD** [comment]
I do indeed have a Nvidia graphics card and I am running GeForce Game Ready Driver Version 452.06

**Comment by k4yt3x** [comment]
Hmmm from your log it looks like a driver issue.
Could you please try upscaling one single image using waifu2x-caffe?

**Comment by SCHOOLAAD** [comment]
I have used waifu2x-caffe on a single image like a week ago, although not the copy included in video2x full, when I tried that one it said that the split size was possibly too large.

**Comment by k4yt3x** [comment]
The copy included in Video2X's 4.7.0 release is quite new. Take a look and see if the newest version still runs fine.

**Comment by SCHOOLAAD** [comment]
Hello k4yt3x, the problem also occurs when using a copy of waifu2x-caffe downloaded straight from the releases page on its github, so it isn't video2x's fault, sorry.

**Comment by k4yt3x** [comment]
I also have 452.06, not quite sure why it's not working for you.
You can try using a older release or waifu2x-caffe right now.
You can also join the telegram group, some in that group might know what's wrong.

**Comment by SCHOOLAAD** [comment]
I'm sorry, but I don't have a telegram I'll see wgen I can use the pc next.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by k4yt3x** [comment]
I was just reading waifu2x-caffe's release notes:

> CUDA Toolkitを11.0に更新(同梱しているdllも更新)
> cuDNNをv8.0.3に更新(同梱しているdllも更新)
> CUDA Toolkitを更新した影響でGPUの要求環境をCompute Capability 3.5以上に変更

Which roughly translates to:

> Upgraded CUDA Toolkit to 11.0 (also the bundled DLLs)
> Upgraded cuDNN to v8.0.3 (also the bundled DLLs)
> CUDA Toolkit's upgrade requires GPU runtime environment to have Compute Capability 3.5 or higher

This should be the cause of the problem.
