### ISSUE TITLE
waifu2x-ncnn-vulkan error

### ISSUE THREAD

**Issue by ramzymbk** [k4yt3x/video2x#364]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5253171/video2x_error.log)
## Component Versions

- Video2X 4.7.0 :
- Upscaler version: latest:
- GUI version 2.8.0:
- CLI version 2.3.0:

## Symptom

Command '['C:\\Users\\X\\Desktop\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\X\\Desktop\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-i', 'C:\\Users\\X\\AppData\\Local\\Temp\\video2x\\tmpo1c5h3eo', '-o', 'C:\\Users\\X\\AppData\\Local\\Temp\\video2x\\tmp7gwjli1f']' returned non-zero exit status 4294967295.

**Comment by k4yt3x** [comment]
Please attach the error log.

**Comment by ramzymbk** [comment]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5267418/video2x_error.log)

**Comment by k4yt3x** [comment]
Hmm sorry I didn't see the reply in time. Please reopen if you're still having problems with 4.8.1.
