### ISSUE TITLE
Upscale from 720p to 4k On AMD Pc

### ISSUE THREAD

**Issue by Gamescomjk** [k4yt3x/video2x#367]
Specs 
RX 580
Amd Ryzen 5 2600
16 Gb Ram
 
And here is log file
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5257614/video2x_error.log)

**Comment by k4yt3x** [comment]
This following command ran into an error. I can't see any FFmpeg error messages. I'll suggest trying to extract the frames manually to see what actually went wrong.

```shell
ffmpeg -hwaccel auto -y -i C:\Users\dearb\Downloads\y2mate.com - Minecraft Speedrunner VS 4 Hunters_7BCojznmtRE_720p.mp4 -pix_fmt rgb24 C:\Users\dearb\AppData\Local\Temp\video2x\tmpwn9smzkq\extracted_%0d.png
```

**Comment by k4yt3x** [comment]
Optionally you can also try disabling hardware acceleration
