### ISSUE TITLE
Anime 4k error

### ISSUE THREAD

**Issue by Nitheshspeedy** [k4yt3x/video2x#368]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **2.8.0**:
- **Upscaler version**:
- **4.7.0**:
- **CLI version**:

## Symptom

I tried to upscale 1080p to 4k.

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5262701/video2x_error.log)

**Comment by k4yt3x** [comment]
Looks like a duplicate of
