### ISSUE TITLE
Upscaling keeps failing.

### ISSUE THREAD

**Issue by Khrysostamos** [k4yt3x/video2x#369]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5267231/video2x_error.log)

![Screenshot (371)_LI](https://user-images.githubusercontent.com/71761156/94026869-ceb06f80-fdec-11ea-9594-6c075ce49ce0.jpg)

I just downloaded the application and I don't think I'm doing anything wrong since I've tried not tweaking the settings of the dependencies and this still happened. This always happens at the end during upscaling. Just in case you're are asking, I've installed the latest versions of both Cuda Toolkit and cuDNN.

The only thing I have changed is the is output video extension.

**Comment by k4yt3x** [comment]
Do you have the error log?

**Comment by k4yt3x** [comment]
Something's wrong with the logging system. It's not redirecting `sys.stderr` correctly on Windows. I'll take a look at what's wrong.

**Comment by k4yt3x** [comment]
If this is still happening please reopen this issue.
