### ISSUE TITLE
After completing an upscale the temporary files aren't being deleted

### ISSUE THREAD

**Issue by AusNaminator** [K4YT3X/video2x#37]
I'm not sure if it is supposed to but the extracted frames images aren't being deleted from my temp folder. Is it possible to change the temp folder location to say perhaps a different hard drive?

**Comment by K4YT3X** [comment]
I'm noticing similar things as well. The temp folders aren't deleted, especially if the program throws an exception. I should make a `except` statement wrapping the whole program, so in case the program fails, the garbages will be purged.

As for now, the temp folder is generated by `tempfile.mkdtemp`.
Should I just make a value in the config file that will allow you to specify where the temp folder is?

**Comment by AusNaminator** [comment]
Adding a value to the config file would be ideal because my SSD has limited space.

**Comment by K4YT3X** [comment]
@AusNaminator I have added the function to specify the cache folder location. You can also choose to preserve the extracted/upscaled frames.
