### ISSUE TITLE
ffmpeg.zeranoe.com is no longer in operation

### ISSUE THREAD

**Issue by donicrosby** [k4yt3x/video2x#372]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 2.8.0
- **Upscaler version**: N/A
- **GUI version**: 2.8.0
- **CLI version**: N/A

## Symptom

ffmpeg.zeranoe.com has shut down and is no longer available the video2x_setup.py (possibly the video2x_setup_ubuntu.py as well) is currently broken with it gone,

## Error Log or Screenshots

N/A this isn't really a Video2X CLI/GUI issue...
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Thanks for the notification. I'm working on it right now.
I think I'll use gyan.dev's builds from now on.

**Comment by k4yt3x** [comment]
I've just pushed commit https://github.com/k4yt3x/video2x/commit/b37acfa31d505084009e7746b6f3af3d789334ea which changed the provider to gyan.dev. Try it out.
