### ISSUE TITLE
BSOD irql_not_less_or_equal when rendering over long periods

### ISSUE THREAD

**Issue by PhoenixHSC** [k4yt3x/video2x#376]
- 4.7.0
- Waifu2x-Caffe
- GUI Version 2.8.0

## Symptom

When trying to use Video2x over periods longer than 2 hours, I get a blue screen of death with the error message "irql_not_less_or_equal". I'm not sure if anyone else has encountered this issue. I'm running on a GTX 2070, zen 2700x 16GB RAM with all my drivers updated. 

## Error Log or Screenshots

IRQL_NOT_LESS_OR_EQUAL (a)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If a kernel debugger is available get the stack backtrace.
Arguments:
Arg1: ffff8000000003a0, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000001, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff8000ce49f82, address which referenced memory

**Comment by k4yt3x** [comment]
I'm not sure what's causing this exactly. I've seen IRQL_NOT_LESS_OR_EQUAL in all kinds of situations, including but not limited to faulty/incompatible RAM, memory starvation, malfunctioning drivers.

Video2X doesn't deal with these lower level stuff theoretically as a superglue written in Python. I think it's more likely that the issue lies within your hardware setup and/or your resource usage.

**Comment by PhoenixHSC** [comment]
Is memory starvation likely with 16GB RAM?

**Comment by k4yt3x** [comment]
16GB RAM should be fine, usually GPU VRAM is more important. RTX 2070 should have 8GB of VRAM, which should be fine.
I think it's more likely a driver issue or an API issue. I would suggest the following actions:

- Try to upgrade your GPU driver to the newest version temporarily to see if the issue remains.
  - If it is not possible, or if it doesn't work, then:
- Try to see if you encounter the same problem with waifu2x-ncnn-vulkan.

**Comment by PhoenixHSC** [comment]
Alright I'll try that. On another note, do you have any plans of integrating Dandere2x with video2x? Its a faster version of waifu2x.

https://github.com/aka-katto/dandere2x/

**Comment by k4yt3x** [comment]
I know that project. It actually uses some of Video2X's code. I'm not sure it's an easy task to pull that project apart and stuff it into V2X'a framework, and I don't, currently, have the luxury of time to work on it either.

So my answer is, I'm not sure if nor when it will happen.
