### ISSUE TITLE
Downscaling is extremely slow when scale ratio is a non-integer

### ISSUE THREAD

**Issue by RedStine** [k4yt3x/video2x#377]
-Video2X 4.7.0
-GUI 2.8.0

Lanczos downscaling is extremely slow when the scale ratio is a non-integer, like when converting from 480p to 1080p (scale ratio = 2.25). This happens with any driver. It only takes seconds when the scale ratio is an integer, but takes hours when it isn't.
Using Ryzen 3700x, 32GB ram.

![Screenshot_15](https://user-images.githubusercontent.com/25717589/95010541-c4ae1e00-05ef-11eb-90f4-927a4aa10cdf.png)

**Comment by k4yt3x** [comment]
It is supposed to. These machine-learning-based drivers are trained with models that only support one or more fixed upscaling ratios. For example, waifu2x-ncnn-vulkan supports only 2x. In this case, when you request 2.25x, what happens is the frame gets 2x, then 2x again to a total of 4x, then downscaled using Lanczos to 2.25x.

You can look at #300 for more details.

**Comment by mirh** [comment]
There seems to be some problem with threading though. 
Downscaling doesn't really seem to be using more than a single core (or maybe two at most)
Even 21K frames should be a relative breeze for a 8 core ryzen cpu

**Comment by k4yt3x** [comment]
That's also a known issue. This process will be multi-threaded in the next release.
