### ISSUE TITLE
First time user error messages.

### ISSUE THREAD

**Issue by SimonBuysse** [K4YT3X/video2x#38]
Just followed the tutorial everything was smooth but on my try out video I get these errors, it does not crash tho. (video was 480p mp4 to 1080p mp4.
![index](https://user-images.githubusercontent.com/10955886/53301247-aa776000-3850-11e9-86ef-01df1245cdc8.png)

**Comment by K4YT3X** [comment]
Do you have the full log or could you please share the input video?
I can't get too much information from this screenshot. I need to know which section went wrong and what was being executed.

**Comment by SimonBuysse** [comment]
How would I send you a private link to the file, its also NSFW video fyi :p

**Comment by SimonBuysse** [comment]
I tried another video and it worked fine so its probably the video itself.

**Comment by K4YT3X** [comment]
I have recently added the "migrate audio tracks and subtitles" feature. I wonder if that's what's going wrong.

**Comment by cr08** [comment]
Looks like it is happening during the stage the input file is being processed into individual frames as it is decoding the original video. And these are ffmpeg's own error messages indicating something is up with the original file. Not necessarily anything wrong or directly involving video2x.

If you let the entire thing process does it complete properly or does it fail in some way?

**Comment by SimonBuysse** [comment]
Yes @cr08 you are right. I did some editing on my own with just ffmpeg and I always get an error ( I tried extracting images out of the video). So its def not a problem related to video2x but with ffmpeg. The process for me did end up getting stuck.

When I tried doing my own thing with the video some of the images I retrieved were corrupted. Since then I found another source of the same video and its working just fine now. I'm not going to look into it further for now cause I won't know how to bug test further anyway.

**Comment by K4YT3X** [comment]
Ok I see. If this issue continues to come up with other videos, then I'm going to take a deeper look into it. As for now though, it looks like it's a video problem that's not related to video2x.

I'm going to close this issue, but feel free to reopen or open a new issue if you encounter similar problems with other videos.
