### ISSUE TITLE
C:\Users\****\AppData\Local\video2x\ffmpeg-latest-win64-static\bin

### ISSUE THREAD

**Issue by Pk555555** [k4yt3x/video2x#380]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5358228/video2x_error.log)

**Comment by k4yt3x** [comment]
Which version are you using?

**Comment by Pk555555** [comment]
video2x 4.7.0 light

**Comment by k4yt3x** [comment]
If you use the light version, be aware that the old provider used in 4.7.0 is no longer in operation. See #372 for more details.
Please use the latest setup script (which is not yet in a release) or use the full version.
The setup script will be updated in a future release.
