### ISSUE TITLE
Subprocess execution ran into an error

### ISSUE THREAD

**Issue by Pk555555** [k4yt3x/video2x#381]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**: 4.7.0 full
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
<img width="989" alt="Capturar2" src="https://user-images.githubusercontent.com/60222764/95674348-0443af80-0b86-11eb-8f3a-60d27c9103bf.PNG">
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5360799/video2x_error.log)

**Comment by k4yt3x** [comment]
You may need to update your GPU driver.

**Comment by Pk555555** [comment]
I have the latest version of both the video card and the windons installed...

**Comment by k4yt3x** [comment]
The newest version of waifu2x-caffe requires cuDNN 8 instead of 7 in the older versions. Are you sure you have the right version?

**Comment by Pk555555** [comment]
yes...
video2x 4.7.0 full
<img width="93" alt="Capturar" src="https://user-images.githubusercontent.com/60222764/95703400-5ee01880-0c25-11eb-9f31-02fcb34ea791.PNG">

**Comment by k4yt3x** [comment]
Actually you're not using cuDNN so that's fine. I saw a cuDNN error message so I thought you were using waifu2x-caffe in cuDNN mode. I got your case confused with another issue's case. I see that you're using multiple processes, which is unnecessary. Multi-processing doesn't benefit ML-based solutions much. It does, however, benefit Anime4KCPP much since it's a traditional non-ML algorithm.

Unfortunately the logging system is malfunctioning after I changed the way it works the last time. I'll need to fix that so I can see the stderr stream. From what I can see so far, it still seems to be a driver issue.

- What is your GPU driver version?
- What GPU do you have?

**Comment by Pk555555** [comment]
456.71
GTX 1660 Super

**Comment by k4yt3x** [comment]
I checked your card's Compute Capability and everything looks fine. This card should be capable of running this version of waifu2x-caffe, theoretically.
Does Video2X 4.6.0 work for you? That version contains an older version of waifu2x-caffe.

**Comment by Pk555555** [comment]
I never used this version but I will try to use it.

**Comment by Pk555555** [comment]
I'm using version 4.6.0 and so far it's going well but it's VERY slow it's been 15 hours and it has only advanced 5%

**Comment by k4yt3x** [comment]
It IS a driver issue then. Your current environment isn't compatible with the newest version of waifu2x-caffe some how. Here are some options:

1. Replace the `dependencies/waifu2x-caffe` folder with the older release of waifu2x-caffe.
1. Upgrade your drivers (or whatever actions required) and try fixing the compatibility issues.
1. Use waifu2x-ncnn-vulkan instead. It's also faster than waifu2x-caffe.

The processing speed depends on your hardware and the original clip's size. You'll also need to make sure that waifu2x-caffe is using either GPU or cuDNN (which requires a complex setup process). Running on CPU is extremely slow.

You can verify if it's using GPU by going to task manager > performance > {YOUR GPU} > select CUDA in one of the graphs.

**Comment by Pk555555** [comment]
I will use waifu2x-caffe then
And yes he is using the GPU

**Comment by Pk555555** [comment]
Using waifu2x-ncnn-vulkan I was able to finish the process with a good result in much less time thank you.
However I still couldn't solve the compatibility problem...
But I can use the old version of waifu2x-caffe so no problem.

**Comment by k4yt3x** [comment]
If you can use the old version but not the new one, then it's a client-side problem.
Feel free to post a solution here if you ever find one. I'll add it into the Q&A page in case someone else finds it helpful.

**Comment by Pk555555** [comment]
Well I ended up finding the incompatibility, and the cause is a program that I use NVIDIA RTX Voice that basically it works to "lick the noises" of your microphone well I ended up deactivating it before using video2x and coincidentally I used it a way that was not "working" previously and finally I discovered the error. 
I then tried all the video2x "modes" and they all worked very well with the program turned off.

**Comment by k4yt3x** [comment]
I use RTX Voice as well and didn't have any issues with it. I guess it's that some other program that's causing the issues.
Though RTX Voice still crashes my games sometimes.

**Comment by Pk555555** [comment]
I just did it differently ...
And I use RTX Voice version o.5.12.6
