### ISSUE TITLE
D:\video2x-4.7.0-win32-full\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by shuaidaming** [k4yt3x/video2x#383]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
You have included no information regarding the issue. Please upload a screenshot or error logs.
