### ISSUE TITLE
Check failed: status == CDNN_STATUS_SUCCESS (1 vs. 0) CDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by milaIZ** [k4yt3x/video2x#387]
## Component Versions

- **Video2X release version**: 4.6.1
- **Upscaler version**: "waifu2x-caffe-cui.exe  version: 1.0.0"
- **GUI version**: 2.7.2
- **CLI version**: 4.2.0

## Symptom

I was trying to upscale a video when I received an error from cuDNN that was not "available"

I tried all I can do to correct this error, reinstall the driver, install NVidia geforce experience, try to install cuDNN by hand, see if the error came from Waifu2x-Caffe ( 
![waifu2x-caffe_T31HchRfcg](https://user-images.githubusercontent.com/73024182/96337338-b8fa3700-1086-11eb-9fa7-ac0dc6453b3c.png)
 Translation: "You can use cuDNN" )

So I don't know if the problem is with my driver or the software, but I don't know how to fix this error.

## Error Log or Screenshots

![chrome_NzwTsB1aKD](https://user-images.githubusercontent.com/73024182/96337366-ecd55c80-1086-11eb-8295-d504ff207be3.png)

(I also tried GPU: 0 and it didn't work too)

**Comment by k4yt3x** [comment]
First of all, you're using an older version of v2x. Please use 4.7.0.
If the problem persists, try upgrading your GPU drivers.

**Comment by k4yt3x** [comment]
Closed due to inactivity.
