### ISSUE TITLE
ffmpeg extraction fails to start if missing extracted frames folder with custom paths

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#39]
Found out with the custom extracted and upscaled frames folders if those are missing, at the very least the ffmpeg extraction step fails. Not sure if waifu2x-caffe will do the same as I did not get that far. Where this comes in is the end of the script when it wipes those folders, it'll do so whether using the temp directory or custom paths. In a batch this is a no-go.

I've done a potentially crude fix for this which I'll try and do a PR for. You may wish to do a cleaner version of course. :)

**Comment by K4YT3X** [comment]
Oh yeah I should add the function to create folders automatically if they're missing.
I'll add that into the next commit and push it with the fix for #28 .

**Comment by K4YT3X** [comment]
I saw your code review, and I've already finished adding the features.
I came up with something more complicated and fault-tolerant.
I'll just make some more tests before releasing the new version.

**Comment by K4YT3X** [comment]
I have just released version `2.4.2`.
Problem should be solved.

**Comment by cr08** [comment]
One minor addition to this to request: Adding either a command line or config option to skip the "Create folder/directory?" request. Currently this breaks batching the script when intending to use custom paths.

**Comment by K4YT3X** [comment]
By design, if you have the destination folder created, it shouldn't prompt you. Is it not working properly?

**Comment by cr08** [comment]
Part of the original concern is there in which regardless of whether the temp folders are used or custom paths, they are deleted at the tail end of the script. Specifically this section of code: 

https://github.com/K4YT3X/video2x/blob/ecb65aad35e51490e160af272084831368576891/bin/upscaler.py#L72-L80

So I can create the custom folders I wish to use for extracted and upscaled frames, but when the script finishes it will delete these outright and the next cycle it will ask to create those because they no longer exist.

**Comment by K4YT3X** [comment]
Maybe you can set "preserve_frames" to `true` in the config file?
That might be the cheapest solution to this problem for now.

I'll look into adding an option for it, or make changes that will make this problem go away.
Also, please open a new issue as this is a separate topic from the original one. Opening a new issue also helps organizing my work.
