### ISSUE TITLE
File List Removal Button Shouldn't Use The Keyword Delete

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#390]
## Description

To remove files from the input selection list you need to highlight them and click "delete selected". But this could cause some concern and confusion that the original files will be deleted from the file system. This should be changed to "remove selected".

## Sources

![image](https://user-images.githubusercontent.com/32424764/96882818-4d78e680-1445-11eb-8d6f-52025c8baf68.png)

**Comment by k4yt3x** [comment]
Sure thing.

**Comment by k4yt3x** [comment]
Wait a second, doesn't that mean exactly the same thing? Either from a list perspective of a file system perspective?

**Comment by timsu92** [comment]
I think "deselect selected" would be better, for delete and remove are really the same sometimes

**Comment by k4yt3x** [comment]
> I think "deselect selected" would be better, for delete and remove are really the same sometimes

Now that sounds confusing and unnecessary. Realistically, you all know what "delete selected" is supposed to mean here right?

**Comment by timsu92** [comment]
> > I think "deselect selected" would be better, for delete and remove are really the same sometimes
> 
> Now that sounds confusing and unnecessary. Realistically, you all know what "delete selected" is supposed to mean here right?

Actually, no. When I see this the first time, I copied my video and had a test 😂

**Comment by k4yt3x** [comment]
Hmmm interesting... I'll ask for more opinions in the group.
