### ISSUE TITLE
You should create a discord

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#392]
## Description

If Video2x had a discord it would allow for the community to quickly and casually help new people with the program as well as discuss optimal settings for specific scenarios. It could probably help reduce work on your part and be a great resource to fans of the project.

Obviously, If you make a discord I would recommend advertising it near the top of the main github page. 

I see you're already using something named telegram. I think discord is far more casual and approachable for the general audience. Plus discord doesn't require you download an app to view channels unlike telegram. The second I saw I needed to create an account and download the app for telegram I instantly rejected joining it. This wouldn't be the case with discord.

That said while writing this I decided to dig deeper into what telegram actually is and their is one thing that really stood out to me as a major benefit.  That is apparently telegram has a 1.5GB file transfer limit vs the like 8mb of discord. If that's still true I can see how telegram would be a better fit for video2x and I'll prob take the time to join it after my research. 

That said a normal person wouldn't bother to write a GitHub issue and do further research into telegram the way I have. So I think making a discord would still be a great option. I would recommend making one and then creating a channel dedicated to pointing to telegram for any uploading content they want to post. This way you can probably capture a lot of people who prefer and know of discord only while simultaneously explaining to them why they should join telegram. I bet you would see numbers for both services increase if you did this.

**Comment by Felixkruemel** [comment]
@MatteCrystal Telegram is one of the most popular messengers out there. Widely adapted in nearly every country. You would be surprised how many people use Telegram due to it's impressive groups and permission features for a simple messenger.

Discord has a huge Privacy problem.

**Comment by k4yt3x** [comment]
For the record, we have had discussions around this in the Telegram group. I think it's beneficial to create a group in Discord for those that want to discuss about Video2X or video upscaling.
However, I won't be maintaining the group actively due to the said privacy concerns.

**Comment by k4yt3x** [comment]
I'll add the Discord group invitation URL to the homepage (README) soon.
