### ISSUE TITLE
PermissionError: [WinError 5] Access denied

### ISSUE THREAD

**Issue by Mozza7** [k4yt3x/video2x#393]
## Component Versions

- **Video2X release version**: 4.7.0
- **Upscaler version**: 4.4.0
- **GUI version**: 2.8.0

## Symptom

Program errors out when moving/copying the file. I've checked permissions and this **shouldn't** be causing issues, video2x, input and output locations are all OK permission wise and **not** read only.

This is using Waifu2x NCNN Vulkan in particular, but tested with each other drive and issue persists.

I don't believe it matters for this particular issue, but I'm using a 2080ti.

## Error Log or Screenshots
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5429774/video2x_error.log)

**Comment by Mozza7** [comment]
So I tried dropping down to version 4.6.1, but this also fails so with the following:

[console_output.txt](https://github.com/k4yt3x/video2x/files/5429884/console_output.txt)
[video2x_2020-10-23_14-53-21.log](https://github.com/k4yt3x/video2x/files/5429885/video2x_2020-10-23_14-53-21.log)


I uploaded the console output as I couldn't see the error in the log file

**Comment by k4yt3x** [comment]
> encode image C:\Users\Andrew\Desktop\video2x-4.7.0-win32-full\testimage_output.png failed

It does actually sound like a permission issue in the console log, but I can't quite see what's wrong in the error logs. I'm not quite sure what's causing the problem at the moment.

**Comment by Mozza7** [comment]
I've tried moving the cache location in case there were any issues there but same error, but this time it starts upscaling the image and immediately after starts cleaning up cache directory? Not sure if that's helpful in any way
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5432763/video2x_error.log)

I've also screenshot the permissions/attributes:
[attributes](https://user-images.githubusercontent.com/43605638/97080076-b6509200-15f0-11eb-8021-ad0d4448f50a.png)
[permissions](https://user-images.githubusercontent.com/43605638/97080106-f879d380-15f0-11eb-9655-02fed6321519.png)
All users have the same permissions to this folder ^

**Comment by Mozza7** [comment]
OK so I've been messing with this today, I downloaded the source code and all the requirements etc.. when ran through here, this worked. 

So, I copied the installed requirements in %appdata%/local/video2x, checked the names were the same as in the dependencies folder, and moved them over. This is working - so I assume the issue was with one of the drivers. I had issues downloading ffmpeg using the setup py file, so I installed it manually from:
[ffmpeg](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2020-10-21-git-289e964873-full_build.7z)

**Comment by k4yt3x** [comment]
Hmmm.... Could it be that the permissions set on my workstation can't be recognized on your computer due to the SID not being recognized in your environment?
I'm not quite sure yet, the windows (NTFS) permission system is a bit more complex than that of the Linux (ext4) system.

**Comment by k4yt3x** [comment]
I honestly still have no idea how to reproduce this error.

**Comment by k4yt3x** [comment]
I'll re-investigate this issue if I come across it again in 5.0.0.
