### ISSUE TITLE
FFmpeg hwaccel error

### ISSUE THREAD

**Issue by teebox1** [k4yt3x/video2x#395]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:  4.7.0-win32-full
- **Upscaler version**:  4.4.0
- **GUI version**: 2.8.0
- **CLI version**: not running command line interface

## Symptom

Execution from the Win10 GUI proceeds successfully but terminates with the attached error log.  Can you please offer resolution steps?

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5431051/video2x_error.log)
![video2x failure](https://user-images.githubusercontent.com/73357478/97038334-44187880-1530-11eb-8186-aa7b466f843c.JPG)

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
The logger is broken at the moment. Could you please supply a console screenshot?

**Comment by Balls0fSteel** [comment]
Had the same error just now. When I had 1x Processes, no crash. Then I put it on a higher amount and then it crashed.
CPU: 3900X
GPU: GTX 1070TI
VRAM: 8.0GB
RAM: 32.0GB

[error1.log](https://github.com/k4yt3x/video2x/files/5455219/error1.log)

![error1](https://user-images.githubusercontent.com/6089378/97505402-27899f80-1979-11eb-8266-e4dda5202502.png)

**Comment by k4yt3x** [comment]
> vkAllocateMemory failed

Yes you ran out of VRAM. I do not recommend going higher than one process for machine-learning based drivers.

**Comment by teebox1** [comment]
Help me please.  I supplied what I thought was the picture of the gui console and the error log file.  What is a "console screenshot"?

**Comment by k4yt3x** [comment]
@teebox1 there would be a black console/terminal window as well like what @Balls0fSteel has sent.
Take a screenshot of that as well, or simply copy&past all texts from it.
I'm still fixing the logging system. It's a bit more annoying than I thought.
It's also midterm week here so I'm quite busy.

**Comment by teebox1** [comment]
Thank you for your reply.  I'll stand aside.  Focus on your mid-terms.  I wish you the highest grades!  Good luck!  Meanwhile, here's the console terminal window in a text file.
[error console log.txt](https://github.com/k4yt3x/video2x/files/5470052/error.console.log.txt)

**Comment by k4yt3x** [comment]
Ok I see what's wrong.

> [h264 @ 000001f7994fdfc0] Failed to retrieve decoder device GUIDs
> [h264 @ 000001f7994fdfc0] Failed setup for format dxva2_vld: hwaccel initialisation returned error.

Try turning off hardware acceleration for FFmpeg. Go to the FFmpeg Settings tab, and uncheck hwaccel under each of the child tabs.

**Comment by teebox1** [comment]
Gave it a go acting on your advice.  Still fails.  Here's the new error log.
[error console log 2.txt](https://github.com/k4yt3x/video2x/files/5471362/error.console.log.2.txt)

**Comment by k4yt3x** [comment]
Hmmmm FFmpeg's error is gone, and I don't see any useful error messages. Could you please turn on `Preserve Frames`, run the upscale, and go to `%TEMP%/video2x` to see if the frames are extracted correctly? That's only thing I can think of right now.

**Comment by teebox1** [comment]
Checked Preserve Frames.  Still fails.  %TEMP%/video2x has 2 files as per .jpg.  The tmpkyks1oo file has as many images as there are frames reported in the execution of the Upscale in the GUI
[error console log 3.txt](https://github.com/k4yt3x/video2x/files/5471897/error.console.log.3.txt)
![tmpvkyks1oo file](https://user-images.githubusercontent.com/73357478/97817370-a88ab480-1c61-11eb-96ab-fcfc96248013.JPG)
![vidieo2x](https://user-images.githubusercontent.com/73357478/97817374-a9234b00-1c61-11eb-8d9b-5f36c0293f5c.JPG)


.

**Comment by k4yt3x** [comment]
That is so strange...I still can't tell what went wrong.
I'm assuming all other drivers are failing as well?

**Comment by teebox1** [comment]
I don't know.  How can I tell?

**Comment by k4yt3x** [comment]
Change the driver from Waifu2X NCNN Vulkan to something else like Anime4KCPP and see if it works.

**Comment by teebox1** [comment]
I tried every driver.  Anime4KCPP completed successfully.  The others
failed.  I'd be happy to act as a tester with other processes if you'd
like.  What sources would you recommend as a learning tool for film
restoration?  Thank you again for your help.

**Comment by k4yt3x** [comment]
> Anime4KCPP completed successfully.

That is very strange. What does your setup look like? What GPU are you using?

>  What sources would you recommend as a learning tool for film restoration?

Quite frankly I don't know any. There are some professionals in the Telegram group who have been doing this for the last couple of years. Maybe you can ask them.
