### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ewedel** [k4yt3x/video2x#397]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**:
- **GUI version**: 2.8.0
- **CLI version**: 4.3.1

Installed by unzipping video2x-4.7.0-win32-full.zip

## Symptom

In this section, briefly describe what's going on.

Simply launched a run attempt via the gui, using a 90 second clip from the front of an mpeg. Clip was extracted using ffmpeg like so:

    ...\ffmpeg.exe -i VTS_02.mpg -ss 0 -t 90 -c:a copy -c:v copy -y -target ntsc-dvd 90_vts_02.mpg

video2x run through gui with these settings:
driver: Waifu2X NCNN Vulkan
procs: 1
scale: 2.00
width: 0
height: 0

"show preview" and "keep aspect ration" both are ticked.

### Other info
Poked around and found the ffprobe command used by wrappers/ffmpeg.py.
Looks like this, which with my target 90 second file runs like so:

    ...\ffprobe.exe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 90_vts_02.mpg
    2698

so it seems like that 2698 should be getting returned, instead of an empty string.

Note that my own copies of ffmpeg and ffprobe are not on the path. If it matters, they are from this daily build:

2020-10-21-git-289e964873-full_build-www.gyan.dev
## Error Log or Screenshots
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-10-24 01:02:04.793698 [+] INFO: Input path(s): D:\works\video\hd_conv\video2x\try1\90_vts_02.mpg[0m
[90m2020-10-24 01:02:04.797694 [+] INFO: File MIME type: video/mpeg[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-10-24 01:02:04.800693 [+] INFO: Input file: D:\works\video\hd_conv\video2x\try1\90_vts_02.mpg[0m
[32m[+] INFO: Reading file information[0m
[90m2020-10-24 01:02:04.803692 [+] INFO: Executing: d:\works\video\hd_conv\video2x\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\works\video\hd_conv\video2x\try1\90_vts_02.mpg[0m
[90m2020-10-24 01:02:05.390936 [+] INFO: Creating cache directory C:\Users\eric\AppData\Local\Temp\video2x[0m
[90m2020-10-24 01:02:05.394934 [+] INFO: Extracted frames are being saved to: C:\Users\eric\AppData\Local\Temp\video2x\tmpbhr6d37l[0m
[90m2020-10-24 01:02:05.395933 [+] INFO: Upscaled frames are being saved to: C:\Users\eric\AppData\Local\Temp\video2x\tmp3fs1mfuh[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2020-10-24 01:02:05.397932 [+] INFO: Executing: d:\works\video\hd_conv\video2x\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\works\video\hd_conv\video2x\try1\90_vts_02.mpg[0m
Cleaning up cache directory: C:\Users\eric\AppData\Local\Temp\video2x\tmpbhr6d37l
Cleaning up cache directory: C:\Users\eric\AppData\Local\Temp\video2x\tmp3fs1mfuh
Cleaning up cache directory: C:\Users\eric\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 589, in run
  File "wrappers\ffmpeg.py", line 106, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''

**Comment by ewedel** [comment]
Was just playing with the CLI version, which fails just the same way. But it showed the exact ffprobe invocation:

    dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 d:\works\video\hd_conv\video2x\try1\90_vts_02.mpg

However, that v:1 stream selection is wrong. Changing it to zero causes the desired frame count to be returned:

    dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 d:\works\video\hd_conv\video2x\try1\90_vts_02.mpg
    2698

Now of course the question is why the bad stream number? A simple ffprobe of the file looks like so:

    dependencies\ffmpeg-latest-win64-static\bin\ffprobe d:\works\video\hd_conv\video2x\try1\90_vts_02.mpg
    ...
    [mpeg @ 000002408a00ff40] start time for stream 0 is not set in estimate_timings_from_pts
    Input #0, mpeg, from 'd:\works\video\hd_conv\video2x\try1\90_vts_02.mpg':
      Duration: 00:01:30.02, start: 0.533367, bitrate: 6572 kb/s
        Stream #0:0[0x1bf]: Data: dvd_nav_packet
        Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
        Side data:
          cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
        Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 448 kb/s
    Unsupported codec with id 100357 for input stream 0

**Comment by k4yt3x** [comment]
Hmm.. Could you please post the output of this command?

```shell
d:\works\video\hd_conv\video2x\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\works\video\hd_conv\video2x\try1\90_vts_02.mpg
```

**Comment by ewedel** [comment]
Apologies for the delay, haven't been checking mail as I should. Had found a workaround by doing a second ffmpeg copy after doing the initial time-limited extraction.

But after hitting a second and presumably unrelated bug (8GB file "isn't a video"), decided it was time to start debugging.

The following small diff fixes the frame counting. Turns out it wasn't the index that was wrong, but how it was presented. Can't say I understand that, but was thinking about submitting this as a tiny pull request. Would be very interested in your thoughts on it. And if you like it feel free to just commit it yourself if you'd prefer.

    diff --git a/src/wrappers/ffmpeg.py b/src/wrappers/ffmpeg.py
    index a8f74b7..a7db955 100755
    --- a/src/wrappers/ffmpeg.py
    +++ b/src/wrappers/ffmpeg.py
    @@ -85,13 +85,14 @@ class Ffmpeg:
		 int: number of frames in the video
	     """
     
    +        # NB: -select_streams sometimes fails with v:N, but works with just N
	     execute = [
		 self.ffmpeg_probe_binary,
		 '-v',
		 'quiet',
		 '-count_frames',
		 '-select_streams',
    -            f'v:{video_stream_index}',
    +            f'{video_stream_index}',
		 '-show_entries',
		 'stream=nb_read_frames',
		 '-of',

For reference, also attaching the json output you requested. Hmm, gitlab doesn't like raw json, so .txt it is: [streams_info.json.txt](https://github.com/k4yt3x/video2x/files/5444309/streams_info.json.txt)

**Comment by ewedel** [comment]
(hmm, please excuse the mucked-up indent in the above diff)

**Comment by k4yt3x** [comment]
I think this ended up getting fixed in a later version. Sorry for not replying to this thread in time. My schedule gets pretty messed up during a semester

**Comment by ewedel** [comment]
Ok, thanks for the update. Haven't been putting much time into this lately
anyway.

Had put together a single-pass test driver for exercising different
settings. Nothing really worked as I'd like, so next up is a two-pass
version.

Have a couple other projects to get sorted first, then will try to remember
to upgrade first when coming back to this. :-)

**Comment by k4yt3x** [comment]
If you're comfortable playing with CLI and Docker, I'll recommend you to fiddle around with the new [5.0.0-beta1 container](https://github.com/k4yt3x/video2x/pkgs/container/video2x). 4.8.x still has some residual issues that are not patched. 5.0.0 is much more stable and performant, but I've only built the CLI for it so far. This following command upscales the video `sample_input.mp4` under the current directly to 720p with waifu2x.

```shell
docker run -it --rm --gpus all -v /dev/dri:/dev/dri -v $PWD:/host ghcr.io/k4yt3x/video2x:5.0.0-beta1-cuda -i sample_input.mp4 -o output.mp4 -p5 upscale -h 720 -d waifu2x -n3
```
