### ISSUE TITLE
video2x_setup.py points to non-zip version of ffmpeg

### ISSUE THREAD

**Issue by dawja** [k4yt3x/video2x#398]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- 4.7.0:
- python:

## Symptom

video2x_setup.py points to non-zip version of ffmpeg which created a "zipfile.BadZipFIle: File is not a zip file" error message on install.

I bypassed the error by changing to 
"https://github.com/GyanD/codexffmpeg/releases/download/4.3.1-2020-10-01/ffmpeg-4.3.1-2020-10-01-full_build.zip" 
on line 129 in the set up py file

**Comment by k4yt3x** [comment]
They seem to have removed the link embedded in `video2x_setup.py`.
I'll update the link. Thanks for reporting.

**Comment by k4yt3x** [comment]
They seem to have start packing releases in 7z format. That's such an annoying format to decompress. Only the 7zip binary can handle 7z files properly. I'll update the script to decompress the new 7z file with 7zip.

**Comment by k4yt3x** [comment]
Addressed in https://github.com/k4yt3x/video2x/commit/4f8bb1be1c9d15083d311290e600f597d1fd5e3e
