### ISSUE TITLE
include new models (improvement)

### ISSUE THREAD

**Issue by ArmandBernard** [K4YT3X/video2x#40]
Hello,

I've just found your tool and I've been digging through the code a bit. I've noticed that your code does not allow for the use of the newer models included in waifu2x caffe, in particular "cunet" and "upresnet10". From my experience, cunet can give even better results than anime_style_art_rgb with better handling of noise and haloing even without turning on much noise reduction. I've not compared their performance though.

Would it be possible to have those models included in the -y / --model_type option?

Thanks.

**Comment by K4YT3X** [comment]
Of course. I'll update the options section.
It will be better if I would be able to dynamically detect the supported models, but I don't know a way to do it elegantly.

**Comment by K4YT3X** [comment]
New models are now included in the most recent update.
