### ISSUE TITLE
FFmpeg -tune Setting Cannot Be Turned Off

### ISSUE THREAD

**Issue by Genje5** [k4yt3x/video2x#401]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**: 
- **GUI version**: 2.8.0
- **CLI version**:

## Symptom

In the GUI mode, under FFmpeg settings --> Video Assembly, there is no option to turn the -tune option off, and you are forced to select one. Could you allow the option to turn this off.

**Comment by k4yt3x** [comment]
That's a good point. I'll add a `none`.

**Comment by AlanBAKA** [comment]
if the -turn option can turn off, it is posable to use GPU buildin encoder like nvenc_hevc hevc_amf
and if is posable to add a custom option for ffmpeg, or just add a Advance setting let user to type in there own option

**Comment by k4yt3x** [comment]
@AlanBAKA technically everything can be customized via the config file.

**Comment by AlanBAKA** [comment]
I have try to remove the -tune setting and add some my setting into the config file, but nothing happen in CLI mode and GUI mode, How can I fully custom the ffmpeg option myself

**Comment by k4yt3x** [comment]
The CLI will strictly obey the config file settings, whereas the GUI will read from the GUI settings and overwrite some of the config file values.

**Comment by k4yt3x** [comment]
Fixed with https://github.com/k4yt3x/video2x/commit/4694c557ec73f0a18a558d0720401c5924d3bdb3
