### ISSUE TITLE
Hardware Acceleration on Downscaling

### ISSUE THREAD

**Issue by Super99Master** [k4yt3x/video2x#405]
## Description

Add Hardware Acceleration to the Downscaling process since it's barely using the CPU.

## Sources

![HADownscaling](https://user-images.githubusercontent.com/35634158/97968388-dd604e00-1dbe-11eb-8629-666c4b8570e5.png)

Running 2 Downscaler for a max of 32% CPU utilization.

**Comment by GitGerby** [comment]
I haven't looked at the code yet; would it be possible to launch N downscaling processes where N is the number of logical processors on the system?

**Comment by Super99Master** [comment]
> I haven't looked at the code yet; would it be possible to launch N downscaling processes where N is the number of logical processors on the system?

Yes
https://github.com/Super99Master/video2x/commit/a1b2aa380d67fe423d63c113d6bc471b03c8c3ff

**Comment by Super99Master** [comment]
https://github.com/Super99Master/video2x/commits/master

This is more or less how multithreading the downscaling process should work,

**Comment by Rmdhn1** [comment]
Can i leave the downscaling, put that commit into mine, and then continue where i left off

**Comment by Super99Master** [comment]
> Can i leave the downscaling, put that commit into mine, and then continue where i left off
> don't wanna spend 5 hours downscaling when you spent 4 upscaling

Sorry, but i don't understand what you mean.
Multy threaded downscaling was added in the dev tree

**Comment by Rmdhn1** [comment]
also, huh, i downloaded it from git and the downscaling isn't multi threaded, i checked it on the python code and it isn't there

**Comment by Super99Master** [comment]
> also, huh, i downloaded it from git and the downscaling isn't multi threaded, i checked it on the python code and it isn't there
> 
> edit: OH GOD DAMNIT, DEV TREE? I DOWNLOADED THE MASTER

https://github.com/k4yt3x/video2x/pull/449

**Comment by k4yt3x** [comment]
FYI:  The 5.0 beta will be streamlined, so it will also be multi-threaded...or multi-processed rather.
