### ISSUE TITLE
无法打开GUI

### ISSUE THREAD

**Issue by NTDLX** [k4yt3x/video2x#406]
下载了video2x-4.7.0-win32-full，但是打开video2x_gui.exe只显示一个CMD窗口，无任何内容，也没有显示GUI界面

**Comment by MatteCrystal** [comment]
video2x_gui.exe will open a blank cmd for a short while before showing the actual GUI. Make sure you try waiting while with the blank cmd open awhile first. If you wait more than a min than probably something wrong. 

Respond back if just waiting fixed the issue or not.

**Comment by k4yt3x** [comment]
Basically what he said.
