### ISSUE TITLE
Command returned non-zero exit status 1.

### ISSUE THREAD

**Issue by samurai-for-hire** [k4yt3x/video2x#407]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**: 
- **GUI version**: 2.8.0
- **CLI version**:

## Symptom

The upscaler throws an error on reaching a certain frame in the video

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5508343/video2x_error.log)

**Comment by k4yt3x** [comment]
Might be a hardware acceleration error.
Try unchecking hwaccel under all FFmpeg Settings tabs.
