### ISSUE TITLE
ERROR: File video.mkv (inode/blockdevice) neither an image nor a video

### ISSUE THREAD

**Issue by sfremerey** [k4yt3x/video2x#408]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: video2x-4.7.0-win32-full
- **Upscaler version**: Waifu2X NCNN Vulkan or Waifu2X Caffee
- **GUI version**: 2.8.0
- **CLI version**: ?

## Symptom

I have the feeling that the release version video2x-4.7.0-win32-full has a bug if you try to upscale bigger video files.
How to reproduce: Create a bigger video file, duration should be at least 2 minutes using some lossless video codec, e.g. using ffmpeg:

```
ffmpeg -r 50 -f image2 -i frames\%05d.png -c:v ffvhuff -pix_fmt yuv422p video.mkv
```

If you now try to use this video file as input for video2x, the error shown below is thrown. The created file for sure is a video file.
It doesn't matter whether you are using Waifu2X NCNN Vulkan or Waifu2X Caffee as driver. 

This error is **not** shown if you use an older version of video2x. I tested it with video2x-4.6.1-win32-full and it works, using Waifu2X Caffee as driver.

## Error Log or Screenshots

Error log:

```
[+] INFO: Loading files into processing queue
2020-11-11 14:22:49.012990 [+] INFO: Input path(s): video.mkv
2020-11-11 14:22:49.013986 [+] INFO: File MIME type: inode/blockdevice
[!] ERROR: File video.mkv (inode/blockdevice) neither an image nor a video
[!] WARNING: Skipping this file
[+] INFO: Loaded files into processing queue
```

**Comment by k4yt3x** [comment]
It's a problem with python-magic. Try the latest nightly version: https://github.com/k4yt3x/video2x/actions/runs/330081402

**Comment by sfremerey** [comment]
Using the nightly version it seems to work again - thank you for the hint.
