### ISSUE TITLE
noise level option (improvement)

### ISSUE THREAD

**Issue by ArmandBernard** [K4YT3X/video2x#41]
After digging through your code, I found that you've hardcoded the use of level 3 noise reduction for waifu2x. That seems a bit excessive for most anime encodes files imo. Could you possibly include an option -n / --noise_level to let the user set this? That would be awesome.

**Comment by K4YT3X** [comment]
Sure. Will be available in the next update.

**Comment by K4YT3X** [comment]
This is now supported via editing the config file.
I might make it available via command line as well in the future.
