### ISSUE TITLE
Command '['B:\\Program Files\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'B:\\Program Files\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '8:8:8', '-i', 'C:\\Users\\steel\\AppData\\Local\\Temp\\video2x\\tmpbysp419g', '-o', 'C:\\Users\\steel\\AppData\\Local\\Temp\\video2x\\tmp1y0fd6zk']' returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by Steelviper44** [k4yt3x/video2x#413]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-11-22 03:00:28.430826 [+] INFO: Input path(s): C:\Users\steel\Pictures\1521305659_Like_Rock.gif[0m
[90m2020-11-22 03:00:28.432820 [+] INFO: File MIME type: image/gif[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-11-22 03:00:28.435395 [+] INFO: Input file: C:\Users\steel\Pictures\1521305659_Like_Rock.gif[0m
[32m[+] INFO: Reading file information[0m
[90m2020-11-22 03:00:28.435395 [+] INFO: Executing: B:\Program Files\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\steel\Pictures\1521305659_Like_Rock.gif[0m
[90m2020-11-22 03:00:28.488256 [+] INFO: Creating cache directory C:\Users\steel\AppData\Local\Temp\video2x[0m
[90m2020-11-22 03:00:28.489269 [+] INFO: Extracted frames are being saved to: C:\Users\steel\AppData\Local\Temp\video2x\tmpbysp419g[0m
[90m2020-11-22 03:00:28.490250 [+] INFO: Upscaled frames are being saved to: C:\Users\steel\AppData\Local\Temp\video2x\tmp1y0fd6zk[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[32m[+] INFO: Calculating scaling parameters[0m
[90m2020-11-22 03:00:28.491247 [+] INFO: Framerate: 19.833333333333332[0m
[90m2020-11-22 03:00:28.491247 [+] INFO: Width: 500[0m
[90m2020-11-22 03:00:28.492245 [+] INFO: Height: 643[0m
[90m2020-11-22 03:00:28.492245 [+] INFO: Total number of frames: 12[0m
[90m2020-11-22 03:00:28.492245 [+] INFO: Output width: 1000[0m
[90m2020-11-22 03:00:28.492245 [+] INFO: Output height: 1286[0m
[90m2020-11-22 03:00:28.492245 [+] INFO: Required scale ratio: 2.0[0m
[90m2020-11-22 03:00:28.493243 [+] INFO: Upscaling jobs queue: [2][0m
[90m2020-11-22 03:00:28.493243 [+] INFO: Executing: B:\Program Files\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffmpeg -hwaccel auto -y -i C:\Users\steel\Pictures\1521305659_Like_Rock.gif -pix_fmt rgb24 C:\Users\steel\AppData\Local\Temp\video2x\tmpbysp419g\extracted_%0d.png[0m
[90m2020-11-22 03:00:28.499226 [+] INFO: Main process waiting for subprocesses to exit[0m
[90m2020-11-22 03:00:28.700815 [+] INFO: Subprocess 2108 exited with code 0[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
[90m2020-11-22 03:00:28.804603 [+] INFO: [upscaler] Subprocess 6500 executing: B:\Program Files\video2x-4.7.0-win32-full\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan -n 2 -s 2 -t 400 -m B:\Program Files\video2x-4.7.0-win32-full\dependencies\waifu2x-ncnn-vulkan\models-cunet -g 0 -j 8:8:8 -i C:\Users\steel\AppData\Local\Temp\video2x\tmpbysp419g -o C:\Users\steel\AppData\Local\Temp\video2x\tmp1y0fd6zk[0m
[90m2020-11-22 03:00:28.811118 [+] INFO: Starting progress monitor[0m
[90m2020-11-22 03:00:28.812089 [+] INFO: Starting upscaled image cleaner[0m
[90m2020-11-22 03:00:28.813087 [+] INFO: Main process waiting for subprocesses to exit[0m

Processing: 1521305659_Like_Rock.gif (pass 1/1):   0%|                                          | 0/12 [00:00<?, ?it/s]
Processing: 1521305659_Like_Rock.gif (pass 1/1):   0%|                                          | 0/12 [00:01<?, ?it/s]
Processing: 1521305659_Like_Rock.gif (pass 1/1):   8%|##8                               | 1/12 [00:02<00:11,  1.01s/it]
Processing: 1521305659_Like_Rock.gif (pass 1/1):  33%|###########3                      | 4/12 [00:03<00:06,  1.23it/s]
Processing: 1521305659_Like_Rock.gif (pass 1/1):  50%|#################                 | 6/12 [00:04<00:04,  1.31it/s][31m[1m[!] ERROR: Subprocess 16404 exited with code 3221225477[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2020-11-22 03:00:34.238227 [+] INFO: Killing progress monitor[0m

Processing: 1521305659_Like_Rock.gif (pass 1/1):  50%|#################                 | 6/12 [00:06<00:06,  1.07s/it]
[90m2020-11-22 03:00:35.238430 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: C:\Users\steel\AppData\Local\Temp\video2x\tmpbysp419g
Cleaning up cache directory: C:\Users\steel\AppData\Local\Temp\video2x\tmp1y0fd6zk
Cleaning up cache directory: C:\Users\steel\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 692, in run
  File "upscaler.py", line 347, in _upscale_frames
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 409, in _wait
  File "upscaler.py", line 393, in _wait
subprocess.CalledProcessError: Command '['B:\\Program Files\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'B:\\Program Files\\video2x-4.7.0-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '8:8:8', '-i', 'C:\\Users\\steel\\AppData\\Local\\Temp\\video2x\\tmpbysp419g', '-o', 'C:\\Users\\steel\\AppData\\Local\\Temp\\video2x\\tmp1y0fd6zk']' returned non-zero exit status 3221225477.

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by Steelviper44** [comment]
i cant get this program to work with any settings no matter what

**Comment by k4yt3x** [comment]
It seems like waifu2x has been running just fine. Are you out of storage or something?

**Comment by Steelviper44** [comment]
> It seems like waifu2x has been running just fine. Are you out of storage or something?

nope, i have 1.29TB free on the drive im exporting to, and its only an upscaled GIF, that shouldn't be over my free space lmao. it seems to have trouble exporting any kind of video\image and ive even ran it as admin

**Comment by k4yt3x** [comment]
waifu2x seems to have ran just fine until it's half way through. I'm quite confused as for what cause the error there.
If waifu2x was able to launch, then the environment is fine. It has all the required libraries; it is able to work with your hardware.
Thus, the problem, it looks like, may lie somewhere external to this program. Storage, for example, being the first one that came to my mind. There could be other things, but it's hard for me to debug remotely.

**Comment by Steelviper44** [comment]
im just as confused, probably more windows 10 BS
