### ISSUE TITLE
Video2X Doesn't Recognise Many Valid MP4 Files as Videos

### ISSUE THREAD

**Issue by Mrjamin** [k4yt3x/video2x#419]
## Component Versions
video2x-4.7.0-win32-full.zip

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:   4.7.0 full
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

Video2x exits the upscale process immediately after "start" is pressed in the GUI, with the following error showing in the command window:

[!] ERROR: File D:\{filename}.mp4 (inode/blockdevice) neither an image nor a video

The video in question is a valid .MP4 video file.  It was created using Adobe Media Encoder CC 2020 from a SD .AVI source video (originally captured from PAL DV tape).  

To test this as a bug, I created several different encodes from the original AVI file with both Adobe Media Encoder and also Handbrake.  None of the .MP4 files created with AME are recognised as 'videos' by Video2x, and only one of the .MP4 files created with Handbrake were recognised.  All the videos were compressed as h264/x264.

The output from MediaInfo for each file is as follows (only the last one was recognised by Video2X as a video):

**1) Original AVI file (not recognised as a video by Video2x):**

General
Complete name                            : D:\{filename}.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Commercial name                          : DVCAM
Format profile                           : OpenDML
File size                                : 11.7 GiB
Duration                                 : 55 min 11 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 30.3 Mb/s
Recorded date                            : 2009-02-23T00:37:31.00032Z

Video
ID                                       : 0
Format                                   : DV
Commercial name                          : DVCAM
Codec ID                                 : dvsd
Codec ID/Hint                            : Sony
Duration                                 : 55 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 24.4 Mb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Bottom Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 2.357
Time code of first frame                 : 00:00:00:00 / 00:00:00:00
Time code source                         : Adobe tc_A / Adobe tc_O
Stream size                              : 11.1 GiB (95%)

Audio
ID                                       : 1
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 55 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 1 536 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Stream size                              : 606 MiB (5%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 1000  ms (25.00 video frames)
Interleave, preload duration             : 1000  ms

**2) h264 .MP4 encoded with Adobe ME (not recognised as a video by Video2x):**

General
Complete name                            : D:\{filename}.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/mp41)
File size                                : 4.44 GiB
Duration                                 : 55 min 11 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 11.5 Mb/s
Encoded date                             : UTC 2020-11-26 16:59:04
Tagged date                              : UTC 2020-11-26 17:00:24
TIM                                      : 00:00:00:00
TSC                                      : 25
TSZ                                      : 1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 55 min 11 s
Bit rate                                 : 7 339 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.708
Stream size                              : 2.83 GiB (64%)
Language                                 : English
Encoded date                             : UTC 2020-11-26 16:59:04
Tagged date                              : UTC 2020-11-26 16:59:04
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 55 min 11 s
Source duration                          : 55 min 11 s
Bit rate mode                            : Variable
Bit rate                                 : 317 kb/s
Maximum bit rate                         : 419 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 125 MiB (3%)
Source stream size                       : 125 MiB (3%)
Language                                 : English
Encoded date                             : UTC 2020-11-26 16:59:04
Tagged date                              : UTC 2020-11-26 16:59:04

**3) x264 .MP4 encoded with Handbrake (not recognised as a video by Video2x):**

eneral
Complete name                            : D:\{filename}.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/avc1/mp41)
File size                                : 2.11 GiB
Duration                                 : 55 min 11 s
Overall bit rate                         : 5 464 kb/s
Recorded date                            : 2009-02-23T00:37:31.00032Z
Encoded date                             : UTC 2020-11-27 15:41:20
Tagged date                              : UTC 2020-11-27 15:41:20
Writing application                      : HandBrake 1.3.3 2020061300

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 55 min 11 s
Bit rate                                 : 5 140 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.496
Stream size                              : 1.98 GiB (94%)
Writing library                          : x264 core 157 r2935 545de2f
Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=crf / mbtree=1 / crf=16.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=17500 / vbv_bufsize=17500 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2020-11-27 15:41:20
Tagged date                              : UTC 2020-11-27 15:41:20
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 55 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 318 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 125 MiB (6%)
Title                                    : Stereo
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2020-11-27 15:41:20
Tagged date                              : UTC 2020-11-27 15:41:20

**4) Alternative x264 .MP4 encoded with Handbrake (recognised by Video2x as a video)**

General
Complete name                            : D:\{filename}.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/avc1/mp41)
File size                                : 1.91 GiB
Duration                                 : 55 min 11 s
Overall bit rate                         : 4 962 kb/s
Recorded date                            : 2009-02-23T00:37:31.00032Z
Encoded date                             : UTC 2020-11-26 18:44:37
Tagged date                              : UTC 2020-11-26 18:44:37
Writing application                      : HandBrake 1.3.3 2020061300

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 5 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 55 min 11 s
Bit rate                                 : 4 639 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.447
Stream size                              : 1.79 GiB (93%)
Writing library                          : x264 core 157 r2935 545de2f
Encoding settings                        : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=16.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=17500 / vbv_bufsize=17500 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2020-11-26 18:44:37
Tagged date                              : UTC 2020-11-26 18:44:37
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 55 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 318 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 125 MiB (6%)
Title                                    : Stereo
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2020-11-26 18:44:37
Tagged date                              : UTC 2020-11-26 18:44:37

**Comment by k4yt3x** [comment]
Try the latest nightly build. It's a known issue that python-magic fails to recognize these files.
It has been rectified in the nightly build.

**Comment by k4yt3x** [comment]
A new release will be published soon to address this problem.
