### ISSUE TITLE
libpng error: Read Error QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by HondaFit** [k4yt3x/video2x#428]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.8.2
- **Upscaler version**:
- **GUI version**: 
- **CLI version**:

## Symptom
I'm getting this error, not sure what happened because it was running while I was asleep. I checked on it in the middle of the night and it seemed like it was working but when I checked in the morning there were multiple of the same error. I'm not really sure when it the error appeared but it happened somewhere between 50%-75% completion. Even though there was an error, it looked like it was upscalling each frames. I checked the task manager is it confirmed my suspicion, it was using 70-80% of my GPU's Cuda.

Video2x Configuration for Upscalling 
![Video2x Configuration for upscalling](https://user-images.githubusercontent.com/17225364/102241877-536fce80-3eae-11eb-8346-0c0def71d202.png)

Specs: 
CPU: i7 9700K
GPU: RTX 2070
RAM: 16GB 2400MHZ
My drivers are up to date

## Error Log or Screenshots

![Screenshot 2020-12-15 081357](https://user-images.githubusercontent.com/17225364/102242699-325bad80-3eaf-11eb-84e5-88f69791c23f.png)

The video I was trying to upscale:https://mylivewallpapers.com/anime/its-gonna-rain-soon-live-wallpaper/

**Comment by HondaFit** [comment]
I stopped the upscalling. When I checked my drives, my system drive was almost full. There was 200MB left, and still decreasing. I'm not sure if that was the issue

**Comment by k4yt3x** [comment]
You can safely ignore this error for now. That's just libpng failing to load the preview images.

**Comment by HondaFit** [comment]
Ohhh, thx! :)
