### ISSUE TITLE
Command '['i:\\DISTR\\Video2X\\video2x-4.8.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'i:\\DISTR\\Video2X\\video2x-4.8.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '704', '--scale_height', '512', '--input_path', 'C:\\Users\\FRANKS~1\\AppData\\Local\\Temp\\video2x\\tmp_8kvz8nx\\2', '--output_path', 'C:\\Users\\FRANKS~1\\AppData\\Local\\Temp\\video2x\\tmpxg0wgdc0']' returned non-zero exit status 3221226505.

### ISSUE THREAD

**Issue by JohnMcLaren** [k4yt3x/video2x#429]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5719945/video2x_error.log)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
> 20:52:48.065919  1656 cudnn_deconv_layer.cpp:238] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

It seems to be a CUDA/cuDNN issue. Make sure you have an NVIDIA GPU and its drivers installed. Update your driver if it's outdated.

Also, you're using way too many processes for waifu2x-caffe. Use only one process and adjust the crop size.

**Comment by JohnMcLaren** [comment]
My GPU
![gpu](https://user-images.githubusercontent.com/10256841/102705026-e4222200-4293-11eb-8da0-9a03de102329.gif)

Ok, I will try to do it in one process.
