### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by ArmandBernard** [K4YT3X/video2x#43]
A progress bar/percentage has been often asked for but seemed impossible. A possible solution:

Run a side script that tracks the number of files in the waifu2x output folder vs the input folder.
100 * output / input for percentage.

**Comment by K4YT3X** [comment]
Excellent idea. Will do tests on this suggestion, and if it all works out, the progress bar will be back in the next version.

**Comment by K4YT3X** [comment]
I will be using tqdm for the progress bar, so there will be no need for any calculation on our side.

**Comment by K4YT3X** [comment]
I think it's working fine.

![image](https://user-images.githubusercontent.com/21986859/53712518-31aa7200-3e15-11e9-82a4-14aa6f26d193.png)

**Comment by K4YT3X** [comment]
Progress bar has been added in the newest update.
