### ISSUE TITLE
[Mac OS X 10.15.7] Locale error :: locale.getdefaultlocale() <-- (None, 'UTF-8')

### ISSUE THREAD

**Issue by AlfredJKwack** [k4yt3x/video2x#439]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: 4.4.1 - December 13, 2020
- **GUI version**: 2.8.1 - December 13, 2020
- **CLI version**: 4.3.1 - December 13, 2020

## Symptom

Running either the CLI or the GUI version results in the same error related to internationalization.
I'm running video2x on MacOS. All dependencies are satisfied. The issue is not with the app so much as it is with the locale of my shell. Below are the symptoms, what causes them and how it can be remediated. Hopefully this is of use to someone.

## Error Log or Screenshots

```
~/bin/video2x/src (Git#4.8.1 )> python video2x.py                                                                                                                     
Traceback (most recent call last):
  File "/Users/lesparents/bin/video2x/src/video2x.py", line 53, in <module>
    from upscaler import AVAILABLE_DRIVERS
  File "/Users/lesparents/bin/video2x/src/upscaler.py", line 51, in <module>
    language = gettext.translation(
  File "/Users/lesparents/.pyenv/versions/3.9.0/lib/python3.9/gettext.py", line 587, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/Users/lesparents/.pyenv/versions/3.9.0/lib/python3.9/gettext.py", line 558, in find
    for nelang in _expand_lang(lang):
  File "/Users/lesparents/.pyenv/versions/3.9.0/lib/python3.9/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/Users/lesparents/.pyenv/versions/3.9.0/lib/python3.9/locale.py", line 403, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

##  Root cause
```
~/bin/video2x/src (Git#4.8.1 )> locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
The above environment creates a challenge for the localization implementation since `locale.getdefaultlocale()` will give you `(None, 'UTF-8')`. This is the source of the issue... I'm assuming that the `gettext.translation` call doesn't much like it when `default_locale = None`

## Resolution
Either set your locale in your .zshrc or .bashrc file as below (edit as required for your locale)
```
#set locale
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```
Or you can disable 'set locale variables automatically' in iTerm or whatever the equivalent is in the terminal app.

your mileage may vary of course.

**Comment by AlfredJKwack** [comment]
@k4yt3x, feel free to mark this as solved. I only submitted this to help others that may run into this.

**Comment by k4yt3x** [comment]
> @k4yt3x, feel free to mark this as solved. I only submitted this to help others that may run into this.

OK thanks. I'll add a fallback for None as well.
