### ISSUE TITLE
Request: Allow bypassing 'create folder?' request at startup if cache folders are missing

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#44]
As requested in #39 

With the new update to allow creation of the cache folders if missing (if using custom paths) it now adds a user input request to confirm creation upon startup.

The issue is that at the end of the script regardless of whether it is using the default temp folders or custom paths for the cache folders, it will erase the folders outright. So even for custom paths if you originally created the folders, the script will wipe them when one instance of the script finishes and on the next will query the user to create them again. This breaks batch scripts.

Either providing a command line or config option to bypass this query and default it to yes or rewriting the cache erasing section of the script to retain the custom folders would work. Not preferential to either one. Whatever works to get around this. :)

**Comment by K4YT3X** [comment]
Just to let you not wait in despair, I AM working on this. I just haven't decided weather to just fix this folder creating thing alone, or add a `--batch` option to automatically select all default values.

**Comment by K4YT3X** [comment]
You can now use the `-b, --batch` option, and it will skip all those questions.
Referenced commit: https://github.com/K4YT3X/video2x/commit/03d3c165462334db2a12870dabf45a40cc5f772c
