### ISSUE TITLE
Command '['C:\\Users\\sanke\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\sanke\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '2:2:2', '-f', 'png', '-i', 'C:\\Users\\sanke\\AppData\\Local\\Temp\\video2x\\tmpwoz_a94t', '-o', 'C:\\Users\\sanke\\AppData\\Local\\Temp\\video2x\\tmpabzu3rfo']' returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by SanAkhGIT** [k4yt3x/video2x#440]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Please attach the error log.
