### ISSUE TITLE
Signals.SIGABRT:6   Issue

### ISSUE THREAD

**Issue by bkww** [k4yt3x/video2x#441]
I am running this Viedo2X in ubuntu 18.04 environment. And, I am getting following error:

raise subprocess.CalledProcessError(process_status, process.args)
subprocess.CalledProcessError: Command '['/usr/local/bin/waifu2x-converter-cpp', '--png-compression', '5', '--image-quality', '-1', '--block-size', '0', '--processor', '-1', '--jobs', '1', '--model-dir', '/usr/local/bin/models_rgb', '--noise-level', '1', '--mode', 'noise-scale', '--log-level', '1', '--silent', '--tta', '0', '--output-format', 'png', '--scale-ratio', '2.0', '--input', '/tmp/video2x/tmp1iy6sgoc', '--output', '/tmp/video2x/tmp34d_ax1l']' died with <Signals.SIGABRT: 6>.

What can I do to fix this problem?

**Comment by k4yt3x** [comment]
Looks like something else killed waifu2x-converter-cpp's process? I'm not sure what did.
Are you running this on bare metal or Docker?

**Comment by k4yt3x** [comment]
Please reopen if you still want this to be fixed.
