### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by SonOfDiablo** [k4yt3x/video2x#442]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: Where do I find this?
- **Upscaler version**: 4.4.1
- **GUI version**: 2.8.1
- **CLI version**: 4.3.1

## Symptom

Nothing... it starts and then promptly stops.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
```
[32m[+] INFO: Loading files into processing queue[0m
[90m2021-01-04 16:20:03.637398 [+] INFO: Input path(s): D:\Programs\Video2x\Videos\Code.Monkeys.S02E01.The.Story.of.420.mkv[0m
[90m2021-01-04 16:20:03.642549 [+] INFO: File MIME type: video/x-matroska[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2021-01-04 16:20:03.704832 [+] INFO: Input file: D:\Programs\Video2x\Videos\Code.Monkeys.S02E01.The.Story.of.420.mkv[0m
[32m[+] INFO: Reading file information[0m
[90m2021-01-04 16:20:03.706832 [+] INFO: Executing: D:\Programs\Video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\Programs\Video2x\Videos\Code.Monkeys.S02E01.The.Story.of.420.mkv[0m
[90m2021-01-04 16:20:04.810571 [+] INFO: Creating cache directory C:\Users\son_o\AppData\Local\Temp\video2x[0m
[90m2021-01-04 16:20:04.811569 [+] INFO: Extracted frames are being saved to: C:\Users\son_o\AppData\Local\Temp\video2x\tmpvyxzbmc2[0m
[90m2021-01-04 16:20:04.812575 [+] INFO: Upscaled frames are being saved to: C:\Users\son_o\AppData\Local\Temp\video2x\tmpu10n47d4[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2021-01-04 16:20:04.814167 [+] INFO: Executing: D:\Programs\Video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\Programs\Video2x\Videos\Code.Monkeys.S02E01.The.Story.of.420.mkv[0m
Cleaning up cache directory: C:\Users\son_o\AppData\Local\Temp\video2x\tmpvyxzbmc2
Cleaning up cache directory: C:\Users\son_o\AppData\Local\Temp\video2x\tmpu10n47d4
Cleaning up cache directory: C:\Users\son_o\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 810, in run
  File "upscaler.py", line 593, in run
  File "wrappers\ffmpeg.py", line 107, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''
```

**Comment by k4yt3x** [comment]
Do you have the full error log?

**Comment by SonOfDiablo** [comment]
That is all I got from clicking the Copy button when the error happened.
Is there another log I should look at?

**Comment by SonOfDiablo** [comment]
Woops, I'm just an idiot... here it is: [Error Log](https://pastebin.com/eJmMLVWH)

**Comment by k4yt3x** [comment]
Although it looks different, it seems like the errors occurred on the same line of code.
The error seems to have been caused by v2x unable to read FFprobe's output and count the number of frames.
I cannot reproduce this error locally, so do you mind sending the original file over for further inspections?

**Comment by SonOfDiablo** [comment]
Not at all, where do you want me to send the file?

**Comment by SonOfDiablo** [comment]
I really like this issue solved.. so just gonna give it a little bump and again ask "Where would you like me to send the file(s) that are causing this issue?

**Comment by k4yt3x** [comment]
Sorry, I cleared the notification of your message by mistake so I didn't see your response.
You can send it via platforms like Telegram, Google Drive, etc., as long as I can access it.
I used to ask people to send files over on Firefox Send, but unfortunately that's now dead.

**Comment by SonOfDiablo** [comment]
Here is the videos I am having issues with: https://drive.google.com/drive/folders/1Uuz22cNp6v6awIOPGR6ELSeR6v0UT8Jt?usp=sharing

**Comment by k4yt3x** [comment]
Looks like GitHub closed the issue automatically...interesting
I just did some tests and pushed an update. Please check if this works for you: https://github.com/k4yt3x/video2x/actions/runs/506356203

**Comment by SonOfDiablo** [comment]
I got further, but... ran into a new issue.
https://pastebin.com/6ez2q3Be

**Comment by k4yt3x** [comment]
> invalid gpu device

Did you change the GPU settings?

**Comment by SonOfDiablo** [comment]
I didn't catch that.. changed it from 1 to 0 and now it's working like a charm!
Thank you so much for your time and assistance on this issue! :)

**Comment by k4yt3x** [comment]
np. Glad it works now.
