### ISSUE TITLE
Comando '['G:\\GNR_VIDEO-UPSCALING\\Video2XX\\video2x-4.8.1-win32-full\\dependências\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'G:\\GNR_VIDEO-UPSCALING\\Video2XX\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Temp\\video2x\\tmpibk5ox3q', '-o', 'C:\\Temp\\video2x\\tmp94g8dqs6']' retornou status de saída não-zero 3221225477.

### ISSUE THREAD

**Issue by Ewder** [k4yt3x/video2x#444]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Error log please.
