### ISSUE TITLE
4.8.0 regressed Windows 7

### ISSUE THREAD

**Issue by leilei-** [k4yt3x/video2x#448]
## Component Versions

- **Video2X release version**: 4.8.0 and 4.8.1
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

It won't start due to missing api-ms-win-core-path-l1-1-0.dll, and these files aren't part of any redistributable. (outside of a Windows 10 install)

This affects only the video2x executables.  The dependencies execute fine. 

4.7.0 still works, but if Win7 isn't supported anymore in the future, maybe add a bit in the Q&A section about it at least?

**Comment by k4yt3x** [comment]
If it works, great. If it doesn't, I don't think we have the luxury of time or resources to support an EOL operating system.
At least I do not.
