### ISSUE TITLE
Subprocess 7284 exited with code 3221225781

### ISSUE THREAD

**Issue by Legion495** [k4yt3x/video2x#451]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: Waifu2X Caffe
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

It creates the the first frames totally okay as far as I can see (120k frames).
After that is done it seems to error out right away. 
![grafik](https://user-images.githubusercontent.com/15214766/106055471-b7142b00-60ed-11eb-8444-7308b9db39e6.png)
I do use my harddrive as cache which is separate from the OS drive. The same worked on a different PC on the main drive but I got issues with bluesreens (probably hardware issue and I used a questionable SSD).
I ran this 3 times so just to be sure and produce a log file with a neutral filename.

If of any importance I run a 970 for this.
I updated the driver from windowsinstall to latest. It is a fresh Windows.

This is my second PC. I will try use the main drive (Probably will run out of space) just to check. Either way I only use 1 process as I am aware of issues with it.

## Error Log or Screenshots
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5883118/video2x_error.log)

**Comment by Legion495** [comment]
As suspected my guess was totally wrong but it was the only thing I did different to my previous machine.
The error comes up as soon as all extracted files are moved into the "0" folder.

![grafik](https://user-images.githubusercontent.com/15214766/106058487-977f0180-60f1-11eb-9c5e-750228f2fd8e.png)

So any suggestions what to do?

**Comment by k4yt3x** [comment]
970 should be fine...
I don't see any output from waifu2x-caffe.
Try updating your graphics card driver maybe?

**Comment by Legion495** [comment]
It is on the latest version.
I used the basic certified one which comes with Windows update and then updated.
It is the same result.

**Comment by k4yt3x** [comment]
Hmmm that's interesting.
It could be that you're just running out of VRAM. Try decreasing the crop size or try another driver.

**Comment by Legion495** [comment]
Okay I really tried.
Reduced crop size by half.
Reduces my target output size to 1440p.
I changed from driver 461 to 441.

I did run SRMD ncnn Vulkan in between (with whole 12 processes probably the reason it failed) and I guess this is also shown in my logfiles so I had to compress them. But that only produced a black video...

Either way I did run Waifu2X Caffe after that to test all you suggested and those are the logfiles after each try except the 441 driver with half cropsize. This is currently in the works. I upload it as soon as it is done with running into the error
[Desktop.zip](https://github.com/k4yt3x/video2x/files/5892652/Desktop.zip)

I checked the GPU and it doesn't seem to load up at all. 
![grafik](https://user-images.githubusercontent.com/15214766/106251996-fe95d680-6215-11eb-9a8e-665bb33c9d9a.png)

That is my observation so far. I will try other upscalers until I have success. 
I suspect the biggest issue lies within the filetype and or size. 
Do you have a suggestion which upscaler is the most stable to use?

**Comment by Legion495** [comment]
[video2x_error_1440_441_64crop.txt](https://github.com/k4yt3x/video2x/files/5892803/video2x_error_1440_441_64crop.txt)
441 driver, 64crop, 1440p on Caffe.

I will now try several upscalers and notify of success and or fails.
I will continue to try to scale to 3840x2160 and report back on it.
This might take hours and days :)

**Comment by k4yt3x** [comment]
> with whole 12 processes

Actually... it's recommended not to use multi-processing for machine-learning drivers.
The only time you should use that is probably when you're using Anime4KCPP.
Multi-processing other drivers don't give you much performance improvements, and each of the processes consumes a huge amount of VRAM.

**Comment by Legion495** [comment]
> 
> 
> > with whole 12 processes
> 
> Actually... it's recommended not to use multi-processing for machine-learning drivers.
> The only time you should use that is probably when you're using Anime4KCPP.
> Multi-processing other drivers don't give you much performance improvements, and each of the processes consumes a huge amount of VRAM.

Yeah that is why I noted probably the reason it failed but that was with SRMD not with Caffe. I do not use it with more than 1 usually since I first saw you advice against it in a other issue thread. This was just a test for myself. 
It was merely to push through fast so I know it runs. And it did finish within a day.
Furthermore I needed to know if the PC is fine and without any crashes.

I will now test each upscaler anyway under secure options. 1 process, 4k output, ffmpeg set to film. All else is standard. If there are issues I will report them :)
![grafik](https://user-images.githubusercontent.com/15214766/106335449-1f4d4300-628d-11eb-87e1-b1b836b6cca8.png)


This will as said take a lot of time.
We may close this specific issue if you wish.
Still unclear why caffe gets a error... hopefully others report the same so we could pinpoint it.

**Comment by k4yt3x** [comment]
Thanks. I'll keep this issue open. you can keep posting here.
I guess another thing you can try with waifu2x-caffe is to run waifu2x-caffe's GUI independently and see if it errors out or give any useful output.

**Comment by Legion495** [comment]
If you tell me how I would try.
Do I need to download caffe extra or is it included in your downloads?
![grafik](https://user-images.githubusercontent.com/15214766/106351749-56981000-62de-11eb-9870-6a76cac8148c.png)

I treid to just run it seeing if a GUI would show up but it seems to miss .dll files.
![grafik](https://user-images.githubusercontent.com/15214766/106351770-87784500-62de-11eb-88a4-848baddce05b.png)
![grafik](https://user-images.githubusercontent.com/15214766/106351781-96f78e00-62de-11eb-9f0b-2180f3611be0.png)

I will redownload just in case... this concerns me.

**Comment by Legion495** [comment]
Jup now the UI runs.
So I will try again. Probably missed **Microsoft Visual C++ Redistributables 2015**
![grafik](https://user-images.githubusercontent.com/15214766/106352281-0327c100-62e2-11eb-866d-7fdfd634138d.png)

I will check as soon as the current job is done.

**Comment by Legion495** [comment]
Jup that IS the issue. This needs a disclaimer.
**Microsoft Visual C++ Redistributables 2015 required** for Caffe
![grafik](https://user-images.githubusercontent.com/15214766/106361638-481e1880-631f-11eb-82c9-d22ee8c57f90.png)

**Comment by k4yt3x** [comment]
Ah beautiful. I'll write this into the Q&A and the prerequisites.
Thanks.
