### ISSUE TITLE
Setup script looking for invalid waifu2x-converter-cpp

### ISSUE THREAD

**Issue by tecnd** [k4yt3x/video2x#452]
## Component Versions

- **Video2X release version**: 4.8.1
- **Upscaler version**: N/A
- **GUI version**: N/A
- **CLI version**: N/A
- **Setup version**: 2.4.1

## Symptom

When running video2x_setup.py or .exe, script fails when trying to grab waifu2x-converter-cpp from Github.
Fixed by changing the string in line 217 to `r"waifu2x-converter-cpp-win64_v[0-9]*\.zip"`

## Error Log or Screenshots

```
...
Installing waifu2x-converter-cpp
Traceback (most recent call last):
  File ".\video2x_setup.py", line 475, in <module>
    setup.run()
  File ".\video2x_setup.py", line 110, in run
    getattr(self, f"_install_{driver}")()
  File ".\video2x_setup.py", line 224, in _install_waifu2x_converter_cpp
    with zipfile.ZipFile(waifu2x_converter_cpp_zip) as zipf:
UnboundLocalError: local variable 'waifu2x_converter_cpp_zip' referenced before assignment
An error has occurred
Video2X Automatic Setup has failed

Cleaning up temporary files
...
```

**Comment by ThatEvilChickenNextDoor** [comment]
Update: The zip file gets unzipped into a subfolder instead of directly into the directory, so the waifu2x-converter-cpp files need to be moved to the correct location otherwize upscaler.py will fail

**Comment by k4yt3x** [comment]
Thanks for the report. waifu2x-converter-cpp might have changed how they name/structure their releases. I'll take a look.

**Comment by k4yt3x** [comment]
This will no longer be an issue in 5.0.0
