### ISSUE TITLE
Linux cache directory structure issue

### ISSUE THREAD

**Issue by blazini36** [k4yt3x/video2x#454]
## Component Versions

- **CLI version**:
- Version 4.3.1 (AUR)

## Symptom
This isn't the same issue brought up in #181, this is regarding the cache directory and the output directories. 

As for the cache, since these files can be very large and a common thing to do in Linux is to split the /(root) directory from the /home directory by partition or disk, you may not want to dump huge temporary files into the root partition. I typically only give this partition 100gb. I changed the cache directory in video2x.yaml to:
`video2x_cache_directory: "~/.tmp/video2x"`
but it does not respect the "~" as /home/-user-, so I change it to
`video2x_cache_directory: "/home/-user-/.tmp/video2x" `
does not like that either because it can't create the video2x directory in the /home directory. If I create the "/home/-user-/.tmp/video2x" directory with permissions it works for a bit but since it removes the video2x directory on completion it fails on next go. I've tried this multiple times and I think I included the right log. The output driver selected doesn't matter

## Error Log or Screenshots

[video2x_8eoriaok.log](https://github.com/k4yt3x/video2x/files/5905977/video2x_8eoriaok.log)

**Comment by k4yt3x** [comment]
As you know, `video2x_cache_directory` is `null` by default. This tells Video2X to handle both cache directory creation and destruction automatically. However, as you pointed out, the cleanup procedures always deletes the parent directory.

I'll look into this and make the program's actions a bit more reasonable.

**Comment by k4yt3x** [comment]
This will no longer be an issue in 5.0.0
