### ISSUE TITLE
Command '['E:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'E:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\admin\\AppData\\Local\\Temp\\video2x\\tmpzdtm1069', '-o', 'C:\\Users\\admin\\AppData\\Local\\Temp\\video2x\\tmpqbczm99d']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by asheesh9** [k4yt3x/video2x#455]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Attach your error logs please.
I'll reopen this issue when you do.
