### ISSUE TITLE
[Errno 13] Permission denied: 'C:\\Users\\Bloody\\Desktop\\to convert\\IMG-20190801-WA0030_output.png'

### ISSUE THREAD

**Issue by BloodyTakao** [k4yt3x/video2x#456]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

Latest version 2.8.1, GUI

## Symptom

It seems to upscale normaly but stops when it reaches 100%
Says it has permission problems, even though I run it as administrator.

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5953455/video2x_error.log)

**Comment by k4yt3x** [comment]
Hmmm permission error. Not sure why it's happening.
I've seen this kind of errors for a few times, but I'm not sure what's causing it either.
Something with Windows and NTFS permissions.

**Comment by BloodyTakao** [comment]
@k4yt3x is it possible to bypass this "bug" by useing a FAT32 partitioned drive?

**Comment by k4yt3x** [comment]
@BloodyTakao I am not sure. You could try with a USB drive I suppose.

**Comment by BloodyTakao** [comment]
@k4yt3x I just tried it with a USB drive formated on FAT32, it works just fine without any problems, you can keep that in mind if someone else in the future has a similar problem :) thanks for the tipp

**Comment by k4yt3x** [comment]
I just never figured out what's wrong with Windows' NTFS
