### ISSUE TITLE
Command '['D:\\Video2x v4.8.1\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'E:\\Persona Live Concert Archive\\Persona Music Live 2008 - Velvetroom in AKASAKA BLITZ.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\2016GA~1.000\\AppData\\Local\\Temp\\video2x\\tmprv9eof5l\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ARandomGuy231** [k4yt3x/video2x#458]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: 4.4.1
- **GUI version**: 2.8.1
- **CLI version**: Not quite sure

## Symptom

I just tried starting an upscale and it just froze for a while, then threw the error

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/5977094/video2x_error.log)

**Comment by k4yt3x** [comment]
> [image2 @ 0000025636966400] Could not open file : C:\Users\2016GA~1.000\AppData\Local\Temp\video2x\tmprv9eof5l\extracted_99692.png
> av_interleaved_write_frame(): I/O error
> frame=99700 fps=140 q=-0.0 Lsize=N/A time=01:09:17.98 bitrate=N/A speed=5.84x    
> video:13994540kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> Conversion failed!

You might be out of storage space.

**Comment by ARandomGuy213** [comment]
> 
> 
> > [image2 @ 0000025636966400] Could not open file : C:\Users\2016GA~1.000\AppData\Local\Temp\video2x\tmprv9eof5l\extracted_99692.png
> > av_interleaved_write_frame(): I/O error
> > frame=99700 fps=140 q=-0.0 Lsize=N/A time=01:09:17.98 bitrate=N/A speed=5.84x
> > video:13994540kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> > Conversion failed!
> 
> You might be out of storage space.

I tried moving to a different drive. Same issue.

**Comment by ARandomGuy213** [comment]
> 
> 
> > > [image2 @ 0000025636966400] Could not open file : C:\Users\2016GA~1.000\AppData\Local\Temp\video2x\tmprv9eof5l\extracted_99692.png
> > > av_interleaved_write_frame(): I/O error
> > > frame=99700 fps=140 q=-0.0 Lsize=N/A time=01:09:17.98 bitrate=N/A speed=5.84x
> > > video:13994540kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> > > Conversion failed!
> > 
> > 
> > You might be out of storage space.
> 
> I tried moving to a different drive. Same issue.

Ok I just tried doing it again and its been stuck on "Main process waiting for subprocesses to exit" for 34mins

**Comment by k4yt3x** [comment]
Yeah if it's running then leave it alone. Frame extraction does take a while.
