### ISSUE TITLE
Command '['C:\\Users\\Neil\\Documents\\Video2X\\video2x-4.8.1-win32-full\\dependencies\\anime4kcpp\\CLI\\Anime4KCPP_CLI\\Anime4KCPP_CLI', '--passes', '2', '--pushColorCount', '2', '--strengthColor', '0.3', '--strengthGradient', '1.0', '--zoomFactor', '2.0', '--threads', '16', '--preFilters', '4', '--postFilters', '40', '--HDNLevel', '1', '--platformID', '0', '--deviceID', '0', '--codec', 'mp4v', '--forceFps', '0.0', '--input', 'C:\\Users\\Neil\\AppData\\Local\\Temp\\video2x\\tmp6zr3iwwh', '--output', 'C:\\Users\\Neil\\AppData\\Local\\Temp\\video2x\\tmpdf_m8wqt']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by neilk59** [k4yt3x/video2x#460]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version*4.4.1*:
- **GUI version*2.8.1*:
- **CLI version**:

## Symptom

I tried upscaling for the first time, using Anime4kccp and Waifu2x Caffe. Both failed after less than 5 minutes. Can you see the problem in the error log?

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5999094/video2x_error.log)

**Comment by k4yt3x** [comment]
Hmmm that's interesting. A4k threw an error without any descriptions.
I'm not quite sure what's wrong with the information given.

**Comment by neilk59** [comment]
I'm new to the program. I guess I will continue to experiment since nothing obvious jumps out at you.
Thank you.

**Comment by k4yt3x** [comment]
Please try running waifu2x-caffe and send the error log of that. Maybe waifu2x-caffe can produce something useful.

**Comment by neilk59** [comment]
Hi,Here us the error log from waifu2x-caffeNeil
    On Friday, February 19, 2021, 12:20:16 PM CST, K4YT3X <notifications@github.com> wrote:  
 
 


Please try running waifu2x-caffe and send the error log of that. Maybe waifu2x-caffe can produce something useful.

**Comment by neilk59** [comment]
Sorry, Log file was blank
    On Friday, February 19, 2021, 02:57:19 PM CST, Neil Koenig <neilk59@yahoo.com> wrote:  
 
  Hi,Here us the error log from waifu2x-caffeNeil
    On Friday, February 19, 2021, 12:20:16 PM CST, K4YT3X <notifications@github.com> wrote:  
 
 


Please try running waifu2x-caffe and send the error log of that. Maybe waifu2x-caffe can produce something useful.

**Comment by neilk59** [comment]
After it failed using waifu2x-caffe, but generated a blank Log file, I am running it again. This time it may be working correctly. It is set to waifu2x-caffe, but I change from GPU to CPU on the Driver Settings Tab. So far, so good.Neil
    On Friday, February 19, 2021, 12:20:16 PM CST, K4YT3X <notifications@github.com> wrote:  
 
 


Please try running waifu2x-caffe and send the error log of that. Maybe waifu2x-caffe can produce something useful.

**Comment by k4yt3x** [comment]
CPU is much slower at this kind of stuff than GPU. Ideally, don't ever use CPU.
Do you have an NVIDIA GPU?

**Comment by neilk59** [comment]
Yes. A Nvidia GeForce GT530 1GB PCI Express. Not particularly high end, I know.
The good news is Video2X hasn't crashed with it set to CPU. The bad news is, it's been processing an eight minute video for almost 24 hours now and still isn't very far into the process. I may stop the run.
I really appreciate your ongoing input.


    On Saturday, February 20, 2021, 11:48:46 AM CST, K4YT3X <notifications@github.com> wrote:  
 
 


CPU is much slower at this kind of stuff than GPU. Ideally, don't ever use CPU.
Do you have an NVIDIA GPU?

**Comment by k4yt3x** [comment]
That may not work... It might take you another 24 hrs without anything.
You'll need something at least GTX. Look at the benchmarks in the Wiki page.

**Comment by mirh** [comment]
The GT 530 isn't just slow per se, it's an old Fermi card that may or may not have decent-enough drivers. 
On the other hand I was getting a similar error (i.e. just a crash in ucrtbase.dll) even on my 950M laptop with 460.89, only with waifu2x-caffe gpu/cudnn. 
I'll try to see if I can get some better insight.
