### ISSUE TITLE
Unrecognized arguments: -m gpu

### ISSUE THREAD

**Issue by james10424** [k4yt3x/video2x#461]
https://github.com/k4yt3x/video2x/wiki/Step-By-Step-Tutorial
I was following this tutorial and it gives `video2x: error: unrecognized arguments: -m gpu` when I run `python video2x.py -m gpu -r 2 -i ....`
I find no `-m` argument in the code. Is gpu not available anymore?

**Comment by k4yt3x** [comment]
`-m gpu` is now an argument specific to waifu2x-caffe. The step-by-step tutorial is outdated.
If you use waifu2x-caffe right now, it will  be specified automatically.
