### ISSUE TITLE
Command '['C:\\Users\\Administrator\\Downloads\\e9e41198467cf32e2f8eec81a9558408_1613876600.zip\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\Administrator\\Downloads\\e9e41198467cf32e2f8eec81a9558408_1613876600.zip\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\video2x\\tmp_livni6e', '-o', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\video2x\\tmpmrjfjl1p']' returned non-zero exit status 3221225595.

### ISSUE THREAD

**Issue by wzj33300** [k4yt3x/video2x#466]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
No error logs provided.
