### ISSUE TITLE
Command '['F:\\wew\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'F:\\please.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\sarag\\AppData\\Local\\Temp\\video2x\\tmp278hlpb4\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by sizlh** [k4yt3x/video2x#467]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version 4.8.1**:
- **Upscaler version**:
- **GUI version 2.8.1**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

some kind of error

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
 

[video2x_error.zip](https://github.com/k4yt3x/video2x/files/6017166/video2x_error.zip)
![Screenshot (108)](https://user-images.githubusercontent.com/79390012/108615017-694ac400-7408-11eb-840c-95ed5f24558d.png)

**Comment by k4yt3x** [comment]
> av_interleaved_write_frame(): I/O error
You might be out of storage.
