### ISSUE TITLE
C:\Users\Erdal\AppData\Local\video2x\ffmpeg\bin

### ISSUE THREAD

**Issue by erenerdal2701** [k4yt3x/video2x#468]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
No error logs attached.

**Comment by erenerdal2701** [comment]
thanks it is working now


K4YT3X <notifications@github.com>, 21 Şub 2021 Paz, 14:58 tarihinde şunu
yazdı:
