### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Spirxty** [k4yt3x/video2x#469]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X version**: 4.8.1
- **Upscaler version**: couldn't find it
- **GUI version**: couldn't find it
- **CLI version**: couldn't find it

## Symptom
I tried to upscale a video and it didn't work, I got the error right after.

## Error Log or Screenshots

[32m[+] INFO: Loading files into processing queue[0m
[90m2021-02-23 01:10:22.305212 [+] INFO: Input path(s): F:\FILMS\Interstella 5555.mp4[0m
[90m2021-02-23 01:10:22.305728 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2021-02-23 01:10:22.309180 [+] INFO: Input file: F:\FILMS\Interstella 5555.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2021-02-23 01:10:22.309180 [+] INFO: Executing: C:\Users\Spirxty\Documents\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i F:\FILMS\Interstella 5555.mp4[0m
[90m2021-02-23 01:10:22.535176 [+] INFO: Creating cache directory C:\Users\Spirxty\AppData\Local\Temp\video2x[0m
[90m2021-02-23 01:10:22.535672 [+] INFO: Extracted frames are being saved to: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmppeijw_17[0m
[90m2021-02-23 01:10:22.536168 [+] INFO: Upscaled frames are being saved to: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmp6rd07dnu[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2021-02-23 01:10:22.537159 [+] INFO: Executing: C:\Users\Spirxty\Documents\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 F:\FILMS\Interstella 5555.mp4[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''
[32m[+] INFO: Loading files into processing queue[0m
[90m2021-02-23 01:12:46.278434 [+] INFO: Input path(s): F:\FILMS\Interstella 5555.mp4[0m
[90m2021-02-23 01:12:46.278930 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2021-02-23 01:12:46.280417 [+] INFO: Input file: F:\FILMS\Interstella 5555.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2021-02-23 01:12:46.280915 [+] INFO: Executing: C:\Users\Spirxty\Documents\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i F:\FILMS\Interstella 5555.mp4[0m
[90m2021-02-23 01:12:46.332994 [+] INFO: Extracted frames are being saved to: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmpx4kntcsu[0m
[90m2021-02-23 01:12:46.334978 [+] INFO: Upscaled frames are being saved to: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmp_1n0f62m[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2021-02-23 01:12:46.336466 [+] INFO: Executing: C:\Users\Spirxty\Documents\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 F:\FILMS\Interstella 5555.mp4[0m
Cleaning up cache directory: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmpx4kntcsu
Cleaning up cache directory: C:\Users\Spirxty\AppData\Local\Temp\video2x\tmp_1n0f62m
Cleaning up cache directory: C:\Users\Spirxty\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''

**Comment by k4yt3x** [comment]
Please try the latest nightly build.

**Comment by roarkindrake** [comment]
Just ran into this today and not sure how to fix it. Any tips?

**Comment by k4yt3x** [comment]
@roarkindrake the tip is right above your response.

**Comment by Tirpitz721** [comment]
> Please try the latest nightly build.

How do you apply this to the Video2X 4.8.1 GUI version?  Just downloaded that as I have no idea how Python works.  Tried a video and got the same error as above.  Downloaded the newest nightly build, but I'm not sure what to do with it.

**Comment by k4yt3x** [comment]
I can't quite patch an already-released version since:

- I no longer have the dev environment for 4.8.1
- Unpacking PyInstaller executables is a nightmare

What I can suggest you to do is to re-encode the video, which should solve this problem. You could do something like:

```shell
ffmpeg -i input.mp4 -c:v libx264 -c:a copy output.mp4
```

Then you can use the re-encoded output.mp4 for upscaling, which should work without problems.

**Comment by tony8077616** [comment]
> Please try the latest nightly build.

When will Windows Version update?
The nightly version is only for linux

**Comment by CPLJimmy** [comment]
The simple answer is that this error from the GUI version means that the source video is in an unsupported format.
