### ISSUE TITLE
Cant seem to get waifu2x-converter-cpp to work.

### ISSUE THREAD

**Issue by SnaxxNZ** [K4YT3X/video2x#47]
Been playing around with this for the last hour or so and I can't get waifu2x-converter-cpp to work.
CPU works fine but every time I use -d waifu2x_converter I run into the same problem.

The video will extract fine but when it comes time to upscale I keep getting a "cv::imread failed" error and then a message saying the process was successfully done.

**Comment by K4YT3X** [comment]
I'm aware of this issue, and I have communicated with the original author of waifu2x-converter-cpp. The original author already had it fixed, but didn't release a new update yet.
For now, please try using this version of waifu2x build: https://share.toji.site/w2x_input_fix.7z

Here's the related issue:
https://github.com/DeadSix27/waifu2x-converter-cpp/issues/109

**Comment by K4YT3X** [comment]
I just pushed a temporary fix for the waifu2x-converter-cpp bug before they release the new build.
You may now clone the newest version of video2x and use it the normal way.
