### ISSUE TITLE
Outdated docker images?

### ISSUE THREAD

**Issue by AbelVM** [k4yt3x/video2x#472]
The image tagged `latest` contains video2x version 4.2 and the recommended tag `4.6.0` contains version 4.1.1

Are they outdated? Is this just a labeling issue?

**Comment by k4yt3x** [comment]
`4.6.0` is a release number. I believe the `4.1.1` you're seeing is the CLI's version, which is a version number specific to that component.

**Comment by AbelVM** [comment]
Roger that! Closing this ticket and sorry for the noise
