### ISSUE TITLE
Image size (400000000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

### ISSUE THREAD

**Issue by wzx1996** [k4yt3x/video2x#473]
## Component Versions

- **Video2X release version**: 4.7.0
- **Upscaler version**: 4.4.0
- **GUI version**: 2.8.0
- **FFMpeg Build**: ffmpeg-20200831-4a11a6f-win64-static

## Symptom

I was testing the upscaling function and decided to try 8x upscale a 2500x2500px image. The result is image size (20000x20000px) exceeds limit.

I'm posting this as a bug because it was triggered by the output size, not the input size, which makes the error message a bit confusing and such error probably should not be triggered in this case (since it's the output which would no way be a decompression bomb).

===
_(The following is more of a feature request related to this issue, if this issue isn't actually a bug.)_

There doesn't seem to be any option to increase the limit (and I have no idea if it's a hard limit by _Waifu 2X Caffe_ driver, or FFMPEG), but such option (or capability) should exist, in my opinion, for the following reasons:

1. When preparing for high resolution (600ppi or higher) printing on large physical size, the limit of 179MP might be surpassed. As far as I know, currently one practical example is those full body waifu pillows, which are both large in physical size and are printed at high resolution. (Kinda a weird example but the point is this limit isn't that hard to reach.)

2. Some people might use AI supersampling as a way to achieve "lossless" (in detail resolution) anti-aliasing, and with an image size limit being in place it limits the possibility to do so on larger images or at higher AA multipliers. 

## Error Log

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6054685/video2x_error.log)

**Comment by k4yt3x** [comment]
I've just check the error log. PIL seems to be responsible for this problem. It is possible to manually adjust the upper limit of this value by setting the value of `PIL.Image.MAX_IMAGE_PIXELS`. I can add that later. You could also add this to the beginning of the `upscaler.py` file for now.

**Comment by wzx1996** [comment]
Well, for the compiled Windows build it's not possible to edit the Python script. And I don't feel like setting up Python runtime and run the uncompiled version at this point because I don't have a need for super high resolution printing yet.

By the way, is it possible to have the pixel limit only applied to the input image/video but not intermediate or output image/video? That would further future-proof the tool, and can probably mean that the pixel limit doesn't have to go too high.

Both for digital painting and for video shooting it's hard to get past 100MP due to hardware limits, making the current pixel limit sufficient for input image/video, and only the output can go past that when printing at both large scale and high resolution.

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/161205044-8bf686c0-5bc6-4449-bb33-a6e56829be6a.png)
