### ISSUE TITLE
C:\Users\raghusai.KALAPALA\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by SAAHO9779** [k4yt3x/video2x#474]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6056731/video2x_error.log)

- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Which version are you using? It seems like you're using light without running the setup script.
