### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SAAHO9779** [k4yt3x/video2x#475]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.8.1
- **Upscaler version**:
- **GUI version**:2.8.1
- **CLI version**:

## Symptom
It is not working. It's showing the main process is waiting for the subprocesses to exit. But it's never happening.
In this section, briefly describe what's going on.
![Screenshot (173)](https://user-images.githubusercontent.com/79498464/109417664-92f88200-79ea-11eb-9986-edea6fd14d6b.png)

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by DieBambusleitung** [comment]
Same problem here. I even tried to install it by the python installer. My CPU usage is at 100% at the time video2x is running, but my gpu (GTX 970, newest drivers) won't get hit. I also tried several drivers (Waifu2X Caffe, Waifu2X NCNN Vulkan, Waifu2X Converter CPP), but it still doesn't work.

**Comment by k4yt3x** [comment]
Just wait. FFmpeg is running frame extraction.
