### ISSUE TITLE
Upscaling Error 3221226505

### ISSUE THREAD

**Issue by Marly212** [k4yt3x/video2x#477]
## Component Versions

- Video2X release version: 4.8.1 Full release

## Symptom

I am getting the error "returned non-zero exit status 3221226505" after trying to Upscale a video with waifu2xCaffe.
I tested with Scale Ratio and Manuel height and width and both times the error.
I also tested if waifu2x can use cuDNN (Screenshot below)
The log is also Below.

## Error Log or Screenshots

![grafik](https://user-images.githubusercontent.com/42452096/109810183-7f872a00-7c29-11eb-8194-3c5e0bf7d321.png)

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6076100/video2x_error.log)

**Comment by k4yt3x** [comment]
> F0303 13:56:47.676195  8264 cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

Have you tired updating your GPU driver?

**Comment by Marly212** [comment]
Ok so I updated my GPU Drivers and now its a 50/50 Chance if its gonna work or not, I am fine with this so thanks for the help
