### ISSUE TITLE
[Feature request] Use waifu2x-ncnn-vulkan's recursive scaling

### ISSUE THREAD

**Issue by CobaltSpace** [k4yt3x/video2x#478]
## Description

waifu2x-ncnn-vulkan supports recursive scaling using `-s` (1/2/4/8/16/32), so this can be used instead of running waifu2x-ncnn-vulkan twice to get 4x scaling.

## Sources

https://github.com/nihui/waifu2x-ncnn-vulkan/commit/dacd97df7a147545ba89262e48ed3e1d66bbee9a

https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20210210

https://github.com/nihui/waifu2x-ncnn-vulkan

**Comment by CobaltSpace** [comment]
Looking at this myself, recursive scaling has higher system requirements, so for maybe this request should be ignored for higher compatibility.

**Comment by timsu92** [comment]
At the present, this seems not working it self. [issue in the repository](https://github.com/nihui/waifu2x-ncnn-vulkan/issues/138)

**Comment by k4yt3x** [comment]
This might be a new feature. When I last checked I think it only supported 2.

**Comment by ArchieMeng** [comment]
You may use my waifu2x-ncnn-vulkan-python build. It supports any ratio sizes which are not limited to powers of 2: 1/2/4/8/16/32.

**Comment by mirh** [comment]
This was fixed in their last version.
