### ISSUE TITLE
Command '['C:\\Users\\User\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\srmd-ncnn-vulkan', '-n', '3', '-s', '2', '-t', '400', '-m', 'C:\\Users\\User\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\models-srmd', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\User\\AppData\\Local\\Temp\\video2x\\tmps8ltg0ve', '-o', 'C:\\Users\\User\\AppData\\Local\\Temp\\video2x\\tmp89xe5c_u']' returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by qwertli** [k4yt3x/video2x#479]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
No error logs attached.
