### ISSUE TITLE
TypeError: ask() got an unexpected keyword argument 'batch'

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#48]
With the new batch argument added I'm now seeing the above error when attempting to use it. Tried to debug on my own but unfortunately not seeing what is up. Here's the full error message. Tried both -b and --batch at the end of the command

> [!] WARNING: Specified cache folder/directory Z:\video2x does not exist
Traceback (most recent call last):
  File "video2x.py", line 207, in <module>
    if Avalon.ask('Create folder/directory?', default=True, batch=args.batch):
TypeError: ask() got an unexpected keyword argument 'batch'

**Comment by cr08** [comment]
Never mind. My mistake. I missed the requirement to update avalon_framework. Did so and all's well.

**Comment by K4YT3X** [comment]
@cr08 yeah for the batch to work well, I had to update the framework as well
