### ISSUE TITLE
Calculate Rate/FPS since "driver" starts

### ISSUE THREAD

**Issue by mirh** [k4yt3x/video2x#484]
## Component Versions

- **Video2X release version**: 4.8.1

## Symptom

Framerate is calculated since the moment the "start" button is pressed, not when the "upscaling driver" has actually started. 
Its denominator should only be the time elapsed since ffmpeg has finished to extracts frames.

**Comment by k4yt3x** [comment]
This is a known issue that's a bit annoying to fix.
The ideal way to carry this out will be to read the progress information directly from tqdm, but tqdm doesn't expose such an interface which makes it hard.
I'll see what I can do with it. For now, look at the console for more accurate information.
