### ISSUE TITLE
Wrong input video framerate readings (r_frame_rate/ avg_frame_rate)

### ISSUE THREAD

**Issue by tomini** [k4yt3x/video2x#485]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1 & 4.7.0
- **Upscaler version**: Waifu2x-caffe
- **GUI version**: 2.8.1 & 2.8.0
- **CLI version**: don't know :-(

## Symptom

Output video is faster. Player ends at 00:09 and the original video has 00:17. Output video still shows 17secs in File Explorer, but the video ends at the 9s mark and audio continues.
Original video has: 12,05 FPS
Output video has: 25,08 FPS

What did I do wrong?

Thank you.

## Error Log or Screenshots (I'm uploading info about 4.8.1 output file, because the only thing that changed between 4.7.0 is bitrate)
<details><summary>Original/Input (MP4 version):</summary>
<p>

```
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "Constrained Baseline",
      "codec_type": "video",
      "codec_time_base": "23333/562240",
      "codec_tag_string": "avc1",
      "codec_tag": "0x31637661",
      "width": 320,
      "height": 200,
      "coded_width": 320,
      "coded_height": 208,
      "closed_captions": 0,
      "has_b_frames": 0,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "8:5",
      "pix_fmt": "yuv420p",
      "level": 32,
      "chroma_location": "left",
      "refs": 1,
      "is_avc": "true",
      "nal_length_size": "4",
      "r_frame_rate": "289/12",
      "avg_frame_rate": "281120/23333",
      "time_base": "1/12048",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 209996,
      "duration": "17.429947",
      "bit_rate": "477466",
      "bits_per_raw_sample": "8",
      "nb_frames": "210",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "creation_time": "2021-03-27T00:08:54.000000Z",
        "language": "und",
        "handler_name": "VideoHandler",
        "encoder": "AVC Coding"
      }
    },
    {
      "index": 1,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_time_base": "1/44100",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 1,
      "channel_layout": "mono",
      "bits_per_sample": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/44100",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 769023,
      "duration": "17.438163",
      "bit_rate": "194032",
      "max_bit_rate": "192000",
      "nb_frames": "751",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "creation_time": "2021-03-27T00:08:54.000000Z",
        "language": "und",
        "handler_name": "SoundHandler"
      }
    }
```
</p>
</details>

<details><summary>Output video (double framerate issue):</summary>
<p>

```
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High",
      "codec_type": "video",
      "codec_time_base": "27901/1344000",
      "codec_tag_string": "avc1",
      "codec_tag": "0x31637661",
      "width": 1920,
      "height": 1200,
      "coded_width": 1920,
      "coded_height": 1200,
      "closed_captions": 0,
      "has_b_frames": 2,
      "pix_fmt": "yuv420p",
      "level": 50,
      "chroma_location": "left",
      "refs": 1,
      "is_avc": "true",
      "nal_length_size": "4",
      "r_frame_rate": "289/12",
      "avg_frame_rate": "672000/27901",
      "time_base": "1/16000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 139504,
      "duration": "8.719000",
      "bit_rate": "2830106",
      "bits_per_raw_sample": "8",
      "nb_frames": "210",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "VideoHandler"
      }
    },
    {
      "index": 1,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_time_base": "1/44100",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 1,
      "channel_layout": "mono",
      "bits_per_sample": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/44100",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 769024,
      "duration": "17.438186",
      "bit_rate": "194032",
      "max_bit_rate": "194032",
      "nb_frames": "751",
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "SoundHandler"
      }
    }
```
</p>
</details>

<details><summary>SMACKER (originally original video :D)</summary>
<p>

```
{
  "streams": [
    {
      "index": 0,
      "codec_name": "smackvideo",
      "codec_long_name": "Smacker video",
      "codec_type": "video",
      "codec_time_base": "0/1",
      "codec_tag_string": "SMK2",
      "codec_tag": "0x324b4d53",
      "width": 320,
      "height": 200,
      "coded_width": 320,
      "coded_height": 200,
      "closed_captions": 0,
      "has_b_frames": 0,
      "pix_fmt": "pal8",
      "level": -99,
      "refs": 1,
      "r_frame_rate": "1000/83",
      "avg_frame_rate": "0/0",
      "time_base": "83/1000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 210,
      "duration": "17.430000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "smackaudio",
      "codec_long_name": "Smacker audio",
      "codec_type": "audio",
      "codec_time_base": "1/22050",
      "codec_tag_string": "SMKA",
      "codec_tag": "0x414b4d53",
      "sample_fmt": "s16",
      "sample_rate": "22050",
      "channels": 1,
      "channel_layout": "mono",
      "bits_per_sample": 0,
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/44100",
      "start_pts": 0,
      "start_time": "0.000000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    }
```
</p>
</details>

**Comment by k4yt3x** [comment]
>      "r_frame_rate": "289/12",
>      "avg_frame_rate": "281120/23333",

I think what happened is that these two values aren't matching. The first value suggests that video has a frame rate of 24 FPS, where the second one says 12 FPS. I think v2x read `r_frame_rate`, so it assembled the output video as 24 FPS, which is twice as fast.

I'm actually not sure how to solve this problem. Some videos have mistmatching `r_frame_rate` and `avg_frame_rate` values, and I'm not sure how to tell which one to read.

**Comment by tomini** [comment]
> > ```
> >  "r_frame_rate": "289/12",
> >  "avg_frame_rate": "281120/23333",
> > ```
> 
> I think what happened is that these two values aren't matching. The first value suggests that video has a frame rate of 24 FPS, where the second one says 12 FPS. I think v2x read `r_frame_rate`, so it assembled the output video as 24 FPS, which is twice as fast.
> 
> I'm actually not sure how to solve this problem. Some videos have mistmatching `r_frame_rate` and `avg_frame_rate` values, and I'm not sure how to tell which one to read.

I saw that you wrote this reply to someone like a year or two ago and I thought it was fixed. So there isn't like a toggle or perhaps a fixed frame rate to change? Like when I can choose forced resolution of output...then I could do that with output FPS fixed to 12.
Or is the problem in input? Should I re-encode it or something?
Thanks

**Comment by k4yt3x** [comment]
A quick fix for it is to re-encode it. I am not sure which key should be used. I see a lot of video have conflicting values, but the correct value could be stored in either of the two keys.

Providing a way to edit this value or selecting between the two keys might be a good idea. I'll look into implementing it in the next version (but I don't know when that'll happen). For now, please just try re-encoding the video.

**Comment by tomini** [comment]
> A quick fix for it is to re-encode it. I am not sure which key should be used. I see a lot of video have conflicting values, but the correct value could be stored in either of the two keys.
> 
> Providing a way to edit this value or selecting between the two keys might be a good idea. I'll look into implementing it in the next version (but I don't know when that'll happen). For now, please just try re-encoding the video.

### **URGENT**
I forced the FPS to 12.048 and it is fine now.
But I ran 5:59 minute video and it's stuck at 46%...
`46%|###########################################################9                                                                       | 1983/4331 [2:38:51<3:02:43,  4.67s/it]`
What should I do? Can I somehow backup upscaled and extracted frames and continue from when I start new upscale?
I spent a lot of time on this... I'm reaaally scr*wed.
Thank you.

PS: I'm fine with making a chat if you want to.

**Comment by k4yt3x** [comment]
I can chat, but I only use [Telegram](https://t.me/k4yt3x) and XMPP (k4yt3x@xmpp.k4yt3x.com).

Could you please send a screenshot of what you see in the console? Are there any errors in the output?

**Comment by attania** [comment]
Hey, I'm having the same issues as the user above--my avg_frame_rate is accurate but my r_frame_rate isn't. I've tried re-encoding the video a couple of times through FFMPEG but to no avail--is there anyway to get video2x to read the avg_frame_rate rather than the r_frame_rate?

Running the video through makes the output file go 2x or 3x faster due to a different r_frame_rate (avg_frame_rate is at 124225/5181, r_frame_rate is 60000/1001)

**Comment by k4yt3x** [comment]
@attania Did you re-encode the video instead of re-encoding it?
