### ISSUE TITLE
RealSR Driver Setting for "Jobs" is always ignored

### ISSUE THREAD

**Issue by alexmaurizio** [k4yt3x/video2x#486]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: RealSR NCNN Vulkan
- **GUI version**: 2.8.1 (reported in top bar, shouldn't it be 4.8.1?)

## Symptom

Jobs parameters from RealSR NCNN Vulkan do not get passed in processing thread, resulting in a default of 1:1:1 and seriously cripping performances.

When changing "processes" instead, it gets changed to N:N:N, based on the number of process setted up (without the ability to setup a proper job string)

This is an error on the GUI part, since the Jobs option in RealSR is useless and the Processes option in Main tab is misleading for this.

## Error Log or Screenshots

![2021-03-27 (10)](https://user-images.githubusercontent.com/15074818/112736995-64bd8200-8f57-11eb-8318-1f2cf180dbd6.png)

**Comment by alexmaurizio** [comment]
(The same will happen for other drivers too)

**Comment by k4yt3x** [comment]
`Processes` on the main menu overwrites this parameter. Change that instead of this.
This design may be changed to be more intuitive in a distant future release.

**Comment by alexmaurizio** [comment]
@k4yt3x I know that the `Processes` will always override that parameter, and that is why this is a bug and not only something "not clear": the Jobs label is 100% ignored because Processes will be at least 1, overriding the string to 1:1:1.

There is no ability to fine-tune or use multiple GPUs (eg: I want to have 1 load thread, 2 processing threads on each GPU and 1 save thread, i'll have to input 1:2,2:1), but there is no way since it will always get overrided to a single, always constant process number

**Comment by k4yt3x** [comment]
That is how it's designed for now. Let process be `n` then job will always be `n:n:n`. The more fine-grained control is possible and it will be in a future release. For now, I'm waiting on a few FFIs to be in place so I can get back into this project again. I'm also waiting for this semester to be over.

**Comment by alexmaurizio** [comment]
Thanks, and GL on the semester :)
