### ISSUE TITLE
Command '['C:\\Users\\ALEX\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'C:\\Users\\ALEX\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '704', '--scale_height', '576', '--input_path', 'C:\\Users\\ALEX\\AppData\\Local\\Temp\\video2x\\tmp0qhol009\\0', '--output_path', 'C:\\Users\\ALEX\\AppData\\Local\\Temp\\video2x\\tmpve88moh4']' returned non-zero exit status 3221226505.

### ISSUE THREAD

**Issue by GEROSPRUT** [k4yt3x/video2x#487]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by GEROSPRUT** [comment]
![Error](https://user-images.githubusercontent.com/81963401/113568225-d1e8ab80-9618-11eb-96d2-ed1b4ad0c3c0.JPG)

**Comment by GEROSPRUT** [comment]
![Error](https://user-images.githubusercontent.com/81963401/113568376-1c6a2800-9619-11eb-90b6-5977c6e05645.JPG)

**Comment by k4yt3x** [comment]
Why did you close this issue? Did you figure it out?
