### ISSUE TITLE
Config for dynamically deleting source images

### ISSUE THREAD

**Issue by Keridos** [k4yt3x/video2x#490]
## Description
Config option to delete the source images of already upscaled png images. 
Since they use up a LOT of storage. (270GB for a 1080p movie to be upscaled -> ~1100GB of upscaled images with 2x scaling)

**Comment by k4yt3x** [comment]
Hmm. This has already been implemented:

https://github.com/k4yt3x/video2x/blob/master/src/image_cleaner.py

**Comment by utack** [comment]
Does not seem operational for me  
Is this a bug or is the function implemented but not in use yet?

**Comment by k4yt3x** [comment]
It should be functioning... I didn't write it and i don't remember how it was implemented, it may be a bug. However, the next version will be using a frame server and there will no longer be on-disk cache images.
