### ISSUE TITLE
Linux dependencies Requirements Python3

### ISSUE THREAD

**Issue by tidypy** [k4yt3x/video2x#491]
## Description
I can't install this,  i've cloned, updated, ect.  
1. the setup.Ubuntu.sh  does nothing.
2. a Quest to install the correct Driver is not working.  
3. I cloned and install nearly all drivers, yet it will not find a single driver.  (waifu2x: vulkan, cpp, etc...)
2. the Requirements for PIP do nothing.  pip install -r requirements.txt  does nothing.
3. most commands run as Python**3** and not 'Python' so we have nothing in the right app space.  system variables are incorrect in instructions,  nor do I know how to edit Path. 
4. "Command not found" after build issues.
5. **AppImage** needed, not SnapD,  although SnapD version is not working either. 

python3 video2x_gui.py 
Traceback (most recent call last):
  File "video2x_gui.py", line 12, in <module>
    from upscaler import UPSCALER_VERSION
  File "/home/l/video2x/src/upscaler.py", line 17, in <module>
    from progress_monitor import ProgressMonitor
  File "/home/l/video2x/src/progress_monitor.py", line 16, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by k4yt3x** [comment]
Try the new docker image: https://github.com/k4yt3x/video2x/pkgs/container/video2x
