### ISSUE TITLE
Is Video2x temporarily coherent?

### ISSUE THREAD

**Issue by bryanndg** [k4yt3x/video2x#492]
## Description
All models used by the programme are intended for SR imaging. I understand that there is no temporal coherence, as was the case in TecoGAN. Could you confirm this for me.

Briefly describe the feature that you'd like Video2X to have.

**Comment by k4yt3x** [comment]
Frame interpolation has existed in alpha versions that were never available to the public.
There are already plans to add this feature into the master branch such as #358.
Ideally, I'll add them after rewriting v2x. You can read more about that here: https://t.me/video8x/13
