### ISSUE TITLE
C:\Users\Intel\Desktop\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin

### ISSUE THREAD

**Issue by nurik200max** [k4yt3x/video2x#493]
![Снимок](https://user-images.githubusercontent.com/82484531/114643873-4cd85300-9cf8-11eb-8894-072914617ec5.PNG)

**Comment by k4yt3x** [comment]
Hmmm that doesn't make sense...
Check if `ffmpeg.exe` exists under `dependencies\ffmpeg\bin`.
