### ISSUE TITLE
VOB无法转换

### ISSUE THREAD

**Issue by sakura2333** [k4yt3x/video2x#494]
**vob文件无法处理
同目录下MP4文件可以处理**

**release为最新**
**log：**

<details>
[90m2021-04-15 20:45:39.139998 [+] INFO: Executing: D:\工具\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 C:\Users\U2\Pictures\VTS_01_1.VOB[0m
清理缓存目录：C:\Users\U2\AppData\Local\Temp\video2x\tmpi37h0m_y
清理缓存目录：C:\Users\U2\AppData\Local\Temp\video2x\tmpph7sx9ga
清理缓存目录：C:\Users\U2\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''

**ffprobe运行结果：**
**简化信息**
ffprobe -v quiet -print_format json -show_format -show_streams -i /Volumes/D/动画/VTS_01_1.VOB | grep frame
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "has_b_frames": 1,
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "30000/1001",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",

ffprobe -v quiet -print_format json -show_format -show_streams -i /Volumes/D/动画/2.mp4  | grep frame
            "has_b_frames": 2,
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "nb_frames": "32704",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            **"nb_frames": "63939",**

**原始信息：**
VOB：
ffprobe -v quiet -print_format json -show_format -show_streams -i /Volumes/D/动画/VTS_01_1.VOB 
{
    "streams": [
        {
            "index": 0,
            "codec_name": "dvd_nav_packet",
            "codec_long_name": "DVD Nav packet",
            "codec_type": "data",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "id": "0x1bf",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 25257,
            "start_time": "0.280633",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        },
        {
            "index": 1,
            "codec_name": "mpeg2video",
            "codec_long_name": "MPEG-2 video",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "1001/30000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 720,
            "height": 480,
            "coded_width": 0,
            "coded_height": 0,
            "closed_captions": 0,
            "has_b_frames": 1,
            "sample_aspect_ratio": "32:27",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 8,
            "color_range": "tv",
            "chroma_location": "left",
            "field_order": "tt",
            "refs": 1,
            "id": "0x1e0",
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "30000/1001",
            "time_base": "1/90000",
            "start_pts": 25257,
            "start_time": "0.280633",
            "duration_ts": 100029930,
            "duration": "1111.443667",
            "bit_rate": "7200000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "side_data_list": [
                {
                    "side_data_type": "CPB properties"
                }
            ]
        },
        {
            "index": 2,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "id": "0x80",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 25257,
            "start_time": "0.280633",
            "duration_ts": 100054080,
            "duration": "1111.712000",
            "bit_rate": "192000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        },
        {
            "index": 3,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "id": "0x81",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 25257,
            "start_time": "0.280633",
            "duration_ts": 100054080,
            "duration": "1111.712000",
            "bit_rate": "192000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ],
    "format": {
        "filename": "/Volumes/D/动画/VTS_01_1.VOB",
        "nb_streams": 4,
        "nb_programs": 0,
        "format_name": "mpeg",
        "format_long_name": "MPEG-PS (MPEG-2 Program Stream)",
        "start_time": "0.280633",
        "duration": "1111.712000",
        "size": "1073403904",
        "bit_rate": "7724330",
        "probe_score": 26
    }
}

MP4
 ffprobe -v quiet -print_format json -show_format -show_streams -i /Volumes/D/动画/2.mp4 
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1001/48000",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "closed_captions": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 40,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/24000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 32736680,
            "duration": "1364.028333",
            "bit_rate": "2996717",
            "bits_per_raw_sample": "8",
            "nb_frames": "32704",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2021-04-06T05:14:22.000000Z",
                "language": "und",
                "encoder": "AVC Coding"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 65473520,
            "duration": "1364.031667",
            "bit_rate": "253375",
            "max_bit_rate": "262912",
            "nb_frames": "63939",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2021-04-06T05:14:22.000000Z",
                "language": "jpn"
            }
        }
    ],
    "format": {
        "filename": "/Volumes/D/动画/2.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "1364.031667",
        "size": "554798258",
        "bit_rate": "3253873",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "mp42mp41isomavc1",
            "creation_time": "2021-04-06T05:14:22.000000Z"
        }
    }
}
</details>

**Comment by sakura2333** [comment]
是不是取的是nb_frame导致vob直接取不到值

**Comment by k4yt3x** [comment]
好像是是个 known issue，试试 nightly

**Comment by sakura2333** [comment]
> 好像是是个 known issue，试试 nightly
好像有依赖更新了

https://github.com/k4yt3x/video2x/blob/master/src/video2x_setup.py
line:211~218

  latest_release = requests.get(
            "**https://api.github.com/repos/DeadSix27/waifu2x-converter-cpp/releases/latest**"
        ).json()

        for a in latest_release["assets"]:
            if re.search(
                r"**waifu2x-DeadSix27-win64**_v[0-9]*\.zip", a["browser_download_url"]
            ):

下waifu2x-converter-cpp报错了

**Comment by k4yt3x** [comment]
先别用 setup script，直接把 nightly 的 exe 覆盖进 full

**Comment by sakura2333** [comment]
video2x-4.8.1-win32-full.zip\
                              video2x.exe
                              video2x_gui.exe

video2x-4.8.1-win32-light.zip\
                              video2x.exe
                              video2x_gui.exe

这几个文件一模一样。。还是会报错

**Comment by mirh** [comment]
The -select_streams command uses separate indexes for each different category of stream_specifier, not the "global" one. 
```
Input #0, mpeg, from 'VTS_01_2.VOB':
  Duration: 26:20:00.68, start: 652.792633, bitrate: 36 kb/s
    Stream #0:0[0x1bf]: Data: dvd_nav_packet
    Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, bottom first), 720x480 [SAR 32:27 DAR 16:9], 7380 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Side data:
      cpb: bitrate max/min/avg: 7380000/0/0 buffer size: 1835008 vbv_delay: N/A
    Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 224 kb/s
```

Here (not the same dvd, but still similar) you won't get a single line from `v:1`, you need `v:0`. 
https://github.com/k4yt3x/video2x/blob/37d567f20833affd0552fd1797e7593563e70eef/src/upscaler.py#L686-L690
So unless you want some smarter method to pick up the streams (I don't know, the longest video track if there is more than one?) you should just dispose of this function.

**Comment by k4yt3x** [comment]
5.0.0 changed how video streams are processed. This should no longer be relevant.
