### ISSUE TITLE
no output file suffix specified

### ISSUE THREAD

**Issue by kimipan168** [k4yt3x/video2x#495]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
I think the error message is quite self-descriptive?
