### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Testv123** [k4yt3x/video2x#496]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6337684/video2x_error.log)

**Comment by k4yt3x** [comment]
You might need this:
https://github.com/k4yt3x/video2x/wiki/Q&A#waifu2x-caffe-cuiexe-returned-non-zero-exit-status-1

**Comment by Testv123** [comment]
> You might need this:
> https://github.com/k4yt3x/video2x/wiki/Q&A#waifu2x-caffe-cuiexe-returned-non-zero-exit-status-1

thx
