### ISSUE TITLE
Command '['D:\\Video\\Muumipeikko Pyrstötähti\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'D:\\Video\\Muumipeikko Pyrstötähti\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '1440', '--scale_height', '1152', '--input_path', 'C:\\Users\\stari\\AppData\\Local\\Temp\\video2x\\tmp1_tutn2n\\0', '--output_path', 'C:\\Users\\stari\\AppData\\Local\\Temp\\video2x\\tmpo4izt6_c']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by starinspace** [k4yt3x/video2x#498]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
No error logs or descriptions provided.
