### ISSUE TITLE
Completes at 50% output video is unplayable.

### ISSUE THREAD

**Issue by sryug** [k4yt3x/video2x#50]
new user here. I followed the tutorial and my process runs to 50% about and then INFO: program completed, appears and it closes the task and deletes all temporary images.  the video file that it creates is a small 4mb file with no video (the input file is 60mb).  I've gone to the temp folder while it is running and i've seen it is creating the images.
i'm unclear on where the log is but here's this for now
![elp](https://user-images.githubusercontent.com/48486738/54471008-b4212300-477f-11e9-9688-02f96ce392d3.JPG)

**Comment by sryug** [comment]
trying different videos gives the same results so far

**Comment by K4YT3X** [comment]
> > i'm unclear on where the log is but here's this for now
> 
> @sryug all logs in the same directory where your video2x.py - `video2x/bin/`. Their names are like `error_log_%date%-%number%.%number%`

Could you please post the error log content?

**Comment by sryug** [comment]
I don't seem to have that.
![error](https://user-images.githubusercontent.com/48486738/54476657-fa04d800-47cd-11e9-9dbd-9a522d1757be.JPG).

it is successfully deleting the temp folder though.  I've watched it run, fill out the folder with images then poof disappear once it hits 50% and claims it has completed the operation.

**Comment by sryug** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\upscale\video2x-master\bin

C:\upscale\video2x-master\bin>python video2x.py -m gpu -r 2 -iC:\Users\jomb\Docu
ments\redshort.mp4 -o C:\Users\jomb\Documents\redshorta.mp4
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.6.1

[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memor
y
[!] WARNING: You demanded 5 threads to be created, but you only have 7.8535 GB G
PU memory available
[!] WARNING: 17.5 GB of GPU memory is recommended for 5 threads
[!] WARNING: With your current amount of GPU memory available, 2 threads is reco
mmended
[?] USER: Change to the recommended value? [Y/n]: y
[+] INFO: Upscaling single video file: C:\Users\jomb\Documents\redshort.mp4
2019-03-16 10:03:10.714703 [+] INFO: Extracted frames are being saved to: C:\Use
rs\jomb\AppData\Local\Temp\video2x\tmpsgnkes22
2019-03-16 10:03:10.714703 [+] INFO: Upscaled frames are being saved to: C:\User
s\jomb\AppData\Local\Temp\video2x\tmpp80ennye
2019-03-16 10:03:10.714703 [+] INFO: Executing: "C:\Users\jomb\AppData\Local\vid
eo2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -i "C:\Users\jomb\Documents\redshor
t.mp4" "C:\Users\jomb\AppData\Local\Temp\video2x\tmpsgnkes22"\extracted_%0d.png
-y
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfi
g --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-lib
freetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amr
wb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --
enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-l
ibwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --
enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --en
able-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --en
able-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --e
nable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enab
le-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\jomb\Documents\redshort.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 19529854
    compatible_brands: mp42isom
    creation_time   : 2019-03-16T15:02:22.000000Z
  Duration: 00:00:23.52, start: 0.000000, bitrate: 1057 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, flt
p, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Sound Media Handler
    Stream #0:1(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 640x4
80 [SAR 1:1 DAR 4:3], 924 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\jomb\AppData\Local\Temp\video2x\tmpsgnkes22\extr
acted_%0d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 19529854
    compatible_brands: mp42isom
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Video: png, rgb24, 640x480 [SAR 1:1 DAR 4:3], q=2-31, 200
kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Video Media Handler
      encoder         : Lavc58.35.100 png
frame=   88 fps=0.0 q=-0.0 size=N/A time=00:00:03.36 bitrate=N/A dup=1 drop=0 sp
frame=  181 fps=176 q=-0.0 size=N/A time=00:00:07.08 bitrate=N/A dup=1 drop=0 sp
frame=  273 fps=177 q=-0.0 size=N/A time=00:00:10.76 bitrate=N/A dup=1 drop=0 sp
frame=  362 fps=176 q=-0.0 size=N/A time=00:00:14.32 bitrate=N/A dup=1 drop=0 sp
frame=  457 fps=178 q=-0.0 size=N/A time=00:00:18.12 bitrate=N/A dup=1 drop=0 sp
frame=  553 fps=179 q=-0.0 size=N/A time=00:00:21.96 bitrate=N/A dup=1 drop=0 sp
frame=  588 fps=178 q=-0.0 Lsize=N/A time=00:00:23.52 bitrate=N/A dup=1 drop=0 s
peed=7.11x
video:83390kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing
 overhead: unknown
[+] INFO: Reading video information
2019-03-16 10:03:14.068703 [+] INFO: Executing: "C:\Users\jomb\AppData\Local\vid
eo2x\ffmpeg-4.1-win64-static\bin/ffprobe.exe" -v quiet -print_format json -show_
format -show_streams "C:\Users\jomb\Documents\redshort.mp4"
[+] INFO: Framerate: 25.0
[+] INFO: Starting to upscale extracted images
2019-03-16 10:03:14.177903 [+] INFO: [upscaler] Thread 0 started
2019-03-16 10:03:14.177903 [+] INFO: Executing: ['C:\\Users\\jomb\\AppData\\Loca
l\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--mode', 'noise_scale', '--s
cale_width', '1280', '--scale_height', '960', '--noise_level', '3', '--process',
 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '
--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\jomb
\\AppData\\Local\\Temp\\video2x\\tmpsgnkes22\\1', '--output_path', 'C:\\Users\\j
omb\\AppData\\Local\\Temp\\video2x\\tmpp80ennye', '--model_dir', 'models/cunet']
Upscaling Progress:   0%|                              | 0/588 [00:00<?, ?it/s]

2019-03-16 10:03:14.193503 [+] INFO: Executing: ['C:\\Users\\jomb\\AppData\\Loca
l\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--mode', 'noise_scale', '--s
cale_width', '1280', '--scale_height', '960', '--noise_level', '3', '--process',
 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '
--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\jomb
\\AppData\\Local\\Temp\\video2x\\tmpsgnkes22\\1', '--output_path', 'C:\\Users\\j
omb\\AppData\\Local\\Temp\\video2x\\tmpp80ennye', '--model_dir', 'models/cunet']

Upscaling Progress:  50%|#########9          | 293/588 [05:54<05:20,  1.09s/it]?
????????
?????????
2019-03-16 10:09:09.978503 [+] INFO: [upscaler] Thread 0 exiting
2019-03-16 10:09:10.110503 [+] INFO: [upscaler] Thread 1 exiting
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-03-16 10:09:10.111503 [+] INFO: Executing: "C:\Users\jomb\AppData\Local\vid
eo2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -r 25.0 -f image2 -s 1280x960 -i "C
:\Users\jomb\AppData\Local\Temp\video2x\tmpp80ennye"\extracted_%d.png -vcodec li
bx264 -crf 25 -pix_fmt yuv420p "C:\Users\jomb\AppData\Local\Temp\video2x\tmpp80e
nnye"\no_audio.mp4 -y
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfi
g --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-lib
freetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amr
wb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --
enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-l
ibwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --
enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --en
able-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --en
able-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --e
nable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enab
le-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, image2, from 'C:\Users\jomb\AppData\Local\Temp\video2x\tmpp80ennye\ext
racted_%d.png':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1280x960, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000000000057a480] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
AVX FMA3 BMI2 AVX2
[libx264 @ 000000000057a480] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 000000000057a480] 264 - core 157 r2935 545de2f - H.264/MPEG-4 AVC cod
ec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 r
ef=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed
_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pski
p=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 deci
mate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_
adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=2
5 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=25.0 qcomp=0.6
0 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\jomb\AppData\Local\Temp\video2x\tmpp80ennye\no_audi
o.mp4':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1280x960, q
=-1--1, 25 fps, 12800 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.35.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=30.0 Lsize=      12kB time=00:00:00.00 bitrate=1214974.4kb
its/s speed=0.00134x
video:11kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing ov
erhead: 7.232733%
[libx264 @ 000000000057a480] frame I:1     Avg QP:23.26  size: 10358
[libx264 @ 000000000057a480] mb I  I16..4: 21.9% 77.5%  0.6%
[libx264 @ 000000000057a480] 8x8 transform intra:77.5%
[libx264 @ 000000000057a480] coded y,uvDC,uvAC intra: 11.8% 39.7% 4.3%
[libx264 @ 000000000057a480] i16 v,h,dc,p: 31% 52%  5% 12%
[libx264 @ 000000000057a480] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 64% 12% 12%  2%  2%
 2%  3%  2%  1%
[libx264 @ 000000000057a480] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 48%  7%  3%  1%
 2%  5%  1%  2%
[libx264 @ 000000000057a480] i8c dc,h,v,p: 56% 18% 22%  4%
[libx264 @ 000000000057a480] kb/s:2071.60
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
2019-03-16 10:09:10.226503 [+] INFO: Executing: "C:\Users\jomb\AppData\Local\vid
eo2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -i "C:\Users\jomb\AppData\Local\Tem
p\video2x\tmpp80ennye"\no_audio.mp4 -i "C:\Users\jomb\Documents\redshort.mp4" -m
ap 0:v:0? -map 1? -c copy -map -1:v? "C:\Users\jomb\Documents\redshorta.mp4" -y

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfi
g --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-lib
freetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amr
wb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --
enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-l
ibwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --
enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --en
able-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --en
able-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --e
nable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enab
le-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\jomb\AppData\Local\Temp\video2
x\tmpp80ennye\no_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:00.04, start: 0.000000, bitrate: 2369 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960,
 2209 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\jomb\Documents\redshort.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 19529854
    compatible_brands: mp42isom
    creation_time   : 2019-03-16T15:02:22.000000Z
  Duration: 00:00:23.52, start: 0.000000, bitrate: 1057 kb/s
    Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, flt
p, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Sound Media Handler
    Stream #1:1(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 640x4
80 [SAR 1:1 DAR 4:3], 924 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
Output #0, mp4, to 'C:\Users\jomb\Documents\redshorta.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960,
 q=2-31, 2209 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, flt
p, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-03-16T15:02:22.000000Z
      handler_name    : Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-1.0 Lsize=     383kB time=00:00:23.44 bitrate= 133.9kbits
/s speed=7.82e+03x
video:11kB audio:367kB subtitle:0kB other streams:0kB global headers:0kB muxing
overhead: 1.485315%
Cleaning up cache directory: C:\Users\jomb\AppData\Local\Temp\video2x\tmpsgnkes2
2
Cleaning up cache directory: C:\Users\jomb\AppData\Local\Temp\video2x\tmpp80enny
e
[+] INFO: Program completed, taking 359.6238 seconds


C:\upscale\video2x-master\bin>

**Comment by Smarthard** [comment]
@sryug which graphics card do you have? I had the same behavior on my nvidia grahics card when I tried to use gpu upscaling method without installed CUDA Toolkit.

**Comment by sryug** [comment]
it's a 1080gtx

**Comment by Smarthard** [comment]
ok then try to download and install this - [CUDA Toolkit 10.1](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64).

**Comment by sryug** [comment]
I just did and it did not fix the issue.  I used the network installer from the page

**Comment by Smarthard** [comment]
@sryug in your very first message on the bottom of screenshot Permission Error has occured. But command prompt has runned with administrator rights. Hm... Maybe something is blocking this folder. I not sure.
Did you try any other video to upscale? Try to upscale [demo sample](https://files.flexio.org/Resources/Videos/sample_input.mp4) for example

**Comment by sryug** [comment]
the sample video gives the same results.  i've done a bunch of different videos of different lengths and get the same exact result every time. it cuts out at 50% progress.
![half](https://user-images.githubusercontent.com/48486738/54480134-e455d980-47f2-11e9-855e-3e5f614b30cd.JPG)

I don't understand what is happening at 50% is the program starting some new operation at that point?  according to the command line it has only finished upscaling half the images that it extracted. so I assume it is not even at the point where it recompiles it all into a video.
Is there a way to change the temp folder?  I can set it to my desktop or C: and see how that goes.

**Comment by Smarthard** [comment]
>Is there a way to change the temp folder?

I only know that in config file (video2x.json) you may specify `input_path` and `output_path`. Note that you need to escape backslashes in paths like that: `C:\\Users\\th3_smart\\`

**Comment by sryug** [comment]
I succeeded in changing the temp folder. you have to edit the line at the bottom "video2x_cache_folder" change the false statement into whatever file path you want.

unfortunately this didn't solve the issue

**Comment by sryug** [comment]
also I now realize it is not actually failing at 50% that is just the workload spread across two threads.  so it's actually getting to 100% in upscaling the frames but fails to compile them into a video.

**Comment by K4YT3X** [comment]
> also I now realize it is not actually failing at 50% that is just the workload spread across two threads. so it's actually getting to 100% in upscaling the frames but fails to compile them into a video.

@sryug it IS actually failing at 50%. Progress of both threads are calculated.

> Upscaling Progress: 50%|#########9 | 293/588 [05:54<05:20, 1.09s/it]?
> ????????
> ?????????
> 2019-03-16 10:09:09.978503 [+] INFO: [upscaler] Thread 0 exiting
> 2019-03-16 10:09:10.110503 [+] INFO: [upscaler] Thread 1 exiting
> [+] INFO: Upscaling completed
> [+] INFO: Converting extracted frames into video

The `???????` is error message printed in Japanese since waifu2x-caffe output is in Japanese. You'll have to change your cmd codec, otherwise we won't be getting any useful information out of that.

**Comment by sryug** [comment]
ok. I don't know what that means could you point me in the right direction?

**Comment by K4YT3X** [comment]
> > i'm unclear on where the log is but here's this for now
> 
> @sryug all logs in the same directory where your video2x.py - `video2x/bin/`. Their names are like `error_log_%date%-%number%.%number%`

Not quite. Most logs are only printed on screen to both stdout and stderr. Only Nvidia errors will be saved to the log format that you mentioned.

**Comment by K4YT3X** [comment]
> ok. I don't know what that means could you point me in the right direction?

instead of trying to fix waifu2x-caffe though, have you tried waifu2x-converter-cpp?

**Comment by sryug** [comment]
I've discovered a fix of sorts. if I limit it to one thread it works.
of course it's quite slow when I do this.  I'll try the other converter later today once I figure out how to install it.

**Comment by K4YT3X** [comment]
@sryug ok, glad to hear. Please keep me posted.
This is the only reported case for something similar.

**Comment by k4yt3x** [comment]
This issue has been here for quite a long time without further updates. I'm closing the thread for now. If you still experience problems, feel free to reopen the issue.
