### ISSUE TITLE
invalid literal for int() with base 10: '118445\r\n118445'

### ISSUE THREAD

**Issue by SgtBlade** [k4yt3x/video2x#502]
## Component Versions

- **Video2X release version**: 2.8.1
- **Upscaler version**:  Anime4k CPP Latest 30/04/2021
- **GUI version**: 2.8.1 Latest 30/04/2021
- **CLI version**:  Latest 30/04/2021

## Symptom
I was just converting a movie when it gave an error and said I should create a ticket issue with the error log attached. I'm not sure what went wrong, I tried upscaling a few images before to make sure it worked.

## Error Log or Screenshots

![image](https://user-images.githubusercontent.com/23322965/116740711-abd6e100-a9f5-11eb-8a79-bc3f026c7038.png)
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6407428/video2x_error.log)

**Comment by k4yt3x** [comment]
Try the latest nightly release.

**Comment by Shockkota** [comment]
> 
> 
> Try the latest nightly release.

Any change of getting a refresh of the nightly. That link is now expired.

**Comment by k4yt3x** [comment]
It's kinda annoying since I can't re-run that build manually. If I want to trigger the build again, I'll have to push a new commit, which will break the history.

The easier solution is to transcode your video into H.264 MP4.

```shell
ffmpeg -i input.something -vcodec libx264 output.mp4
```
