### ISSUE TITLE
Command '['C:\\Users\\Eddie\\Downloads\\Video Enhancement Software\\video2x v4.8.1\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'E:\\Video Capture\\OBS Capture\\Nick&Buddy_USA.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\Eddie\\AppData\\Local\\Temp\\video2x\\tmpbr8vhgq1\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Phillip-Kovakar** [k4yt3x/video2x#503]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: VERSION 4.8.1-WIN32-FULL
- **Upscaler version**: ?
- **GUI version**: ?
- **CLI version**: ?

## Symptom:
I GET THIS ERROR MESSAGE WHEN ATTEMPTING TO RUN VIDEO2X:
_**Command '['C:\\Users\\Eddie\\Downloads\\Video Enhancement Software\\video2x v4.8.1\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'E:\\Video Capture\\OBS Capture\\Nick&Buddy_USA.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\Eddie\\AppData\\Local\\Temp\\video2x\\tmp2gphvghi\\extracted_%0d.png']' returned non-zero exit status 1.**
PLEASE BE AWARE THAT I AM AN ABSOLUTE NOVICE AT THIS.  HOPEFULLY YOU CAN GET ME BACK ON THE RIGHT TRACK.

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
ERROR _LOG:-
[32m[+] INFO: Loading files into processing queue[0m
[90m2021-05-01 09:56:54.601858 [+] INFO: Input path(s): E:\Video Capture\OBS Capture\Nick&Buddy_USA.mp4[0m
[90m2021-05-01 09:56:54.606863 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2021-05-01 09:56:54.617202 [+] INFO: Input file: E:\Video Capture\OBS Capture\Nick&Buddy_USA.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2021-05-01 09:56:54.618201 [+] INFO: Executing: C:\Users\Eddie\Downloads\Video Enhancement Software\video2x v4.8.1\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i E:\Video Capture\OBS Capture\Nick&Buddy_USA.mp4[0m
[90m2021-05-01 09:56:55.792503 [+] INFO: Creating cache directory C:\Users\Eddie\AppData\Local\Temp\video2x[0m
[90m2021-05-01 09:56:55.794507 [+] INFO: Extracted frames are being saved to: C:\Users\Eddie\AppData\Local\Temp\video2x\tmp2gphvghi[0m
[90m2021-05-01 09:56:55.794507 [+] INFO: Upscaled frames are being saved to: C:\Users\Eddie\AppData\Local\Temp\video2x\tmpvt1wlbzf[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[32m[+] INFO: Calculating scaling parameters[0m
[90m2021-05-01 09:56:55.796503 [+] INFO: Framerate: 50.0[0m
[90m2021-05-01 09:56:55.797502 [+] INFO: Width: 768[0m
[90m2021-05-01 09:56:55.797502 [+] INFO: Height: 432[0m
[90m2021-05-01 09:56:55.797502 [+] INFO: Total number of frames: 14275[0m
[90m2021-05-01 09:56:55.797502 [+] INFO: Output width: 1536[0m
[90m2021-05-01 09:56:55.798502 [+] INFO: Output height: 864[0m
[90m2021-05-01 09:56:55.799498 [+] INFO: Required scale ratio: 2.0[0m
[90m2021-05-01 09:56:55.800500 [+] INFO: Upscaling jobs queue: [2.0][0m
[90m2021-05-01 09:56:55.801501 [+] INFO: Executing: C:\Users\Eddie\Downloads\Video Enhancement Software\video2x v4.8.1\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i E:\Video Capture\OBS Capture\Nick&Buddy_USA.mp4 -pix_fmt rgb24 C:\Users\Eddie\AppData\Local\Temp\video2x\tmp2gphvghi\extracted_%0d.png[0m
[90m2021-05-01 09:56:56.807654 [+] INFO: Main process waiting for subprocesses to exit[0m
ffmpeg version 4.3.1-2020-11-19-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Video Capture\OBS Capture\Nick&Buddy_USA.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:04:45.50, start: 0.000000, bitrate: 4261 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 768x432, 4059 kb/s, 50 fps, 50 tbr, 12800 tbn, 100 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[h264 @ 000001a9b0173c40] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\Eddie\AppData\Local\Temp\video2x\tmp2gphvghi\extracted_%0d.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: png, rgb24, 768x432, q=2-31, 200 kb/s, 50 fps, 50 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.91.100 png
frame=   63 fps=0.0 q=-0.0 size=N/A time=00:00:01.10 bitrate=N/A speed=2.19x    
frame=  118 fps=117 q=-0.0 size=N/A time=00:00:02.20 bitrate=N/A speed=2.18x    
frame=  192 fps=127 q=-0.0 size=N/A time=00:00:03.68 bitrate=N/A speed=2.43x    
frame=  266 fps=132 q=-0.0 size=N/A time=00:00:05.16 bitrate=N/A speed=2.56x    
frame=  340 fps=135 q=-0.0 size=N/A time=00:00:06.64 bitrate=N/A speed=2.64x    
frame=  407 fps=134 q=-0.0 size=N/A time=00:00:07.98 bitrate=N/A speed=2.64x    
frame=  477 fps=135 q=-0.0 size=N/A time=00:00:09.38 bitrate=N/A speed=2.66x    
frame=  548 fps=136 q=-0.0 size=N/A time=00:00:10.80 bitrate=N/A speed=2.68x    
frame=  619 fps=137 q=-0.0 size=N/A time=00:00:12.22 bitrate=N/A speed= 2.7x    
frame=  681 fps=135 q=-0.0 size=N/A time=00:00:13.46 bitrate=N/A speed=2.67x    
frame=  737 fps=133 q=-0.0 size=N/A time=00:00:14.58 bitrate=N/A speed=2.63x    
frame=  779 fps=129 q=-0.0 size=N/A time=00:00:15.42 bitrate=N/A speed=2.55x    
frame=  843 fps=129 q=-0.0 size=N/A time=00:00:16.70 bitrate=N/A speed=2.55x    
frame=  911 fps=129 q=-0.0 size=N/A time=00:00:18.06 bitrate=N/A speed=2.56x    
frame=  985 fps=131 q=-0.0 size=N/A time=00:00:19.54 bitrate=N/A speed=2.59x    
frame= 1059 fps=132 q=-0.0 size=N/A time=00:00:21.02 bitrate=N/A speed=2.61x    
frame= 1129 fps=132 q=-0.0 size=N/A time=00:00:22.42 bitrate=N/A speed=2.62x    
frame= 1196 fps=132 q=-0.0 size=N/A time=00:00:23.76 bitrate=N/A speed=2.62x    
frame= 1260 fps=132 q=-0.0 size=N/A time=00:00:25.04 bitrate=N/A speed=2.62x    
frame= 1329 fps=132 q=-0.0 size=N/A time=00:00:26.42 bitrate=N/A speed=2.62x    
frame= 1403 fps=133 q=-0.0 size=N/A time=00:00:27.90 bitrate=N/A speed=2.64x    
frame= 1471 fps=133 q=-0.0 size=N/A time=00:00:29.26 bitrate=N/A speed=2.64x    
frame= 1545 fps=133 q=-0.0 size=N/A time=00:00:30.74 bitrate=N/A speed=2.66x    
[image2 @ 000001a9b0174540] Could not open file : C:\Users\Eddie\AppData\Local\Temp\video2x\tmp2gphvghi\extracted_1541.png
av_interleaved_write_frame(): I/O error
frame= 1549 fps=133 q=-0.0 Lsize=N/A time=00:00:30.82 bitrate=N/A speed=2.65x    
video:862287kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
[31m[1m[!] ERROR: Subprocess 8640 exited with code 1[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
Cleaning up cache directory: C:\Users\Eddie\AppData\Local\Temp\video2x\tmp2gphvghi
Cleaning up cache directory: C:\Users\Eddie\AppData\Local\Temp\video2x\tmpvt1wlbzf
Cleaning up cache directory: C:\Users\Eddie\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 817, in run
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\Eddie\\Downloads\\Video Enhancement Software\\video2x v4.8.1\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'E:\\Video Capture\\OBS Capture\\Nick&Buddy_USA.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\Eddie\\AppData\\Local\\Temp\\video2x\\tmp2gphvghi\\extracted_%0d.png']' returned non-zero exit status 1.

**Comment by k4yt3x** [comment]
Could you please upload the original log file instead of pasting the log?

**Comment by Phillip-Kovakar** [comment]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6408735/video2x_error.log)
ORIGINAL LOG FILE UPLOADED

**Comment by k4yt3x** [comment]
> av_interleaved_write_frame(): I/O error

Do you have enough disk space?

**Comment by Phillip-Kovakar** [comment]
Drive C:   7.95gb
Drive E:   515.24gb (output file is to be saved to this drive)

**Comment by k4yt3x** [comment]
Make sure the temp directory is also set to E:.
