### ISSUE TITLE
I don't see the bin folder

### ISSUE THREAD

**Issue by LKPSA** [k4yt3x/video2x#505]
Ok so, I unzipped the file that I was told to download and all the folder contains is this (shown in the screenshot). I don't see any Bin folder...

![Untitled11](https://user-images.githubusercontent.com/83636012/116974100-de1a6400-acbd-11eb-8d26-e8d2769e9db8.png)

**Comment by k4yt3x** [comment]
If you're following the step-by-step tutorial, that things is outdated.
If you have no particular reason for running from the source code, I'd recommend you to just download and run the release.
