### ISSUE TITLE
C:\Users\jaygu\AppData\Local\video2x\ffmpeg\bin

### ISSUE THREAD

**Issue by FlowThru** [k4yt3x/video2x#507]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

[32m[+] INFO: Loading files into processing queue[0m
[90m2021-05-05 11:37:05.384134 [+] INFO: Input path(s): C:\Users\jaygu\Videos\Doors 3 The Finale.mp4[0m
[90m2021-05-05 11:37:05.387133 [+] INFO: File MIME type: video/mp4[0m
[31m[1m[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path[0m
[31m[1m[!] ERROR: Please check the configuration file settings[0m
Traceback (most recent call last):
  File "C:\Users\jaygu\Desktop\video2x-master\src\video2x_gui.py", line 107, in run
    self.fn(*self.args, **self.kwargs)
  File "C:\Users\jaygu\Desktop\video2x-master\src\upscaler.py", line 635, in run
    self._check_arguments()
  File "C:\Users\jaygu\Desktop\video2x-master\src\upscaler.py", line 283, in _check_arguments
    raise FileNotFoundError(self.ffmpeg_settings["ffmpeg_path"])
FileNotFoundError: C:\Users\jaygu\AppData\Local\video2x\ffmpeg\bin

**Comment by k4yt3x** [comment]
Are you running from source?
