### ISSUE TITLE
Error while upscaling an image using Waifu2X Caffe

### ISSUE THREAD

**Issue by pawa2401** [k4yt3x/video2x#508]
## Error (Moved from the title)
Command '['C:\\Users\\gamae\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'C:\\Users\\gamae\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '2560', '--scale_height', '1440', '--input_path', 'C:\\Users\\gamae\\AppData\\Local\\Temp\\video2x\\tmp26p_bvxh\\0', '--output_path', 'C:\\Users\\gamae\\AppData\\Local\\Temp\\video2x\\tmpr_svukir']' returned non-zero exit status 3221226505.
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**:
- **GUI version**:2.8.1
- **CLI version**:

## Symptom

I made it upscale an image, and it just crashed.
## Error Log or Screenshots
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6429803/video2x_error.log)
Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended including your error log.**

**Comment by k4yt3x** [comment]
> Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

Try referring to this: https://github.com/k4yt3x/video2x/wiki/Q&A#waifu2x-caffe-cuiexe-returned-non-zero-exit-status-1
