### ISSUE TITLE
Store temporary frames as JPEG to save space

### ISSUE THREAD

**Issue by peterhhk** [K4YT3X/video2x#51]
PNG files get pretty big pretty quick and using JPEG images would help with that.

**Comment by K4YT3X** [comment]
The difference in quality is too big between PNG and JPEG. Therefore, this feature request will not be implemented at this point.

### PNG

![extracted_34](https://user-images.githubusercontent.com/21986859/54638384-50d61000-4a61-11e9-9a83-0337ebc05755.png)

### JPEG
![extracted_34](https://user-images.githubusercontent.com/21986859/54638389-54699700-4a61-11e9-9734-2f2e8bd4ce0d.jpg)

**Comment by cr08** [comment]
To be fair, and this is just additional technical info on the topic, it does look like the default jpg output in ffmpeg without specifying a quality rate is pretty poor not only from your test images but a brief test of my own. Selecting the jpg output quality is done using the same `-q` or `-qscale` modifiers like other codecs. Looks like it ranges from 2-32 for jpeg with 2 being the best and 32 being the worst. Not setting it, looks like with my test samples it was defaulting to about 24-25. Setting to 1 (before I found that it MAY be limited to a max of 2 for jpeg, but doesn't seem to make much difference) seems to produce VERY minor artifacting at best which takes zooming in past 100% to identify. YMMV however.

Sample size of 750 720x576 frames. Current PNG output is 390MB, JPEG at `-q 1` is 35.3MB. So there IS a significant size difference at minimal quality loss.

With that said this is where my opinion and bias on this request comes in: JPEG is lossy and PNG is lossless. When dealing with the numerous conversion stages here (source video > png/jpg/etc frames > waifu2x processing and encoding to another set of png/jpg/etc frames > h264) especially with the focus of improving the quality of the source content, I would never trust a lossy intermediate format like jpg no matter how good of quality you can get it to produce. Disk space is cheap and for your average ~24 minute SD episode (again, based off my current working set of content at 720x576 source resolution, being processed up to 1440x1080) it should only be producing around ~130-150GB of frames both source and output.

**Comment by K4YT3X** [comment]
@cr08 I understood the problem afterwards.
https://github.com/DeadSix27/waifu2x-converter-cpp/issues/114

Here was my conversation with waifu2x-converter-cpp's developer on this topic.
I might still try JPEG later.

**Comment by K4YT3X** [comment]
It's so sad that I've already written the code, but I `git reset --hard`'ed the thing.

**Comment by K4YT3X** [comment]
Added JPEG support in the newest version
