### ISSUE TITLE
input output path type mismatch

### ISSUE THREAD

**Issue by VeizerTOP** [k4yt3x/video2x#511]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6517700/video2x_error.log)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
If your input is a single file, your output path must also be an existing file (will be overwritten) or a non-existent file (will be created).
