### ISSUE TITLE
Command '['C:\\Users\\Админ\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\realsr-ncnn-vulkan\\realsr-ncnn-vulkan', '-s', '4', '-t', '0', '-m', 'C:\\Users\\Админ\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\realsr-ncnn-vulkan\\models-DF2K_JPEG', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\7272~1\\AppData\\Local\\Temp\\video2x\\tmp0ugfltz8', '-o', 'C:\\Users\\7272~1\\AppData\\Local\\Temp\\video2x\\tmpoar_laf4']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by VeizerTOP** [k4yt3x/video2x#512]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6517766/video2x_error.log)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Do you have a discrete graphics card?

**Comment by VeizerTOP** [comment]
i dont have a  discrete graphics card. what should I do?

  
>Суббота, 22 мая 2021, 0:49 +03:00 от K4YT3X ***@***.***>:
> 
> 
>Do you have a discrete graphics card?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Егор Евдокимов

**Comment by k4yt3x** [comment]
You'll have a really hard time running it. Even if you can get some drivers like waifu2x-converter-cpp to run, it will take forever to upscale anything. It's pretty much mandatory to have a dGPU.
