### ISSUE TITLE
Command '['C:\\天翼云盘下载\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\天翼云盘下载\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\Administrator\\Desktop\\缓存\\tmpl4dsmw78', '-o', 'C:\\Users\\Administrator\\Desktop\\缓存\\tmppx753gg4']' returned non-zero exit status 3221226505.

### ISSUE THREAD

**Issue by hjz112** [k4yt3x/video2x#514]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by hjz112** [comment]
![QQ截图20210529191751](https://user-images.githubusercontent.com/78725323/120068354-d67a8f00-c0b2-11eb-9895-ef546e1e424a.png)

**Comment by hjz112** [comment]
How should I do?
![QQ截图20210529191751](https://user-images.githubusercontent.com/78725323/120068368-eb572280-c0b2-11eb-9c71-cb31cc4c3a47.png)

**Comment by k4yt3x** [comment]
Please upload the full error log.
