### ISSUE TITLE
C:\Users\hamoo\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by 8RADH** [k4yt3x/video2x#515]
![Screenshot (21)](https://user-images.githubusercontent.com/85068235/120108230-4f421f80-c175-11eb-92a6-c55504b91a73.png)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Please upload your error log.

**Comment by 8RADH** [comment]
> Please upload your error log.

what do you mean i already uploaded screenshot

**Comment by k4yt3x** [comment]
If you click the "save" button it will ask you where to save the error log.

**Comment by 8RADH** [comment]
> If you click the "save" button it will ask you where to save the error log.
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6567899/video2x_error.log)

**Comment by k4yt3x** [comment]
> [!] ERROR: Specified driver executable directory doesn't exist
> [!] ERROR: Please check the configuration file settings

Did you download the light version? Try the full version.
