### ISSUE TITLE
TecoGAN implementation

### ISSUE THREAD

**Issue by Pk555555** [k4yt3x/video2x#516]
Description

I think the software is the most practical and that works best for upscaling but I still think it's a bit "weak" for certain things and I think TecoGAN would bring a way to carry out processes where you have very "ugly" initial material.

Sources

Well you should know TecoGAN but still here its link on github: https://github.com/thunil/TecoGAN

**Comment by k4yt3x** [comment]
Right now I'm working on the 5.0.0 version of video2x, and it's quite tightly coupled with *-ncnn-vulkan. While I do think adding more algorithms is a good thing, it will be less prioritized than adding motion interpolation support. That said, I do think this is a valid suggestion and I'll keep it for when I'll have time for these nice-to-haves.

**Comment by Pk555555** [comment]
Thank you very much for accepting the suggestion and I look forward to this and other possible implementations.
