### ISSUE TITLE
Keep frames in memory instead of dumping them in the mass storage

### ISSUE THREAD

**Issue by aleferri** [k4yt3x/video2x#518]
## Description

Process frames in batch, keep frames in RAM (or ramdisk) while they are processed.
Pros: cutting writes to disk (really important with SSD for example) and reducing wasted space. More performance because less IO is required (not the bottleneck in this application, i know).
Cons: an added binary to generate the ramdisk if a solution for ffmpeg writing in memory directly is not found

## Sources

https://stackoverflow.com/questions/38253406/extract-list-of-specific-frames-using-ffmpeg
RAM disk require a dedicated program, but a few exists for Linux

**Comment by k4yt3x** [comment]
I'm writing version 5.0.0 right now. I'm trying to make the entire process streamlined so the frames will never have to be written to disk, including RAM disks.

**Comment by k4yt3x** [comment]
Addressed in 5.0.0-beta.
