### ISSUE TITLE
Command '['D:\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'D:\\Videos\\Sonic OVA.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\caleb\\AppData\\Local\\Temp\\video2x\\tmpvwd175mo\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by CalebKOnline** [k4yt3x/video2x#519]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 2.8.1
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**: 2.8.1

## Symptom

Enhancing an hour-long video but does this for all videos.

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6643068/video2x_error.log)

**Comment by k4yt3x** [comment]
> av_interleaved_write_frame(): I/O error

Is your disk full?

**Comment by CalebKOnline** [comment]
No

**Comment by k4yt3x** [comment]
Turn on preserve frames and see if your disk is full when it crashes. Cleanup the cash manually afterwards at `%TEMP%\video2x`.
