### ISSUE TITLE
Sorry to ask. But I have a problem. Its not giving me an error but just stops...

### ISSUE THREAD

**Issue by FeKgr** [K4YT3X/video2x#52]
C:\Users\Felix\Desktop\waifu2x>waifu2x-converter-cpp.exe -i sample_input.mp4
OpenCL: Ellesmere

... That's all it gives out
Then it prints the usual cmd line again and it magically stops. It also created a file called Ellesmere.bin I can upload that
https://www32.zippyshare.com/v/R480MwnD/file.html
there it is.
I really don't know how to continue. I am running gon Windows 10 64x with latest amd driver.

**Comment by K4YT3X** [comment]
> C:\Users\Felix\Desktop\waifu2x>waifu2x-converter-cpp.exe -i sample_input.mp4

What are you trying to do with this command anyways?

**Comment by K4YT3X** [comment]
What you're trying to do with this command is to upscale a video clip via `waifu2x-converter-cpp`, which is not related to `Video2X` at all, and will not work.

If you're not sure how to use this program, it might not be a bad idea to look at:
https://github.com/K4YT3X/video2x/wiki/Step-By-Step-Tutorial

**Comment by K4YT3X** [comment]
Well, I'm closing this issue since no further posts are seen.
Feel free to reopen at any time.
