### ISSUE TITLE
Image size (253956096 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

### ISSUE THREAD

**Issue by jonathancolledge** [k4yt3x/video2x#520]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- 4.4.1
- **GUI version**:
- 2.81
- **CLI version**:
- Ah, I  can't seem to find this. I am using the GUI though.

## Symptom

In this section, briefly describe what's going on.
So I have a 4k frame that I am upscaling 1.2 times. (This is just a trial, what I will actually be doing is very slightly cropping a 5.3 or 4k video and then upscaling back to 4k). It fails as per the log, on both my Quadro P2000 and my 1080.

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6668783/video2x_error.log)

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Assuming that the user input is always benign, this exception can be disabled by setting `Image.MAX_IMAGE_PIXELS` to `None` at the beginning of `upscaler.py`. I don't have the proper environment at the time to rebuild a version with this patch. If you can't fix it yourself lmk. I can see if it's possible for me to rebuild the old dev environment and build a patched version just for you.

**Comment by jonathancolledge** [comment]
Ah, thank you. I had a look and it turns out I'm not clever enough ☹️ I looked for upscaler.py, then realised it was in the source, and I have no idea where to go from there, let alone build it...

**Comment by k4yt3x** [comment]
OK I'll see what I can do. It'll take some time though.

**Comment by k4yt3x** [comment]
I just made a build. Try this: https://files.k4yt3x.com/.hidden/video2x-temp-win32-full.zip

**Comment by jonathancolledge** [comment]
Ah, thank you! It works!

**Comment by k4yt3x** [comment]
Added an option for this in 5.0.0-beta.
