### ISSUE TITLE
Anti-Error Comparison System

### ISSUE THREAD

**Issue by Pk555555** [k4yt3x/video2x#521]
## Description

You could try to put in a "comparison system" to avoid errors in the frames, it would be something that compares the original frame with the processed frame and sees if there are differences between the two that might be an error in this case and send an order to redo this frame with errors....

## Sources

I don't know of any software that does something like this and I don't have enough programming knowledge to create something like this but I imagine you can develop something like this "easily".

**Comment by k4yt3x** [comment]
The output is produced by a trained model. Even if you redo it, there won't be any differences.

**Comment by Pk555555** [comment]
I understand that it would still be something that could help if, for example, I gave an order for other software to make this specific frame or something like that.

**Comment by Pk555555** [comment]
Well anyway, it was just an idea to try to minimize errors.

**Comment by k4yt3x** [comment]
> I understand that it would still be something that could help if, for example, I gave an order for other software to make this specific frame or something like that.

Then you'll get inconsistent frame styles. I appreciate that you're providing suggestions, but for this particular problem, I think it will be more helpful if we can increase the quality of the models.

**Comment by Pk555555** [comment]
I understand and good thanks for considering my lay opinion.
Well I'll close the topic for now and eagerly await version 5.0 😁
