### ISSUE TITLE
Close PC when the process is done

### ISSUE THREAD

**Issue by JFMugen** [k4yt3x/video2x#522]
Hey there, great tool. Just a small request/idea so you can launch before you sleep and it would automatically shut down once the process is complete. I think it would be handy overall as upscaling is a time consuming thing overall.

**Comment by k4yt3x** [comment]
Should be easy enough to implement.

**Comment by k4yt3x** [comment]
Though this will have to wait until 5.0.0 is stable.

**Comment by JFMugen** [comment]
It is nothing urgent or something like that, I just thought that it would be neat :)
