### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by EmreL** [k4yt3x/video2x#523]
I heard or rather read, that you're currently writing version 5.0 of this awesome app. Am just curious and wanted to ask if you have a rough idea on when that release might be ? Also thanks for all your hard work

**Comment by k4yt3x** [comment]
As 5.0 is pretty much a complete rewrite, we are experimenting with a lot of new techs, which leads us into new unforeseen obstacles. I personally would love to finish the core and the CLI before July 15, but there are no guarantees at the moment.

**Comment by Pk555555** [comment]
Sorry to intrude on the conversation but I have a simple question to ask well you are doing version 5.0 and with it comes the frame interpolation thus allowing not only to increase the relosuction but also the fps however with my knowledge of the subject these programs that do frame interpolation allow you to increase the fps x times for example 2 times in a 30 fps video leaving it with 60 fps but in none of them I have used it gives the option to for example leave a video from 24 fps to 60 for example, to allow the person to lively choose the fps and what I want to get is that not only would it be a difference for your software to do this, but also if it weren't people would never get a "full" fps, for example 30 or 60 or even even 120 fps....... Anyway, will your software have a free fps school option or will it be standard even with x times such fps....?
Sorry for bad English.

**Comment by Pk555555** [comment]
> Desculpe me intrometer na conversa mas tenho uma pergunta simples para perguntar bem, vocês estão fazendo a versão 5.0 e com ela vem a interpolação de frames permitindo assim não só aumentar o relosuction mas também o fps porém com meu conhecimento do assunto esses programas que fazem a interpolação de quadros permite que você aumente o fps x vezes por exemplo 2 vezes em um vídeo de 30 fps deixando-o com 60 fps, mas em nenhum deles eu usei dá a opção de, por exemplo, deixar um vídeo de 24 fps a 60 por exemplo, para permitir que a pessoa escolha animadamente o fps e o que eu quero é que não só seria uma diferença para o seu software fazer isso, mas também, se não fosse, as pessoas nunca obteriam um fps "completo", por exemplo 30 ou 60 ou mesmo 120 fps ... De qualquer forma,seu software terá uma opção de escola de fps grátis ou será padrão mesmo com x vezes tais fps ...?
> Desculpe pelo péssimo inglês.

> Como o 5.0 é praticamente uma reescrita completa, estamos experimentando várias novas tecnologias, o que nos leva a novos obstáculos imprevistos. Eu pessoalmente adoraria terminar o núcleo e a CLI antes de 15 de julho, mas não há garantias no momento.

**Comment by k4yt3x** [comment]
@Pk555555 that's hell of a long sentence.

You will be able to set the exact output FPS (e.g., 120).

**Comment by Pk555555** [comment]
@k4yt3x Thanks for the answer and I'm glad it's going to be in this simpler intuitive way I'm increasingly looking forward to getting my hands on this 5.0 version!
It really was a long sentence 😂

**Comment by k4yt3x** [comment]
I'm looking forward to its release as much as you do. Here's a teaser btw. I'm debugging the upscaler functions.

![image](https://user-images.githubusercontent.com/21986859/123818904-e3c0ae80-d8e8-11eb-9efe-d571a7d079ae.png)

**Comment by Pk555555** [comment]
I sincerely thank this project for existing and for being from someone so "good" what I mean is that I can see great achievements for this software in the future and thank you for being able to follow this.
Just thinking about what this might turn out to be in version 10.0 for example, even if it takes a while, I can imagine something really big happening.
And thanks for the preview too!
