### ISSUE TITLE
Erro Video Time and Frames

### ISSUE THREAD

**Issue by emersondonizeti** [k4yt3x/video2x#524]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version: 4.8.1:
- **Upscaler version**:
- **GUI version: 2.8.1 :
- **CLI version**:

## Symptom

Sorry my english:

For some reason, when I tried to upscale a specific video, the frame counter shows about 37000 frames but in the end, the folder has about 41000 frames and when the upscale is over, the video has half the original time it was of 24 minutes, was left with 12 minutes and reproducing quickly.

I'm using the Waifu2X Caffe, resolution 1440x1080, video container .mkv and changed the driver settings to cudnn and anyme_style_art

## Error Log or Screenshots

Show no error, but the video is this one, it's a raw from Hajime no Ippo

The video: https://drive.google.com/file/d/1Dk18GWOrjNvDAVNTbJ9FT5pHIid9YNeK/view?usp=sharing

**Comment by k4yt3x** [comment]
For some videos, the `r_frame_rate` is the correct framerate, but for some, it's `avg_frame_rate`. This may be a similar case. Try re-encoding the whole video into h.264 first before upscaling it. This should eliminate the error. Also, anime_style_art is quite an old model and it tends to produce video with worse quality than the newer cunet model (according to my own experiences).

**Comment by emersondonizeti** [comment]
I'll try, thanks for the help
