### ISSUE TITLE
Command '['C:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\836D~1\\AppData\\Local\\Temp\\2\\video2x\\tmp9_btie79', '-o', 'C:\\Users\\836D~1\\AppData\\Local\\Temp\\2\\video2x\\tmpfzx88eeg']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by Kolkapetkinsyn** [k4yt3x/video2x#525]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 2.8.1
- **Upscaler version**: all
- **GUI version**: gtx550ti
- **CLI version**: 

## Symptom
The error appears when you click the start button
## Error Log or Screenshots
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6747150/video2x_error.log)

**Comment by k4yt3x** [comment]
Sorry I didn't see this issue earlier. It was marked read. Please reopen if you are still having this problem.
