### ISSUE TITLE
Command '['C:\\Programs\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\srmd-ncnn-vulkan', '-n', '3', '-s', '2', '-t', '400', '-m', 'C:\\Programs\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\models-srmd', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\dk\\AppData\\Local\\Temp\\video2x\\tmpt2nnz6_0', '-o', 'C:\\Users\\dk\\AppData\\Local\\Temp\\video2x\\tmppgupdmq6']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by micatsu** [k4yt3x/video2x#526]
## Component Versions

- **Video2X release version**: 4.8.1
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

The error appears after clicking the "Start".

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6821693/video2x_error.log)

**Comment by k4yt3x** [comment]
Crap sorry for some reason I didn't see this issue. Somehow it was marked read. Please keep posting or open an new issue if you are still having this problem.
