### ISSUE TITLE
video does not stop processing at 100%

### ISSUE THREAD

**Issue by KCGD** [k4yt3x/video2x#527]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **4.8.1**:
- **Waifu 2X NCNN Vulcan**:
- **2.8.1**:
- **4.8.1**:

## Symptom

I was running Waifu 2X NCNN Vulcan with 10, but at 100% progress it doesnt stop processing (switching to ffmpeg). The fps keeps updating, 

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
![gui](https://user-images.githubusercontent.com/48497186/126235971-ba80ab62-3dd1-4c65-bc94-3dad39d27d0a.png)
![cmd](https://user-images.githubusercontent.com/48497186/126235972-4d05ba5d-599d-4365-8e4d-c4708c27bbf3.png)

**Comment by k4yt3x** [comment]
That's normal. When all frames have been processed, FFmpeg will need to assemble the frames back into a video, which will take some time. The progress bar doesn't show this portion because FFmpeg does not provide an easy interface to communicate its progress. This behavior (of Video2X's) has changed in the 5.0.0 beta version since v2x has switched to frame-serving.

**Comment by KCGD** [comment]
ffmpeg wasnt running during this, it was just sitting idle

**Comment by k4yt3x** [comment]
Have you verified the running processes with task manager pwsh or something?

**Comment by PierrePDP** [comment]
I have the same issue.

It reaches 100% and just stops. ffmpeg isn't running at all; double checked with task manager and process explorer.
I left it for about 3 hours with no change at all.

**Comment by Kpoop123** [comment]
Same thing here, 2h of "Main process waiting for subprocesses to exit" while ffmpeg uses around 0,8 to 1,8 CPU% and the Console Windows Host 9 CPU% GPU and Disk are at 0% all the time

**Comment by jaroslavstreit** [comment]
I have same problem with GUI 4.8.1. on Windows 11. The computer is not processing anything, no resources utilisation.

**Comment by jayPare** [comment]
Same on my side with AVI file using Packed YUV 4:2:2, U:Y:V:Y (UYVY) codec.

Windows 11
GUI v2.8.1
Upscaler 4.4.1
