### ISSUE TITLE
Conda Venv | FileNotFoundError(driver_path) | FileNotFoundError: C:\Users\USERNAME\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by vexersa** [k4yt3x/video2x#528]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**:
- **GUI version**: 
- **CLI version**: 4.8.1

## Symptom

When calling video2x.py within a conda environment, the script looks for waifu2x-nccn-vulkan within the AppData\local\video2x location. As this script is running in a conda virtual environment, would the script not need to reference the waifu2x driver within the current conda environment? 

## Error Log or Screenshots

python.exe ./video2x/video2x.py -i c:/Users/USERNAME/anaconda3/envs/venv/VQGAN-CLIP/tmp/yeet.png -o c:/Users/USERNAME/anaconda3/envs/venv/VQGAN-CLIP/output/yeet.png -r 16  

    __      __  _       _                  ___   __   __
    \ \    / / (_)     | |                |__ \  \ \ / /
     \ \  / /   _    __| |   ___    ___      ) |  \ V /
      \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
       \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
        \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

                  Video2X Video Enlarger

                       Version 4.3.1

[+] INFO: Loading files into processing queue
2021-07-23 13:28:47.021794 [+] INFO: Input path(s): c:\Users\USERNAME\anaconda3\envs\venv\VQGAN-CLIP\tmp\yeet.png
2021-07-23 13:28:47.025301 [+] INFO: File MIME type: image/png
[!] ERROR: Specified driver executable directory doesn't exist
[!] ERROR: Please check the configuration file settings
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "C:\Users\USERNAME\anaconda3\envs\venv\VQGAN-CLIP\video2x\video2x.py", line 342, in <module>
    upscaler.run()
  File "C:\Users\USERNAME\anaconda3\envs\venv\VQGAN-CLIP\video2x\upscaler.py", line 633, in run
    self._check_arguments()
  File "C:\Users\USERNAME\anaconda3\envs\venv\VQGAN-CLIP\video2x\upscaler.py", line 294, in _check_arguments
    raise FileNotFoundError(driver_path)
FileNotFoundError: C:\Users\USERNAME\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan
[!] ERROR: The error log file can be found at: C:\Users\USERNAME\AppData\Local\Temp\video2x_zbl7cu83.log

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by vexersa** [comment]
Solved by specifying different  -d paramater worked: "-d waifu2x_caffe"

**Comment by k4yt3x** [comment]
Did you use the full release?
