### ISSUE TITLE
Error Cunet

### ISSUE THREAD

**Issue by emersondonizeti** [k4yt3x/video2x#529]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

    **Video2X release version: 4.8.1:
    Upscaler version:
    **GUI version: 2.8.1 :
    CLI version:

## Symptom

I'm trying to use the CUDNN process, if I select anime_style_art it works fine, if I select cunet, it shows the error in the log below.

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/6878769/video2x_error.log)

**Comment by k4yt3x** [comment]
> Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

Do you have an Nvidia GPU?

**Comment by emersondonizeti** [comment]
> 
> 
> > Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
> 
> Do you have an Nvidia GPU?

Yep, I have a Lenovo L340 with GTX 1050, I only have this problem with CUNET, when I select ANIME_STYLE_ART it works fine.

**Comment by emersondonizeti** [comment]
![print](https://user-images.githubusercontent.com/60696755/127073058-57303c9d-9d5e-4f8c-aa6e-dafc536bb911.jpg)

**Comment by k4yt3x** [comment]
> Yep, I have a Lenovo L340 with GTX 1050, I only have this problem with CUNET, when I select ANIME_STYLE_ART it works fine.

If that's the case then it's probably something inside of waifu2x-caffe going busted. I'm not in a good position to tell what's wrong. I'd say just go with waifu2x-ncnn-vulkan which is more performant and compatible all while producing comparable results. If you insist on using waifu2x-caffe, try running waifu2x-caffe directly. If it still doesn't work, you'll probably have better luck asking waifu2x-caffe's developers.

**Comment by emersondonizeti** [comment]
Sometimes I have some errors using Vulkan kakaka, but ok, i'll try, thank you
