### ISSUE TITLE
Rescource usage. 100% CPU 0% GPU

### ISSUE THREAD

**Issue by wompshmack** [k4yt3x/video2x#53]
Hey, not sure if this is an issue, or if my CPU is actually bottlenecking this somehow. I'm running -m gpu and it's always at max cpu usage but barely touching the GPU. Also it seems to say it'll take around 7 hours to process a 20 min video file, so I'm guessing that may be a problem. CPU is a ryzen 1300x and the gpu is a gtx1080.

**Comment by K4YT3X** [comment]
That's strange. Could you please provide a screenshot of the waifu2x command executed?

**Comment by wompshmack** [comment]
![image](https://user-images.githubusercontent.com/2308987/54877386-dce29180-4deb-11e9-9290-718d8eeb0e66.png)

**Comment by wompshmack** [comment]
And while that did take a very long time I just watched the finished product and it was quite good!

**Comment by K4YT3X** [comment]
Wow 10.25 hours. Still no GPU usage though?

**Comment by wompshmack** [comment]
Yeah, stayed very close to 0 the whole time. I thought that maybe that was just frame extraction that was CPU intensive, because of course that takes a while at the beginning, but I checked it several times over the process. -m gpu should be using cuda, right?

**Comment by K4YT3X** [comment]
> -m gpu should be using cuda, right?

Right, but make sure you're checking Compute instead of 3D or encoding/decoding.

![image](https://user-images.githubusercontent.com/21986859/54891411-a6f0ec00-4e83-11e9-9b25-07105543df29.png)

**Comment by u2knwy** [comment]
Hey, I had the same problem with i7 2600 and 1080ti but I got it figured out:

First install the CUDA toolkit from the nvidia website (https://developer.nvidia.com/cuda-toolkit)
and after that you still need the cuDNN library (https://developer.nvidia.com/cudnn), from which you paste the cudnn64_7.dll into the waifu2x-caffe folder that is located in AppData\Local\video2x\waifu2x-caffe
to test if it works you can start the waifu2x-caffe.exe and click "Check cuDNN" if everything is fine it will say something like cuDNN can be used 

I hope this fixed ur problem 👍

**Comment by K4YT3X** [comment]
@wompshmack does the problem still exist?

**Comment by wompshmack** [comment]
I haven't been back to that machine to test yet, but I definitely did not
have the cuda toolkit installed, so I'd say it's likely that was the issue.
Will update after testing

**Comment by k4yt3x** [comment]
No further feedback from thread owner. Closing thread.
Feel free to reopen.
