### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by UrubuFesteiro** [k4yt3x/video2x#530]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/6880525/video2x_error.log)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by UrubuFesteiro** [comment]
Also, in other posts related to this same problem, you said to download the nightly build. I can't download the nightly build because the artifact is expired. Sorry to bother you.

**Comment by k4yt3x** [comment]
Unfortunately I don't seem to be able to trigger the build manually without pushing a new commit. By doing that I'll have to merge the head of master and 5.0.0-beta which will be a bit of a hassle.

The easiest solution is to re-encode your video into h.264 via FFmpeg. It could be as easy as:

```shell
ffmpeg -i input.mp4 -c:v libx264 output.mp4
```

**Comment by UrubuFesteiro** [comment]
Thank you, I'll try doing that.

**Comment by UrubuFesteiro** [comment]
It worked, thank you very much!
