### ISSUE TITLE
Command '['C:\\Users\\*****\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\aalsu\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-upconv_7_anime_style_art_rgb', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\aalsu\\AppData\\Local\\Temp\\video2x\\tmpqgn0j5gr', '-o', 'C:\\Users\\aalsu\\AppData\\Local\\Temp\\video2x\\tmpk253kqfv']' returned non-zero exit status 4294967295.

### ISSUE THREAD

**Issue by AliWaelM** [k4yt3x/video2x#531]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version*2.8.1
[video2x_error2.txt](https://github.com/k4yt3x/video2x/files/6917900/video2x_error2.txt)
*:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
> vkCreateInstance failed -9
> invalid gpu device

What GPU are you using?

**Comment by AliWaelM** [comment]
Thank you for your response.

I'm using Intel(R) HD Graphics 5500
I read about this GPU and I found that it does not have Vulkan API, just OpenGL and OpenCL
is there a way to download Vulkan API in this old GPU?
