### ISSUE TITLE
Cannot launch, there is no mail program installed

### ISSUE THREAD

**Issue by asr210600** [k4yt3x/video2x#534]
## Component Versions

- **Video2X release version**: 2.8.1
- **Upscaler version**: 4.4.1
- **GUI version**:
- **CLI version**:

## Symptom

The video which I want to upscale is done 100% after which there is an error

## Error Log or Screenshots

`

![Screenshot (30)](https://user-images.githubusercontent.com/89294814/130315399-4e4eea27-6419-4b7c-acc9-3b4eb14916ea.png)
![Screenshot (31)](https://user-images.githubusercontent.com/89294814/130315400-4c253271-df01-4451-adc5-ede823194bb8.png)
![Screenshot (32)](https://user-images.githubusercontent.com/89294814/130315401-6b42b02a-c040-4597-a416-62fd5f03c198.png)
![Screenshot (33)](https://user-images.githubusercontent.com/89294814/130315402-e29049be-b174-4aa5-af6a-35686a4ba079.png)
![Screenshot (34)](https://user-images.githubusercontent.com/89294814/130315397-58c7156c-2f21-41ec-a522-3984c7439b23.png)
![Screenshot (35)](https://user-images.githubusercontent.com/89294814/130318796-f558e14b-67e0-42c4-8fbb-35357a898ac8.png)

**Comment by k4yt3x** [comment]
I'm not quite sure why you'll need a mail program there. The video will finish processing a while after it shows it's 100%. Did you click anything else before that finishes?

**Comment by asr210600** [comment]
No, I waited for almost 3hrs but it's stuck there.

**Comment by k4yt3x** [comment]
Didi you get an error pop up window?

**Comment by asr210600** [comment]
No nothing

**Comment by asr210600** [comment]
I'll try agian, is there anything we should do particularly after it's 100% done

**Comment by k4yt3x** [comment]
Not really. After it's completely done, you should just see a new file.

Also, I'd recommend that you try with the [sample video](https://akas.io/s) first instead of whatever long video you're trying to do to save some time.
