### ISSUE TITLE
E:\wojtek\program files x86\ffmpeg\ffmpeg-2021-08-25-git-e41bd075dd-full_build\bin\ffplay.exe

### ISSUE THREAD

**Issue by nightspicer** [k4yt3x/video2x#538]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
[video2x_error.log](https://github.com/k4yt3x/video2x/files/7071821/video2x_error.log)

**Comment by k4yt3x** [comment]
> FileNotFoundError: E:\Pobrane\ffmpeg-win-2.2.2\ffmpeg.exe

The immediate recommendation will be to check your FFmpeg path. However, I think you should just go with the full release.
