### ISSUE TITLE
Is there any research on how to run it with TPU's?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [k4yt3x/video2x#539]
I used algorithm in google colab to convert 45 seconds hd video to 4K. 
And it took 3 hours.
Talking into account that I had colab PRO.

**Comment by k4yt3x** [comment]
My knowledge of the low-level details on the current implementation of Video2X stops at the fact that waifu2x-caffe uses Caffe (CUDA/cuDNN), and that *-ncnn-vulkan use ncnn + the Vulkan API. It is unclear to me what v2x or what the upstream can do, if any, to better optimize our programs for TPUs.
