### ISSUE TITLE
Image scale sample on what options/driver?

### ISSUE THREAD

**Issue by lhalcyon** [k4yt3x/video2x#541]
## Description
I tried all options , and I can't get the lossless scaled image like the sample in README did .  Someone can tell me which options or drivers lead to the expected result ?

**Comment by k4yt3x** [comment]
There is a chance that you've got some settings wrong. It would be helpful if you can provide some examples and lay out exactly what kind of options you have tried and what kind of images you have fed it.

Also, although AI upscaling can yield very impressive results compared to traditional means like Lanczos3, it is no magic. You'll still see some artifacts.

**Comment by lhalcyon** [comment]
... Thank u for reply. 我看大佬有B站同名账号 = = .  我是用的demo中的图片例子.  但是放大8倍后得到的效果不如demo中展示的那样.   我是挨个driver去尝试的. demo中那种效果是需要使用Waifu2x Converter CPP吗 ,  
![tumblr_c83f9965933acd1ad946f515b9a5776b_d7315885_500](https://user-images.githubusercontent.com/21357951/131940279-ee8ffa6a-55e8-455f-8019-6bbb734bbcfa.png)

以下是我的配置:
![QQ截图20210903101636](https://user-images.githubusercontent.com/21357951/131940500-4cc790bc-d8da-4c0b-ab06-b1bf11c147d9.png)
![QQ截图20210903101647](https://user-images.githubusercontent.com/21357951/131940501-8194c0ed-933d-404e-9390-06cf7a620bf6.png)

**Comment by k4yt3x** [comment]
我记得我用的是 waifu2x-caffe 的 cunet 模型，也没做什么特殊的处理，就选了个 8 倍

**Comment by lhalcyon** [comment]
好的, 我单独再试试.多谢!

**Comment by k4yt3x** [comment]
不行的话 reopen issue 就好了

**Comment by lhalcyon** [comment]
呃. 我再次尝试了下, 还是得不到readme中那么清晰的图 , 那张清晰图是原作者在twitter上po出来的吧.  我们自己对模糊图进行无损放大,得到的好像达不到那个清晰图的效果

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/81631903-79a12d80-93f8-11ea-9c3c-f340240cf08c.png)

请问说的是这张图吗？这张图左边是我把原图的背景色去掉了，手动把分辨率降到 600x600，右图是用 waifu2x-caffe 直接从左边放大上来的，不是拿原图凑数的

**Comment by k4yt3x** [comment]
我刚才意识到作者发了两张图，您用的是第二张像素风格的吧，我是用的第一张图做的基础

![image](https://user-images.githubusercontent.com/21986859/132216182-10bc2c8d-7925-4096-99c4-0937bae763ba.png)

**Comment by lhalcyon** [comment]
呃. 我理解了.  拿上面的清晰图 手动降低分辨率, 然后放大得到的sample.    我去试试 . 非常感觉作者的耐心回复!

**Comment by k4yt3x** [comment]
>  拿上面的清晰图 手动降低分辨率, 然后放大得到的sample

是的，waifu2x 的算法不是很适合像素风格的图片，因为它会尝试对颜色边缘做平滑处理，看起来会有点怪
只能说很不巧我选的这张图有两张原画...
