### ISSUE TITLE
Command '['C:\\Video2x\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'cudnn', '--model_dir', 'C:\\Video2x\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '3840', '--scale_height', '2080', '--input_path', 'E:\\Tmp\\tmp8uo4zlaf\\2', '--output_path', 'E:\\Tmp\\tmpf3tx13xr']' returned non-zero exit status 3221226505.

### ISSUE THREAD

**Issue by gfurtado** [k4yt3x/video2x#542]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.8.1
- **Upscaler version**:
- **GUI version**::2.8.1
- **CLI version**

## Symptom

Upscale process stops and show a error message. Looking into logs i've found this error " Check failed: error == cudaSuccess (700 vs. 0)  an illegal memory access was encountered"
It's my second try, first happened the same so i updated my Nvidia driver tried again but nothing changed. Any Ideas?

My configs are:
Ryzen 5 3600XT
GTX1650
16Gb Ram
Windows 10

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/7108831/video2x_error.log)
![image](https://user-images.githubusercontent.com/19507724/132072742-db9c5924-8338-4000-94a8-f5083c3c6ce3.png)

**Comment by k4yt3x** [comment]
> Check failed: error == cudaSuccess (700 vs. 0)  an illegal memory access was encountered

This is likely a problem with the GPU driver or waifu2x-caffe. Try using waifu2x-ncnn-vulkan?

**Comment by gfurtado** [comment]
> 
> 
> > Check failed: error == cudaSuccess (700 vs. 0)  an illegal memory access was encountered
> 
> This is likely a problem with the GPU driver or waifu2x-caffe. Try using waifu2x-ncnn-vulkan?

With waifu2x-ncnn-vulkan i don't get any error message but it never ends, i tried a few times with different configs but always the same. What happens is that start the process, extract frames than upscale process than upscale reaches 100%  resources usage reduces drastically and stays that way forever.

In this picture, i let for 10 hours, something like 1,5 to hours to extract and upscale and more than 8 hours on low resources usage. Not sure what is happening.
![Vulkan](https://user-images.githubusercontent.com/19507724/132252630-3dec3d99-08a9-4798-87f1-2f2f87c6a29c.png)



Now i'm using Anime4k, most of the contents works perfectly. Just in some videos i face problems like this after conversion: 
![Capturar](https://user-images.githubusercontent.com/19507724/132252732-7bb36d09-8e30-4b80-86c9-3beaa8a14590.PNG)
But i think is something with filters, i'm trying different configs to make it convert flawless.

Thanks for the help

**Comment by k4yt3x** [comment]
> more than 8 hours on low resources usage

That makes no sense to me. After the frames are upscaled, it will use FFmpeg to assemble the frames back into a video. For a video your size, it shouldn't take more than a few minutes.

In your case, from your screenshot, though, I think the upscaling phase never finished for some reason. I'd say try again with waifu2x-ncnn-vulkan using the [sample video](https://akas.io/s) and use only 1 process this time. Multi-processing doesn't speed it up THAT much anyways. I'm suspecting that might be what's causing the problem since that's the only thing I see that's out of the ordinary.

Also, try making sure that E: is not a network drive.

**Comment by gfurtado** [comment]
> 
> 
> > more than 8 hours on low resources usage
> 
> That makes no sense to me. After the frames are upscaled, it will use FFmpeg to assemble the frames back into a video. For a video your size, it shouldn't take more than a few minutes.
> 
> In your case, from your screenshot, though, I think the upscaling phase never finished for some reason. I'd say try again with waifu2x-ncnn-vulkan using the [sample video](https://akas.io/s) and use only 1 process this time. Multi-processing doesn't speed it up THAT much anyways. I'm suspecting that might be what's causing the problem since that's the only thing I see that's out of the ordinary.
> 
> Also, try making sure that E: is not a network drive.

Got back to default settings with 1 process and worked with the sample video. I'll try with my video next and i'll post the result. 
And E: is local SSD
