### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by cobraycloud** [k4yt3x/video2x#549]
Noob here, so go easy. Got to the last 2 mins and crashed with error. Reminder to try a small video file before doing a big one lol.

System
os: win10
ram:16gb
gpu: 2070super

## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X 4.81 Full **:

## Symptom

OpenCV(3.4.3) Error: Assertion failed

[video2x_error.log](https://github.com/k4yt3x/video2x/files/7171727/video2x_error.log)

**Comment by k4yt3x** [comment]
This might be more of an upstream issue. I found these corresponding issues:

- https://github.com/lltcggie/waifu2x-caffe/issues/180
- https://github.com/opencv/opencv/issues/6595

Through some Google searches on your error message, it also appears that you might be out of memory.

**Comment by cobraycloud** [comment]
Thanks, will take a look at them.
System
os: win10
ram:16gb
gpu: 2070super

**Comment by k4yt3x** [comment]
Your specs should be fine. What settings have you changed?

**Comment by cobraycloud** [comment]
On main tab i changed it to caffe then driver settings - process to cunet.

**Comment by cobraycloud** [comment]
Tried a very small file which works with no problems.

**Comment by k4yt3x** [comment]
I think it's some low-level memory-management-related problem. Maybe try waifu2x-ncnn-vulkan?

**Comment by cobraycloud** [comment]
It's a full film, so ill try it again when I get time
