### ISSUE TITLE
Anime4KCPP black lines with scale ratio 3,00.

### ISSUE THREAD

**Issue by TechnoMasterBoy** [k4yt3x/video2x#550]
## Component Versions
- **Video2X release version**: 4.8.1 win32 full
- **Upscaler version**: 4.4.1
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom
Black lines when upscaling with Scale Ratio 3,00 with Anime4KCPP at top and left side but not with 2,00
These lines are not in the original video I used.
Ignore the black at bottom and right side, those are in original video too.
Currently doing an upscale where I manually set the output to be 2560x1440 and it doesn't seem to have the issue when I look at the temporary images it has created. Which kinda brings me to another issue I hope gets fixed soon. Downscaling being insanely slow when you don't use scale ratio, but manually set output. Like 80 times slower than upscaling, going at 1.08s/it whereas upscale is 81.93it/s.
I saw issue #377 talk about the same thing and you said the process will be multi-threaded in the next release, but do you have an estimate as to when that will happen?
Original video is 852x480 btw.
The black lines are just 1 pixel wide so you might need to open images in full view to see them.

## Error Log or Screenshots
3,00:
![Bilde_2021-09-16_080848](https://user-images.githubusercontent.com/90092517/133558852-0ef13e5d-a2d5-4b30-9b8b-d69c1fc346f9.png)
2,00:
![Bilde_2021-09-16_080932](https://user-images.githubusercontent.com/90092517/133558941-a4c69382-30cf-4802-8a20-3300121d2ea0.png)
Settings for Anime4KCPP:
![Bilde_2021-09-16_081222](https://user-images.githubusercontent.com/90092517/133559215-2b9e0328-e1c4-48f8-b7d0-2b6805d588dc.png)

**Comment by k4yt3x** [comment]
I've been thinking about this for a while now. At first I thought it's this thing that I've applied to FFmpeg that's causing the problem, but it doesn't make sense since your output height is an odd number. I'm guessing that you're upscaling only a single image?

![image](https://user-images.githubusercontent.com/21986859/133949518-b1bbe98b-b94c-49ce-9267-84a45d58bf9a.png)

Also, what happens if you try upscaling something like waifu2x? Does the issue persist?

**Comment by TechnoMasterBoy** [comment]
>  I'm guessing that you're upscaling only a single image?
I'm upscaling a video.

> Also, what happens if you try upscaling something like waifu2x? Does the issue persist?
With Waifu2x Caffe it runs way too slow to test, even with GPU. Around 2.5s/it when setting it to use either cudnn or gpu.
If I set the model to "anime_style_art" I get 1.2s/it though.
Waifu2x Converter CPP also has horrendous speed at 2s/it and it's barely even using my CPU or GPU. CPU jumping around 6-17% and GPU 4-9%.
I don't have "Disable GPU" checked so I dunno why it's that slow.
Waifu2x NCNN Vulkan is significantly faster at around 2.4it/s. But it's not using any of my CPU and is only using about 30-35% GPU. And the estimated time for a 480p video with the length of 5 minutes and a scale ratio of 3.0 is gonna take 2 hours and 20 minutes. Whereas Anime4KCPP took 10 minutes.

I think I found the issue though. It's when I turn on "GPU Mode" for Anime4KCPP. If I don't use that, there are no black lines. However, it takes maybe 4 times longer to upscale video or 2 with fast mode on lol.
I might have found a workaround though. If I turn on "CNN Mode" the black lines are gone. However, that slows down the upscale by about 50% from 80it/s to 38it/s. I can turn on fast mode though which brings it back up to 74it/s.
Downside to CNN though is that every line becomes incredibly thick.
CNN off:
![Anime4KCPP GPU](https://user-images.githubusercontent.com/90092517/134523669-3637e472-8ddb-445f-8337-f5e50fb7c41b.png)
CNN on:
![Anime4KCPP GPU+CNN](https://user-images.githubusercontent.com/90092517/134523747-13cb9244-d228-4199-a0f0-b7ea53ae5c3d.png)

**Comment by k4yt3x** [comment]
> It's when I turn on "GPU Mode" for Anime4KCPP. If I don't use that, there are no black lines.

Theoretically even if you use Anime4KCPP, the final assembly process will go through video2x, which should make both the width and height even numbers. I'm not quite sure how you got an odd number with that.

> Whereas Anime4KCPP took 10 minutes.

waifu2x is a machine-learning algorithm, whereas Anime4k is not. Therefore, waifu2x is GPU-bound and Anime4k is CPU-bound. Using a traditional non-ML algorithm will be significantly faster at the cost of a lower quality.

CNN mode is Anime4KCPP's machine-learning addon that improves the quality slightly, but it's not as powerful as waifu2x.

**Comment by TechnoMasterBoy** [comment]
> Theoretically even if you use Anime4KCPP, the final assembly process will go through video2x, which should make both the width and height even numbers. I'm not quite sure how you got an odd number with that.

Not sure what you're talking about as I'm not getting an odd number? The resolution becomes 2556x1440 which is even?
Since 852x3=2556 and 480x3=1440?

> waifu2x is a machine-learning algorithm, whereas Anime4k is not. Therefore, waifu2x is GPU-bound and Anime4k is CPU-bound. Using a traditional non-ML algorithm will be significantly faster at the cost of a lower quality.

So basically with my current GPU I'm kinda fucked and have to spend almost 7 hours on a 5 min video if I want good quality?
Thanks for all the help btw :)

**Comment by k4yt3x** [comment]
> Not sure what you're talking about as I'm not getting an odd number? The resolution becomes 2556x1440 which is even?
Since 852x3=2556 and 480x3=1440?

Nvm for some reason I saw an odd number when I ran exiftool on it earlier. I might have goofed something up. That black line might just be an Anime4KCPP bug.

> So basically with my current GPU I'm kinda fucked and have to spend almost 7 hours on a 5 min video if I want good quality?

You'll have to wait for quite a while, but not exactly 7 hours. You said that waifu2x-ncnn-vulkan will take you about 2 hours-ish. waifu2x-ncnn-vulkan will you pretty much the best quality within the shortest time. You can go with that.

**Comment by TechnoMasterBoy** [comment]
> You said that waifu2x-ncnn-vulkan will take you about 2 hours-ish. waifu2x-ncnn-vulkan will you pretty much the best quality within the shortest time. You can go with that.

I must have messed by only looking at estimated time on first pass when I wrote 2 hours, because it actually took 8 hours and 46 minutes (31595 seconds) :(

**Comment by k4yt3x** [comment]
That's what it will take then. If your hardware isn't strong enough to handle the load, maybe consider Google Colab.
