### ISSUE TITLE
Folders deleted on failure

### ISSUE THREAD

**Issue by louist103** [k4yt3x/video2x#551]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 
- **Upscaler version**: 4.4.1
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.
If a process fails the entire folder is deleted, not just the files directly related to the current job.  This is a major problem if there are many unrelated files in the same folder.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
- There shouldn't be multiple Video2X instances running simultaneously. At least not in the current version.
- The cache directories are designed to be deleted the way they are.
- If you want to run multiple instances anyways, turn on preserve frames and delete the cache manually.
