### ISSUE TITLE
windows appdata tmp folder up to 70g

### ISSUE THREAD

**Issue by wanghaisheng** [k4yt3x/video2x#552]
my video is about 20 min cartoon ,2 times enlarge.
but  i notice tmp folder quickly crash my c disk

**Comment by k4yt3x** [comment]
5.0 has switched to a frame server model. It won't be a problem when that's live.

**Comment by wanghaisheng** [comment]
just wonder  how much space do i need to process a 20 min video now?

**Comment by k4yt3x** [comment]
Depends on how big your input is and how much you're upscaling it.
