### ISSUE TITLE
Command '['C:\\Users\\user\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\user\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\user\\AppData\\Local\\Temp\\video2x\\tmpqn65cax8', '-o', 'C:\\Users\\user\\AppData\\Local\\Temp\\video2x\\tmp29ooy2ia']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by donboury** [k4yt3x/video2x#553]
i want to upsclaing a commercial it was 30 second i want it but i got message
it calls =
subprocess.CalledProcessError: Command '['C:\\Users\\user\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\user\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\user\\AppData\\Local\\Temp\\video2x\\tmpqn65cax8', '-o', 'C:\\Users\\user\\AppData\\Local\\Temp\\video2x\\tmp29ooy2ia']' returned non-zero exit status 3221225781.

i don't know what is mean but fix it please thanks love your work

**Comment by k4yt3x** [comment]
That message itself isn't enough for me to diagnose the problem. Do you have the error log?
