### ISSUE TITLE
docker image isn't updated anymore

### ISSUE THREAD

**Issue by debian-user-france1** [k4yt3x/video2x#554]
_no description_

**Comment by debian-user-france1** [comment]
And what's that: ??

```
    ~/video2x    master !1  sudo docker run --rm -it --gpus all -v /dev/dri:/dev/dri -v $PWD:/host k4yt3x/video2x:4.6.0 -d waifu2x_ncnn_vulkan -r 2 -i /home/france1/Videos/Crimson\ Desert\ -\ World\ Premiere\ Gameplay\ Trailer\ The\ Game\ Awards\ 2020.mp4 -o /home/france1/Videos/CrimsonDesert-better
[sudo] Passwort für france1: 
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
    ~/video2x    master !1       
```

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/135689270-52205547-8a29-4d8e-afad-7b030289fabe.png)

https://collabnix.com/introducing-new-docker-cli-api-support-for-nvidia-gpus-under-docker-engine-19-03-0-beta-release/

I think you're missing `nvidia-container-toolkit` or `nvidia-container-runtime`.

**Comment by debian-user-france1** [comment]
Well it's nonexistent on Manjaro

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/135751442-8b8238a9-8265-486b-bd24-cef16995da3c.png)

Manjaro is based on Arch. In Arch these two packages are in the AUR.

**Comment by debian-user-france1** [comment]
FileNotFoundError: /home/france1/Videos/CrimsonDesert.mp4 is neither file nor directory
but it exists
How do I have to do that?

**Comment by k4yt3x** [comment]
Try the new 5.0.0 beta container https://github.com/k4yt3x/video2x/pkgs/container/video2x
