### ISSUE TITLE
Fixing container errors in WSL2

### ISSUE THREAD

**Issue by fuleinist** [k4yt3x/video2x#557]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**: n/a
- **GUI version**: n/a
- **CLI version**: n/a

## Symptom
docker up results in error per follow:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container pr
ocess caused “process_linux.go:449: container init caused “process_linux.go:432: running prestart hook 0 ca
used \“error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creati
on failed: /var/lib/docker/overlay2/35b2ed80985f81e2e2a6a0703b0a3b4c687b1e77fccba7d6605f77f402556078/merged/
usr/lib/x86_64-linux-gnu/libcuda.so.1: file exists\\n\”””: unknown.

**Comment by k4yt3x** [comment]
You are running this in WSL?

**Comment by fuleinist** [comment]
yes, docker up in WSL2

**Comment by k4yt3x** [comment]
Thanks for providing a solution to make it usable on Windows. Please see the related PR #558 for more details.

**Comment by k4yt3x** [comment]
I just rebuilt an image for 5.0.0 using the cuda image. Can you try this out?
https://github.com/k4yt3x/video2x/pkgs/container/video2x
