### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by DITlieD** [k4yt3x/video2x#564]
## Component Versions

- **Video2X release version**: video2x-4.8.1-win32-full
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

this error happen seconds after i click start

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/7547475/video2x_error.log)

**Comment by k4yt3x** [comment]
Hmm looks like a problem with `mimetypes`? Is one of your input files not an image or not of a common format (JPEG/PNG)?

**Comment by DITlieD** [comment]
I used NOT *.png anf after NOT *.jpg in the same folder filtring it, and i founf a .jfif image but removing it didnt make difference

**Comment by DITlieD** [comment]
I tried with only 1 single jpg image and another error:
[
[video2x_error.log](https://github.com/k4yt3x/video2x/files/7547650/video2x_error.log)
](url)
(Before i succesfuly upscaled 200 images, but at sudden this started happening with same config, i already tried re-download it)

**Comment by DITlieD** [comment]
i tried with an empty folder and got the first error again

**Comment by k4yt3x** [comment]
I see input/output type mismatch. If your input is a single file, then your output also needs to be a single file.

**Comment by DITlieD** [comment]
I dont understand, i searched everything, have a way to put 2 outputs ? i dont understand how to fix it, sorry

**Comment by DITlieD** [comment]
![Uploading Screenshot_1.png…]()

**Comment by DITlieD** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/93692472/142169895-55937aa7-6602-4a45-a089-dfb7fe57b2ba.png)

**Comment by k4yt3x** [comment]
This issue should have been fixed in the newest nightly, but I'll close this issue since it won't be a thing in 5.0.0 anyways.
