### ISSUE TITLE
C:\Users\LEGION\AppData\Local\video2x\ffmpeg\bin

### ISSUE THREAD

**Issue by YoungZoe-gh** [k4yt3x/video2x#566]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
Sounds like you downloaded the light version or ran it from source code. It'll be easier if you get the full version.

**Comment by YoungZoe-gh** [comment]
> 

WOW! The issue has been resolved after downloading the full version. Thank you very much!
