### ISSUE TITLE
PARSE ERROR: Argument: --model_dir Couldn't find match for argument

### ISSUE THREAD

**Issue by xDololow** [K4YT3X/video2x#57]
`
C:\Users\xDololow\Desktop\video2x-master\bin>video2x.py -i Untitled.mp4 -o 2K.mp4 -m gpu -r 2 -d waifu2x_converter
__      __  _       _                  ___   __   __
\ \    / / (_)     | |                |__ \  \ \ / /
 \ \  / /   _    __| |   ___    ___      ) |  \ V /
  \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
   \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
    \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\

               Video2X Video Enlarger

                   Version 2.6.3

[!] WARNING: Nvidia-smi not available, skipping available memory check
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using
[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memory
[!] WARNING: You demanded 5 threads to be created, but you only have 5.4873 GB system memory available
[!] WARNING: 12.5 GB of system memory is recommended for 5 threads
[!] WARNING: With your current amount of system memory available, 2 threads is recommended
[?] USER: Change to the recommended value? [Y/n]:
[+] INFO: Upscaling single video file: Untitled.mp4
2019-03-26 02:07:11.486039 [+] INFO: Extracted frames are being saved to: C:\Users\xDololow\AppData\Local\Temp\video2x\tmpwjb0dulg
2019-03-26 02:07:11.487040 [+] INFO: Upscaled frames are being saved to: C:\Users\xDololow\AppData\Local\Temp\video2x\tmpzw4lua0n
2019-03-26 02:07:11.489040 [+] INFO: Executing: C:\Users\xDololow\AppData\Local\video2x\ffmpeg-4.1-win64-static\bin\ffmpeg.exe -i C:\Users\xDololow\Desktop\video2x-master\bin\Untitled.mp4 C:\Users\xDololow\AppData\Local\Temp\video2x\tmpwjb0dulg\extracted_%0d.png -y
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\xDololow\Desktop\video2x-master\bin\Untitled.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-03-25T18:08:52.000000Z
  Duration: 00:01:49.92, start: 0.000000, bitrate: 10240 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], 10048 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2019-03-25T18:08:52.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2019-03-25T18:08:52.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\xDololow\AppData\Local\Temp\video2x\tmpwjb0dulg\extracted_%0d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Video: png, rgb24, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      creation_time   : 2019-03-25T18:08:52.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : Lavc58.35.100 png
frame= 2638 fps= 13 q=-0.0 Lsize=N/A time=00:01:49.91 bitrate=N/A speed=0.541x
video:4090373kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-03-26 02:10:34.989954 [+] INFO: Executing: C:\Users\xDololow\AppData\Local\video2x\ffmpeg-4.1-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\xDololow\Desktop\video2x-master\bin\Untitled.mp4
[+] INFO: Framerate: 24.0
[+] INFO: Starting to upscale extracted images
2019-03-26 02:10:35.109962 [+] INFO: [upscaler] Thread MainThread started
2019-03-26 02:10:35.109962 [+] INFO: Executing: ['C:\\Users\\xDololow\\AppData\\Local\\video2x\\waifu2x-converter-cpp\\waifu2x-converter-cpp.exe', '--jobs', '2', '--model_dir', 'C:\\Users\\xDololow\\AppData\\Local\\video2x\\waifu2x-converter-cpp\\models_rgb', '--scale_ratio', '2.0', '--noise_level', '3', '--mode', 'noise_scale', '--quiet', '-i', 'C:\\Users\\xDololow\\AppData\\Local\\Temp\\video2x\\tmpwjb0dulg', '-o', 'C:\\Users\\xDololow\\AppData\\Local\\Temp\\video2x\\tmpzw4lua0n']
Upscaling Progress:   0%|                                                                     | 0/2638 [00:00<?, ?it/s]PARSE ERROR: Argument: --model_dir
                         Couldn't find match for argument

Brief USAGE:
   C:\Users\xDololow\AppData\Local\video2x\waifu2x-converter-cpp\waifu2x-co
                                        nverter-cpp.exe
                                        [--list-opencv-formats] [-l] [-f
                                        <png,jpg,webp,...>] [-c <0-9>] [-q
                                        <0-100>] [--block-size <integer>]
                                        [--disable-gpu] [--force-OpenCL]
                                        [-p <integer>] [-j <integer>]
                                        [--model-dir <string>]
                                        [--scale-ratio <double>]
                                        [--noise-level <0|1|2|3>] [-m
                                        <noise|scale|noise-scale>] [-s] [-r
                                        <bool>] [-o <string>] -i <string>
                                        [--] [--version] [-h]

For complete USAGE and HELP type:
   C:\Users\xDololow\AppData\Local\video2x\waifu2x-converter-cpp\waifu2x-converter-cpp.exe --help

Waifu2x OpenCV - Version v5.2.4 (b4566c0) - https://github.com/DeadSix27/waifu2x-converter-cpp

If you find issues or need help, visit: https://github.com/DeadSix27/waifu2x-converter-cpp/issues

[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-03-26 02:10:36.155384 [+] INFO: Executing: C:\Users\xDololow\AppData\Local\video2x\ffmpeg-4.1-win64-static\bin\ffmpeg.exe -r 24.0 -f image2 -s 2560x1440 -i C:\Users\xDololow\AppData\Local\Temp\video2x\tmpzw4lua0n\extracted_%d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p C:\Users\xDololow\AppData\Local\Temp\video2x\tmpzw4lua0n\no_audio.mp4 -y
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[image2 @ 000002974214ac00] Could find no file with path 'C:\Users\xDololow\AppData\Local\Temp\video2x\tmpzw4lua0n\extracted_%d.png' and index in the range 0-4
C:\Users\xDololow\AppData\Local\Temp\video2x\tmpzw4lua0n\extracted_%d.png: No such file or directory
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "C:\Users\xDololow\Desktop\video2x-master\bin\video2x.py", line 254, in <module>
    upscaler.run()
  File "C:\Users\xDololow\Desktop\video2x-master\bin\upscaler.py", line 305, in run
    fm.convert_video(framerate, '{}x{}'.format(int(self.scale_width), int(self.scale_height)), self.upscaled_frames)
  File "C:\Users\xDololow\Desktop\video2x-master\bin\ffmpeg.py", line 125, in convert_video
    subprocess.run(execute, shell=True, check=True)
  File "C:\Users\xDololow\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\xDololow\\AppData\\Local\\video2x\\ffmpeg-4.1-win64-static\\bin\\ffmpeg.exe', '-r', '24.0', '-f', 'image2', '-s', '2560x1440', '-i', 'C:\\Users\\xDololow\\AppData\\Local\\Temp\\video2x\\tmpzw4lua0n\\extracted_%d.png', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', 'C:\\Users\\xDololow\\AppData\\Local\\Temp\\video2x\\tmpzw4lua0n\\no_audio.mp4', '-y']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using
Traceback (most recent call last):
  File "C:\Users\xDololow\Desktop\video2x-master\bin\video2x.py", line 277, in <module>
    shutil.rmtree(video2x_cache_folder)
  File "C:\Users\xDololow\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\xDololow\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\xDololow\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 393, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] Папка не пуста: 'C:\\Users\\xDololow\\AppData\\Local\\Temp\\video2x'
`

**Comment by K4YT3X** [comment]
Your command seems to be fine, I don't know exactly what went wrong.

**Comment by T3553** [comment]
For some reasons in Version 5.2.4 of waifu2x-converter-cpp all arguments have a minus instead of an underscore.

v 5.2.4: http://0x0.st/zKwO.png
v 5.2.3: http://0x0.st/zKwV.png

**Comment by K4YT3X** [comment]
@T3553 Nice catch. I'll see if I can get this sorted out.

**Comment by K4YT3X** [comment]
The problem should be solved in the latest release.
