### ISSUE TITLE
[WinError 5] Access is denied: 'C:\\Users\\*****\\AppData\\Local\\Temp\\video2x\\tmp9dx2tr37\\cover.jpg'

### ISSUE THREAD

**Issue by Erick2317** [k4yt3x/video2x#576]
## Component Versions

- **Video2X release version**: 4.8.1-win32-full
- **Upscaler version**: Waifu2X NCNN Vulkan
- **GUI version**: 2.8.1
- **CLI version**: -

## Symptom

I try to upscale some image but I get this error at the end of the process and I don't get the upscaled image.
ERROR: `PermissionError: [WinError 5] Access is denied: 'C:\\Users\\*****\\AppData\\Local\\Temp\\video2x\\tmpsqdh3r19\\cover.jpg'`
My computer has an Intel Core i7-8750H with an Intel UHD Graphics 630 and a NVIDIA GeForce GTX 1050 running Windows 10 x64.

## Error Log or Screenshots

[video2x_error.log](https://github.com/k4yt3x/video2x/files/7700136/video2x_error.log)

**Comment by k4yt3x** [comment]
Looks like a bug, but I don't think I'll fix it since the publishing of the next version will fix it anyways.
