### ISSUE TITLE
Command '['C:\\Users\\david\\OneDrive\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'C:\\Users\\david\\OneDrive\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '3840', '--scale_height', '2160', '--input_path', 'C:\\Users\\david\\AppData\\Local\\Temp\\video2x\\tmpc6esq7ux\\0', '--output_path', 'C:\\Users\\david\\AppData\\Local\\Temp\\video2x\\tmpgwqsty3q']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by KHGamerYT** [k4yt3x/video2x#577]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: ?
- **Upscaler version**: 2.8.1
- **GUI version**: ?
- **CLI version**: ?

## Symptom

In this section, briefly describe what's going on.

## ![image](https://user-images.githubusercontent.com/82169209/145827381-951d3fc1-e75e-4997-a08a-52fffb353ad6.png)
Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
There isn't enough info in the screenshot. I'll need to see the error log.
