### ISSUE TITLE
Add Option for Width and Height using converter-cpp

### ISSUE THREAD

**Issue by thescratcho** [k4yt3x/video2x#58]
It would be nice if Widht and Height are supported by converter-cpp

It could be archived by calculating the ratio using the Widht/Height of the source file.
waifu2x-gui has an implementation for that. Maybe look there for reference
https://github.com/maz-1/waifu2x-gui

**Comment by K4YT3X** [comment]
It is indeed possible, and it's not very hard to implement.
However, since waifu2x-converter-cpp doesn't natively support it, the output cannot be stretched in any kind of ways.

**Comment by thescratcho** [comment]
That wouldnt be a big deal
Noone like stretched pictures anyways:)

Would be cool if you type in a resolution that doesnt match the aspect ratio, that the nearest correct resolution would be automatically used or suggested that fits the aspect ratio and afterwards sets the correct scaling ratio

**Comment by k4yt3x** [comment]
@thescratcho I looked through the code, and I still believe that this feature should not be implemented. In order to convert the width height input into scale ratio, too many things need to be added, and the benefit will not outweigh the cost.
