### ISSUE TITLE
Format string extension is ignored when doing more than a single process

### ISSUE THREAD

**Issue by Kuroonehalf** [k4yt3x/video2x#582]
- **Video2X release version**: 2.8.1
- **GUI version**: yes

Example of steps to reproduce:
- Import more than 1 GIF
- Set output file name format string to something like "{original_file_name}.mp4"
- Run conversion
And the output will be in GIF form instead of MP4. If you run just a single GIF at a time the conversion to MP4 works, but if it's more than one it won't.

**Comment by k4yt3x** [comment]
Interesting... I'll fix this when GIF support is added in 5.0.0.
