### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by richardcgiroux** [k4yt3x/video2x#583]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/7791903/video2x_error.log)
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
> cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

Do you have an Nvidia GPU?
