### ISSUE TITLE
Input file not found

### ISSUE THREAD

**Issue by Kofro** [k4yt3x/video2x#585]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

[video2x_error.log](https://github.com/k4yt3x/video2x/files/7807009/video2x_error.log)
- **Video2X release version**: Latest
- **Upscaler version**: Latest
- **GUI version**:Latest
- **CLI version*Latest

*:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots
![image](https://user-images.githubusercontent.com/10164925/148050175-60700f63-7dcf-4d27-a8e1-def3f0824192.png)
https://i.imgur.com/EWXzwDf.png

**Comment by Kofro** [comment]
![image](https://user-images.githubusercontent.com/10164925/148050226-a9857c1a-5237-4478-895a-f9a146d64f99.png)
![image](https://user-images.githubusercontent.com/10164925/148050251-bd45d44b-4798-4d8e-b464-35e0475b82f9.png)

**Comment by Erick2317** [comment]
If I remember correctly I got that error two weeks ago, when I finished the upscaling I got two files: a **.mkv** and a **.mp4** where one of them was corrupted. Anyway, if your input file that you were upscaling is an **.mkv**, in the **GUI** you must change the **Output** and **Video Output Extension** _(what is underlined in red in the attached image)_ from **.mp4** to **.mkv** for it to work correctly. If you enabled the **Preserve Frames** option in the **GUI** you could still just do the video through **FFmpeg** with the commands that the **CLI** uses for the Video Assembly process so you don't need to upscale it again. If that's not the error, then it's different than mine _lol_.
![2022-01-04 (3)](https://user-images.githubusercontent.com/91224267/148114580-ec85aa9b-7fb3-43e6-ba54-6b234b8befb0.png)

**Comment by k4yt3x** [comment]
Looks like your input path doesn't exist? Try dragging the file in.
