### ISSUE TITLE
Command '['C:\\Users\\epicm\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\epicm\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\epicm\\AppData\\Local\\Temp\\video2x\\tmp234qxfj2', '-o', 'C:\\Users\\epicm\\AppData\\Local\\Temp\\video2x\\tmpbpboeqf5']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by oofermaster** [k4yt3x/video2x#587]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

In this section, briefly describe what's going on. tried to upscale vid and error

## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
![Screenshot (2)](https://user-images.githubusercontent.com/77516622/149248380-243e4990-f137-4b52-a81f-6f88a4eb06df.png)

**Comment by k4yt3x** [comment]
Could you please attach the error log?

**Comment by k4yt3x** [comment]
I'll reopen this when you attach the logs.
