### ISSUE TITLE
Crash when encoding a 1080p file

### ISSUE THREAD

**Issue by mohxinn** [k4yt3x/video2x#588]
Attaching error log. only thing changed in GUI was the encoder to Waifu2x-Caffe
[video2x_error.log](https://github.com/k4yt3x/video2x/files/7889258/video2x_error.log)

**Comment by k4yt3x** [comment]
I'm not sure what happened. Looks like the temp files were deleted by another program or something?

**Comment by mohxinn** [comment]
The program files and the video file were in a folder that belonged to OneDrive. Could that have caused the issue?

**Comment by k4yt3x** [comment]
I don't think so. Do you have any file cleaners running like CCleaner?

**Comment by mohxinn** [comment]
Yes but I didn't run it when video2x was running. Can it interfere while running in background?

**Comment by k4yt3x** [comment]
It might. Try stopping it and see if you encounter the same problem.
