### ISSUE TITLE
Feature: de-noising low-bitrate video

### ISSUE THREAD

**Issue by DonaldTsang** [k4yt3x/video2x#59]
Since waifu2x has de-noising, video2x should have a de-noising feature as well for low bitrate video, and turn them into a high bitrate video. Better still is to use previous and next few frames to enhance the frame in question.

**Comment by K4YT3X** [comment]
Could you please provide more details or documentations? I'll take a look.

**Comment by DonaldTsang** [comment]
https://github.com/nagadomi/waifu2x#summary has an image showing that Waifu2x can be used for de-noising images.

**Comment by K4YT3X** [comment]
If I'm understanding your question right, you can set "mode" to "noise" in the configuration file.

![image](https://user-images.githubusercontent.com/21986859/55048653-5b734500-501f-11e9-9a35-38f3d00d92fc.png)

**Comment by DonaldTsang** [comment]
@K4YT3X I would say that you can change the model a bit to accept previous and next frames along the frame in question to enhance fluidity (since waifu2x only deals with images).

**Comment by K4YT3X** [comment]
@DonaldTsang I have no idea how to.
Waifu2x and video2x are completely different types of applications, and not even the creator of `waifu2x-converter-cpp` knows how to train a basic model, let alone altering the algorithm. 

If you mean frame interpolation, it's a different topic then.

**Comment by DonaldTsang** [comment]
I am not talking frame interpolation but super resolution and de-noising using multiple fames for one singular frame.

**Comment by K4YT3X** [comment]
How are you supposed to do that?

**Comment by k4yt3x** [comment]
Unclear feature request without further responses. Closing issue.
