### ISSUE TITLE
Add man page entry for Unix operating systems

### ISSUE THREAD

**Issue by rail01** [k4yt3x/video2x#590]
## Description

This program apparently lacks a man page entry fox UNIX operating systems. Man pages help users get detailed documentation for all available application options in a standardized, well-established way. In general, it is desirable to have a man page for your application.

**Comment by k4yt3x** [comment]
Yeah I know it'll be nice to include one. Right now I'm putting all of the time I have on the development of 5.0.0. Once things stabilize I can start looking into some of these nice-to-haves. Though, for the time being, I don't think I'll write anything just yet when the core functionalities are still incomplete.

**Comment by k4yt3x** [comment]
Thanks for the suggestion though. I'll put this on a TODO list.
