### ISSUE TITLE
FFmpeg video assembly failure

### ISSUE THREAD

**Issue by Charles-the-hacker** [k4yt3x/video2x#591]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X 4.8.1
- **Upscaler version: anime4kcpp
- **GUI version**:
- **CLI version**:

## Symptom

FFmpeg will fail to re compile the upscaled video, and the command line will display "main process waiting for subprocess to exit"
## Error Log or Screenshots

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**
![image](https://user-images.githubusercontent.com/84184276/151466161-14cc092e-0812-4efd-9a96-da4708fc211a.jpeg)![image](https://user-images.githubusercontent.com/84184276/151466162-96bd8445-77bd-4c68-ac8f-37c43a3013e6.jpeg)

**Comment by k4yt3x** [comment]
This screenshot doesn't contain enough information. Do you have an error log file?

**Comment by k4yt3x** [comment]
Looks like it is assembling the frames indeed, though without any output I can't quite tell what's going on either. Do you see any CPU usage from FFmpeg in task manager?

**Comment by Charles-the-hacker** [comment]
Yeah, task manager reports 100% cpu usage, but ffmpeg isn't listed as a task.

**Comment by Charles-the-hacker** [comment]
I don't know what the problem is. I think I'll just use the anime4kcpp cl app. Thanks for the support though!

**Comment by k4yt3x** [comment]
You can probably try the new Colab notebook?

**Comment by k4yt3x** [comment]
I'll close this since I've got no environment to fix the old version.
