### ISSUE TITLE
Ошибка в Google Colab

### ISSUE THREAD

**Issue by Zzip7** [k4yt3x/video2x#594]
Здраствуйте.Несколько дней назад,было всё хорошо,но,сегодня появилась ошибка.
![1](https://user-images.githubusercontent.com/87704893/153219297-cfe589b9-2ff6-463e-bb27-a1395d0d630c.jpg)
Как исправить?

**Comment by k4yt3x** [comment]
Hey I just update the master branch... yesterday. I'll either post a new Colab script or patch the old one soon.

**Comment by Zzip7** [comment]
Спасибо!

**Comment by k4yt3x** [comment]
Hey the new Colab notebook is available. Try it out: https://colab.research.google.com/drive/1gWEwcA9y57EsxwOjmLNmNMXPsafw0kGo

**Comment by k4yt3x** [comment]
I've already update the link on the home page, but I can't update the old notebook directly since I'm not the owner of that notebook.
