### ISSUE TITLE
Feature: SVP support

### ISSUE THREAD

**Issue by DonaldTsang** [k4yt3x/video2x#60]
Adding SVP to video2x would make it more useful. See https://svp-team.com/

**Comment by k4yt3x** [comment]
Exactly how do you suggest it to be integrated?
SVP is paid stand-alone software. It also should be used after upscaling.

**Comment by DonaldTsang** [comment]
Streamlining the process possibly into one single utility, command line or GUI.

**Comment by k4yt3x** [comment]
SVP is more like a video player plugin, how am I supposed to integrate it into video2x?

**Comment by WSADKeysGaming** [comment]
You have to pay for svp pro to encode videos to 60fps and it's not
opensource. If anything use butterflow after the video is upscaled

**Comment by k4yt3x** [comment]
@WSADKeysGaming not a bad idea. Although this might be a bit outside the scope of this project, but I will take a look once my jobs on hand are done.

**Comment by DonaldTsang** [comment]
@WSADKeysGaming so what other options are there except SVP and butterflow? Also any detailed comparisons of these tools?

**Comment by k4yt3x** [comment]
Might take a look into butterflow, but SVP is a no-go. It's paid standalone software.

**Comment by Sparktank** [comment]
SVP primarily relies on either Avisynth (c++) or Vapoursynth (python) to interpolate video.
The plugins required are based on open-source plugins.
Paying for it primarily gives you a more flexible GUI to customize the settings more than you can with the free version, as well as additional features (outside the scope of interpolating).

The same can be achieved with open-source Avisynth/Vapoursynth plugins like MVTools,etc.
There's a few threads on doom9 with free alternatives (but mainly aiming at Avisynth usage).

The most useful script I've seen using MVTools, RemoveGrain, and FFTW3 is this modded script:
https://forum.doom9.org/showthread.php?p=1847109#post1847109

There are other scripts that largely rely on MVTools but either require too much work to start off with or don't produce favorable results like the modded "JohnFPS" script.
Default settings are an average, and require testing with different sources (as well as the setting for "DCT=0", whereas "DCT=1" might improve on minor motion artefacts).

**Comment by DonaldTsang** [comment]
@k4yt3x I would rename the issue for any SVP alternatives
