### ISSUE TITLE
5.0.0 Streams (audio, subtitle) migration support

### ISSUE THREAD

**Issue by Zzip7** [k4yt3x/video2x#600]

**Comment by Zzip7** [comment]
На выходе,видео без звука.

**Comment by k4yt3x** [comment]
I don't think I've added the part where it copies the streams and stuff yet. I'll add it before the 5.0.0 (non-beta) release.

**Comment by Zzip7** [comment]
Спасибо!

**Comment by k4yt3x** [comment]
Has been added in beta4.
