### ISSUE TITLE
image file is truncated error.

### ISSUE THREAD

**Issue by Justplayedcards** [k4yt3x/video2x#601]
This has happened multiple times anyone knows how to fix it?

![Screenshot 2022-02-14 224453](https://user-images.githubusercontent.com/90477765/153988905-5483eb3d-40d1-426a-a3c3-de32b1bf4bd5.png)

![wsx](https://user-images.githubusercontent.com/90477765/153988975-9bf94d81-99a6-4ee9-9b88-0ee89ea93e41.png)

![3f3f](https://user-images.githubusercontent.com/90477765/153989134-f21b0775-e0f1-4321-a4b0-ade5466df6c6.png)

LOG FILE:

[video2x_error.log](https://github.com/k4yt3x/video2x/files/8065640/video2x_error.log)

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/154002568-c84739d2-7a23-4147-8584-2d07e86baf73.png)

It seems like RealSR ran into an error but didn't crash, which lead to a lot of the frames being corrupted. I'm not quite sure what happened. Maybe you ran out of VRAM or something?

**Comment by k4yt3x** [comment]
This error message alone honestly provides too little information. I don't have a good fix for it for now. Maybe consider Colab?

**Comment by Justplayedcards** [comment]
Thanks for the help I just restarted my pc and it worked :)

**Comment by k4yt3x** [comment]
Oh great. Reopen if it fails again.
