### ISSUE TITLE
No audio is copying to the output file

### ISSUE THREAD

**Issue by mahmud624683** [k4yt3x/video2x#602]
<img width="1134" alt="Screenshot 2022-02-16 at 12 59 13 AM" src="https://user-images.githubusercontent.com/21043410/154135206-3cd83a01-68dc-40a7-80a5-6c876ef55601.png">
<img width="964" alt="Screenshot 2022-02-16 at 1 30 59 AM" src="https://user-images.githubusercontent.com/21043410/154135250-98101c6f-da1f-4065-b4d9-e067763a5bae.png">

**Comment by k4yt3x** [comment]
That's expected. I haven't added the copy audio track function to 5.0 yet. You can do it manually with FFmpeg. It will be added before the final non-beta release.
