### ISSUE TITLE
GPU 1 not found

### ISSUE THREAD

**Issue by gomme600** [k4yt3x/video2x#606]
Hi,

I have a laptop with integrated graphics and a GTX 1060. When changing GPU: 0 to GPU: 1 I get an error message about the GPU not being found. I don't understand why my second GPU isn't working, upscaling on the integrated GPU is very slow.

Thanks for any help

**Comment by k4yt3x** [comment]
ncnn Vulkan only finds GPUs that support Vulkan. If your iGPU doesn't support vulkan, GPU 0 should already be your 1060.

**Comment by gomme600** [comment]
That's the problem, the iGPU (Intel 620) does support Vulkan as that's the one being used. The GTX 1060 doesn't seem to be found as there is no GPU 1.

**Comment by k4yt3x** [comment]
That's indeed a bit of a problem... I've been wanting to make it possible for users to choose which GPUs to use, but I've yet found a way to list all GPUs that support Vulkan and their ID. I'll also have to make sure that the displayed ID is identical to how ncnn Vulkan reads it.

What version of v2x are you using?

**Comment by k4yt3x** [comment]
If you run the program and select *-ncnn-vulkan as the algorithm, it should print all of the devices it finds. Can you share a screenshot or the output? I should look something like:

![image](https://user-images.githubusercontent.com/21986859/157385722-7232853d-2886-4932-81c6-24a14fcb1a69.png)
