### ISSUE TITLE
请问大佬，windows或python命令怎样转换一个文件夹的图片？微信nlanguage 这个命令报错了 video2x.exe -i L:/jpdrama/testvideo2x/ -o 'L:/jpdrama/testvideo2x_2/ -r 2 -d realsr_ncnn_vulkan -p 2

### ISSUE THREAD

**Issue by nissansz** [k4yt3x/video2x#609]
请问大佬，windows或python命令怎样转换一个文件夹的图片？微信nlanguage
这个命令报错了

video2x.exe -i L:/jpdrama/testvideo2x/ -o 'L:/jpdrama/testvideo2x_2/ -r 2 -d realsr_ncnn_vulkan -p 2

[+] INFO: 正在将文件添加到处理队列中
2022-03-08 20:43:46.503822 [+] INFO: 输入路径：L:\jpdrama\testvideo2x
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "pathlib.py", line 1312, in mkdir
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: "'L:\\jpdrama\\testvideo2x_2"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "video2x.py", line 342, in <module>
  File "upscaler.py", line 526, in run
  File "pathlib.py", line 1321, in mkdir
  File "pathlib.py", line 1422, in is_dir
  File "pathlib.py", line 1221, in stat
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: "'L:\\jpdrama\\testvideo2x_2"
[!] ERROR: The error log file can be found at: C:\Users\Ni\AppData\Local\Temp\video2x_vvoulm19.log

**Comment by k4yt3x** [comment]
直接开 GUI 把文件夹拖进去就完了

**Comment by nissansz** [comment]
拖进去比较慢。好像还要单独转换。
我想用这个子程序直接转换图片，但是不管是路径放单独一张，还是目录，都提示，invalid outputpath extension type不对。
只有把单张图片放在程序所在目录才能转换，是怎么回事？

另外GPU要怎么选？只能0? 不写-g 0。会出错,写 -g 1也是无法转换。realsr-ncnn-vulkan.exe 子程序-s 2也不能用，只能默认的4倍
realsr-ncnn-vulkan.exe -i 'L:/jpdrama/Tonari.no.Chikara.Ep02.Chi_Jap.HDTVrip.1280X720-5/jp/0_00_21_016__0_00_22_351_0000000000000000000000001.png' -o 'L:/jpdrama/Tonari.no.Chikara.Ep02.Chi_Jap.HDTVrip.1280X720-5/jp1/0_00_21_016__0_00_22_351_0000000000000000000000001.png'
![image](https://user-images.githubusercontent.com/41010669/157344523-2988beed-282f-4ca4-b90a-9b3191dcef97.png)

**Comment by k4yt3x** [comment]
```shell
video2x.exe -i L:/jpdrama/testvideo2x/ -o 'L:/jpdrama/testvideo2x_2/ -r 2 -d realsr_ncnn_vulkan -p 2
#                                                               |
#                                                                -----------这里是不是多了个 '
```

**Comment by k4yt3x** [comment]
啊这不是等宽字体真麻烦

我看着这里多打了个 '

![image](https://user-images.githubusercontent.com/21986859/157344900-313b5789-49ea-4309-a459-9af731fa4bf2.png)

**Comment by nissansz** [comment]
没有多打。看我上面windows运行截图

realsr-ncnn-vulkan.exe -i 0_00_21_016__0_00_22_351_0000000000000000000000001.png -o 0_00_21_016__0_00_22_351_0000000000000000000000001_2.png  -g 0


realsr-ncnn-vulkan.exe -i 'L:/jpdrama/Tonari.no.Chikara.Ep02.Chi_Jap.HDTVrip.1280X720-5/jp/0_00_21_016__0_00_22_351_0000000000000000000000001.png' -o 'L:/jpdrama/Tonari.no.Chikara.Ep02.Chi_Jap.HDTVrip.1280X720-5/jp1/0_00_21_016__0_00_22_351_0000000000000000000000001.png' -g 0

**Comment by nissansz** [comment]
把文件夹移到程序所在目录，提前创建好新目录，也可以转换目录下所有文件。就是不知道gpu P620是否用上了。只能用 -g 0，其余都报错
realsr-ncnn-vulkan.exe -i testvideo2x -o testvideo2x_2 -g 0


L:\jpdrama\video2x-4.8.1-win32-full\dependencies\realsr-ncnn-vulkan>realsr-ncnn-vulkan.exe -i testvideo2x -o testvideo2x_2 -g 0
[0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
[1 Quadro P620]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 Quadro P620]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[1 Quadro P620]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1

**Comment by k4yt3x** [comment]
> [0 Intel(R) UHD Graphics] queueC=0[1] queueG=0[1] queueT=0[1]
> [0 Intel(R) UHD Graphics] bugsbn1=0 buglbia=0 bugcopc=0 bugihfa=0
> [0 Intel(R) UHD Graphics] fp16p=1 fp16s=1 fp16a=1 int8s=1 int8a=1
> [1 Quadro P620] queueC=2[8] queueG=0[16] queueT=1[2]
> [1 Quadro P620] bugsbn1=0 buglbia=0 bugcopc=0 bugihfa=0
> [1 Quadro P620] fp16p=1 fp16s=1 fp16a=0 int8s=1 int8a=1

看起来 Quadro 是识别出来了的，看错误是 `vkQueueSubmit failed -4`，先升级个驱动试试？

**Comment by nissansz** [comment]
驱动好像已经是最新的了

**Comment by k4yt3x** [comment]
那我怀疑可能是显存太小了，2G 可能根本跑不起来默认 tile size 的 realsr-ncnn-vulkan，Intel UHD 用的应该是系统普通 RAM 所以还勉强能跑。直接调用 realsr-ncnn-vulkan 用 `-t` 把默认 tile size 调小一点试试，这个数值大概在 200 左右，如果不行的话就逐步减少，最少 32.

**Comment by nissansz** [comment]
用32可以勉强运行几步，然后又报错了。p620显存是4G. 但怎么会集成显卡反而能用gpu, 独显不能用

![image](https://user-images.githubusercontent.com/41010669/157384854-43065b97-f87d-46b6-a0b1-b7b32b3edba5.png)

**Comment by k4yt3x** [comment]
> p620显存是4G. 但怎么会集成显卡反而能用gpu, 独显不能用

我上面说了

> Intel UHD 用的应该是系统普通 RAM 所以还勉强能跑

---

我怀疑 P620 撑不起 realsr 需要的 VRAM，我跑的时候 22G VRAM 都觉得不够

**Comment by nissansz** [comment]
谢谢。colab或kaggle怎么运行realsr-ncnn-vulkan

**Comment by k4yt3x** [comment]
Colab 可以直接跑 video2x 5.0.0 倒是，不过要放大的是单个照片对吧，我还没做单帧的支持，可以自己开个 Colab notebook wget 一个 realsr-ncnn-vulkan 下来然后把 Google Drive mount 上去，如果写不来的话我可以写一个

**Comment by k4yt3x** [comment]
或者如果不需要经常用直接发给我我来跑也行的（

**Comment by nissansz** [comment]
好的，帮忙写个realsr-ncnn-vulkan colab吧。
只看到windows下的exe, 不知道在colab怎么跑。

我现在是想提取日剧日文字幕。
但是日文识别，要自己训练模型，还在训练。达到80%准确率了。不知道怎么提高到95%以上。
在将图片优化成白底黑字时也没有找到完美的方法，有的会少笔画，或者背景较杂
![0_00_21_016__0_00_22_351_0000000000000000000000001_output](https://user-images.githubusercontent.com/41010669/157386927-fa07de59-97d2-4973-875c-d4e11b0dba8d.png)
![0_00_21_016__0_00_22_351_0000000000000000000000001_output](https://user-images.githubusercontent.com/41010669/157386950-dda357d5-aef6-457d-a806-1f78085cd219.png)
![0_12_58_473__0_13_00_642_0000000000000000000000223_output](https://user-images.githubusercontent.com/41010669/157387028-84d8d0af-546f-4a06-b5d8-f974eb444820.png)

**Comment by k4yt3x** [comment]
这超出我知识范围了，我不是学 NLP 的，我主要的图形处理知识都只在 OpenCV 上
Colab 差不多这样：https://colab.research.google.com/drive/1UIrVmP-PwwY-A_7EfO4g0l5ZT5bvguZZ?usp=sharing

**Comment by nissansz** [comment]
colab运行报以下错误，是 怎么解决？

!realsr-ncnn-vulkan/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp' -o '/content/jp_w'

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/bin/bash: realsr-ncnn-vulkan/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan: Transport endpoint is not connected

![image](https://user-images.githubusercontent.com/41010669/157388841-0c709baa-1365-4c27-aefa-a8f71f913d35.png)

**Comment by k4yt3x** [comment]
`-o /content/jp_w` 改成 `/content/drive/MyDrive` 下的子目录，比如 `/content/drive/MyDrive/Colab Notebooks/jp_w`

**Comment by nissansz** [comment]
!realsr-ncnn-vulkan/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp/' -o '/content/drive/MyDrive/jp_w'
还是报错
!realsr-ncnn-vulkan/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp/' -o '/content/drive/MyDrive/jp_w'

改成!/content/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp/' -o '/content/drive/MyDrive/jp_w' -g 0
报如下错误
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
vkEnumeratePhysicalDevices failed -3
invalid gpu device

**Comment by k4yt3x** [comment]
这是没使用 GPU instance 吧，换个 runtime type 就好了

![image](https://user-images.githubusercontent.com/21986859/157394178-59c49cee-15ab-4f03-934a-3ab3af61a49d.png)

我顺便把 notebook 稍微改了下，刚才 path 有点问题

**Comment by nissansz** [comment]
可以运行了。
!/content/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp' -o '/content/jp_w'

但是好像没法改分辨率。只能说默认的4倍，没法2倍
!/content/realsr-ncnn-vulkan-20210210-ubuntu/realsr-ncnn-vulkan -i '/content/drive/MyDrive/Colab Notebooks/jp' -o '/content/jp_w' -s 2
invalid scale argument

**Comment by nissansz** [comment]
你的那个gui也是放大4x，然后改尺寸？

**Comment by nissansz** [comment]
怪不得我对比放大2倍的结果realsr-ncnn-vulkan最清晰。如果同样放大4倍，gui里的哪个方式最清晰，最好？

**Comment by k4yt3x** [comment]
看情况，按照我的经验这个主要还是看图片本身的类型，实际上最好是抽个样张试一试

**Comment by nissansz** [comment]
就是日剧，背景每张都不同的

**Comment by k4yt3x** [comment]
按道理说 realsr 是效果最好的，抽几帧对比试试就知道了

**Comment by nissansz** [comment]
好的，谢谢
