### ISSUE TITLE
Error setting option video_size

### ISSUE THREAD

**Issue by gian800** [K4YT3X/video2x#61]
I'm getting this error after following the tutorial. I've set the threads to 1 in case that was the issue, but it didn't fix it.
![1](https://user-images.githubusercontent.com/48959138/55013426-67441480-4fe9-11e9-9a44-34e3219956b0.png)
I've tried multiple resolution settings, but all return this error.
I'm using a gtx1080 and I have CUDA installed.

**Comment by K4YT3X** [comment]
This problem has already been fixed in the latest version.
Please download video2x again.
