### ISSUE TITLE
Is there a reason not to use ffmpeg's -vf scale=wxh:flags=lanczos ?

### ISSUE THREAD

**Issue by Boteium** [k4yt3x/video2x#610]
I think the downscale part can be done by ffmpeg's lancoz downscale filter and remove the need to re-scale it by python.
It's much faster and efficient. The downscale and encoding process can be done together in only one step.
There is really no need to add parallelism in python in the next version when ffmpeg can already do that.

**Comment by k4yt3x** [comment]
Sounds like a nice idea, I'll try implementing that.

**Comment by thekryz** [comment]
does this work now? What does the flag have to look like for video2x command line version?

**Comment by k4yt3x** [comment]
No it wasn't implemented in the new version yet. Implementing this is more complex with the C++ version since we aren't calling FFmpeg commands anymore and it's no longer a simple string. We'll need to create buffer sinks and filtergraphs. It's most likely going to be added in #1196
