### ISSUE TITLE
On windows cache folder must be NTFS

### ISSUE THREAD

**Issue by louist103** [k4yt3x/video2x#611]
If the cache drive is not NTFS the program throws the error:
`OSError: [WinError 1] Incorrect function: <File path>`

**Comment by k4yt3x** [comment]
What version of v2x are you using? I recall someone using FAT32 before without problems.

**Comment by louist103** [comment]
4.8.1 
From releases

**Comment by k4yt3x** [comment]
Can you share a screenshot of how you configured the path?
