### ISSUE TITLE
video2x.org down?

### ISSUE THREAD

**Issue by DillFrescott** [k4yt3x/video2x#619]
It brings me to an error page...

**Comment by k4yt3x** [comment]
Yeah I took that page down since I didn't want to mix website content and travis CI stuff with other things in this repo. Everything that's on that page is on this repo's README anyways. I can redirect video2x.org to our repo home page for now I guess.

**Comment by k4yt3x** [comment]
I just brought it back up, along with some shortcuts:

- video2x.org
- video2x.org/release
- video2x.org/mirror
- video2x.org/container
- video2x.org/colab

I'll also update the homepage soon. Thanks for reminding me of this.
