### ISSUE TITLE
in colab when using realsr: nexpected keyword argument 'noise'

### ISSUE THREAD

**Issue by mortenthorsen** [k4yt3x/video2x#620]
Hi,

In google colab when using "realsr" algorithm I get the following error:

TypeError: __init__() got an unexpected keyword argument 'noise'

I see that realsr have a option called noise-level.

also when using "srmd" I don't see any activity in the GPU resource monitor, only when using waifu2x or interpolate.

Great project though
M

**Comment by k4yt3x** [comment]
Thanks for the report, I've already noticed that when testing locally. I've already pushed a change to realsr to accept **kwargs. I kinda forgot about it after I fixed it locally. I'll publish a new version soon.

**Comment by k4yt3x** [comment]
It should be working fine now. Try again.
