### ISSUE TITLE
Returned Non-Zero Exit Status

### ISSUE THREAD

**Issue by knpoe03** [k4yt3x/video2x#621]
Hey there!

Apologies in advance. It is my first time using GitHub and my first time using any one of these programs. I am merely trying to enhance a 3 second video. However, each time that I run the program, this error pops up: 

```console
subprocess.CalledProcessError: Command '['C:\\Users\\Katie\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\realsr-ncnn-vulkan\\realsr-ncnn-vulkan', '-s', '4', '-t', '0', '-m', 'C:\\Users\\Katie\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\realsr-ncnn-vulkan\\models-DF2K_JPEG', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\Katie\\AppData\\Local\\Temp\\video2x\\tmpn52xj4gs', '-o', 'C:\\Users\\Katie\\AppData\\Local\\Temp\\video2x\\tmpulfwzdo9']' returned non-zero exit status 3221225781.
```

How do I fix this?

[video2x_error.log](https://github.com/k4yt3x/video2x/files/8354410/video2x_error.log)

**Comment by k4yt3x** [comment]
Curiously the logs doesn't really contain why the process failed. What GPU do you have?
