### ISSUE TITLE
ERROR: Subprocess 9292 exited with code 3221225477

### ISSUE THREAD

**Issue by TinManAD** [k4yt3x/video2x#623]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/8366897/video2x_error.log)
![image](https://user-images.githubusercontent.com/102560739/160502751-9947d6b3-de35-41c7-a491-bc14847285a7.png)
![image](https://user-images.githubusercontent.com/102560739/160502421-0cf17993-bab5-4e27-a771-d7228e39e93f.png)
![image](https://user-images.githubusercontent.com/102560739/160502455-8c797a7a-d1c3-4001-a629-51694a81b899.png)

Hi, I recently started using video2x to upscale some DVDs. It worked well for a couple days, but now I always get this error when the program finishes compiling the video back from the upscaled frames. Sometimes it even causes my computer to blue-screen. Since it began throwing this error I have not been able to get it to work on any driver(algorithm) for any video file. Single images are still bale to be upscaled just fine. The error seems to be related to an attempt to access unregistered memory, but I'm not sure.

Specs:
Core i7-6700k - 4.6GHz OC
16 GB DDR4 -2666Mhz
Nvidia RTX 3070ti

I'm running up-to-date Windows 10 21H1 19043.1586, the latest Nvidia GeForce drivers with CUDA and CuDNN, and python 3.7.

**Comment by k4yt3x** [comment]
It looks like FFmpeg ran into some kind of an error half-way through the last step, which is uncommon. Do you have enough storage left on your device?

**Comment by TinManAD** [comment]
So, I tried replacing the ffmpeg folder in video2x/dependencies with the latest version of ffmpeg (5.0). Doing so gave the same error on the first test run. I toggled off the setting for "Ensure output width and height are divisible by 2" under the ffmpeg settings tab and did a second run. It caused an error and my pc Blue screened, "System_Service_Exception" in "NTFS.sys".

On that second test I did I checked the box to "Preserve Frames". When my PC restarted I checked the temp files and all of the upscaled frames were there, but not the originals. Is that the correct behavior for the setting?

[video2x_error_3.log](https://github.com/k4yt3x/video2x/files/8389702/video2x_error_3.log)
[Windows_Error_Report.txt](https://github.com/k4yt3x/video2x/files/8390010/Windows_Error_Report.txt)

**Comment by k4yt3x** [comment]
I'm sorry this version has been so buggy. I'll try to make 5.0.0 beta available on Windows soon so people can start using the much less buggy version.

> all of the upscaled frames were there, but not the originals.

- If you open the frames, do they look normal? (a proper image instead of some scrambled nonsense or pure black)
- What's the version of GPU driver you're using?

**Comment by k4yt3x** [comment]
Hi sorry for the late reply, I've got way too much on my plate recently.

> This may indicate a problem with the caching cleanup system?

It is unlikely. I don't see any logical problems with the caching mechanism. There should also be a separate directory created for every run. It should be something else that went wrong, but the logs don't contain much information to work with. It just stopped.

**Comment by k4yt3x** [comment]
You can take a look at the [Colab notebook](https://colab.research.google.com/drive/1gWEwcA9y57EsxwOjmLNmNMXPsafw0kGo) if you want to give 5.0.0 a try. I'll close this issue for now since there's no code I can fix in this for now. Feel free to keep replying.
