### ISSUE TITLE
--model_dir output

### ISSUE THREAD

**Issue by robzombie91** [K4YT3X/video2x#63]
https://pastebin.com/YDkrDKGk

**Comment by K4YT3X** [comment]
Redundant `-y` argument in command.

**Comment by robzombie91** [comment]
new paste no extra argument, sorry
https://pastebin.com/QdNEvVQq

**Comment by robzombie91** [comment]
so, what i did is i added two \\'s in each of the lines and now it magically works

**Comment by K4YT3X** [comment]
>  '--model_dir', 'C:UsersrobAppDataLocalvideo2xwaifu2x-caffemodelsphoto'

Try quoting your `--model_dir`:

```shell
python video2x.py -m gpu --width=1280 --height=720 --model_dir "C:\Users\rob\AppData\Local\video2x\waifu2x-caffe\models\photo" -i sample2.mp4 -o sample4.mp4
```

**Comment by robzombie91** [comment]
ill try that argument after this one is done processing if it finishes

**Comment by K4YT3X** [comment]
> so, what i did is i added two \'s in each of the lines and now it magically works

I guess argparse just assumed the `\` being escape sequences.
I don't understand why `-i` and `-o` works but this one doesn't.

**Comment by K4YT3X** [comment]
Conclusion: `git` shell arguments need to be escaped.

**Comment by robzombie91** [comment]
[30 days sample.zip](https://github.com/K4YT3X/video2x/files/3010811/30.days.sample.zip)

**Comment by K4YT3X** [comment]
I guess it really doesn't do that good for real-life footages.
