### ISSUE TITLE
Issue with encoder looping during interpolation job

### ISSUE THREAD

**Issue by snixon** [k4yt3x/video2x#632]
https://github.com/k4yt3x/video2x/blob/f2b2e11c41d8744e43a0fa4c4f1a3d26bec5d1cf/video2x/encoder.py#L143-L173

Hi Folks,
I've noticed an issue when trying to run an interpolation job, the code seems to get stuck in this loop, specifically in lines 151-154.

What I see is the job process normally, the decoder queue empties and the decoder thread stops, then we get stuck with supposedly two remaining tasks to complete, but the requested frame_index is None, so we end up in a loop.

I don't quite understand the logic around the interpolation yet, but I was wondering if the calculation of total tasks at the start of the run might be off, if the decision engine decides not to process a frame or two and we end up with a situation where the total job length extends past the number of actual frames to process?

The behavior seems to be the same regardless of the input file, I've made a couple small ones for testing.

Cheers

EDIT: Launch args:   `python -m video2x -i ../1min_sample.mkv -o ../int_test.mkv interpolate`

**Comment by k4yt3x** [comment]
Hi there sorry, this somehow didn't end up on my task list in my notifications. I didn't see this until I comb through all issues to close stale issues. I've also noticed this problem while processing some clips. I'm not sure why it's like that just yet. I am rewriting some core logic, and I'll take a look at it while I'm at it.
