### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by Keerigan45** [k4yt3x/video2x#637]
Hey when i try to upscale it it run on my cpu with a 100% usage i have an I7 8700kf and a rtx 2060. i let it run on cpu but even 5 minutes after i launched it there is still no preview of the files i've checked the temp files and apparently it's extracting all the images but i don't know if it's normal to run this task on the cpu. I've checked Compute_1 and Cuda but it's not using it. By the way your work is incredible you've saved my day =)

**Comment by Keerigan45** [comment]
nvm i'm domb amazing work dude

**Comment by Keerigan45** [comment]
All is good i'm just really dumb

**Comment by k4yt3x** [comment]
The frame decoding part is done by FFmpeg, and it does run on CPU. It'll take a while before you see previews. Completely normal.
