### ISSUE TITLE
C:\ffmpeg\bin\ffmpeg.exe file not found

### ISSUE THREAD

**Issue by HotPizzaYT** [k4yt3x/video2x#639]
How to replicate:

Open FFMpeg binary in FFMpeg settings > Global options > Select FFMpeg Binary Directory > Pick FFMpeg

[video2x_error.log](https://github.com/k4yt3x/video2x/files/8551688/video2x_error.log)

**Comment by k4yt3x** [comment]
Does the included one not work? Could you please share a screenshot of the setting and your FFmpeg's path?
