### ISSUE TITLE
Error: Could find no file with path 'C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png' and index in the range 0-4 C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png: No such file or directory

### ISSUE THREAD

**Issue by marchkarcz** [K4YT3X/video2x#64]
I don't know how to get rid of the styling.

frame=10721 fps= 78 q=-0.0 Lsize=N/A time=00:05:57.72 bitrate=N/A speed=2.61x
video:2994530kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-03-27 13:22:47.637065 [+] INFO: Executing: C:\Users\March M. Cain\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\videoplayback.mp4
[+] INFO: Framerate: 29.970027177371907
[+] INFO: Starting to upscale extracted images
2019-03-27 13:22:48.286873 [+] INFO: [upscaler] Thread MainThread started
2019-03-27 13:22:48.286873 [+] INFO: Executing: ['C:\\Users\\March M. Cain\\AppData\\Local\\video2x\\waifu2x-converter-cpp\\waifu2x-converter-cpp.exe', '--output-format', 'png', '--jobs', '1', '--model-dir', 'C:\\Users\\March M. Cain\\AppData\\Local\\video2x\\waifu2x-converter-cpp\\models_rgb', '--scale-ratio', '2.0', '--noise-level', '3', '--mode', 'noise-scale', '--silent', '--output', 'C:\\Users\\MARCHM~1.CAI\\AppData\\Local\\Temp\\video2x\\tmpmqh2d0n3', '--input', 'C:\\Users\\MARCHM~1.CAI\\AppData\\Local\\Temp\\video2x\\tmpp36798d2']
Upscaling Progress:   0%|                                        | 0/10721 [00:03<?, ?it/s]CUDA: GeForce MX150
We're going to be operating in a directory. dir:C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpp36798d2
Upscaling Progress:   0%|                                        | 0/10721 [00:04<?, ?it/s][Upscaling Progress:   0%|                                        | 0/10721 [00:06<?, ?it/s]
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-03-27 13:22:55.627960 [+] INFO: Executing: C:\Users\March M. Cain\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffmpeg.exe -r 29.970027177371907 -f image2 -s 960x736 -i C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\no_audio.mp4 -y
ffmpeg version N-93461-g6e42021128 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.105 / 58. 47.105
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[image2 @ 000001f06fa5a080] Could find no file with path 'C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png' and index in the range 0-4
C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png: No such file or directory
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 254, in <module>
    upscaler.run()
  File "C:\Users\March M. Cain\Desktop\video2x-master\bin\upscaler.py", line 305, in run
    fm.convert_video(framerate, '{}x{}'.format(self.scale_width, self.scale_height), self.upscaled_frames)
  File "C:\Users\March M. Cain\Desktop\video2x-master\bin\ffmpeg.py", line 125, in convert_video
    subprocess.run(execute, shell=True, check=True)
  File "C:\Users\March M. Cain\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\March M. Cain\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '29.970027177371907', '-f', 'image2', '-s', '960x736', '-i', 'C:\\Users\\MARCHM~1.CAI\\AppData\\Local\\Temp\\video2x\\tmpmqh2d0n3\\extracted_%d.png', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', 'C:\\Users\\MARCHM~1.CAI\\AppData\\Local\\Temp\\video2x\\tmpmqh2d0n3\\no_audio.mp4', '-y']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using

**Comment by marchkarcz** [comment]
> frame=10721 fps= 78 q=-0.0 Lsize=N/A time=00:05:57.72 bitrate=N/A speed=2.61x
> video:2994530kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> [+] INFO: Reading video information
> 2019-03-27 13:22:47.637065 [+] INFO: Executing: C:\Users\March M. Cain\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\videoplayback.mp4
> [+] INFO: Framerate: 29.970027177371907
> [+] INFO: Starting to upscale extracted images
> 2019-03-27 13:22:48.286873 [+] INFO: [upscaler] Thread MainThread started
> 2019-03-27 13:22:48.286873 [+] INFO: Executing: ['C:\Users\March M. Cain\AppData\Local\video2x\waifu2x-converter-cpp\waifu2x-converter-cpp.exe', '--output-format', 'png', '--jobs', '1', '--model-dir', 'C:\Users\March M. Cain\AppData\Local\video2x\waifu2x-converter-cpp\models_rgb', '--scale-ratio', '2.0', '--noise-level', '3', '--mode', 'noise-scale', '--silent', '--output', 'C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3', '--input', 'C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpp36798d2']
> Upscaling Progress: 0%| | 0/10721 [00:03<?, ?it/s]CUDA: GeForce MX150
> We're going to be operating in a directory. dir:C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpp36798d2
> Upscaling Progress: 0%| | 0/10721 [00:04<?, ?it/s][Upscaling Progress: 0%| | 0/10721 [00:06<?, ?it/s]
> [+] INFO: Upscaling completed
> [+] INFO: Converting extracted frames into video
> 2019-03-27 13:22:55.627960 [+] INFO: Executing: C:\Users\March M. Cain\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffmpeg.exe -r 29.970027177371907 -f image2 -s 960x736 -i C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\no_audio.mp4 -y
> ffmpeg version N-93461-g6e42021128 Copyright (c) 2000-2019 the FFmpeg developers
> built with gcc 8.2.1 (GCC) 20190212
> configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
> libavutil 56. 26.100 / 56. 26.100
> libavcodec 58. 47.105 / 58. 47.105
> libavformat 58. 26.101 / 58. 26.101
> libavdevice 58. 7.100 / 58. 7.100
> libavfilter 7. 48.100 / 7. 48.100
> libswscale 5. 4.100 / 5. 4.100
> libswresample 3. 4.100 / 3. 4.100
> libpostproc 55. 4.100 / 55. 4.100
> [image2 @ 000001f06fa5a080] Could find no file with path 'C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png' and index in the range 0-4
> C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png: No such file or directory
> [!] ERROR: An exception has occurred
> Traceback (most recent call last):
> File "video2x.py", line 254, in 
> upscaler.run()
> File "C:\Users\March M. Cain\Desktop\video2x-master\bin\upscaler.py", line 305, in run
> fm.convert_video(framerate, '{}x{}'.format(self.scale_width, self.scale_height), self.upscaled_frames)
> File "C:\Users\March M. Cain\Desktop\video2x-master\bin\ffmpeg.py", line 125, in convert_video
> subprocess.run(execute, shell=True, check=True)
> File "C:\Users\March M. Cain\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['C:\Users\March M. Cain\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffmpeg.exe', '-r', '29.970027177371907', '-f', 'image2', '-s', '960x736', '-i', 'C:\Users\MARCHM1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\extracted_%d.png', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', 'C:\Users\MARCHM~1.CAI\AppData\Local\Temp\video2x\tmpmqh2d0n3\no_audio.mp4', '-y']' returned non-zero exit status 1.
> [!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using

**Comment by marchkarcz** [comment]
woops did not mean to close

**Comment by K4YT3X** [comment]
The previous build of waifu2x-converter-cpp is malfunctioning.
It's not video2x's problem.

**Comment by marchkarcz** [comment]
Oh, damn. I just downloaded it yesterday. I'm assuming theres a new update?

**Comment by K4YT3X** [comment]
See this issue for more details:
https://github.com/DeadSix27/waifu2x-converter-cpp/issues/121

You can also just set the processor to OpenCL.
