### ISSUE TITLE
Conversion legth/limit select option?

### ISSUE THREAD

**Issue by StevenNani** [k4yt3x/video2x#642]
Is there an option where I can convert specific parts of a video or set a start and end time to be converted? Like if I wanted to convert the first five minutes of a 10 min video?

**Comment by k4yt3x** [comment]
It is possible -- by adding the `-t 00:00:5.0` to the FFmpeg args. I don't think there will be a specific option for it as FFmpeg has way too many args. Instead, the FFmpeg args will be customizable through a config file of sort in the future, but that'll not happen for a while.

For now, you could easily do it manually with FFmpeg:

```shell
ffmpeg -ss 00:01:00 -to 00:02:00  -i input.mp4 -c copy output.mp4
```
