### ISSUE TITLE
Command '['C:\\video2x\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\video2x\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\video2x\\tmpb20hlq_n', '-o', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\video2x\\tmptfzmfb76']' returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by EugeneLiu2013** [k4yt3x/video2x#646]
I was testing for 2x and 10x. The error is from 10x process
[video2x_error.log](https://github.com/k4yt3x/video2x/files/8671007/video2x_error.log)

**Comment by k4yt3x** [comment]
10 processes is too many. You've probably just ate up all your VRAM. Also these AI algorithms don't scale well with mult-processing. You'll find that running multiple processes ain't that much faster than just one.
