### ISSUE TITLE
Need a general tutorial guide to fix bad scaling quality.

### ISSUE THREAD

**Issue by simplyexperimental** [k4yt3x/video2x#647]
Was really excited to get this but results are bad. There is no video tutorial on the best settings this is is very much needed.
I'm pretty sure I'm doing something wrong but no way to know except to see the results.
The problem is when changing settings and the results still the same.
I want to upscale 1080p video to 4k and when I do this the result is blurry and worse than original.
Even the images in the processing folders upscaled are blurry even though I can see the dimensions are double in size or more.
I'd love to get the premium but right now the results are **unusable.**

I tried different engines but there's so much options is annoying I don't know if the settings even do anything the results always the same.

If too lazy to post a video then maybe some images of best settings for real life video and different set for anime video, different set for single 2d image only.

**Comment by simplyexperimental** [comment]
To help this problem I tried switch all 3 engines to real ESREGanNcnnVulkan. The tool tip says it is the best for real life.
I chose realesrgan4-xplus
I attached my settings maybe you can see somethings wrong. I have Nvidia RTX 3070 am I using it to full here?
From the results now I can see that this is better than the others - the other engines I tested degraded badly the image.
However it looks like the plugin really struggles with human body skin. Like it makes it look hand painted style which is wrong.
It should be crisp and clear instead not sure why it doesn't do this.
The thing is the settings I used have no problem with other objects like bed cloth pattern and keyboard in image but person near it is like the algorithm is using wrong setting?
![1-Video Setting](https://user-images.githubusercontent.com/62986011/168216211-ed460f43-3169-47e3-afc3-1a4d67b587ee.jpg)
![1-Additional Setting](https://user-images.githubusercontent.com/62986011/168216217-5523f7c3-2a05-4bdf-9282-2aeeda9112c0.jpg)
![1-Home Setting](https://user-images.githubusercontent.com/62986011/168216221-7ec9c41e-4074-471d-83cc-19c8802a49db.jpg)

**Comment by simplyexperimental** [comment]
Update I wanted to say there is nothing wrong with my settings just the engine being used are trash.
At least for me literally the only one worthy of a mention here in terms of scaling a grainy 1080p video to 4k looking crisp was the realcugan one. Select for your video engine the Real-CUGAN - settings are good as they are. 
Then in the home page turn off video frame interpolation (we don't need to change fps).
Then in the home page choose your video scale (2 or 4) and then below choose video denoise I put mine -1 as it's best.
I have an Nvidia card so I can benefit from RTX and Cuda.

**Comment by k4yt3x** [comment]
Did you come to the wrong project? The screenshots you've posted don't belong to this project.

**Comment by simplyexperimental** [comment]
I'm so sorry hahahah. Feel free to delete this post.
