### ISSUE TITLE
Starting from where it left off.

### ISSUE THREAD

**Issue by Insephet** [k4yt3x/video2x#648]
I was trying to upscale a video last night, the power went out. Is there a possible way that I can make it start where it left off, all of the image files are still in the temp folder.

Is there an easy way that you can make it to recognize the extracted and processed cache, and finish the ones that haven't been processed?

**Comment by k4yt3x** [comment]
Currently the only implemented feature is pause & continue in the same session, and it's only in 5.0.0. I've been wanting to implement the pause & continue with the possibility to continue after a reboot for a long time (see #65), but it is a complicated feature. Even if the program is stopped gracefully, it'll still have to save all of the processing settings, and the progress of the processing. That's quite a bit to write in code. With accidental termination of the program it's even harder.
