### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Bergmott** [k4yt3x/video2x#650]
![image](https://user-images.githubusercontent.com/98070516/168457682-40d9e0bb-70ea-4a47-a14b-1125b505b291.png)
the console show this when i run it

**Comment by k4yt3x** [comment]
Ah that's a bug fixed in a nightly, I can't rebuild it, but you can re-encode the video manually to temporarily circumvent the problem. I think this will do:

```shell
ffmpeg -i input.mp4 -vcodec libx264 output.mkv
```

**Comment by Bergmott** [comment]
it works, thank you!
