### ISSUE TITLE
[NULL @ 000002142e00e980]

### ISSUE THREAD

**Issue by TotallyDerp** [K4YT3X/video2x#66]
After it's 'done', it throws me this error message (in red):

> [NULL @ 000002142e00e980] Unable to find a suitable output format for 'C:\Users\shail\Videos'
> C:\Users\shail\Videos: Invalid argument
> [!] ERROR: An exception has occurred\

I used this to launch it:

> video2x.py -m gpu -r 2 -d waifu2x_converter -i "C:\Users\shail\X.mp4" -o C:\Users\shail\Videos\

Is there something I did wrong here?

**Comment by metzo007** [comment]
I am new to this, but dont you have to specify the output file like

video2x.py -m gpu -r 2 -d waifu2x_converter -i "C:\Users\shail\X.mp4" -o C:\Users\shail\Videos\Y.mp4

also fits the error message. It cant find the output formal because you did not provide a output file.

**Comment by TotallyDerp** [comment]
> I am new to this, but dont you have to specify the output file like
> 
> video2x.py -m gpu -r 2 -d waifu2x_converter -i "C:\Users\shail\X.mp4" -o C:\Users\shail\Videos\Y.mp4
> 
> also fits the error message. It cant find the output formal because you did not provide a output file.

Yup, that fixed it. Thanks a lot metzo007!

**Comment by K4YT3X** [comment]
Output should be a file, not a folder, as described by @metzo007 .
