### ISSUE TITLE
Command '['C:\\Users\\apple\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\apple\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\apple\\AppData\\Local\\Temp\\video2x\\tmpph51eplt', '-o', 'C:\\Users\\apple\\AppData\\Local\\Temp\\video2x\\tmp69i73le6']' returned non-zero exit status 4294967295.

### ISSUE THREAD

**Issue by RyutoSetsujin** [k4yt3x/video2x#660]
I just want to upscale a anime DVD I legally own so I can watch it in a higher quality
[video2x_error.log](https://github.com/k4yt3x/video2x/files/8802132/video2x_error.log)

**Comment by RyutoSetsujin** [comment]
I have a GTX 3060 iirc

**Comment by k4yt3x** [comment]
You're getting a `vkCreateInstance failed` which is indicates it's likely that you have a device that doesn't support vulkan. Please verify your GPU model and try updating its driver.

**Comment by RyutoSetsujin** [comment]
It's a "NVIDIA GeForce RTX 3060". I don't know how to update my GPU drivers.

**Comment by RyutoSetsujin** [comment]
Oh... my drivers are already updated...

**Comment by k4yt3x** [comment]
And it's still not working? It might be detecting the wrong GPU device. Just to make sure, get a GPU-Z and see if you can see the Vulkan checkbox at the bottom. If you're not sure, post a screenshot. I can help debugging thy it might be using the wrong device, but I really don't have time atm.
