### ISSUE TITLE
McAfee detects as virus

### ISSUE THREAD

**Issue by NcMasters** [k4yt3x/video2x#663]
![image](https://user-images.githubusercontent.com/99719002/171990137-ccaba36d-e921-4f28-bb23-a2ccf02f5524.png)
The gui file gets deleted
![image](https://user-images.githubusercontent.com/99719002/171990166-fb7f3426-8214-4e22-8bdb-cd66215b24e8.png)

**Comment by k4yt3x** [comment]
I don't think AVs can properly scan Python scripts embedded in PyInstaller bundles. Try scanning it on [VirusTotal](https://www.virustotal.com/) too just to see what other engines say about it. If you're still not confident, run directly from source code (which will take a lot of effort to set up) or run the Colab version.
