### ISSUE TITLE
test_upscale_image()

### ISSUE THREAD

**Issue by HuShenS** [k4yt3x/video2x#664]
Running the test_upscale_image there are two errors：
`
tests/test_upscaler.py->test_upscale_image
`

1、The first error is that the Upscaler parameter is given too much, guessing that it should be the processed_frames list given more parameters：

      Traceback (most recent call last):

        File "/host/tests/test_upscaler.py", line 59, in <module>

          test_upscale_image()

        File "/host/tests/test_upscaler.py", line 37, in test_upscale_image

          upscaler = Upscaler(processing_queue, processed_frames, pause)

      TypeError: __init__() takes 3 positional arguments but 4 were given

2、The second error is  'Upscaler' object has no attribute 'upscale_image'
      

        Traceback (most recent call last):

        File "/host/tests/test_upscaler.py", line 59, in <module>

          test_upscale_image()

        File "/host/tests/test_upscaler.py", line 41, in test_upscale_image

          upscaled_image = upscaler.upscale_image(image, 1680, 960, "waifu2x", 3)

      AttributeError: 'Upscaler' object has no attribute 'upscale_image'

**Comment by k4yt3x** [comment]
This is intended to be used with pytest.

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/172017168-c61e8a4c-b4a8-439d-8979-29d36c473aa7.png)

Segfault is a known upstream issue

**Comment by HuShenS** [comment]
Dear author, can you provide the latest version of docker image or code? I'd like to batch enlarge the images to improve the clarity, thank you very much, I appreciate it!
