### ISSUE TITLE
LLVM ERROR: Broken function

### ISSUE THREAD

**Issue by rsrrohit** [k4yt3x/video2x#676]
This is  the output I get when I run the video2x

`2022-07-06 23:39:15.244 | INFO     | video2x.video2x.video2x:_get_video_info:143 - Reading input video information
23:39:15.438983 | INFO     | Starting video decoder
23:39:15.450156 | INFO     | Starting video encoder
23:39:15.466056 | INFO     | Upscaler process 0 initiating
23:39:15.474625 | INFO     | Upscaler process 2 initiating
23:39:15.474100 | INFO     | Upscaler process 1 initiating
23:39:15.474865 | INFO     | Upscaler process 3 initiating
23:39:15.477220 | INFO     | Upscaler process 4 initiating
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  bugsbn1=0  bugbilz=102  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf54.63.104
  Duration: 00:21:27.56, start: 0.000000, bitrate: 2121 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x540 [SAR 1:1 DAR 4:3], 1997 kb/s, 25 fps, 25 tbr,
12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 117 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 720x540 [SAR 1:1 DAR 4:3], q=2-31, 233280 kb/s, 25 fps, 25
tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 rawvideo

[0 llvmpipe (LLVM 12.0.0, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  bugsbn1=0  bugbilz=214  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Invalid bitcast
  %379 = bitcast i32 %378 to i16
LLVM ERROR: Broken function
Invalid bitcast
  %379 = bitcast i32 %378 to i16
LLVM ERROR: Broken function
23:39:18.478249 | ERROR    | process died unexpectedly
Traceback (most recent call last):

  File "run_video2x.py", line 7, in <module>
    video2x.upscale(
    |       -> <function Video2X.upscale at 0x7efe83fdd0d0>
    -> <video2x.video2x.video2x.Video2X object at 0x7efe913acc10>

  File "/root/video2x/video2x/video2x.py", line 410, in upscale
    self._run(
    |    -> <function Video2X._run at 0x7efe83fdd040>
    -> <video2x.video2x.video2x.Video2X object at 0x7efe913acc10>

> File "/root/video2x/video2x/video2x.py", line 307, in _run
    raise Exception("process died unexpectedly")

Exception: process died unexpectedly
23:39:18.494460 | INFO     | Stopping processor processes`

**Comment by k4yt3x** [comment]
See #607
