### ISSUE TITLE
For some reason it crashes before processing the first frame.

### ISSUE THREAD

**Issue by guillemdc** [k4yt3x/video2x#678]
It starts working and does so for a while. After a minute or two it crashes with this message and the attached log.

Command '['D:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'D:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '3840', '--scale_height', '2160', '--input_path', 'D:\\Temp\\video2x\\tmp969v38f4\\0', '--output_path', 'D:\\Temp\\video2x\\tmphxiihs5i']' returned non-zero exit status 3221226505.

[video2x_error.log](https://github.com/k4yt3x/video2x/files/9074729/video2x_error.log)

**Comment by mirh** [comment]
> Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

The problem seems pretty obvious. Do you even have an nvidia card?

**Comment by k4yt3x** [comment]
Try updating your GPU drivers too.

**Comment by k4yt3x** [comment]
Reopen if it's still not fixed.
