### ISSUE TITLE
Error in Step-By-Step Tutorial

### ISSUE THREAD

**Issue by metzo007** [K4YT3X/video2x#68]
Hi, if you use the example Line in the Step-By-Step Tutorial like 

python video2x.py -m gpu -r 2 --width=1920 --height=1080 -i D:\1.mp4 -o D:\2.mp4

you will get a 

[!] ERROR: You can only specify either scaling ratio or output width and height

Please Update the tutorial. Thanks

**Comment by Smarthard** [comment]
@K4YT3X in [running-video2x-for-the-first-time](https://github.com/K4YT3X/video2x/wiki/Step-By-Step-Tutorial#running-video2x-for-the-first-time) section

**Comment by K4YT3X** [comment]
Thanks. I forgot to remove the `-r 2` when I copied the command over from elsewhere.
