### ISSUE TITLE
[question] Where to modify (perpetually) output path?

### ISSUE THREAD

**Issue by masterofobzene** [k4yt3x/video2x#681]
I know I can change it from the GUI but this change is temporal and after relaunching the program this goes to default again..
I found some clues on the yaml config file but I fear breaking everything.

Can I just modify this line?:

waifu2x_ncnn_vulkan:
  path: 'dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan'
  v: null # verbose output
  #i: null # input-path: input image path (jpg/png/webp) or directory
  **_#o: null # output-path: output image path (jpg/png/webp) or directory_** <--- THIS ONE
  'n': 2 # noise-level: denoise level (-1/0/1/2/3, default=0)
  s: 2 # scale: upscale ratio (1/2, default=2)
  t: 400 # tile-size: tile size (>=32, default=400)
  m: null # model-path: waifu2x model path (default=models-cunet)
  g: 0 # gpu-id: gpu device to use (default=0)
  j: '1:2:2' # thread count for load/proc/save (default=1:2:2) can be 1:2,2,2:2 for multi-gpu
  x: false # enable tta mode
  #f: png # output image format (jpg/png/webp, default=ext/png)

-------------------------
EDIT: that didn't work.

**Comment by k4yt3x** [comment]
For that you'll need to modify this string

![image](https://user-images.githubusercontent.com/21986859/188336484-5af47fd0-d724-4124-8191-db853043ecf1.png)
