### ISSUE TITLE
Command '['D:\\迅雷云盘\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'D:\\迅雷云盘\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '2250', '--scale_height', '4002', '--input_path', 'C:\\Users\\daizf\\AppData\\Local\\Temp\\video2x\\tmpn9bb2by2\\0', '--output_path', 'C:\\Users\\daizf\\AppData\\Local\\Temp\\video2x\\tmpaxjimhk_']' returned non-zero exit status 3221226505.

### ISSUE THREAD

**Issue by whomustnotbename** [k4yt3x/video2x#683]
The error log is as follows

[32m[+] INFO: 正在将文件添加到处理队列中[0m
[90m2022-07-27 20:09:02.970594 [+] INFO: 输入路径：C:\Users\daizf\Desktop\微信图片_20220702134139.jpg[0m
[90m2022-07-27 20:09:02.971593 [+] INFO: 文件 MIME 类型：image/jpeg[0m
[32m[+] INFO: 文件已添加到处理队列[0m
[90m2022-07-27 20:09:02.980959 [+] INFO: 输入文件：C:\Users\daizf\Desktop\微信图片_20220702134139.jpg[0m
[32m[+] INFO: 正在读取视频信息[0m
[90m2022-07-27 20:09:02.981961 [+] INFO: Executing: D:\迅雷云盘\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\daizf\Desktop\微信图片_20220702134139.jpg[0m
[90m2022-07-27 20:09:04.843247 [+] INFO: 创建缓存目录 C:\Users\daizf\AppData\Local\Temp\video2x[0m
[90m2022-07-27 20:09:04.846239 [+] INFO: 提取的帧将被保存到：C:\Users\daizf\AppData\Local\Temp\video2x\tmpn9bb2by2[0m
[90m2022-07-27 20:09:04.848323 [+] INFO: 已放大的帧将被保存到：C:\Users\daizf\AppData\Local\Temp\video2x\tmpaxjimhk_[0m
[32m[+] INFO: 开始放大图像[0m
[32m[+] INFO: 正在计算缩放参数[0m
[90m2022-07-27 20:09:04.850714 [+] INFO: 帧率：1[0m
[90m2022-07-27 20:09:04.850714 [+] INFO: 宽：750[0m
[90m2022-07-27 20:09:04.850714 [+] INFO: 高：1334[0m
[90m2022-07-27 20:09:04.851709 [+] INFO: 总帧数：1[0m
[90m2022-07-27 20:09:04.851709 [+] INFO: 输出宽度：2250[0m
[90m2022-07-27 20:09:04.851709 [+] INFO: 输出高度：4002[0m
[90m2022-07-27 20:09:04.851709 [+] INFO: 需要的缩放比例：3.0[0m
[90m2022-07-27 20:09:04.851709 [+] INFO: 放大工作队列：[3.0][0m
[90m2022-07-27 20:09:04.851709 [+] INFO: Executing: D:\迅雷云盘\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -pix_fmts[0m
[90m2022-07-27 20:09:04.921210 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0, 'y210be': 20, 'y210le': 20}[0m
[32m[+] INFO: 开始对提取的帧进行放大[0m
[90m2022-07-27 20:09:04.927905 [+] INFO: [upscaler] Subprocess 15332 executing: D:\迅雷云盘\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 24 --output_quality -1 --process gpu --model_dir D:\迅雷云盘\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\waifu2x-caffe\models\cunet --noise_level 3 --mode noise_scale --output_extention png --scale_width 2250 --scale_height 4002 --input_path C:\Users\daizf\AppData\Local\Temp\video2x\tmpn9bb2by2\0 --output_path C:\Users\daizf\AppData\Local\Temp\video2x\tmpaxjimhk_[0m
[90m2022-07-27 20:09:06.201222 [+] INFO: 启动进度监视器[0m
[90m2022-07-27 20:09:06.202209 [+] INFO: 启动已放大图像清理程序[0m
[90m2022-07-27 20:09:06.219474 [+] INFO: 主进程开始等待子进程结束[0m

正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:00<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:01<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:02<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:03<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:04<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:05<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:06<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:07<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:08<?, ?it/s]Could not create log file: File exists
COULD NOT CREATE LOGFILE '20220727-200915.23352'!
F0727 20:09:15.001786 21560 cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***

正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:09<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:10<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:11<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:12<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:13<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:14<?, ?it/s]
正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:15<?, ?it/s][31m[1m[!] ERROR: 子进程 23352 结束，返回码 3221226505[0m
[31m[1m[!] ERROR: 子进程执行遇到错误[0m
[33m[1m[!] WARNING: 正在终止所有进程[0m
[90m2022-07-27 20:09:22.395866 [+] INFO: 终结进度监视器[0m

正在处理：微信图片_20220702134139.jpg（进度）:   0%|                                             | 0/1 [00:16<?, ?it/s]
[90m2022-07-27 20:09:22.399839 [+] INFO: 终结已放大图像清理程序[0m
清理缓存目录：C:\Users\daizf\AppData\Local\Temp\video2x\tmpn9bb2by2
清理缓存目录：C:\Users\daizf\AppData\Local\Temp\video2x\tmpaxjimhk_
清理缓存目录：C:\Users\daizf\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 849, in run
  File "upscaler.py", line 416, in _upscale_frames
  File "upscaler.py", line 408, in _upscale_frames
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['D:\\迅雷云盘\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'D:\\迅雷云盘\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '2250', '--scale_height', '4002', '--input_path', 'C:\\Users\\daizf\\AppData\\Local\\Temp\\video2x\\tmpn9bb2by2\\0', '--output_path', 'C:\\Users\\daizf\\AppData\\Local\\Temp\\video2x\\tmpaxjimhk_']' returned non-zero exit status 3221226505.

**Comment by k4yt3x** [comment]
> Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0) CUDNN_STATUS_NOT_INITIALIZED

Looks like you don't have an NVIDIA GPU installed? If you do, try updating your drivers.
