### ISSUE TITLE
Unable to parse option value "0x0" as image size

### ISSUE THREAD

**Issue by metzo007** [k4yt3x/video2x#69]
I am sure this is my mistake, but using the simple line

video2x.py -m gpu -r 2 -i D:\1.VOB -o D:\2.mp4

I get the following error message

![image](https://user-images.githubusercontent.com/49093328/55275029-247f8680-52e0-11e9-900d-d922051e2d75.png)

**Comment by K4YT3X** [comment]
Try running ffprobe manually and see what information you can get from the input video.

```shell
ffprobe.exe -v quiet -print_format json -show_format -show_streams -i VIDEO
```

**Comment by metzo007** [comment]
will do. I found out that the problem was that I used a VOB file as input. Once I changed it to mp4 the error was gone. So the error should be rare and easy to avoid.

**Comment by K4YT3X** [comment]
I want to make the script compatible with all formats though. FFMPEG should be able to handle VOB, so I wonder what's wrong.

**Comment by plneappl** [comment]
I got the same error with a `.mpg`:
```
ffprobe version N-90610-g2accdd3871 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 13.100 / 56. 13.100
  libavcodec     58. 17.100 / 58. 17.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 14.100 /  7. 14.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, mpeg, from 'video.mpg':
  Duration: 00:07:19.11, start: 0.340078, bitrate: 1395 kb/s
    Stream #0:0[0x1e0]: Video: mpeg1video, yuv420p(tv), 352x240 [SAR 200:219 DAR 880:657], 1150 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 29.97 tbc
    Stream #0:1[0x1c0]: Audio: mp2, 44100 Hz, stereo, s16p, 224 kb/s
```

**Comment by k4yt3x** [comment]
The output you provided doesn't give much information.
Could you please provide more context?

**Comment by plneappl** [comment]
> 
> 
> The output you provided doesn't give much information.
> Could you please provide more context?

Whoops, sure, updated last comment.

**Comment by k4yt3x** [comment]
Thanks.
Hmmmm basically ffmpeg cannot read video stream width&height.
There doesn't seem to by anything wrong with the ffprobe command, so is it just the problem of the video?

**Comment by plneappl** [comment]
`ffprobe` reports a `coded_width`/`coded_height` of 0, what's the difference between `coded_width` and `width`?

**Comment by k4yt3x** [comment]
ahhhh lemme take a look at the difference between the two

**Comment by k4yt3x** [comment]
should be fixed in https://github.com/k4yt3x/video2x/commit/405c4b66363c534eda8c08f4820080497c7bb1d3
