### ISSUE TITLE
docker: cannot find input file /home/user/th.webp

### ISSUE THREAD

**Issue by arch-user-france1** [k4yt3x/video2x#694]
I ran this command:
`docker run --gpus all -it --rm -v $PWD:/host ghcr.io/k4yt3x/video2x -i /home/france1/Downloads/th.webp -o th.png -p3 upscale -h 4000 -a waifu2x -n3`

But it doesn't work for whatever reason. I am sure the file exists because I was able to use bash autocompletion.

**Comment by k4yt3x** [comment]
You might have specified the wrong path. `-v $PWD:/host` mounts the current directory into `/host` in the container. Assuming `th.webp` is under your working directory, the input path will be `/host/th.webp`.
