### ISSUE TITLE
I wanted to upscale a gif with Waifu2X NCNN Vulkan and 2 Processes, but it put out this error

### ISSUE THREAD

**Issue by Aaron987BTW** [k4yt3x/video2x#696]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/9446202/video2x_error.log)
Command '['C:\\Users\\Ben\\OneDrive\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\gifski\\win\\gifski', '-o', 'C:\\Users\\Ben\\OneDrive\\Downloads\\tbate_output.gif', '--fps', '10', '--width', '120', '--height', '90', '--quality', '100', 'C:\\Users\\Ben\\AppData\\Local\\Temp\\video2x\\tmpf54zhaqp\\extracted_*.png']' returned non-zero exit status 1.

**Comment by k4yt3x** [comment]
This is the part of the log that shows where the problem is.

```console
error: Video support is permanently disabled in this executable.

To enable video decoding you need to recompile gifski from source with:
cargo build --release --features=video

Alternatively, use ffmpeg command to export PNG frames, and then specify
the PNG files as input for this executable.
```

I'm actually not quite sure just yet why this is happening because Gifski shouldn't need video support to process PNG images.

**Comment by k4yt3x** [comment]
A temporary alternative is to set the output to a video (e.g., mp4 or mkv).

**Comment by Aaron987BTW** [comment]
Thank you for your help. The temporary solution worked. Another solution I found, was to reinstall video2x and restart my pc.
