### ISSUE TITLE
ERROR: FFmpeg or FFprobe cannot be found under the specified path.😕

### ISSUE THREAD

**Issue by ZeroCool22** [k4yt3x/video2x#697]
![Error video2x](https://user-images.githubusercontent.com/13344308/187325517-fed8faee-26a4-4c2a-9a12-170a83bfa7ca.jpg)

But, it's in the correct path or not?

**Comment by k4yt3x** [comment]
It's the correct path. You just don't have FFprobe in there.
Closed since already solved in the Telegram group.

**Comment by MagdyKishk** [comment]
sorry are you talking to me ??
