### ISSUE TITLE
Small error in the Step By Step Tutorial

### ISSUE THREAD

**Issue by metzo007** [K4YT3X/video2x#70]
This was putting me off a bit. The Tutorial says:

"Determine how big you want the output video to be. For example, if you want the video to be 2 times bigger than the original, append -r 2 to the end of the command." 

while the command -r 2 will make the video only 1 time bigger, right?

**Comment by Smarthard** [comment]
@metzo007 `-r` option multiplies original width and height by specified value.

**Comment by metzo007** [comment]
@Smarthard I know, but -r 2 will not make the video 2 times bigger. ;-) I would simply say "If you want to double the size of the video..."

**Comment by Smarthard** [comment]
@metzo007 oh okay I got it

**Comment by K4YT3X** [comment]
> while the command -r 2 will make the video only 1 time bigger, right?

Emmm technically, you're right. I'll change the wording a bit.
