### ISSUE TITLE
input output path type mismatch

### ISSUE THREAD

**Issue by jalalmansour** [k4yt3x/video2x#700]
it simply doens't work

**Comment by k4yt3x** [comment]
Follow what it says. If you set your input to a directory, then the output must also be a directory. Vice versa, input image, output image.

**Comment by jalalmansour** [comment]
I think only realisr when i put x8 with 512x512 doesn't work but for other
dependencies it work great

K4YT3X ***@***.***> schrieb am So., 4. Sept. 2022, 11:33 PM:

**Comment by k4yt3x** [comment]
The reason why RealSR doesn't work might because your GPU doesn't have enough VRAM.
