### ISSUE TITLE
ERROR: Could not build wheels for rife-ncnn-vulkan-python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Curry30h** [k4yt3x/video2x#701]

**Comment by k4yt3x** [comment]
Not enough information.

**Comment by Curry30h** [comment]
> Not enough information.

I already pip installed pyproject.toml,what information should I need?

**Comment by k4yt3x** [comment]
I'll need to know exactly what you've done, your environmental information, and the full error logs.

What command did you use to install which version of v2x on what system?

**Comment by k4yt3x** [comment]
You're still not proving nearly enough information for me to be able to help you.

**Comment by Curry30h** [comment]
> 

There is a lib called realcugan_ncnn_vulkan_python,I want to konw how to intsall it into my conda env,I can't built it with command line "pip install realcugan_ncnn_vulkan_python",I use ubuntu OS.
