### ISSUE TITLE
Traceback (most recent call last):   File "setup.py", line 90, in <module>     if sys.argv[1] == "bdist_wheel": IndexError: list index out of range

### ISSUE THREAD

**Issue by Curry30h** [k4yt3x/video2x#702]
when i build with setup.py,it happens.

**Comment by k4yt3x** [comment]
Insufficient information. The error message itself is not enough, please provide more logs and supplemental information like the version you're building and your environment. Also, this doesn't seem like a part of video2x, it looks like it's some other component that has failed.

**Comment by Curry30h** [comment]
>
yeah,it's a wheel called rife-ncnn-vulkan-python,which used in the code,I use python setup.py to setup but this error occured.

**Comment by k4yt3x** [comment]
Do not open duplicate issues.
