### ISSUE TITLE
Black outputs or endless CPU spinning when using `RealSR NCNN Vulkan`

### ISSUE THREAD

**Issue by Zylann** [k4yt3x/video2x#704]
I gave the software a try with with a small image (512x512 Lena photo) by using the build available here https://github.com/k4yt3x/video2x/releases/tag/4.8.1
The default driver `Waifu2X NCNN Vulkan` works, but everytime I try `RealSR NCNN Vulkan`, it either gives a black output image, or remains stuck at progress `1/1` yet not outputting anything, and one CPU core continuously spinning. Waited for 5 minutes but it looks stuck rather than doing anything.

My graphics card is nVidia GeForce GTX 1060 and CPU AMD Ryzen 5 2600.

**Comment by k4yt3x** [comment]
RealSR requires a lot of VRAM. I'm not sure exactly how much, but a lot. It's outputting black frames mostly likely because your GTX 1060 doesn't have enough VRAM. (usually speaking it should just exit with error but I'm not sure why realsr would just keep running)

**Comment by k4yt3x** [comment]
I see three solutions:

1. Get a better card
2. Use GPU on a cloud service like Colab
3. If you're fine fiddling with Linux stuff try 5.0.0 beta
