### ISSUE TITLE
On Waifu2x NCNN Vulkan, it does not go anywhere past "[+] INFO: Main process waiting for subprocesses to exit"

### ISSUE THREAD

**Issue by Doctorloo56** [k4yt3x/video2x#705]
![2022-09-06 (1)](https://user-images.githubusercontent.com/61024030/188674043-3fe730ae-1614-4574-bbfe-bbb1594520b5.png)
![2022-09-06](https://user-images.githubusercontent.com/61024030/188674046-d392e63e-f2d2-4fa9-8c27-d7dbe897fb92.png)
Two screenshots if they help. Video file was obtained by ripping my copy of "The Batman (2022)" through VLC. 
The exact same thing happens on 2x scale, and after relaunching the application.
In the event that this has a really easy fix, keep in mind I am new to this.

**Comment by monxas** [comment]
I'm also experiencing exactly this issue

**Comment by k4yt3x** [comment]
It will take time for FFmpeg to decode all frames from the video. At least that is how it works in version 4.8.1. If you're processing an entire movie, it's going to take a long time. It's going to take even longer to upscale the the video. Maybe start with something short just to get an idea.
