### ISSUE TITLE
GUI Crash when loading large source file

### ISSUE THREAD

**Issue by K-Haigh** [k4yt3x/video2x#706]
Video2X stable release fro Windows 4.8.1 appears to crash when attempting to input a large source file, either by drag 'n' drop, or using the _Select File_ button.
All I can say at this point is, I can import a 2,144,689,376 byte file (1.99GiB), but not a 2,182,650,184 byte file (2.03GiB).

Educated guess: somewhere in the file reading code, there's a ~2GB limit and an unhandled exception.

Edit: Had a brainwave. Under above circumstances, a split-second before the whole program crashes, line "_Unhandled Python Exception_" is printed to the CLI window.

**Comment by k4yt3x** [comment]
If you can first start a terminal (by running `cmd` or starting a Windows Terminal) then start `video2x_gui.exe` in that terminal, the error messages will remain in the terminal since that window won't get closed. Then you can actually see what went wrong.

**Comment by K-Haigh** [comment]
Not much to go on I'm afraid.
![image](https://user-images.githubusercontent.com/103034655/189546774-3f0194b0-10c0-4fcc-a5fe-cf745e3ba01d.png)

As a CS student, I'll probably end up digging around in the source anyway, at some point. Will post any findings.

**Comment by k4yt3x** [comment]
> Will post any findings.

Appreciated. I just realized something. When talking about a "source file," do you mean an image or a video file? If it's a single image, it might have hit the `PIL.Image.MAX_IMAGE_PIXELS` limit, which would cause a "possible DDoS attack" error.

**Comment by k4yt3x** [comment]
If this is the case, it's been fixed in 5.0.0, but I can't disable in the released 4.8.1 version because I no longer have the dev environment and the means to re-pack the release binary.
