### ISSUE TITLE
get this error while rendering

### ISSUE THREAD

**Issue by Tman7511** [k4yt3x/video2x#709]
Command '['D:\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'D:\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\ASUS\\AppData\\Local\\Temp\\video2x\\tmpdbzfmesk', '-o', 'C:\\Users\\ASUS\\AppData\\Local\\Temp\\video2x\\tmppszsmm5l']' returned non-zero exit status 4294967295.

**Comment by k4yt3x** [comment]
You'll need to supply the error log.
