### ISSUE TITLE
GUI version flagged as a virus and force restarts my PC?

### ISSUE THREAD

**Issue by Adzeiros** [k4yt3x/video2x#717]
I tried to install the GUI version of video2x but my anti-virus flagged it as a super malicious virus (trojan to be specific) and forced me to restart my PC in order to disinfect it... According to my Anti Virus, the installer changed a bunch of my system settings such as "auto load/start USB", "Auto start/load CD/DVD", and more...

**Comment by k4yt3x** [comment]
Where did you download it? I noticed a malicious change to our Wiki roughly 14 hours ago. I've just locked the Wiki editing permissions and reported the malicious user to GitHub. See updates on this page: https://github.com/k4yt3x/video2x/wiki

I might have under estimated the risk of opening access to the Wiki page. If you did download from this page, please let me know. If you did download from one of these two links, I'd recommend you to fully scan your system and reinstall it if possible.

**Comment by Adzeiros** [comment]
I downloaded it from the GUI's page. Where it stated "Download the latest GUI release from [here]." I clicked here and it downloaded the zip with an exe in it... I didn't even get to run the exe before my antivirus deleted it and restarted to disinfect. So I hope I have no need to re-install as I do not wish to lose my data. I performed 2 scans, 1 quick scan of critical system files and then a full scan. None of which found any viruses... So hopefully my not running the EXE (as I did find it a bit sketchy) prevented me from getting infected...

I waited a while before trying to download again, but this time I went to the releases page and found the latest version and downloaded it there which had a zipped file with the proper files and my AV didn't flag it.

**Comment by k4yt3x** [comment]
Fortunately the AV seems to have done its job. If you didn't execute that exe file you should be fine. The Wiki used to be open to edits so people can update information such as the performance benchmarks, but I guess that's history now. All contents in this repo will only be editable by contributors from now on. Sorry for the trouble.
