### ISSUE TITLE
Command '['C:\\Users\\4242u\\OneDrive\\Desktop\\Other apps\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\4242u\\OneDrive\\Desktop\\Other apps\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\4242u\\AppData\\Local\\Temp\\video2x\\tmphgae5pqo', '-o', 'C:\\Users\\4242u\\AppData\\Local\\Temp\\video2x\\tmpli15ujiq']' returned non-zero exit status 4294967295.

### ISSUE THREAD

**Issue by PwutLord** [k4yt3x/video2x#718]
I'm trying to use the Video2X upscaling Ai tool however a few of the modes don't seem to work Specifically the RealSR NCNN Vulkan, and the Waifu2X NCNN Vulkan

Is there anyone who knows the reason for this error?

![Video2X error](https://user-images.githubusercontent.com/113719249/190708350-1be69b0e-1849-4d42-bbb9-ba198362ab6d.png)

**Comment by k4yt3x** [comment]
Please save and upload the error log.

**Comment by PwutLord** [comment]
Here is the error log:

[video2x_error.log](https://github.com/k4yt3x/video2x/files/9590867/video2x_error.log)

**Comment by k4yt3x** [comment]
> no vulkan device
> invalid gpu device

You'll need to ensure that your GPU supports Vulkan.

**Comment by PwutLord** [comment]
Okay thank you
