### ISSUE TITLE
Running the executable rises runtime errors

### ISSUE THREAD

**Issue by dvdvideo1234** [k4yt3x/video2x#719]
![image](https://user-images.githubusercontent.com/9112662/190926460-be726027-97e2-427b-883e-a2a3a4bfc02a.png)

**Comment by dvdvideo1234** [comment]
https://www.sts-tutorial.com/download/api-ms-win-core-path-l1-1-0

**Comment by dvdvideo1234** [comment]
Second error:
```
D:\video2x-4.8.1-win32-full>video2x.exe
Error loading Python DLL 'K:\TEMP\_MEI95242\python39.dll'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.
D:\video2x-4.8.1-win32-full>
```

**Comment by dvdvideo1234** [comment]
There is nothing related to `K:\TEMP\_MEI95242\python39.dll` in my registry.

**Comment by k4yt3x** [comment]
It appears you're using Windows 7, Vista or older. Since they're officially EOL, this project will not support these platforms.

**Comment by dvdvideo1234** [comment]
Is there an older version that runs on 7 ?

**Comment by dvdvideo1234** [comment]
Version 4.5.0 runs just fine with python 3.7.14
