### ISSUE TITLE
Set video bit rate in FFmpeg images back to video

### ISSUE THREAD

**Issue by dtgraham9** [k4yt3x/video2x#72]
Instead of just relying on ffmpeg's -crf flag for quality, I would like to set the bit rate to the value I want.

**Comment by k4yt3x** [comment]
Do you know how to do that by any chance? If you have a recommended method, I won't bother looking up solutions anymore.

**Comment by k4yt3x** [comment]
Should I just add `-b:v` and `-b:a` options?

**Comment by dtgraham9** [comment]
Just add flag -b:v.  I know the format is along this -b 800K for 800kB.  M can be used instead of k for mB could be specified.  I remux the original audio tracks anyway.  A second potential change is make it so the -crf flag flag can be changed by user.  -crf flag I believe goes the higher the value the lower the quality.  I am just pointing this out because I don't personally like how my raw 480p video at 1.1GB is larger than the 1080p version at 310MB.  I rather have a large uncompressed file and recompress it myself with tools like handbrake.

**Comment by k4yt3x** [comment]
You can simply add a new key into the config, but I will update the template config as well.
