### ISSUE TITLE
[NULL @ 000001d568c48480] Unable to find a suitable output format

### ISSUE THREAD

**Issue by AltWhite** [k4yt3x/video2x#73]
## Environment Information

Latest Version as of March 28, 2019:

|Module|Version|
|-|-|
|`video2x`| 2.7.0|
|`ffmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||

## Symptom
Output format [NULL @ 000001d568c48480] - [!] ERROR: An exception has occurred
The program successfully completes the conversion and migrates audio and subtitles (https://imgur.com/a/bZwGkw4 , https://imgur.com/a/IfwpFB6), but during ffmpeg it seems to have an issue with the output format? I specified a local folder and it accepted the MKV, so I'm unsure why it's having problems after all that. 

Initial setup Code:

```shell
python video2x.py -m gpu -r 2 -d waifu2x_converter -i C:\Users\Master\Documents\BDmade\AttackOnTitan\S1_Ep1-7\Small_Encode\S1_D1_1-7_Ex -o C:\Users\Master\Documents\BDmade\AttackOnTitan\S1_Ep1-7\Small_Encode\test
```

Image of Error Code:
https://imgur.com/a/XWZIH14
![error screenshot](https://i.imgur.com/0X4bA9G.png)

```
[NULL @ 000001d568c48480] Unable to find a suitable output format for 'C:\Users\Master\Documents\BDmade\AttackOnTitan\S1_Ep1-7\Small_Encode\test'
C:\Users\Master\Documents\BDmade\AttackOnTitan\S1_Ep1-7\Small_Encode\test: Invalid argument
[!] ERROR: An exception has occurred
```
NOTES: After some sourcing for information, I think I figured it out - am I supposed to not only copy the destination as output, but also include Title.MKV ? I figured it would just reassign the original name and format as default? Have not tested yet, will try with smaller size.

**Comment by k4yt3x** [comment]
Hello there, I looked at your screenshot and you seemed to have configured everything properly.
Video2X should automatically output the video in the same format the input video is using, but I'm not sure why it's not working properly.

Could you please insert these lines in `video2x.py` just to debug the problem?

https://github.com/k4yt3x/video2x/blob/3d46e1a822236db1cb25f970ae1c8bf492334f1d/bin/video2x.py#L314

After line 314, change this:

```python
output_video = '{}\\{}'.format(args.output, input_video)
upscaler = Upscaler(input_video=os.path.join(args.input, input_video), output_video=output_video, method=args.method, waifu2x_settings=waifu2x_settings, ffmpeg_settings=ffmpeg_settings)

```

into this:

```python
output_video = '{}\\{}'.format(args.output, input_video)
 print(output_video)
breakpoint()
upscaler = Upscaler(input_video=os.path.join(args.input, input_video), output_video=output_video, method=args.method, waifu2x_settings=waifu2x_settings, ffmpeg_settings=ffmpeg_settings)
```

It should look something like this:

![image](https://user-images.githubusercontent.com/21986859/55429862-6e73a100-555a-11e9-9b2a-39d17628da55.png)

Then, run the script again using the command you provided above, and the script should stop shortly after execution. Take a screenshot of the output, and post it on here.

**Comment by AltWhite** [comment]
Ah weird, well I ran it https://imgur.com/a/zOvgI5e

**Comment by k4yt3x** [comment]
I think you pasted the lines wrong.
Take a screenshot of the code.

**Comment by AltWhite** [comment]
Hmm https://imgur.com/a/HfXzTw3

**Comment by k4yt3x** [comment]
line 316 and 317 should be indented. compare your code with my screenshot above

**Comment by AltWhite** [comment]
You're correct, lol just saw my bad

**Comment by AltWhite** [comment]
It skipped upscaling part and went to ffmpeg as it should, it then looped back and started to convert frames without stopping (just for future debugging purposes) https://imgur.com/a/bMS7zuf

**Comment by k4yt3x** [comment]
It should not be skipping. It should pause before upscaling.

**Comment by AltWhite** [comment]
Ah okay, well it didn't pause for me so I must have done something wrong: inserted code, compile test, saved, cmd, same command as before. 

Yes, I dragged the file into the command prompt, it created the path (which is correct). https://imgur.com/a/o5BHGcN

**Comment by k4yt3x** [comment]
Ok now I see what's going on.
If the input is the file, then the output should also be a file, not a folder.

Video2x is working as intended.

**Comment by AltWhite** [comment]
This is a bug though, you have to specify the file type. 

For instance, this works:
C:\Users\Master\Documents\waifu2x_video2x\video2x-master\video2x-master\bin>python video2x.py -m gpu -r 4 -d waifu2x_converter -i C:\Users\Master\Desktop\Test4.mkv -o C:\Users\Master\Desktop\G\**Name.mkv**  

So how do I get it to automatically input the original name automatically with the correct file type?

**Comment by k4yt3x** [comment]
If you're handling a single file, you'll have to specify both the input file name and the output file name.
If you're handling files in a folder, then all input file names will be copied, also the video codec.

Maybe I can add a function where if you don't specify the output file, it generates the file name and copies the input file format for you?

**Comment by AltWhite** [comment]
That would be a nice function, but I think just adding in the instructions a note about my updated comment - thank you for the timely responses.

**Comment by k4yt3x** [comment]
I'll consider adding a function to check the path.
You're welcome.

**Comment by k4yt3x** [comment]
I just thought about it, how would I perform the check though?
match "^*.*" ?

**Comment by AltWhite** [comment]
What I was thinking is if --> Input =/= Output (file type) follow path and get directory items as list, parse the end of the path and look for a name match in directory (File.Type), then output that type if found, else output a message to the user at least telling them for this specific situation what's wrong. Not a big deal anymore, but it's a feature haha.

**Comment by k4yt3x** [comment]
> parse the end of the path and look for a name match in directory (File.Type), then output that type if found

Sorry I'm kinda confused. Maybe I didn't sleep enough.
Could you please give an example?

**Comment by AltWhite** [comment]
Haha it is late, I just got two ideas confused there, I don't want to waste more of your time though so don't worry about it if it still doesn't make sense or isn't feasible. Take this path for example:

python video2x.py -m gpu -r 4 -d waifu2x_converter -i C:\Users\Master\Documents\Input.mkv -o C:\Users\Master\StoreVideo\SubFolder   (notice missing .mkv on output)

Take path directory (C:\Users\Master\StoreVideo\SubFolder), Check directory is empty (dir C:\Users\Master\StoreVideo\SubFolder) else look for similar Name.Type so we don't create a conflict, Assume "Output" = folder, Add onto the path InputName.mkv as the output file name.

New adjustments:
python video2x.py -m gpu -r 4 -d waifu2x_converter -i C:\Users\Master\Documents\Input.mkv -o C:\Users\Master\StoreVideo\SubFolder\Output.mkv

**Comment by k4yt3x** [comment]
I'm expecting input type to match output type, so I think what I'm going to do is:

1. input = something.mp4
1. output = folder1

if output is folder:
    warn user file IO mismatch
elif output does not match *.* (missing suffix):
    warn suffix needed

**Comment by AltWhite** [comment]
Ah yeah, that's way more simple than mine. Looks great to me! Thanks.

**Comment by k4yt3x** [comment]
Implemented in the newest commit.
