### ISSUE TITLE
Raises FFPROBE Error in google colab

### ISSUE THREAD

**Issue by SASIN83** [k4yt3x/video2x#731]
14:07:21.598385 | INFO     | Reading input video information

Error                                     Traceback (most recent call last)
[<ipython-input-9-f02213ec12d4>](https://localhost:8080/#) in <module>
     50     processes,
     51     threshold,
---> 52     algorithm,
     53 )

2 frames
[/usr/local/lib/python3.7/dist-packages/ffmpeg/_probe.py](https://localhost:8080/#) in probe(filename, cmd, **kwargs)
     21     out, err = p.communicate()
     22     if p.returncode != 0:
---> 23         raise Error('ffprobe', out, err)
     24     return json.loads(out.decode('utf-8'))
     25 

**Error: ffprobe error (see stderr output for detail)**

**Comment by mikanator10** [comment]
I've got the same type of problem
