### ISSUE TITLE
AttributeError: 'Interpolator' object has no attribute 'process' in Google Colab

### ISSUE THREAD

**Issue by SASIN83** [k4yt3x/video2x#732]
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-13460b72c6bd>](https://localhost:8080/#) in <module>
     35     processes,
     36     threshold,
---> 37     algorithm,
     38 )

1 frames
[/usr/local/lib/python3.7/dist-packages/video2x/video2x.py](https://localhost:8080/#) in _run(self, input_path, width, height, total_frames, frame_rate, output_path, output_width, output_height, mode, processes, processing_settings)
    206             tasks_queue, processed_frames, pause_flag
    207         )
--> 208         processor_pool = Pool(processes, processor.process)
    209 
    210         # create progress bar

AttributeError: 'Interpolator' object has no attribute 'process'

**Comment by CiaranCrowley** [comment]
Also getting this issue

**Comment by restingmeatface** [comment]
Any fixes here yet?

**Comment by Jarvis3310** [comment]
Also getting this issue~~~~ thanks~~~~please~~~

**Comment by plambe** [comment]
If you pin the video2x version to some older one it works in colab. Here's my current code:

```
#!python3.7 -m pip install -Uvf /content/wheels video2x@git+https://github.com/k4yt3x/video2x.git@66f4c17
!python3.7 -m pip install -Uvf /content/wheels video2x@git+https://github.com/k4yt3x/video2x.git@5.0.0-beta4
```

**Comment by plambe** [comment]
I suspect this commit to have introduced this issue: https://github.com/k4yt3x/video2x/commit/9fc0aa787e400ac1c4791a2cc8ed3a4b0effe4ce
