### ISSUE TITLE
FFmpeg encode after upscale taking over 8 hours

### ISSUE THREAD

**Issue by CiaranCrowley** [k4yt3x/video2x#733]
I'm trying to upscale a .mkv video file to 1080p from 480p.  The actual upscaling process took less than 5 minutes, but the FFmpeg task/tasks that come afterwards are a very long time to finish.  This is for a video file which has dual audio tracks and subtitles.  The file is 111.4MB.  

The only changes I made in the most recent windows release of video2x was the number of process (90) to speed up. 

What changes in the GUI can I make to speed up the FFmpeg process? 

I am not hardware bound by this issue. 

CPU: i9-9900k 
Memory:  32GB 2666mhz
GPU:  RTX 2080 Super

This FPS value is dropping extremly slowly.  At above 28 FPS the value was dropping relatively quickly but began slowing below 28 FPS.  What is happening here?
![image](https://user-images.githubusercontent.com/36445870/193590855-685ed568-28bf-430b-be5e-644592c190f1.png)

This was originally written when the fps count was ~2 fps.  At the 8 hour mark the fps count was at 1.16

**Comment by DifferentialityDevelopment** [comment]
Basically I think by default it will encode the video with your CPU.
What you wanna do is under FFmpeg Settings, set your Video Codec to hevc_nvenc, which will utilize your GPU and run much quicker
