### ISSUE TITLE
input output path type mismatch/select file button in output section requires an existing file

### ISSUE THREAD

**Issue by devz3r0** [k4yt3x/video2x#734]
Autocompletion feature is not working?

[+] INFO: Loading files into processing queue
2022-10-03 12:22:32.279079 [+] INFO: Input path(s): E:\video.mp4
2022-10-03 12:22:32.281045 [+] INFO: File MIME type: video/mp4
[!] ERROR: Input and output path type mismatch
[!] ERROR: Input is single file but output is directory

Output is set to: E:\temp\
and File is set to:
 {original_file_name}_output{extension}
Additional to that the "select file" on the output part is not working, because it wants to open an existing file instead of creating one.

I googled with this error message, only found two sassy replies with out any explanations.
The rest is set to default, to test the app.

**Comment by Skoffin77** [comment]
having the same issue here and now it wont do anything after working fine for a week
