### ISSUE TITLE
Multi-gpu?

### ISSUE THREAD

**Issue by akhilleusuggo** [k4yt3x/video2x#741]
Hello, I'm not able to find a guide or a proper answer if this project does support multi-gpu usage.
Can someone please confirm whatever does or does not support it?

Thank you.

**Comment by salmanhasni** [comment]
yes it does. use `--gpus all` args to use all your gpus

**Comment by akhilleusuggo** [comment]
I'm using windows, and using the GUI build.
I don't mind using the CLI, but still not working. Can you provide an example? And the argument should be set?
On the video2x.yaml, also doesn't work.

`video2x: error: unrecognized arguments: --gpu all`
`video2x: error: unrecognized arguments: --gpus all`

**Comment by Engrish** [comment]
Can confirm OP's finding. Using v4.8.1 win 32 command line tool and in the help readme, no where does it say it supports the parameter --gpus all. When I try to define waifu2x_ncnn_vulkan parameter using -- -g 0,1,2,3, it complains that it's expecting an integer. However, waifu2x_ncnn_vulkan should support multi-gpu.

So are you talking about the v5.0 beta that support --gpus all? Or a non Windows binary?
