### ISSUE TITLE
The latest version permanently deleted my files

### ISSUE THREAD

**Issue by herpaderpader** [k4yt3x/video2x#743]
I don't even understand how this is possible.
I started the converting and got a permission error on Windows.
Then I checked the temp folder that I set to the Desktop and it DELETED MOST OF MY SHORTCUTS.
Ok...
Then I set the temp folder to the Pictures folder.
Again permission error and not it permanently deleted an entire folder full with pictures that didn't even have anything to do with Video2x. I mean it wasn't the temp folder or the folder to be converted or anything.
Your software just deleted a folder in the Pictures folder and I lost several pictures of mine.
How is this even possible? This is some serious bug.

I'm sending you the log file but my pictures are gone forever as they are not even in the trashcan.
[video2x_error.log](https://github.com/k4yt3x/video2x/files/9779031/video2x_error.log)

**Comment by herpaderpader** [comment]
Important to add that this happened after the latest Windows 10 update.
Before that I used version 2.4 and the latest version of Video2x without any problem.
Ever since the Windows update I cannot use video2x and it just permanently deletes my files...

**Comment by bonessnap** [comment]
for me everything is the same, the application keeps removing all files from the output (including the result, so it just upscales and instantly removes the results)
