### ISSUE TITLE
No output generated for images

### ISSUE THREAD

**Issue by DCsunset** [k4yt3x/video2x#747]
Hello,

Video2x is said to support video/GIF/image files. However, when I tried to upscale a PNG image, the program exited normally (Processing completed successfully), but no output image file was generated.

I'm using the latest container image (5.0.0-beta6), and the command to upscale is shown as follows:

```sh
docker run --gpus all -it --rm -v $PWD:/host ghcr.io/k4yt3x/video2x -i input.png -o output.png -p3 upscale -h 720 -a waifu2x -n3
```

However, if I use another video file, the output can be generated successfully.
Is it because the newest version no longer supports image files?

(P.S. Thanks for this great project!)

**Comment by jamescochran** [comment]
I'm in the same boat. I'm starting by running the help by passing only the ```-h``` argument
