### ISSUE TITLE
Issue with video output

### ISSUE THREAD

**Issue by DJDiarrhea** [k4yt3x/video2x#75]
The Video I get after upscaling is, according to the details section of the file itself the correct resolution and framerate but 0 seconds long

**Comment by k4yt3x** [comment]
Could you please provide the program outputs?

**Comment by DJDiarrhea** [comment]
Sure here's the cmd logs and a copy of the temp directory
![Uploading error.JPG…](cmd logs)
[Uploading video2x.zip…](temp directory)

**Comment by DJDiarrhea** [comment]
Sure here's the cmd logs and the temp directory
![error](https://user-images.githubusercontent.com/49327254/55674938-85e4be00-58bb-11e9-8a0f-f996fc5c69a4.JPG)
[video2x.zip](https://github.com/k4yt3x/video2x/files/3050915/video2x.zip)

**Comment by k4yt3x** [comment]
Hi, based on the output, I don't see any problems.
Is it possible for you to send the video over so I can do some debugging?

**Comment by DJDiarrhea** [comment]
[sure here you go](https://github.com/k4yt3x/video2x/files/3060740/wankel.zip)
Sorry for forgetting to answer.

**Comment by k4yt3x** [comment]
This video upscales on my end just fine.

Command used:


[wankel_upscaled.zip](https://github.com/k4yt3x/video2x/files/3066431/wankel_upscaled.zip)

**Comment by k4yt3x** [comment]
I think it's just something wrong with your setup.
If you still can't figure it out, keep posting on this thread. I'm closing the issue for now.

**Comment by DJDiarrhea** [comment]
Yeah I guess my installation went wrong somewhere. I'll try around a bit. Thanks for the answers.

**Comment by k4yt3x** [comment]
If it still doesn't work, try using the python version instead of the exe version and see if it fixes anything.

**Comment by DJDiarrhea** [comment]
I'll try that. I'm rather busy at the moment though so that might take a while.
