### ISSUE TITLE
If this is only on Windows, it should be made extremely obvious from a quick look at the readme

### ISSUE THREAD

**Issue by akami-channel** [k4yt3x/video2x#750]
After glancing over the readme, cloning to my local system, trying to run make and failing, looking more carefully at the readme, then looking at the tutorial (which seems outdated? I don't even see the bin directory), then looking over the History part of the wiki, I finally found that it seems to be only for Windows. It doesn't seem to say that anywhere on the readme, thus undoubtedly wasting enormous amounts of people's time.

**Comment by akami-channel** [comment]
Alternatively, if Docker is the only way to run it on macOS and Linux, I think this should be made more clear. Most people are going to skip over the Docker instructions since that is generally less convenient than installing things natively.

**Comment by megapro17** [comment]
Use normal system, not router firmware

**Comment by akami-channel** [comment]
@megapro17 what?

**Comment by hb-webdev** [comment]
it says 'win32' in the release page filename. that means 'windows 32-bit'. also the only executables in the zip are exe's. Only windows can run exe's. you're probably pretty alone in this.
