### ISSUE TITLE
video2x not installing on code lab

### ISSUE THREAD

**Issue by daasdassd** [k4yt3x/video2x#759]
Dear sir.
I get the following error messages on code lab.

Step 1: Install Video2X and Dependencies

 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3.7 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpxtdsrdp8
  cwd: /tmp/pip-install-sxf8wgq0/video2x_1a1a2f14b29f40488ac5ebe00373d851
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Step 3.1 Upscale
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-eb9a53b8aba4> in <module>
      8 
      9 import pathlib
---> 10 from video2x import Video2X
     11 
     12 video2x = Video2X()

ModuleNotFoundError: No module named 'video2x'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

Please I need your help. thank you

**Comment by MichaelFilipan** [comment]
I'm having the same issue as you.

**Comment by Lovkush-A** [comment]
I am having same problem too, with the colab notebook

**Comment by gayanll** [comment]
same thing

**Comment by danfolkes** [comment]
I was able to get around this by removing the  "!python3.7 -m " from these lines: 
!python3.7 -m pip install -U pip wheel pdm-pep517 setuptools setuptools-scm
!python3.7 -m pip install -Uvf /content/wheels video2x@git+https://github.com/k4yt3x/video2x.git@66f4c17
