### ISSUE TITLE
Parameter option to wait for additional VRAM or automatic fallback to system RAM

### ISSUE THREAD

**Issue by databoose** [k4yt3x/video2x#76]
I'd like it if there were two parameters such as the following.

**-vram_fallback**
Utilizes system ram if no more VRAM can currently be allocated with the GPU method, if there is a good, reliable percentage of the VRAM available when some of the data is already within system ram, it queues the next frames to be stored within VRAM, re-checking every 250 milliseconds give or take and changing the queue for the frame to be stored within system ram if it finds out no more VRAM can be allocated anymore and vise versa, if in the rare chance the VRAM is capped during processing of a frame that the queue system miscalculated (vram amount changed before 250ms for example), it tells that specific thread to pause until it can allocate more vram.

**-vram_wait**
The program waits to be allocated more VRAM, continuing the individual threads when it can, and pausing some of them (or all of them, if it is that drastic) when it can't, instead of killing the program and destroying progress.

As for the people thinking "Why don't you just fork and do this yourself?", i have absolutely zero knowledge in python programming, and i think these features should be added to the main project to keep things more unified and for more people to be able to use these features without having to download specific forks for small additions to the program.

**Comment by k4yt3x** [comment]
I'd like to implement it, but video2x doesn't control this part, waifu2x does.
Therefore, if you would like this to be added, you're first in the wrong repository.
Also, I believe memory-related stuff are managed by CUDA, OpenCL and such.

**Comment by k4yt3x** [comment]
This feature will not be implemented as it's not video2x's job to controll vram.
