### ISSUE TITLE
permission error when generating video2x configuration file

### ISSUE THREAD

**Issue by kelsieer** [k4yt3x/video2x#80]
## Environment Information

|Module|Version|
|-|-|
|`video2x`||
|`ffmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||

## Symptom

it installed dependencies but then gave error when when generating configuration file
## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
```
![2223](https://user-images.githubusercontent.com/49539812/56003656-899a8b00-5c95-11e9-9362-306ce7dff3b1.PNG)

**Comment by k4yt3x** [comment]
Did you download/unpack the files and run them as the same user?

**Comment by kelsieer** [comment]
Yes. I downloaded the files stated in the step by step tutorial (python and video 2x). Then i ran the video2x_setup.py as the same user. It downloaded the dependencies but got an error when it got to generating video 2x configuration file.

I am the admin of my computer so I dont know why it gives permission error.

**Comment by k4yt3x** [comment]
Have you tried running it as administrator?

**Comment by kelsieer** [comment]
Isn't it meant to run in the command prompt? How would I run it as administrator in the command prompt?

**Comment by k4yt3x** [comment]
Well run command prompt as admin.

**Comment by kelsieer** [comment]
Thanks for the help! I successfully setup video 2x. But now another problem has happened... :(

When I run it says "an exception has occurred" and stops.
![42](https://user-images.githubusercontent.com/49539812/56074525-6e597980-5d82-11e9-8bf8-60665ba9a6a9.PNG)

**Comment by k4yt3x** [comment]
It looks like that waifu2x-caffe failed. Do you have the CUDA driver installed?

**Comment by kelsieer** [comment]
Okay I installed CUDA from Nvidia website but it removed my Nvidia
graphics card drivers, and now my computer doesn't recognize my graphics
card any more.

**Comment by k4yt3x** [comment]
Oh boy. Sorry but I don't know how to fix that situiation.

**Comment by kelsieer** [comment]
Could you tell me how you installed the CUDA driver? You got it from here
right? : https://developer.nvidia.com/cuda-downloads

Did it not delete your graphics drivers for you?

**Comment by k4yt3x** [comment]
You .. don't need the CUDA toolkit. Just the regular graphics card driver is fine.

**Comment by Urgeistenergie** [comment]
Hi there! I new an very enthusiastic in lossless video upscaling.
This is what I found in a german forum regarding this issue:

"Nvidia has removed the implementation of the CUDA-based encoder (nvcuenc.dll) with version 340.52 from the drivers."
...
"If you cannot see the "H.264 (Nvidia® CUDA™)" option...

Please try the solutions below:
1. Check your graphics card driver
NVIDIA removed the nvcuvenc.dll file from the GeForce 340.43 beta driver.

1) If you use Windows 7/8/10 (64bit), download cuda_enc_windows7_8_64bit.zip and copy&paste the nvcuvenc.dll file to the designated folder. (C:\Windows\System32\nvcuvenc.dll and C:\Windows\SysWOW64\nvcuvenc.dll)

2) If you use Windows 7/8/10 (32bit), download cuda_enc_windows7_8_32bit.zip and copy&paste the nvcuvenc.dll file to the designated folder. (C:\Windows\System32\nvcuvenc.dll)


http://www.bandicam.com/img/forum/cuda_enc_windows7_8_64bit.zip

http://www.bandicam.com/img/forum/cuda_enc_windows7_8_32bit.zip

Works for me for all programs"

Greets

**Comment by k4yt3x** [comment]
@Urgeistenergie Thank you for the suggestions, but ffmpeg and waifu2x are supposed to work with GeForce 419.35+ though. If he installed the newest drivers correctly, there shouldn't be a problem.

**Comment by kelsieer** [comment]
Thank you! It worked. 

I got a questions tho. Does it work with mkv files?

**Comment by k4yt3x** [comment]
@kelsieer should work with all formats that ffmpeg supports (i.e. mkv should work fine.)
