### ISSUE TITLE
Google Collab template: ModuleNotFoundError: No module named 'video2x'

### ISSUE THREAD

**Issue by Charistoph** [k4yt3x/video2x#800]
Hi all, I'm getting a super basic error. When I run the Google Collab notebook template, I get a ModuleNotFoundError: No module named 'video2x' error. I've just run the cells as described (and switched hardware to GPU). Not sure what I could have done wrong since the steps are so simple. Help is much appreciated! (Screenshots attached
<img width="1082" alt="Screen Shot 2022-12-24 at 15 08 59" src="https://user-images.githubusercontent.com/24809775/209439497-436d99b6-a4bd-4d44-9786-b4cf4b8bd265.png">
<img width="1087" alt="Screen Shot 2022-12-24 at 15 09 09" src="https://user-images.githubusercontent.com/24809775/209439499-17dd322e-3313-4583-99ef-9f3a93be9fcd.png">
<img width="1097" alt="Screen Shot 2022-12-24 at 15 09 19" src="https://user-images.githubusercontent.com/24809775/209439501-b696efdd-2143-45e2-a9de-9c94bfe5f841.png">
<img width="1103" alt="Screen Shot 2022-12-24 at 15 09 25" src="https://user-images.githubusercontent.com/24809775/209439503-5abf3401-56b1-4620-8ab4-deb71ce63de4.png">
<img width="1088" alt="Screen Shot 2022-12-24 at 15 09 31" src="https://user-images.githubusercontent.com/24809775/209439504-6ab33597-cf59-4554-a717-2b7d4d1aec84.png">
)

**Comment by ruben2s** [comment]
Same here

**Comment by dpagano** [comment]
I believe the problem is that the dependencies are not installed correctly. In my case I realized that the install code (last 2 lines) references Python 3.7, but actually Python 3.8 is installed.

**Comment by GrahamboJangles** [comment]
@dpagano How can we fix that?

**Comment by GrahamboJangles** [comment]
At the beginning of the notebook, add a code block with this and run it:

```
# This installs python3.7 which is what the notebook was created for
!apt-get install python3.7
# This will create a symbolic link from /usr/local/bin/python to /usr/bin/python3.9, which will make Python 3.9 the default version of Python when you run code cells.
!ln -sf /usr/bin/python3.7 /usr/local/bin/python
```

However, when running the Step 1 installing dependencies, I get this error:
```
Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=c8f3dfce796dcf806a0fa859e91d4284437d9fcbb2320c0d8a56391fb2a3a9bf
  Stored in directory: /root/.cache/pip/wheels/3e/3c/b4/7132d27620dd551cf00823f798a7190e7320ae7ffb71d1e989
Successfully built video2x rife-ncnn-vulkan-python future
Failed to build evdev
Installing collected packages: evdev, commonmark, six, pygments, pillow, numpy, loguru, future, waifu2x-ncnn-vulkan-python, srmd-ncnn-vulkan-python, rife-ncnn-vulkan-python, rich, realsr-ncnn-vulkan-python, realcugan-ncnn-vulkan-python, python-xlib, opencv-python, ffmpeg-python, pynput, video2x
  Running command Running setup.py install for evdev
  running install
  /usr/local/lib/python3.7/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    setuptools.SetuptoolsDeprecationWarning,
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-37
  creating build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/genecodes.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/eventio_async.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/ecodes.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/evtest.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/util.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/uinput.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/eventio.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/__init__.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/device.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/ff.py -> build/lib.linux-x86_64-cpython-37/evdev
  copying evdev/events.py -> build/lib.linux-x86_64-cpython-37/evdev
  running build_ext
  ecodes.c already exists ... skipping build_ecodes
  building 'evdev._input' extension
  creating build/temp.linux-x86_64-cpython-37
  creating build/temp.linux-x86_64-cpython-37/evdev
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.7m -c evdev/input.c -o build/temp.linux-x86_64-cpython-37/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
  evdev/input.c:10:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Running setup.py install for evdev did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3.7 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-oq0dfpgv/evdev_9451abd840ab46aeabc37878b82a323e/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-2ecpo8qk/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/evdev
  cwd: /tmp/pip-install-oq0dfpgv/evdev_9451abd840ab46aeabc37878b82a323e/
  Running setup.py install for evdev ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> evdev

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by dheeraj-rn** [comment]
For installing Python 3.7 this worked for me
```
!apt-get update
!apt install software-properties-common
!add-apt-repository ppa:deadsnakes/ppa -y
!apt-get update
!apt-get install -y --no-install-recommends \
    python3.7 python3-pip libvulkan-dev glslang-dev glslang-tools \
    build-essential swig ffmpeg ninja-build
```

**Comment by dheeraj-rn** [comment]
This worked
```
!apt-get update
!apt install software-properties-common build-essential libssl-dev -y
!add-apt-repository ppa:deadsnakes/ppa -y
!apt-get install -y --no-install-recommends \
    python3.7-dev python3-pip libvulkan-dev glslang-dev glslang-tools \
    build-essential swig ffmpeg ninja-build
```

**Comment by haker88** [comment]
Where did you add it ?

**Comment by dheeraj-rn** [comment]
@haker88 First do Disconnect and delete runtime:  `Runtime > Disconnect and delete runtime`
Then go to `Step 1: Install Video2X and Dependencies` and click on `Show code`
Replace this
```
!apt-get update
!apt-get install -y --no-install-recommends \
    python3-pip libvulkan-dev glslang-dev glslang-tools \
    build-essential swig ffmpeg ninja-build
```
With this
```
!apt-get update
!apt install software-properties-common build-essential libssl-dev -y
!add-apt-repository ppa:deadsnakes/ppa -y
!apt-get install -y --no-install-recommends \
    python3.7-dev python3-pip libvulkan-dev glslang-dev glslang-tools \
    build-essential swig ffmpeg ninja-build
```

**Comment by haker88** [comment]
> 
Still no luck - done all the steps and error is the same:

ModuleNotFoundError: No module named 'video2x'

**Comment by dheeraj-rn** [comment]
> > 
> 
> Still no luck - done all the steps and error is the same:
> 
> ModuleNotFoundError: No module named 'video2x'

Yes i got the same. Only the Step 1 worked without any errors

**Comment by haker88** [comment]
I think I had this one working last night - at least it shown complete.

**Comment by andystumpf** [comment]
@haker88 Thanks! Just need to uncomment out the google drive mount for the NOOBs and works great.

**Comment by iqubik** [comment]
ModuleNotFoundError: No module named 'video2x'
google collab error from base github notepad

**Comment by vinc-vo** [comment]
I had this problem with the current colab notebook. What solved it for me is to change current directory to the path video2x python module is in.
You can find it running 
`pip show video2x`

I did `cd /usr/local/lib/python3.8/dist-packages` just before running the upscale block.

There probably is a better option, but no idea how.
Hope this helps 😄

**Comment by tomasatisocco** [comment]
@simonmicro mehtod worked for me!

**Comment by k4yt3x** [comment]
The official one should be good now. I'm back on active maintenance.

**Comment by isaacchan15947** [comment]
> The official one should be good now. I'm back on active maintenance.

![image](https://github.com/user-attachments/assets/ce9e62c6-4fdb-4fdf-8c8a-20711f2f4733)
I got this error when I ran [Step 5.1: Upscale]. Could you retake a look at the code? Thanks for your script on Colab anyway

**Comment by isaacchan15947** [comment]
> The template has been edited yet I run into the same error. None of the algorithms installation seems to work.
> <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/54849528/369367328-b3420a28-3a09-4da1-8096-becffd3edbe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyNjIsIm5iZiI6MTcyNjgyODk2MiwicGF0aCI6Ii81NDg0OTUyOC8zNjkzNjczMjgtYjM0MjBhMjgtM2EwOS00ZGExLTgwOTYtYmVjZmZkM2VkYmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEwNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Njk0Nzc3YTA3MjQ1NmYzMWYxOWRlMzE4NDgxNmU0NDNhODM3MDM1YmQzOTQ1NzBkNDE5NGI3YjkyZjExMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jXQhBSWv8YEdRyBQ1hehX3p97-e-tLZP5MVWq1EyeLY">

I used my mother tongue to ask them. They are working on this bug I believe.
https://github.com/2noise/ChatTTS/issues/736#issuecomment-2322831232
