### ISSUE TITLE
"main process waiting for subprocesses to end"

### ISSUE THREAD

**Issue by ConsOfficial** [k4yt3x/video2x#802]
So, I believe I am using the program right.  I put in the file into the input, and click start. But for some reason, the program gets stuck on that error above. It's been almost 20 minutes and nothing has happened. I am using an NVIDIA GPU and have installed the most recent drivers. I try closing all other apps but nothing else happens. Is there anyway to get this to be fixed. Also, I tried using the Vulkan driver instead and that didn't work either.

**Comment by tranzmatt** [comment]
I'm having a similar issue.  It worked once, but I don't know why.

**Comment by philpw99** [comment]
What's happening is ffmpeg is extracting all frames and save them as png files into the temp folder. If you check the temp folder, there are thousands of pngs inside and the folder size will blow up.
