### ISSUE TITLE
win64

### ISSUE THREAD

**Issue by keskas** [k4yt3x/video2x#81]
Good day. I would like to know how to run video2x on win64?
![1](https://user-images.githubusercontent.com/20801283/56078417-7cde7a00-5df0-11e9-8be7-a99fa68a99b2.jpg)

**Comment by k4yt3x** [comment]
The architecture doesn't matter. Runs the same on any platform with proper GPU drivers.

**Comment by keskas** [comment]
At startup, 1 screenshot is opened and then the program closes immediately. 
How to fix it?

**Comment by k4yt3x** [comment]
You're not supposed to double click on the exe. Run it from the command line.

**Comment by keskas** [comment]
This was the launch via the command line.

**Comment by k4yt3x** [comment]
Then did you tell it what to do? I don't see any arguments or switches specified.
