### ISSUE TITLE
ffmpeg deinterlace

### ISSUE THREAD

**Issue by godmd5** [k4yt3x/video2x#817]
can you add ffmpeg deinterlace to vob ,mpeg 2 file ,like bwdif yadif

https://github.com/kfrn/ffmpeg-things/blob/master/deinterlacing.md

**Comment by acommonsherpa** [comment]
Hi, you can edit your video2x.yaml. On line 131 under the ffmpeg, extract_frames, output_options add a line that says 
      '-vf': 'yadif'
![image](https://github.com/k4yt3x/video2x/assets/13862962/5856de65-d41c-4699-b85b-2b7dd75df7ee)
