### ISSUE TITLE
Not great for low-end

### ISSUE THREAD

**Issue by Danika207** [k4yt3x/video2x#82]
I got it to "work", i've succesfully downloaded it with python, cmd.
But when the upscaling process was startin, It just crashed and said that i should lower the thread count or something, and before i even started the process it said that my gpu's vram is insufficent or something.
I tought 2gb of Vram is enough, but i guess not. I was trying all day-night (with other programs too), but nothing worked. I am not mad, i am just sad that none of the methods works.

**Comment by cr08** [comment]
So with waifu2x-caffe I believe the new default model is cunet which is a bit more intensive than some of the others. There's a couple options you have:

1) Try a different model that may be less intensive
2) Tweak the crop and batch size settings for waifu2x-caffe which should reduce the Vram load at the tradeoff of maybe taking a little longer (this is what I'm currently having to do with my GTX 950 2GB which seems to be working fine, jury's still out on the change in runtime)

For the crop and batch size settings I would definitely recommend viewing the README over on the waifu2x-caffe github as it covers all the options in pretty good detail. Crop size you'll need to choose on your own as it should be an even divisor of your source material's width/height. Batch size ultimately just determines how many frames/crops it is trying to process at a time if I'm reading their documentation correctly. Both go hand in hand to determine how many chunks it will break a single frame into and how many of those chunks are being processed at a time which will help Vram load. There's also others too but these are the big ones from what I can tell.

**Comment by Danika207** [comment]
Thank you. I'll try.

**Comment by k4yt3x** [comment]
@Danika207 if it warns you about insufficient VRAM, you should still be able to run it with one thread.
