### ISSUE TITLE
No difference in video quality whatsoever

### ISSUE THREAD

**Issue by rosebytee** [k4yt3x/video2x#820]
![image](https://user-images.githubusercontent.com/97028115/212718017-d656200d-1d93-4d20-8f53-707f6d0c11e8.png)
![image](https://user-images.githubusercontent.com/97028115/212718145-41e789af-8a54-4ed9-8775-71924586706d.png)

Both look identical. Was upscaling with 1920x1080 output WxH from a 1280x720 video.
Default settings, was using SRMD NCNN Vulkan

**Comment by denny466** [comment]
are you sure this video was recorded in 720p and has not been upscaled, or fell victim to generation loss? bc upscaling a upscaled and/or 10 times re-encoded product does not improve things at all. i advise downscaling the 'source' to lets say 460p with a high enough bitrate, and experiment with sole frames to see wether srmd, realsr or waifu looks the best to you. best regards

**Comment by TeridaxIcarax** [comment]
I'm having a similar problem as well. trying to upscale a 360p video to 1080p but i see little to no change only gets blurrier.
