### ISSUE TITLE
CUDA does not appear to be working.

### ISSUE THREAD

**Issue by ethanbusswork** [k4yt3x/video2x#822]
![Capture](https://user-images.githubusercontent.com/55262855/213174946-87d67260-b717-4450-9e9e-7dd441ecceea.PNG)
I read through the Q&A after my project started and continued to be slow. It appears as though Cuda just isn't working. Any help would be much appreciated, I'd rather not wait days for something to complete if I don't have to.

**Comment by ethanbusswork** [comment]
I have confirmed with another program that CUDA works on my PC.

**Comment by spencerfrost** [comment]
Same here. CUDA works in other programs but not this

**Comment by spencerfrost** [comment]
@ethanbusswork did you find a solution for this?
