### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by velara3** [k4yt3x/video2x#84]
Support for Mac

**Comment by k4yt3x** [comment]
I don't even have a machine with macOS to test anything.

**Comment by velara3** [comment]
I meant MacDonalds. Support the Big Mac and fries combo.

**Comment by ShikiSuen** [comment]
@k4yt3x What about installing a hackintosh on your current PC desktop with compatible AMD graphics? There is a high possibility that your own AMD graphics is natively supported by macOS.

**Comment by k4yt3x** [comment]
@ShikiSuen I run ESXi, not bare metal.
Hackintosh might support AMD, but not ESXi.

**Comment by k4yt3x** [comment]
Theoretically now video2x should be able to run on Mac if the correct drivers are installed and video2x is configured properly.

**Comment by NightMachinary** [comment]
I get this error:
```
 python video2x_setup.py
Traceback (most recent call last):
  File "video2x_setup.py", line 48, in <module>
    LOCALAPPDATA = pathlib.Path(os.getenv('localappdata'))
  File "/Users/evar/anaconda/lib/python3.7/pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/evar/anaconda/lib/python3.7/pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/evar/anaconda/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by k4yt3x** [comment]
setup script is built for windows

**Comment by JackYoustra** [comment]
Would you be open to a homebrew pr?

**Comment by k4yt3x** [comment]
> Would you be open to a homebrew pr?

Actually I'm thinking about publishing this package on pip.

**Comment by coltenkrauter** [comment]
How can I run this on Mac? I have tried running the Docker container, but I don't seem to have the graphics card at `/dev/dri`... Any suggestions?

**Comment by forresthopkinsa** [comment]
Same problem as above. Guidance is to use the Docker container for Mac, but there is no `/dev/dri` on macOS

**Comment by yudukikun5120** [comment]
Any solutions?

**Comment by forresthopkinsa** [comment]
macOS explicitly does not have Vulkan support, so I don't think this can be done with the internal GPU

**Comment by warlock-lv** [comment]
what is the command to launch the container if I want run video2x in macOS M1 pro with docker?

**Comment by kevinjcoleman** [comment]
@warlock-lv did you ever figure this out?

**Comment by velara3** [comment]
I’ve got it to work on my mac but it didn’t use the gpu. Give me a few days
and I’ll see if I can find the command line arguments. It does work without
a GPU it’s just really slow in comparison.

**Comment by Webbrother** [comment]
@velara3 any updates?

**Comment by velara3** [comment]
For mac I followed the original instructions shown below: 

# MacOS / OSX

You need [Homebrew](https://brew.sh) installed, as well as a newer llvm installed (since Xcode's llvm does not have
 filesystem library)

The following has been tested on macOS Mojave 10.14.3:
```
$ brew install llvm opencv
$ git clone https://github.com/DeadSix27/waifu2x-converter-cpp && cd waifu2x-converter-cpp
$ cmake -DOPENCV_PREFIX=/usr/local/Cellar/opencv/<your version here> .
$ make -j4
$ cp -r models_rgb models
```
IIRC you need to install CUDA or OpenCV. You may need to install Homebrew and pip. 

If that compiles then here are some command line examples using `test.jpg` as an input: 

Users/.../waifu2x/waifu2x-converter-cpp --jobs 8 
--scale-ratio 2 --mode noise-scale --noise-level 3 -c 0 -f png 
--input '/Users/.../test' --output '/Users/.../test2'

/Users/.../waifu2x/waifu2x-converter-cpp --model-dir /Users/.../waifu2x/models --scale-ratio 2 -q 101 --noise-level 3 -m noise-scale -i /Users/.../waifu2x/test/test.jpg -o /Users/.../waifu2x/test.png

/Users/.../waifu2x/waifu2x-converter-cpp --jobs 4 --scale-ratio 2 --mode noise-scale --noise-level 3 -c 0 -f png --input '/Users/.../test/test.jpg' --output /Users/.../test2/

I haven't tested on a M1 macbook but theres no reason it shouldn't work since it will use the CPU if GPU drivers aren't available.
