### ISSUE TITLE
[Errno 2] No such file or directory: 'C:\\...\\VIDEO_FILE.mkv'

### ISSUE THREAD

**Issue by kosuodhmwa** [k4yt3x/video2x#847]
file is attached
[video2x_error.log](https://github.com/k4yt3x/video2x/files/10887095/video2x_error.log)

**Comment by kosuodhmwa** [comment]
what a piece of s**t!!

**Comment by hui1601** [comment]
You seem to be running your program from a temporary directory. Files or directories in the temporary folder are not guaranteed to be preserved for future reference by programs.
Just unzip it to a regular folder and run it.

**Comment by kosuodhmwa** [comment]
Thank you for your feedback. What do you mean with "temporary directory" ?

It's the Download directory in my user profile folder - nothing else?

Maybe you have a hint where i should it run from...?

Thank you very much for your feedback :-)


Best regards

**Comment by kosuodhmwa** [comment]
Same problem when i run it from C:\Tools\video2x-4.
[video2x_error.log](https://github.com/k4yt3x/video2x/files/10905620/video2x_error.log)
8.1-win32-full

Log is attached

**Comment by kosuodhmwa** [comment]
-> Directory name is '$$$', NOT '$$' as in the log - maybe that is the problem / reason...!?

**Comment by kosuodhmwa** [comment]
OK, now i will move the video to C:\Medien\Video... hope that works!!?

**Comment by kosuodhmwa** [comment]
now it seems to work, thank you very much :-)
