### ISSUE TITLE
Nvidia GPU not being used

### ISSUE THREAD

**Issue by TimyIsCool** [k4yt3x/video2x#849]
I am trying to upscale a video but its using my AMD Vega 8 instead of my NVIDIA Tesla P4, i tried changing the GPU ID and it still uses my Vega 8 instead of my P4

**Comment by TimyIsCool** [comment]
trying to run SRMD*

**Comment by ProximalElk6186** [comment]
In Settings, go to System -> Display -> Graphics. Make sure that in the drop-down to add the application "Desktop App" is selected. Click "Browse" and search for an application, then double-click on its icon. Click "Options", then select the GPU you want the program to use, then click "Save". Restart the application.
