### ISSUE TITLE
Upscaling Progress not using GPU

### ISSUE THREAD

**Issue by nostalgicc** [k4yt3x/video2x#85]
waifu2x-caffe-cui

-gpu is used in command.

gpu usage still 0. Is this normal?

**Comment by k4yt3x** [comment]
Which GPU attribute are you looking at?
Could you take a screenshot of the task manager?

**Comment by nostalgicc** [comment]
![image](https://user-images.githubusercontent.com/38463032/56874963-39cb0a80-6a70-11e9-9022-09cd49800b86.png)

**Comment by k4yt3x** [comment]
I meant this page:

![image](https://user-images.githubusercontent.com/21986859/56875398-b62d0180-6a0e-11e9-82a3-3112dc5c3ad8.png)

**Comment by nostalgicc** [comment]
![image](https://user-images.githubusercontent.com/38463032/56875489-e78be880-6a73-11e9-9724-c8ef35736b89.png)

**Comment by k4yt3x** [comment]
Run an upscale and try switching the view to CUDA

![image](https://user-images.githubusercontent.com/21986859/56875519-92b68680-6a0f-11e9-9250-f4273130220d.png)

**Comment by nostalgicc** [comment]
![image](https://user-images.githubusercontent.com/38463032/56875544-510bf700-6a74-11e9-8b31-f46ded9b5034.png)
my bad... didn't even know about this..

**Comment by k4yt3x** [comment]
Seems to be a frequently asked question. I might create a Q&A page to collect these frequent questions.
