### ISSUE TITLE
Error Video2X Colab Notebook

### ISSUE THREAD

**Issue by leanfin** [k4yt3x/video2x#852]
Hi, unfortunately I get this error. Can anyone tell me what I am doing wrong?

Thanks a lot

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-89cd67ecb88b>](https://localhost:8080/#) in <module>
      4 
      5 import pathlib
----> 6 from video2x import Video2X
      7 
      8 video2x = Video2X()

ModuleNotFoundError: No module named 'video2x'

**Comment by tomasatisocco** [comment]
Same problem here, do you find any solution?

**Comment by leanfin** [comment]
Unfortunately no

**Comment by tomasatisocco** [comment]
I fix it following the instructions on this reply to another similar issue.
https://github.com/k4yt3x/video2x/issues/800#issuecomment-1469017748

**Comment by k4yt3x** [comment]
Should be good now.
