### ISSUE TITLE
No module named 'video2x'

### ISSUE THREAD

**Issue by Sadrahel** [k4yt3x/video2x#858]
Hi !
It was working some times ago but now : 

--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-42ee0c403a17>](https://localhost:8080/#) in <module>
      4 
      5 import pathlib
----> 6 from video2x import Video2X
      7 
      8 video2x = Video2X()

ModuleNotFoundError: No module named 'video2x'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

Help please ^^ !
---------------------------------------------------------------------------

**Comment by Sadrahel** [comment]
with this colab https://colab.research.google.com/drive/1gWEwcA9y57EsxwOjmLNmNMXPsafw0kGo

**Comment by 18019300070** [comment]
google看不了
