### ISSUE TITLE
When installing the main project, all vulkan dependencies fail with "The license_file parameter is deprecated, use license_files instead"

### ISSUE THREAD

**Issue by CristolGDM** [k4yt3x/video2x#873]
### What I did:

- cloned the repository to /my/path/video2x
- installed it locally with "pip install -e /my/path/video2x"

### What happened:

The following dependencies:
- realcugan-ncnn-vulkan-python
- realsr-ncnn-vulkan-python
-  rife-ncnn-vulkan-python
-  srmd-ncnn-vulkan-python
-  waifu2x-ncnn-vulkan-python

failed to build:

```
Successfully built video2x
Failed to build realcugan-ncnn-vulkan-python realsr-ncnn-vulkan-python rife-ncnn-vulkan-python srmd-ncnn-vulkan-python waifu2x-ncnn-vulkan-python
ERROR: Could not build wheels for realcugan-ncnn-vulkan-python, realsr-ncnn-vulkan-python, rife-ncnn-vulkan-python, srmd-ncnn-vulkan-python, waifu2x-ncnn-vulkan-python, which is required to install pyproject.toml-based projects
```

Looking at the specific errors, each package failed with the following error:

```
  ERROR: Failed building wheel for srmd-ncnn-vulkan-python
  Building wheel for waifu2x-ncnn-vulkan-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for waifu2x-ncnn-vulkan-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
      C:\Users\Cristol\AppData\Local\Temp\pip-build-env-8rzl71ib\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
```

### What I tried:

- updating setuptools =>no effect
- installing those dependencies directly (for example pip install realcugan-ncnn-vulkan-python) => same result
- looking at github for those dependencies => all haven't been updated in a while

I'm far from a python expert, so I might be installing stuff the wrong way :/ also I couldn't find "how to install" in the doc, sorry if I missed it

### More info:

- Windows 10
- Python 3.9.13
- pip 23.1.2
- setuptools 67.7.2

Please don't hesitate to ask if there is more information I can provide

**Comment by minguo** [comment]
install vulkansdk
install swig
