### ISSUE TITLE
Thread Issues

### ISSUE THREAD

**Issue by 251pigsinspace** [k4yt3x/video2x#88]
Hello

Starting to learn how to use the program, and im having a hard time trying to understand my issue. My computer seems to only want to run 1 thread of the program, and the documentation doesn't really mention how to fix this. 

If i bump into anything else, I will comment on this

**Comment by k4yt3x** [comment]
Hi, honestly, running one thread of `waifu2x-caffe` and multiple threads of it doesn't really create that much of a difference in terms of processing speed. I'm even considering to make 1 thread default due to a higher chance of malfunctioning with more threads.

**Comment by 251pigsinspace** [comment]
Ah, then is there something i'm doing wrong? I'm getting about 100 s of processing time per second of video

**Comment by metzo007** [comment]
a slow GPU will do one frame a second and a fast one two. So 20-40 seconds per second video is normal

**Comment by 251pigsinspace** [comment]
1070ti, is it possible drivers are causing issues?

**Comment by k4yt3x** [comment]
@251pigsinspace I don't think it's the driver. You can also check the task manager for Cuda usage, just switch to your GPU page and select Cuda on one of the graphs and you'll see if your GPU is actually working hard and doing its job.

**Comment by 251pigsinspace** [comment]
Okay so when i go to use the -cudnn option, it crashes out with a bad handle, i tried running it with standard -gpu which went through and processed, but i wound up with a white screen with synced audio

**Comment by 251pigsinspace** [comment]
![Capture 17](https://user-images.githubusercontent.com/47487427/57036472-fca27c00-6c19-11e9-8212-5c1ace8d41ee.PNG)

Duplicated the original cudnn error i got (im assuming cudnn is the fastest between cpu, gpu, and cudnn?)

**Comment by k4yt3x** [comment]
@251pigsinspace to use CUDNN, you first need to have the dll files installed. This can only be done manually. As for how, please Google it and consult Nvidia's official docs.

Also, you seem to be running a older version of video2x? I'll try to fix the problem you have with the `--gpu` option.

**Comment by k4yt3x** [comment]
@251pigsinspace any updates?

**Comment by k4yt3x** [comment]
The issue has been idle for too long. Closing the issue for now.
Reopen if needed.

**Comment by GalGreenfield** [comment]
> 

Hi, are there any updates to this - any optimizations made to utilize multiple threads more efficiently?

**Comment by k4yt3x** [comment]
@GalGreenfield yeah 5.0.0 is now pipelined. You can check the code out on that branch.
