### ISSUE TITLE
Error when output = subprocess.Popen(['ffmpeg', '-i', video_file],stderr=subprocess.PIPE,pipe_stdin=True).communicate()

### ISSUE THREAD

**Issue by sharathyadav1993** [k4yt3x/video2x#89]
I am trying to extract the frames from the video, but it is showing the below error. The code is below

## Code

```python3
def extract_frames(video_file, num_frames):
    """Return a list of PIL image frames uniformly sampled from an mp4 video."""
    try:
        os.makedirs(os.path.join(os.getcwd(), 'frames'))
    except OSError:
        pass
    print(video_file)
    
    #output = subprocess.Popen(video_file)
    
    output = subprocess.Popen(['ffmpeg', '-i', video_file],stderr=subprocess.PIPE,pipe_stdin=True).communicate()
    # Search and parse 'Duration: 00:05:24.13,' from ffmpeg stderr.
    re_duration = re.compile(r'Duration: (.*?)\.')
    duration = re_duration.search(str(output[1])).groups()[0]

    seconds = functools.reduce(lambda x, y: x * 60 + y,
                               map(int, duration.split(':')))
    rate = num_frames / float(seconds)

    output = subprocess.Popen(['ffmpeg', '-i', video_file,
                               '-vf', 'fps={}'.format(rate),
                               '-vframes', str(num_frames),
                               '-loglevel', 'panic',
                               'frames/%d.jpg']).communicate()
    frame_paths = sorted([os.path.join('frames', frame)
                          for frame in os.listdir('frames')])
    frames = load_frames(frame_paths, num_frames=num_frames)
    subprocess.call(['rm', '-rf', 'frames'])
    return frames
```

## Bug
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\Cybersecurity\moments_models-master\test_video.py in <module>()
     59 else:
     60     print('Extracting frames using ffmpeg...')
---> 61     frames = extract_frames(args.video_file, args.num_segments)
     62 
     63 

~\Desktop\Cybersecurity\moments_models-master\utils.py in extract_frames(video_file, num_frames)
     20     #output = subprocess.Popen(video_file)
     21 
---> 22     output = subprocess.Popen(['ffmpeg', '-i', video_file],stderr=subprocess.PIPE,pipe_stdin=True).communicate()
     23     # Search and parse 'Duration: 00:05:24.13,' from ffmpeg stderr.
     24     re_duration = re.compile(r'Duration: (.*?)\.')

~\AppData\Local\Continuum\anaconda3_old_version_Final\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~\AppData\Local\Continuum\anaconda3_old_version_Final\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by k4yt3x** [comment]
I've edited your questions to make it more readable.

My solution is that I first use `ffprobe` to get the framerate, and that framerate is then used when combining the frames back into a video.

https://github.com/k4yt3x/video2x/blob/a7d41cafdfb478ee620ae33764d4bc13cee9f288/bin/ffmpeg.py#L38-L67

For extracting frames, please look at the following code sections:

https://github.com/k4yt3x/video2x/blob/a7d41cafdfb478ee620ae33764d4bc13cee9f288/bin/ffmpeg.py#L69-L85

https://github.com/k4yt3x/video2x/blob/a7d41cafdfb478ee620ae33764d4bc13cee9f288/bin/video2x.json#L44-L48

**Comment by k4yt3x** [comment]
Also, in the future, if it's not a video2x bug, please don't put it under the bug tag. Just open a regular issue.

**Comment by sharathyadav1993** [comment]
Hi k4yt3x,

Thank you for the solution.
I resolved the issue.

**Comment by k4yt3x** [comment]
@sharathyadav1993 ur welcome.
