### ISSUE TITLE
No Audio; No such file or directory

### ISSUE THREAD

**Issue by silentcr0w** [K4YT3X/video2x#9]

**Comment by K4YT3X** [comment]
Hello. I see that you have already closed the issue, but did you manage to solve it? Don't hesitate to reopen the issue if you want.

**Comment by silentcr0w** [comment]
Nope, still havent solved it, any ideas of a solution?

**Comment by silentcr0w** [comment]
Can you make it support waifu2x-converter-cpp?, its for AMD GPUs.

**Comment by K4YT3X** [comment]
Please open new threads if you want something different.
