### ISSUE TITLE
Video2X Colab Notebook

### ISSUE THREAD

**Issue by octrends** [k4yt3x/video2x#906]
Did try it on colab but during runtime I am getting ffprobe not found, seems like its not installed as part of ffmpeg, did try re-installing but no luck

[/usr/local/lib/python3.10/dist-packages/video2x/video2x.py](https://localhost:8080/#) in upscale(self, input_path, output_path, output_width, output_height, noise, processes, threshold, algorithm)
    387     ) -> None:
    388         # get basic video information
--> 389         width, height, total_frames, frame_rate = self._get_video_info(input_path)
    390 
    391         # automatically calculate output width and height if only one is given

[/usr/local/lib/python3.10/dist-packages/video2x/video2x.py](https://localhost:8080/#) in _get_video_info(path)
    120         # probe video file info
    121         logger.info("Reading input video information")
--> 122         for stream in ffmpeg.probe(path)["streams"]:
    123             if stream["codec_type"] == "video":
    124                 video_info = stream

[/usr/local/lib/python3.10/dist-packages/ffmpeg/_probe.py](https://localhost:8080/#) in probe(filename, cmd, **kwargs)
     18     args += [filename]
     19 
---> 20     p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     21     out, err = p.communicate()
     22     if p.returncode != 0:

[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)
    969                             encoding=encoding, errors=errors)
    970 
--> 971             self._execute_child(args, executable, preexec_fn, close_fds,
    972                                 pass_fds, cwd, env,
    973                                 startupinfo, creationflags, shell,

[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861                     if errno_num != 0:
   1862                         err_msg = os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num, err_msg, err_filename)
   1864                 raise child_exception_type(err_msg)
   1865 

FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

**Comment by Styml** [comment]
i have the same issue, tried to `pip install ffprobe`, but to no avail

**Comment by k4yt3x** [comment]
I ran the notebook and couldn't reproduce the issue.
