### ISSUE TITLE
Docker build error: Could not find a version that satisfies the requirement pdm-backend (typo?)

### ISSUE THREAD

**Issue by MindSetFPS** [k4yt3x/video2x#911]
I recently discovered the project and tried to build the docker image locally, but I have this error that as far as I understand, it was a command argument `--pdm-backend`, that due to a typo is considered a package `-- pdm-backend`. I wish I could try to fix it myself, but I don't really know where that line of code Is originated. 

```bash Looking in links: /wheels
Processing /video2x
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-y6dgxceq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /wheels -- pdm-backend
       cwd: None
  Complete output (3 lines):
  Looking in links: /wheels
  ERROR: Could not find a version that satisfies the requirement pdm-backend (from versions: none)
  ERROR: No matching distribution found for pdm-backend

ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-y6dgxceq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /wheels -- pdm-backend Check the logs for full command output.
Error: building at STEP "RUN apt install -y python3.8 python3-pip python3.8-dev python3-opencv python3-pil mesa-vulkan-drivers cuda-drivers ffmpeg     && pip install --no-cache-dir --no-index -f /wheels .     && apt-get clean     && rm -rf /wheels /video2x /var/lib/apt/lists/*": while running runtime: exit status 1
```

**Comment by BigBane** [comment]
Yeah I have this same error any help on this? I'm trying to build my own image using buildx so i can run the container on my m1 mac.

**Comment by LukeShortCloud** [comment]
The problem is that the PyPi package has been renamed. "This project has been renamed and re-published as pdm-backend" https://pypi.org/project/pdm-pep517/

Using the new package name works.

```
$ git clone https://github.com/k4yt3x/video2x.git
$ cd video2x
$ sed -i s'/pdm-pep517/pdm-backend/'g Dockerfile
$ podman build .
```

I have a PR to fix this.

**Comment by BigBane** [comment]
Thanks @LukeShortCloud for updating. Confirming a sucessful build on m1 mac mini with the updated docker file and toml from your repo on m1 mac mini using buildx container to build video2x container.

**Comment by nathanhu1** [comment]
> Thanks @LukeShortCloud for updating. Confirming a sucessful build on m1 mac mini with the updated docker file and toml from your repo on m1 mac mini using buildx container to build video2x container.

Hey im trying to get this to work on m1 mac as well but am not having any luck. What commands did you run to build the buildx image and did you make any changes to the dockerfile?
