### ISSUE TITLE
Too slow to convert

### ISSUE THREAD

**Issue by xpirad** [k4yt3x/video2x#92]
## Environment Information
I'm using a rtx 2060 on win 10 

|Module|Version|
|-|-|
|`video2x`|latest|
|`ffmpeg`|latest|
|`waifu2x-caffe`|latest|
|`waifu2x-converter-cpp`|none|

## Symptom

Trying to up scale a 480p video which is only 10mb~ big into 960p (2x size)
But it's taking way too long, like an hour? (when using waifu2x)
Is it normal?

Also, during the ffmpeg stage
it's not using gpu but cpu (gpu usage is 0%)
also prints "Trailing options were found on the commandline."

I'm using default setting and cudnn

## Screenshots or Error Messages

Trailing options were found on the commandline.
![image](https://user-images.githubusercontent.com/24430064/57238479-1699ef80-705c-11e9-8250-640a3465e487.png)

Take an hour to upscale a 10mb video??
![image](https://user-images.githubusercontent.com/24430064/57238504-20bbee00-705c-11e9-81b8-c557a2138ea7.png)

**Comment by k4yt3x** [comment]
2x upscale an 5MB 240p video, the sample video, takes 12-15 minutes with my 1060 6G. It's normal that it takes that long. Some video takes well beyond 24 hours.

As for FFmpeg, my command did have -hwaccel auto at the end.

**Comment by k4yt3x** [comment]
Also, I'm rewriting the FFmpeg controller, so there will be some big changes coming out soon.

**Comment by xpirad** [comment]
Thanks!

But i just want to know why ffmpeg is not using gpu, even with -hwaccel auto?
And why is it saying Trailing options were found on the commandline.?

**Comment by k4yt3x** [comment]
> And why is it saying Trailing options were found on the commandline.?

I will investigate this first. There has been improvements made to the FFmpeg controller. I'll see if it's gone.

**Comment by k4yt3x** [comment]
I don't see more "Trailing options". I think it's fixed.

![image](https://user-images.githubusercontent.com/21986859/57475389-41559500-7262-11e9-9727-efb8cc446025.png)

**Comment by xpirad** [comment]
Thanks!
