### ISSUE TITLE
RealSR NCNN Vulkan slow and not using dedicated GPU.

### ISSUE THREAD

**Issue by UsernameEqualsGit** [k4yt3x/video2x#939]
When I try upscaling a video, the rate for frames is 0.02 per second (not sure if this is normal) and no matter what I've tried it never seems to speed up or utilize my dedicated GPU at all. I try setting the GPU ID to 1 instead of 0 and it still uses the integrated and no matter how many processes I set it stays at 0.02 FPS and just increases the usage on my integrated GPU. My dedicated GPU is an Nvidia RTX 4070 Laptop GPU so it should be able to handle the processing fine, it just isn't being utilized. Is there some setting I'm missing to use my dedicated GPU? I'm using the latest GUI version and GPU drivers are up to date.

**Comment by peyloride** [comment]
Did you check this page about GPU utilization is being low? https://github.com/k4yt3x/video2x/wiki/Q&A#no-gpu-usage

**Comment by UsernameEqualsGit** [comment]
I did and that isn't the issue. I may not have explained it well enough in the post. Its exclusively using my integrated GPU instead of my dedicated like I've been trying to get it to. As far as GPU utilization goes it will completely use up my integrated GPU but dedicated stays at 0%. My understanding of the settings is that setting the GPU ID to 1 should make it use my dedicated but 0 or 1 both result in my integrated being used.

**Comment by CharlesScoville** [comment]
Old post, but....

When you change GPU ID within the Driver Settings tab, are you navigating to the subtab specifically for RealSR NCNN?

Sorry if that sounds insulting. I just ask because that burned me my first time using the program.
