### ISSUE TITLE
Final mux stage not keeping original non-video tracks/converting primary audio track to ffmpeg's default vorbis

### ISSUE THREAD

**Issue by cr08** [k4yt3x/video2x#94]
Something I have noticed come up on my VM platform and kinda swept it aside and have been manually muxing things in until I can try to see if it was a modification I did or something else but then after grabbing a fresh copy of the latest commit on my personal laptop for some different videos I ran into the same thing here as well.

Essentially it looks like the final mux stage is not working appropriately or at all. For example on my VM I am working with videos with two audio tracks whilst a separate set of videos currently running on my laptop are single audio track videos. Both cases it seems to be ignoring everything and potentially converting a single (primary) audio track instead. If memory serves ffmpeg defaults to Vorbis audio if no codec is selected which is what is happening here. Here's some mediainfo screenshots. First is the original source and second is the final file after video2x is finished. The video track seems to be fine in the end.

![orig_video2x_mux](https://user-images.githubusercontent.com/1199481/57696938-0d8ebc80-7620-11e9-8c99-35724bce921f.PNG)
![output_video2x_mux](https://user-images.githubusercontent.com/1199481/57696948-13849d80-7620-11e9-9a2b-34ae0d37d08f.PNG)

**Comment by k4yt3x** [comment]
I believe that when I changed the `ffmpeg.py` the last time to make it configurable via `video2x.json`, I broke a lot of stuff since when the options are being read, they are no longer in the correct order. I will double check on the final stage to see if I can find out where it went wrong.

**Comment by k4yt3x** [comment]
@cr08 do happen you have a sample video that I can test with?

**Comment by cr08** [comment]
Sorry for the late reply. Real life got in the way. I can get you a couple sample clips directly from files I'm working with.

**Comment by k4yt3x** [comment]
@cr08 yes please. Zip it and upload it here? or any other way that you'd like.

**Comment by cr08** [comment]
Here's two clips I've been working with:

[clips.zip](https://github.com/k4yt3x/video2x/files/3244522/clips.zip)

**Comment by k4yt3x** [comment]
I upscaled both of them and it works just fine for me.

[output.zip](https://github.com/k4yt3x/video2x/files/3268683/output.zip)

**Comment by k4yt3x** [comment]
@cr08 could you please see if the newest commit (https://github.com/k4yt3x/video2x/commit/8e85d6a6d37796f70938fa81c81e3e0962ad6bbc) fixed the problem for you?

**Comment by cr08** [comment]
Getting closer. So the clip I sent you, filename `CL_S01E00-clip.mkv` which has two audio tracks. Ran it again and it still only gets the first audio track but it does a direct copy. Seems somewhere along the line the migrate stage is only grabbing one of the `-map` directives in the json. Or given the ordering somehow it is saying `-map` should come first given the json config but the actual value it's pulling is the last one in the config? Overall my vague guess is something isn't liking having multiple of the same directives in the same command? I'm not seeing any other instances of this in other stages.

`INFO: Executing: ['C:\\Users\\cr08\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'C:\\Users\\cr08\\AppData\\Local\\Temp\\video2x\\tmpdd6ouaag\\no_audio.mp4', '-i', 'C:\\Users\\cr08\\Videos\\test\\CL_S01E00-clip.mkv', '-map', '-1:v?', '-c', 'copy', '-pix_fmt', 'yuv420p', 'C:\\Users\\cr08\\Documents\\GitHub\\video2x\\bin\\sample_out.mkv', '-y']`

**Comment by k4yt3x** [comment]
@Aidolii found another issue last night (#102). Basically there was a typo that influences the program muxing stage.

Sorry about this back and fourth. Could you please check the newest version posted last night?

**Comment by cr08** [comment]
I actually did that test with the latest commit 1280a79 and came up with the results mentioned.

**Comment by k4yt3x** [comment]
@cr08 oh yeah I took a deeper look at the output, and it does appear that your map args are missing. Could you please check the JSON file? There should be a section that looks like this:

![image](https://user-images.githubusercontent.com/21986859/59526465-80fa4700-8ec8-11e9-9d23-5c7640757dd2.png)

Check to see if everything's in place.

**Comment by cr08** [comment]
Yep. That is all there. Just to save my sanity I even tried pulling a fresh copy of the repo and reviewing the json about 3 times. It's still doing the same thing with the same INFO line I listed above.

**Comment by Aidolii** [comment]
@cr08 Can you send me your entire video2x folder along with a bat file containing the command you've been using? With only the relevant clips of course.

**Comment by cr08** [comment]
Sure thing. 
[video2x.zip](https://github.com/k4yt3x/video2x/files/3292302/video2x.zip)

**Comment by Aidolii** [comment]
#105

**Comment by k4yt3x** [comment]
I just pushed a new commit (https://github.com/k4yt3x/video2x/commit/5151be4122369cc11f71ad50fc2e60e25b0fe33e) which should address this issue.

**Comment by Aidolii** [comment]
Seems to be working, on my end. I think if @cr08 has any issues with the output, all it would take is tweaking some json settings at this point.

**Comment by k4yt3x** [comment]
If it's fixed then I'm closing the two issues.

**Comment by cr08** [comment]
Sorry it took so long to reply back. Had to get my VM operational again after upgrading Proxmox and waiting for a batch task to complete. Can confirm this solved the issue on my end.

**Comment by k4yt3x** [comment]
@cr08 beautiful. Good to hear that.
