### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by jlopezv1** [k4yt3x/video2x#944]
Hi, I was trying to use video2X to process a video and got the error detailed in the subject
[video2x_error.log](https://github.com/k4yt3x/video2x/files/12253725/video2x_error.log)

**Comment by HeNeos** [comment]
That error is commonly due to `ffmpeg` not being able to get the number of frames. Try running `ffmpeg` externally and see if it shows any errors.
