### ISSUE TITLE
video2x gui problem.. 

### ISSUE THREAD

**Issue by ararf929** [k4yt3x/video2x#946]
everthing is fine until  i try to open the final mp4 and this pops up "we can't open (file name) this may be because the file type is unsupported, the file extension is incorrect or the file is corrupt"
the only errors and warnings are near the end of the command 

[!] ERROR: Subprocess 27848 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Traceback (most recent call last):
  File "upscaler.py", line 958, in run
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\a\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\a\\AppData\\Local\\Temp\\video2x\\tmpo4h07g4k\\intermediate.mkv', '-i', 'C:\\Users\\a\\Videos\\edits\\davinci not finished edit .mp4', '-map', '0:v?', '-map', '1:a?', '-map', '1:s?', '-map', '1:d?', '-map', '1:t?', '-c', 'copy', '-map_metadata', '0', '-metadata', 'comment=Upscaled by Video2X', '-movflags', 'use_metadata_tags', 'C:\\Users\\a\\Videos\\edits\\davinci not finished edit _output_0.mp4']' returned non-zero exit status 1.
[!] ERROR: Failed to migrate streams
[!] WARNING: Trying to output video without additional streams
[+] INFO: Writing intermediate file to: C:\Users\a\Videos\edits\davinci not finished edit _output_0.mkv
Cleaning up cache directory: C:\Users\a\AppData\Local\Temp\video2x\tmpskxjnzup
Cleaning up cache directory: C:\Users\a\AppData\Local\Temp\video2x\tmpo4h07g4k
Cleaning up cache directory: C:\Users\a\AppData\Local\Temp\video2x

**Comment by NullDivisionOfficial** [comment]
Same error here, mp4 file shows 0 data and the output file is now an mkv copy.
I've tried running gui as administrator and using the RealSR NCNN vulkan driver with no luck
