### ISSUE TITLE
Different upscaling Models?

### ISSUE THREAD

**Issue by Powermann293** [k4yt3x/video2x#95]
I was wondering if the ability to use the different upscaling models of Waifu 2x like UpPhoto or UpRGB are supported by the software and if so how do I configure it?

**Comment by k4yt3x** [comment]
You can specify the model using `--model_dir PATH_TO_MODEL_DIR`.
Note that it's the path to model directory instead of the model's name.

waifu2x-caffe comes with a set of trained models with it. Check its root directory.

**Comment by k4yt3x** [comment]
Question has already been answered, and the original question owner didn't post further responses, therefore closing the issue for now.
Feel free to reopen if needed.
