### ISSUE TITLE
Release exe doesn't follow ffmpeg -pix_fmt settings when using folder input

### ISSUE THREAD

**Issue by Clickin** [k4yt3x/video2x#96]
While using release edition, I managed to upscale multiple videos at once. But exe version ignores some sort of ffmpeg setting in json config(*I've tested video2x.py works well). My command was `video2x -c video2x.json -m cudnn -i test -o output --width=1920 --height=1080` and setting file follows
[video2x.txt](https://github.com/k4yt3x/video2x/files/3194366/video2x.txt)

Here's ffmpeg frames to video command-line output from setting above

Output #0, mp4, to 'E:\program\video2x-2.7.0-win32-full\output\test2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.26.101
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 1920x1080, q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.47.106 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

That shows exe definitely ignores setting, forces to use yuv444p. Even "-pix_fmt": "nv12" doesn't works either. Because I've tested about only pix_fmt, maybe it also ignores some other setting variable.

.ps
Output of same setting and test files with video2x.py

Output #0, mp4, to 'E:\program\video2x-2.7.0-win32-full\output\test2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.27.103
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.52.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

**Comment by k4yt3x** [comment]
The exe file is simply outdated. I'll fix it.

**Comment by k4yt3x** [comment]
Done. See the latest release: https://github.com/k4yt3x/video2x/releases/tag/2.7.1

**Comment by Clickin** [comment]
Thanks for fast response
