### ISSUE TITLE
"You are connected to a GPU runtime, but not utilizing the GPU" - colab issue?

### ISSUE THREAD

**Issue by giaaaacomo** [k4yt3x/video2x#961]
hi, i've followed the step-by-step guide in the notebook, but somehow i've been getting this warning from colab.
also, after an hour nothing new appears on the console-like box of the cell. is this normal?

![image](https://github.com/k4yt3x/video2x/assets/38686675/8307a2ec-5cce-463b-a6af-d564996c1988)

**Comment by CodaCM** [comment]
Yeah I get the exact same problem too where it gets stuck on 3.1 (Upscale) and the not utilizing gpu error.
they also need to update it now sense google has added new gpus to the list and I don't know which is the right one to use.

**Comment by giaaaacomo** [comment]
> Yeah I get the exact same problem too where it gets stuck on 3.1 (Upscale) and the not utilizing gpu error. they also need to update it now sense google has added new gpus to the list and I don't know which is the right one to use.

without the premium account it just lets me use the tesla t4, otherwise no gpu

**Comment by CodaCM** [comment]
> > Yeah I get the exact same problem too where it gets stuck on 3.1 (Upscale) and the not utilizing gpu error. they also need to update it now sense google has added new gpus to the list and I don't know which is the right one to use.
> 
> 
> 
> without the premium account it just lets me use the tesla t4, otherwise no gpu

Well, most of them are locked for me as well but if you are unlocked, I'll have to check again

**Comment by metapea** [comment]
I'm getting the same thing as when it was on, it didn't use any of the gpu and i was kicked out from the runtime by colab after a few hours. Rignt now the program can be without a gpu and it will keep on going for hours, i'm not sure if it's because cell is just using the cpu and it working slowly or it's doing nothing.

**Comment by Mccmark** [comment]
First time using this package, same GPU warning for me also.

**Comment by k4yt3x** [comment]
Should be fixed now. It's an issue with Colab's default nvidia driver. Took me hours to figure out what was wong. Should be fixed now. I close a dozen duplicate issues on this.

**Comment by ivivanov-bg** [comment]
Actually - I'm getting the same with the latest master.
Trying to upscale very low quality (less that 320p) to at least 720p
For 30 min. it was able to process only 5 frames - but got few warnings that I'm not using the GPU
