### ISSUE TITLE
Colab ffmpeg error & pathlib.Path needed to be changed

### ISSUE THREAD

**Issue by metapea** [k4yt3x/video2x#966]
When using anime4k or move threshold & processes in the other models, i get:
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
[<ipython-input-8-8a83b8e58312>](https://localhost:8080/#) in <cell line: 39>()
     37     raise FileNotFoundError(f"file {(gdrive / input_filename)} does not exist")
     38 
---> 39 video2x.upscale(
     40     gdrive / input_filename,
     41     gdrive / output_filename,

3 frames
[/usr/local/lib/python3.10/dist-packages/ffmpeg/_run.py](https://localhost:8080/#) in run(stream_spec, cmd, capture_stdout, capture_stderr, input, quiet, overwrite_output)
    323     retcode = process.poll()
    324     if retcode:
--> 325         raise Error('ffmpeg', out, err)
    326     return out, err
    327 

Error: ffmpeg error (see stderr output for detail)
```

And i had to change `gdrive = pathlib.Path("/mnt/gdrive/MyDrive/")` to `gdrive = pathlib.Path("/content/drive/MyDrive")` in order to run the cell

**Comment by k4yt3x** [comment]
That doesn't make sense to me since this step explicitly mounts Google drive to `/mnt/gdrive`

![image](https://github.com/k4yt3x/video2x/assets/21986859/d7ef95e8-b627-4cb1-9032-a68d1e6e345c)

**Comment by metapea** [comment]
I keep geting:
```
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-7-f30235f5d6bb>](https://localhost:8080/#) in <cell line: 39>()
     38 gdrive = pathlib.Path("/mnt/drive/MyDrive")
     39 if not (gdrive / input_filename).is_file():
---> 40     raise FileNotFoundError(f"file {(gdrive / input_filename)} does not exist")
     41 
     42 video2x.upscale(
```
when it's /mnt/ and using the "_mount google drive_" cell in colab

**Comment by k4yt3x** [comment]
1. Are you sure you're using the right Colab Notebook? I cannot reproduce what you're describing. Your Colab environment should not be any different than mine so I can't imagine what's wrong.
2. Have you executed all steps required?
3. Your error output is incomplete, expand the frames in the middle of the error messages.

**Comment by metapea** [comment]
On other note, tired waifux2 and it gave me
```
RecursionError: maximum recursion depth exceeded
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
[<ipython-input-2-8c8ea8dd56ca>](https://localhost:8080/#) in <cell line: 95>()
     93 
     94 video2x = Video2X()
---> 95 video2x.upscale(
     96     input_file,
     97     output_file,

3 frames
[/usr/local/lib/python3.10/dist-packages/video2x/encoder.py](https://localhost:8080/#) in write(self, frame)
    124         :param frame Image.Image: the Image object to use for writing
    125         """
--> 126         self.encoder.stdin.write(frame.tobytes())
    127 
    128     def join(self) -> None:

BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ckot** [comment]
I don't know if there are different colabs floating around out there or something, but I can confirm that the one currently linked to from within the wiki mounts google drive at /content/drive/MyDrive not /mnt/drive/MyDrive

by changing the path, i was able to get the interpolation to not crash (at least), despite the coment that it doesn't yet work on colab. 

I need to start with a an input video which actually requires some interpolation to tell whether it did anything other than output a slightly larger file.
