### ISSUE TITLE
Colab Request: Add an option to find input file and output the file within colab's current directory

### ISSUE THREAD

**Issue by metapea** [k4yt3x/video2x#967]
Instead of doing everything in google drive have three options to find the input file in `/content/`, output them in `/content/` or both.

**Comment by k4yt3x** [comment]
You can easily modify the code block of that step to look for the file anywhere you'd like.

![image](https://github.com/k4yt3x/video2x/assets/21986859/0895f15a-1c0f-46f6-b6e4-32ac068816a1)

**Comment by metapea** [comment]
It would nice to do this within the cell's gui and not modify code
