### ISSUE TITLE
An Exception Has Occurred

### ISSUE THREAD

**Issue by BakaFlame** [k4yt3x/video2x#97]
## Environment Information

|Module|Version|
|-|-|
|`video2x`|2.7.1|
|`ffmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||

## Symptom

i followed every steps from here https://github.com/k4yt3x/video2x/wiki/Step-By-Step-Tutorial

but i still cant :(

i used your sample video, did what you say, put it on the desktop and other places as well, but it didnt work :(
replying in chinese is also fine for me

i tried the full package one, double clicked it, it appears for just a sec then its gone, i dont know what that is lol...

## Screenshots or Error Messages

http://puu.sh/DuQXj/76b0d44327.png
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
Traceback (most recent call last):
  File "video2x.py", line 318, in <module>
    upscaler.run()
  File "C:\Users\username\Downloads\video2x-master\video2x-master\bin\upscaler.py", line 295, in run
    self._upscale_frames(w2)
  File "C:\Users\username\Downloads\video2x-master\video2x-master\bin\upscaler.py", line 234, in _upscale_frames
    raise(self.upscaler_exceptions[0])
  File "C:\Users\username\Downloads\video2x-master\video2x-master\bin\waifu2x_caffe.py", line 83, in upscale
    completed_command = subprocess.run(execute, check=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\username\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_width', '1920', '--scale_height', '1080', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\username\\AppData\\Local\\Temp\\video2x\\tmp6eqwdwms\\0', '--output_path', 'C:\\Users\\username\\AppData\\Local\\Temp\\video2x\\tmpjje5jlov']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
You might have something like a driver issue.
Do you have CUDA drivers (Nvidia GPU drivers) installed?

**Comment by BakaFlame** [comment]
> Do you have CUDA drivers (Nvidia GPU drivers) installed?

yes im using gtx760 388.13 gpu driver version

**Comment by k4yt3x** [comment]
> i tried the full package one, double clicked it, it appears for just a sec then its gone, i dont know what that is lol...

You're supposed to use that full package one as a command line tool, not double clicking on it.

> yes im using gtx760 388.13 gpu driver version

Have you tried upgrading your drivers? The problem here is that waifu2x didn't give out too much useful information. I can only see that it failed on something, but I don't really know what it failed to do or what caused it. If you can, run waifu2x-caffe on a single image first and see what happens.

**Comment by BakaFlame** [comment]
> Have you tried upgrading your drivers? The problem here is that waifu2x didn't give out too much useful information. I can only see that it failed on something, but I don't really know what it failed to do or what caused it. If you can, run waifu2x-caffe on a single image first and see what happens.

now im using cpu, it works but pretty slow, gpu doesnt work again

it shows 

Upscaling Progress:   0%|                                                                      | 0/456 [00:00<?, ?it/s]
Upscaling Progress:   0%|                                                                      | 0/456 [00:01<?, ?it/s]Could not create log file: File exists
COULD NOT CREATE LOGFILE '20190521-231052.8500'!
F0521 23:10:52.626562  2120 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Upscaling Progress:   0%|                                                                      | 0/456 [00:11<?, ?it/s]2019-05-21 23:11:02.827162 [+] INFO: Killing upscaled image cleaner
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 318, in <module>
  File "upscaler.py", line 295, in run
  File "upscaler.py", line 234, in _upscale_frames
  File "waifu2x_caffe.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\username\\Downloads\\video2x-master\\video2x-2.7.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '2.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\username\\AppData\\Local\\Temp\\video2x\\tmp4p8hpo9v\\0', '--output_path', 'C:\\Users\\username\\AppData\\Local\\Temp\\video2x\\tmpck9_c472']' returned non-zero exit status 3221226505.

btw, this is the latest gpu driver update :o

**Comment by k4yt3x** [comment]
> Check failed: error == cudaSuccess (2 vs. 0) out of memory

That indicates that you're running our of GPU VRAM.
If you're using multiple threads, cut it down to one.
If you're using only one, I think you might not have enough VRAM...
Try waifu2x-converter-cpp

**Comment by BakaFlame** [comment]
gtx 760 2g VRAM :((((((((((

and im not running mulitiple threads, im running this only, without gaming or web browsing

**Comment by k4yt3x** [comment]
2G... might not be enough...
That's the thing about machine learning I guess?

**Comment by BakaFlame** [comment]
oh well, thanks for answering :D

**Comment by k4yt3x** [comment]
@BakaFlame do try `waifu2x-converter-cpp` though. That might just work on your 760.
