### ISSUE TITLE
Anime4k is not recommendable for non-anime videos?

### ISSUE THREAD

**Issue by Tubny70100** [k4yt3x/video2x#975]
Anime4k is for upscale anime videos. But it's not recommendable use that to upscale non-anime video such as western cartoons (SpongeBob SquarePants, The Simpsons, Family Guy, Rick and Morty, South Park, The Loud House, etc...) and live action videos?

**Comment by rtcvb32** [comment]
A little bit ago i did some test images against Anime4K, and the results were so blurry. As such i wouldn't recommend it for anything at all.
