### ISSUE TITLE
Command '['C:\\Video2x\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\srmd-ncnn-vulkan', '-n', '7', '-s', '2', '-t', '400', '-m', 'C:\\Video2x\\video2x-4.8.1-win32-full\\dependencies\\srmd-ncnn-vulkan\\models-srmd', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\Ved\\AppData\\Local\\Temp\\video2x\\tmp7wngsvai', '-o', 'C:\\Users\\Ved\\AppData\\Local\\Temp\\video2x\\tmpk_lr2e2o']' returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by VedDalvi** [k4yt3x/video2x#982]
SRMD and waifu2x ncnn not working while upscaling (standard test clip used). Anime4kcpp works just fine. 

Video2x works fine on my laptop, but on this PC it doesn't. Does this have something to do with the fact that Video2x is on a hard drive ?

PC specs:
CPU: Ryzen 7 5700g (4.6GHz OC)
GPU: Integrated (2.3GHz OC)
RAM: 16GB @3733MHz
 test clip: https://github.com/k4yt3x/video2x/assets/85603580/749d80f8-c6b9-4f34-99cc-4f5bac2b1020

The overclocks were tested prior using Cinebench R23 and were stable but I tested only for 5-7mins. Could the overclocks have contributed?

**Comment by VedDalvi** [comment]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/12682526/video2x_error.log)
log file

**Comment by VedDalvi** [comment]
an earlier issue with the same error was said to be because of not enough VRAM, but I never had this issue on my laptop's integrated GPU running SRMD with 1 gig of VRAM..

The PC now has 3 gigs dedicated to the graphics but errors out

**Comment by pankajdharmik4** [comment]
Got any solution?
