### ISSUE TITLE
Colab Request: Add an option in the cell's gui to find input file and output the file within colab's current directory

### ISSUE THREAD

**Issue by metapea** [k4yt3x/video2x#984]
#967
I still think it would be nice QOE option in the Colab cell's gui then edit code.

**Comment by k4yt3x** [comment]
I'm thinking about another approach where we bypass Google Drive completely and use the `google.colab.files.upload()` function to let the user pick the files from their computer then the `google.colab.files.download()` to retrieve the processed files. This should be way more convenient.

**Comment by k4yt3x** [comment]
I've completely changed how file selection works. Now you can pick a file straight from your Google Drive or upload a new file. I've also changed the default mount location to `/content/drive`.
