### ISSUE TITLE
Passing algorithm options in docker image

### ISSUE THREAD

**Issue by NotherGithubAccount** [k4yt3x/video2x#985]
Is there a way to pass options to the algorithm using the docker image? I've tried various ways of escaping the double dash, but no luck.

Strangely, the method described in the Wiki for getting algo specific options already fails with `invalid choice: 'realsr' (choose from 'upscale', 'interpolate')`, not allowing it run to without setting a mode.

**Comment by k4yt3x** [comment]
I think you might have put the other arguments where the positional argument is supposed to be. The correct syntax is:

`video2x [global args] [action] [action args]`

Let's say you want to process using realsr, it should look something like

`docker run [...] ghcr.io/k4yt3x/video2x -i input.mp4 -o output.mp4 upscale -h 720 -a realsr`

Make sure your syntax is correct. If it's still not working for you, it'll be helpful if you post the command you're using so I can debug what's going wrong.

**Comment by NotherGithubAccount** [comment]
Sorry, misunderstanding. I get that error when I try to run video2x in docker with the [suggested method](https://github.com/k4yt3x/video2x/wiki/CLI) to get additional algo options.

What I'm trying to do is to run realsr in tta mode, passing `-x` as an argument rather than an option to video2x. But passing options to the algo doesn't appear to work with docker at all. `--` would apply to the docker command line, so I tried to pass it as `'--'` or `\-\-`, but that didn't work either.

**Comment by k4yt3x** [comment]
I had to go back and look at the code myself since I don't quite remember. The algorithm part has been reworked since that was written and it doesn't work like this anymore. They now have a more generic interface and you can't turn TTA on from just the command line, mostly because they run very slow without significant quality gains. I will go and correct the documentations.

**Comment by NotherGithubAccount** [comment]
Thanks for looking into it!
