### ISSUE TITLE
Command '['C:\\Users\\k4nme\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'E:\\Ghibli Movies\\Original\\Princess_Mononoke.mkv', '-pix_fmt', 'rgb24', 'E:\\Temp\\tmpksue_k81\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Melon-Catastrophe** [k4yt3x/video2x#986]
[video2x_error4.log](https://github.com/k4yt3x/video2x/files/12731159/video2x_error4.log)
This is the error file that occurred when I tried converting this file via Anime4x. I have no idea what the problem could be, but I figured I would submit an issue here.

**Comment by k4yt3x** [comment]
> [image2 @ 000001c31d624f40] Could not open file : E:\Temp\tmpksue_k81\extracted_18168.png
> av_interleaved_write_frame(): I/O error

You ran out of storage and it can't write more frames onto the disk. The 4th gen pipeline is quite inefficient and saves all frames on the disk. Perhaps try the newly added Anime4K v4 support in Google Colab.
