### ISSUE TITLE
Can't run the container

### ISSUE THREAD

**Issue by chicco-carone** [k4yt3x/video2x#989]
I tried running the container (version video2x:5.0.0-beta4-cuda) on my pc with arch linux and an nvidia gpu with cuda installed and when i run it gives me an bunch of errors and if i check my gpu usage it is at 5% so nothing is working. I installed cuda and i use the proprietary nvidia drivers version 525.78.01-1 (I use the older ones because the newer ones would not run starfield but if i need the new ones ill try with the new ones).
This is the docker logs [logs.txt](https://github.com/k4yt3x/video2x/files/12817774/logs.txt)
This is my docker compose file 
[docker-compose.txt](https://github.com/k4yt3x/video2x/files/12817785/docker-compose.txt) (the file is in yml on my pc but github wouldn't let me upload it.)

**Comment by k4yt3x** [comment]
You might be running too many processes. Try just one.

**Comment by chicco-carone** [comment]
It gives me the exact same issue but only one time instead of 3. one time it worked and i was able to run 12 processes because one uses 1gb of vram.

**Comment by k4yt3x** [comment]
Honestly I'm not sure why it's happening. Try the newest version of the container image maybe?

**Comment by chicco-carone** [comment]
> Honestly I'm not sure why it's happening. Try the newest version of the container image maybe?

Sorry for not replying but i didn' have access to my gpu for a while. I tried the latest version of the container with the same docker-compose file and it gives me this output and doesn't do anything `vkEnumeratePhysicalDevices failed -3` and with the runtime for docker nvidia it just tells me that the runtime wasn't found. I have the nvidia-all drivers installed and the nvidia container toolkit installed

**Comment by chicco-carone** [comment]
In the end i managed to run the program by just compling it from the aur and it just worked. I think that on the wiki you could add for arch linux to use it from the aur since there is already the package. The only issue that i'm having is that in the upscaling phase it used the gpu and with 11 processes it used 11 gb of vram but in the downscaling phase its using the cpu and only one core so it's very slow
