### ISSUE TITLE
Google Colab stuck at 99%

### ISSUE THREAD

**Issue by FXM56K** [k4yt3x/video2x#990]
I'm trying to use the google colab notebook, but every time it get stuck at 99%, the video is very short, 168 frames, but the process never finish, I tried to wait near 3 hours, but it never ends, and when I stop the process the output file ends broken
The Runtime config is Phyton 3 and T4 GPU

```
Input #0, rawvideo, from 'pipe:0':
  Duration: N/A, start: 0.000000, bitrate: 669207 kb/s
  Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 852x1080, 669207 kb/s, 30.30 tbr, 30.30 tbn, 30.30 
tbc
Input #1, matroska,webm, from '/content/drive/MyDrive/simone.mkv':
  Metadata:
    ENCODER         : Lavf60.3.100
  Duration: 00:00:05.53, start: 0.000000, bitrate: 13755 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv420p(tv, bt709, progressive), 852x1080 [SAR 1:1 DAR 71:90], 
30.30 fps, 30 tbr, 1k tbn, 60 tbc
    Metadata:
      DURATION        : 00:00:05.533000000
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[swscaler @ 0x5627ad7ab540] Warning: data is not aligned! This can lead to a speed loss
[libx264 @ 0x5627ad739ac0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5627ad739ac0] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x5627ad739ac0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - 
http://www.videolan.org/x264.html - options: cabac=1 ref=16 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 psy=1 
psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 
chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 
constrained_intra=0 bframes=8 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 
keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 
qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, matroska, to '/content/drive/MyDrive/simone_realsr_852x1080.mkv':
  Metadata:
    comment         : Processed with Video2X
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(tv, progressive), 852x1080, q=2-31, 30.30 fps, 1k tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  167 fps=0.1 q=-0.0 Lsize=  450195kB time=00:00:05.51 bitrate=669207.3kbits/s speed=0.00426x    
video:450195kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

the software get stuck at <cell line: 95> upscale() _run()>

**Comment by k4yt3x** [comment]
Is there any chance you can send me your video so I can try it out? I can only reproduce this issue on my end very occasionally. Being able to reproduce it every time will help debugging what's wrong with it.

**Comment by FXM56K** [comment]
Sorry for the late response, unfortunately I do not have the original video, but I do know how to replicate the problem almost 100%, the videos that gave me errors were those captured with the "Simple Screen Recorder" program, apparently said software does not "close" well the videos (I don't know the correct term) therefore that error is generated (I believe).

**[swscaler @ 0x5627ad7ab540] Warning: data is not aligned! This can lead to a speed loss** <-- Every time I have this error, this line of code appears, that's why I believe it has something to do with the issue.

If you are in Linux you can try capturing a video using this software and you will see the error, don't know why this happen to be honest. I hope this helps you solve the problem, I'm sorry I can't be of much help since my technical knowledge is limited. Anyway thanks for this great software.

The version of Simple Screen Recorder I used was "SimpleScreenRecorder 0.4.4"

**Comment by k4yt3x** [comment]
@FXM56K thanks for the information. I'll take a look when I have time.
