### ISSUE TITLE
Command '['G:\\Docs\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'G:\\Download\\I Am Here... Now (2009).mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\Joe\\AppData\\Local\\Temp\\video2x\\tmp9ssie_2b\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by roughideas** [k4yt3x/video2x#993]
Trying to upscale a movie and I keep getting this same error. Tried Waifu NVNN Vulkan, Caffe, and Converter CPP as well as RealSR NVNN Vulkan. 

I have the NVIDIA drivers installed, tried unchecking "Show Preview" cuz I saw that mentioned in a couple forum posts.

Any help is greatly appreciated.

**Comment by k4yt3x** [comment]
Can you save and attach the error log? This title alone doesn't show enough information.

**Comment by k4yt3x** [comment]
Yeah you simply ran out of disk space

> av_interleaved_write_frame(): I/O error

If you don't want to deal with disk spaces, try the Colab notebook.
