### ISSUE TITLE
D:\downloads\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by Khumzie01** [k4yt3x/video2x#995]
Doesn't let me upscale any video even the sample video as once clicking start it fails. this is the error: !] ERROR: Subprocess 10920 exited with code 3221225477 [!] ERROR: Subprocess execution ran into an error

**Comment by k4yt3x** [comment]
Upload the error logs and I'll reopen.
