### ISSUE TITLE
100% CPU Utilization, 0% GPU, no progress being made

### ISSUE THREAD

**Issue by JetJaguar124** [k4yt3x/video2x#996]
I'm attempting to upscale some video and it just sits at 0% progress indefinitely. When running, I'm getting next to no GPU utilization but my CPU shoots to 100%. This happens regardless of which drivers I use. 

CPU: Ryzen 3600 
GPU: Radeon 5700XT 

![Picture1](https://github.com/k4yt3x/video2x/assets/66703870/66a60d17-e4d4-4419-abbb-1960295e2c0b)

![Picture2](https://github.com/k4yt3x/video2x/assets/66703870/b3c55f08-e52b-4ff6-8289-970ecc580ef8)

![Picture3](https://github.com/k4yt3x/video2x/assets/66703870/aaa036ab-0a5b-40e2-a995-3553501ce256)

**Comment by k4yt3x** [comment]
For this version of Video2X, it will first use FFmpeg to extract all frames before starting to process. If you have a long video, FFmpeg may run for quite a while before processing starts.
