### ISSUE TITLE
Crash from Waifu2X Caffe anime_style_art, ukbench

### ISSUE THREAD

**Issue by andwan0** [k4yt3x/video2x#998]
Command '['D:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'D:\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\anime_style_art', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '896', '--scale_height', '672', '--input_path', 'D:\\Temp\\video2x\\tmppep2tsci\\0', '--output_path', 'D:\\Temp\\video2x\\tmpdacvc_wp']' returned non-zero exit status 3221226505.

[video2x_error_w2xc_asa.log](https://github.com/k4yt3x/video2x/files/12910145/video2x_error_w2xc_asa.log)
anime_style_art

Any obvious signs from the log why this crashed?

UPDATE: another crash but this time using ukbench
(see 2nd attachment)
[video2x_error_w2xc_ukbench.log](https://github.com/k4yt3x/video2x/files/12910139/video2x_error_w2xc_ukbench.log)
ukbench

**Comment by k4yt3x** [comment]
> Check failed: error == cudaSuccess (719 vs. 0)  unspecified launch failure
> *** Check failure stack trace: ***

Honestly out of the hundreds of reports I've never seen one alike. Also the second attachment seems to be empty.
